### ISSUE TITLE
Error:You must specify a URL for a Maven repository.

### ISSUE THREAD

**Issue by papirovdavid** [googlesamples/android-ndk#1]
Thanks for samples!

However, cannot compile, getting "Error:You must specify a URL for a Maven repository." error because maven { url System.getenv('CUSTOM_REPO') }

How should it be configured?
Thanks,
david.papirov@gmail.com

**Comment by ggfan** [comment]
Thank you for your info! I am glad you are checking out our samples. 

It is kind of early peek into next release of gradle plugin/AndroiStudio; I also apologize that we do not have the documentation at this moment.

The way to workaround for early access is:

1) download the source code for gradle plugin and follow instruction to build latest gradle plugin on your location system
       http://tools.android.com/build
     (once you get source code and executed 3 commands: gradlew init;gradlew assemble;gradlew publishLocal, you have latest gradle plugin on your local machine )
2) your local build should be somewhere @
      $(YOUR_LOCAL_SOURCE_CODE_ROOT_DIR)/out/repo   <== this is the one to be set into CUSTOM_REPO on your local machine.  gradle will be able to find the place via System.getenv('CUSTOM_REPO')
3) I would also follow the directory mentioned in step 2), into the end of the classpath to check out what is your build version
       the latest version could beta2, beta3 or others, you could find which one it is by following classpath on your local build --
        $(YOUR_LOCAL_SOURCE_CODE_ROOT_DIR)/out/repo/com/android/tools/build/gradle-experimental
             it should be 1.3.0-beta3 (when I was compiling at that day, latest one was beta2 )
        find what yours is and put it into the classpath [instead of using the 1.3.30-beta2]
       
       Note: plugin name is gradle-experimental,  latest version may change and it changes pretty fast. Final release version could be 1.3.0-rc, 1.3.0, or others
       

with this you will be able to compile.

Currently we use these 2 samples to develop integration into new Android Studio [to be imported directly from github into local Android Studio ]. When the mechanism is ready, more samples with new Android Studio will be pushed in and documentation will follow pretty quickly.

thank you again for checking it out and appreciate your early access and feedback!

**Comment by papirovdavid** [comment]
Thank you for detailed answer!

 

I just downloaded the today's latest Android Studio RC with "ndk support",

Opened the hellow-jni latest source, succeded to compile it, but cannot run:

 

Error:

Error:Execution failed for task ':app:dexAllDebug'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_45\bin\java.exe'' finished with non-zero exit value 1

 

Please help, I stuck

 

THANK YOU VERY MUCH!!!

David

**Comment by ggfan** [comment]
I thought Android Studio has to use Java 1.7, not 1.8; may you help double
check that?

Also the latest gradle-experimental is already released into jcenter, so
you do not need to put anything extra in project build.gradle anymore, just
   jcenter()

would be fine. However the version is changed to 0.1.0, anyhow you could
find out what the latest version is @
jcenter.bintray.com/com/android/tools/build, go into the
gralde-experimental, you see the version(s), feel free to use the latest
one.

There is video clip for help of the new android studio @
http://youtu.be/wXjAkrn905s,

hope this helps

thanks
gerry

**Comment by ggfan** [comment]
Hi @papirovdavid, some more info on Java versions:
https://github.com/googlesamples/android-ndk/issues/34
I like to close this one, if you still have issues, please comment/re-open it.  thanks
