### ISSUE TITLE
validate gradle model in builder project

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#10]
@rschiu pointed out we can get a object representation of the model using https://docs.gradle.org/current/javadoc/org/gradle/tooling/ProjectConnection.html#getModel(java.lang.Class)

We could validate the model against flags and abiFilter to make sure we keep consistency across all samples.

**Comment by ggfan** [comment]
not for gradle experimental but concept still apply to all samples: it is continuously progressing item
