### ISSUE TITLE
Error with linking the shared library

### ISSUE THREAD

**Issue by genehsun** [googlesamples/android-ndk#100]
I tested how to link .so(or .a) library in Android Studio 1.4(which support NDK build and debug), but failed to do that.

The Environment Is:

OS: "Mac 10.10.3"
Java: "1.7.0_80"
NDK: r10e
Android Studio: 1.4 Beta 2
Gradle Env: gradle-experimental:0.2.0 && gradle-2.5-all

The build.grade file is like this:

apply plugin: 'com.android.model.application'

model {
    android {
        compileSdkVersion = 22
        buildToolsVersion = "22.0.1"

        defaultConfig.with {
            applicationId = "me.example"
            minSdkVersion.apiLevel = 15
            targetSdkVersion.apiLevel = 22
            versionCode = 1
            versionName = "1.0"
        }
    }
    android.buildTypes {
        release {
            minifyEnabled = false
            proguardFiles += file('proguard-rules.txt')
        }
    }
    android.ndk {
        moduleName = "test"
        toolchain = "clang"
        cppFlags += "-std=gnu++11"
        cppFlags += "-I/public/projects/android/ffmpeg/arm/include".toString()
        stl = "gnustl_static"
    }
    android.productFlavors {
        create ("armv7") {
            ndk.abiFilters += "armeabi-v7a"
        }
    }
    android.sources {
        main.jni {
            source {
                srcDir '/public/projects/android/ffmpeg/test'
            }
        }
        main.jniLibs {
            source {
                srcDir '/public/projects/android/ffmpeg/arm/lib'
            }
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
}

When build, the terminal print many 'undefined reference to' errors.
What's wrong with it?
Could you pls give me some advice?

**Comment by proppy** [comment]
can you paste the full error, also take a look at https://github.com/googlesamples/android-ndk/tree/master/hello-thirdparty that shows how to link to a third-party `.a` from another project.

**Comment by genehsun** [comment]
Finally, I solved the problem. Yeah, the 'hello-thirdparty' demo shows how to refer to the static library.
For the shared library, we have to copy them to the 'jniLibs' folder. When do this, they will be packed into
the .apk file.

apply plugin: 'com.android.model.application'

model {
android {
compileSdkVersion = 22
buildToolsVersion = "22.0.1"

    defaultConfig.with {
        applicationId = "me.example"
        minSdkVersion.apiLevel = 15
        targetSdkVersion.apiLevel = 22
        versionCode = 1
        versionName = "1.0"
    }
}
android.buildTypes {
    release {
        minifyEnabled = false
        proguardFiles += file('proguard-rules.txt')
    }
}
android.ndk {
    moduleName = "test"
    toolchain = "clang"
    cppFlags += "-std=gnu++11"
    cppFlags += "-I/public/projects/android/ffmpeg/arm/include".toString()
    ldFlags += "-L${file("src/main/jniLibs/armeabi-v7a/")}".toString()
    ldLibs += ["avutil-54", "swresample-1", "swscale-3", "avcodec-56", "avdevice-56", "avfilter-5", "avformat-56", "postproc-53"]
    stl = "gnustl_static"
}
android.productFlavors {
    create ("armv7") {
        ndk.abiFilters += "armeabi-v7a"
    }
}
android.sources {
    main.jni {
        source {
            srcDir '/public/projects/android/ffmpeg/test'
        }
    }
}
}

dependencies {
compile fileTree(dir: 'libs', include: ['*.jar'])
compile 'com.android.support:appcompat-v7:22.2.0'
}

**Comment by proppy** [comment]
Closing this as it doesn't refer to a particular sample and you resolved your error. Solving #45 and #57 would help to make it more discoverable.

**Comment by pushpendra-spartan** [comment]
Hey @genehsun I am trying to use ffmpeg as shared library with my android studio but its not woking:
I followed this tutorial to compile ffmpeg: http://www.roman10.net/2013/08/18/how-to-build-ffmpeg-with-ndk-r9/

After that I configured my build.gradle like this:
```
apply plugin: 'com.android.model.application'

model {
    android {
        compileSdkVersion = 23
        buildToolsVersion = "23.0.2"

        defaultConfig.with {
            applicationId = "com.example.spartan.hello"
            minSdkVersion.apiLevel = 18
            targetSdkVersion.apiLevel = 23
            versionCode = 1
            versionName = "1.0"
        }
    }
    android.buildTypes {
        release {
            minifyEnabled = false
            proguardFiles.add(file('proguard-android.txt'))
        }
    }

    android.ndk {
        moduleName = "tutorial01"
        toolchain = "gcc"
        cppFlags.add("-std=gnu++11")
        cppFlags.add("-I/home/spartan/ndk/android-ndk-r11c/sources/ffmpeg-3.0.1/android/arm/include".toString())
        ldFlags.addAll("-L${file("src/main/jniLibs/armeabi-v7a/")}".toString())
        ldLibs.addAll(["avcodec-57", "avutil-55","swscale-4", "avformat-57"])
        stl = "gnustl_shared"
    }
    android.productFlavors {
        create ("armv7") {
            ndk.abiFilters.add("armeabi-v7a")
        }
    }

    android.sources {
        main {
            jni {
                source {
                    srcDirs = ['src/main/none']
                }

            }

        }
    }

}


```

and in my activity this is how my loading: 
```
static {
        System.loadLibrary("avutil-55");
        System.loadLibrary("avcodec-57");
        System.loadLibrary("avformat-57");
        System.loadLibrary("swscale-4");
        System.loadLibrary("tutorial01");
    }
```
but I am always getting this error:
```
Error:error: cannot find -lavcodec-57
Error:error: cannot find -lavutil-55
Error:error: cannot find -lswscale-4
Error:error: cannot find -lavformat-57
```

**Comment by ggfan** [comment]
Maybe a few lines for gradle dir layout first.  Things under app/src/main are for
 1) compiling into libtutorial01.so ( which is used on host )
 2) tucking into apk ( which will be sent over to target --phone and tablet )

seems your error are at happening when linking at host. To use a prebuilt lib, you would need
   - use repositories {} where you tell gradle your prebuilt lib name, exported header dir, and path to your lib
  - make your lib to be jni dependencies [so you lib will be used to compile your libtutorial01.so]
some example here might help: https://github.com/playgameservices/cpp-android-basic-samples/blob/master/samples-android/ButtonClicker/build.gradle, look at "gpg" for the example there

Your System.loadLibrary() is meant to load the shared lib on the target [hopefully someday we could get rid of all of the java code in ndk examples :-)], those so files need to be packed inside your apk's lib/ folder [you could unzip your apk and find out ], which means you have to put them inside app/src/main/jniLibs folder in your project [gradle/Android Studio will automatically copy them into your apk's lib/ folder at assemble stage]. Then your System.loadLibrary() may work if there is no other errors

Gradle is different from ndk-build, might need efforts to set up; but once it is working for you, the IDE and debugability are attractive and will save lot of time. Full documentation is at http://tools.android.com/tech-docs/new-build-system.

**Comment by genehsun** [comment]
Hi @pushpendra-spartan , I can not figure out the problem from your build file. It looks right.
Please ensure to put the four shared library into jniLibs folder.
And, in my experience, the order of the libraries sometimes matter.

**Comment by pushpendra-spartan** [comment]
Hi @genehsun  and @ggfan 

I am trying to do like this and it looks right approach(I copied .so in jniLibs and include folder of .h files in jni folder). Let me know your points:

 ```
repositories {
        libs(PrebuiltLibraries) {
            libavcodec {
                headers.srcDir "/home/spartan/AndroidStudioProjects/Hello/app/src/main/jni/include/libavcodec"
                binaries.withType(SharedLibraryBinary) {
                    sharedLibraryFile = file("/home/spartan/AndroidStudioProjects/Hello/app/src/main/jniLibs/${targetPlatform.getName()}/libavcodec-57.so")
                }
            }

            libavutil {
                headers.srcDir "/home/spartan/AndroidStudioProjects/Hello/app/src/main/jni/include/libavutil"
                binaries.withType(SharedLibraryBinary) {
                    sharedLibraryFile = file("/home/spartan/AndroidStudioProjects/Hello/app/src/main/jniLibs/${targetPlatform.getName()}/libavutil-55.so")
                }
            }

            libavformat {
                headers.srcDir "/home/spartan/AndroidStudioProjects/Hello/app/src/main/jni/include/libavformat"
                binaries.withType(SharedLibraryBinary) {
                    sharedLibraryFile = file("/home/spartan/AndroidStudioProjects/Hello/app/src/main/jniLibs/${targetPlatform.getName()}/libavformat-57.so")
                }
            }

            libswscale {
                headers.srcDir "/home/spartan/AndroidStudioProjects/Hello/app/src/main/jni/include/libswscale"
                binaries.withType(SharedLibraryBinary) {
                    sharedLibraryFile = file("/home/spartan/AndroidStudioProjects/Hello/app/src/main/jniLibs/${targetPlatform.getName()}/libswscale-4.so")
                }
            }



        }
    }

    android.ndk {
        moduleName = "tutorial01"

        def jniPath = "/home/spartan/AndroidStudioProjects/Hello/app/src/main/jniLibs"
        cppFlags.add("-I${file(jniPath)}".toString())
        file(jniPath).eachDirRecurse { dir ->
            cppFlags.add("-I${file(dir)}".toString())
        }
        ldLibs.addAll(["log", "android","jnigraphics"])
        stl = "gnustl_shared"
    }


    android.sources {
        main {
            jni {
                dependencies {
                    library "libavcodec" linkage "shared"
                    library "libavutil" linkage "shared"
                    library "libavformat" linkage "shared"
                    library "libswscale" linkage "shared"
                }
            }
        }
    }

    android.productFlavors {
        create ("armv7") {
            ndk.abiFilters.add("armeabi-v7a")
        }
    }

    android.sources {
        main {
            jni {
                source {
                    srcDirs = ['src/main/none']
                }

            }

        }
    }

}
```

**Comment by ggfan** [comment]
looks good.  I believe once you set up headers.srcDir for your lib inside repositories{ libs{}}, you do not need add it into "-I..." for it anymore.  Basically you already told Android Studio where the lib and headers are, no need to re-tell it during inside android.ndk{} anymore [it does not hurt either, sure thing]

More of coding style, I guess. if you have the root of your header files, you just tell android studio
  headers  ( root of your header dir)
  binaries (your lib binary)
if you have directories under root of your headers, let source code handle it like #include<subdir/codec.h>. Again this is just nit. It might be good to just tell it once to android studio and tell it right; and separate build script from source code logical.  for Libs, only tell 2 things to android studio:  root of the header, and path to your lib, no more, no less.

The lib and head of your lib could be anywhere else, it does NOT have to be put under app/src/main/jni; whatever you put inside app/src/main/jni, android studio IDE will recursively display them inside IDE in a flat way; not sure you want that, up to you. [this is IDE domain, has nothing to do with gradle script]

your code looks good, thanks

**Comment by pushpendra-spartan** [comment]
@ggfan thank you, it really a valuable information.

**Comment by ggfan** [comment]
hope you get it to work soon [ I fixed a few typos here and there]

**Comment by Mikelle02** [comment]
I think I have the same problem here.

**Comment by ggfan** [comment]
not using gradle experimental, correct? if using CMake or ndk-build, could file a new bug: like to know if it is build problem, or loading problem.

**Comment by Vishnooo** [comment]
> can you paste the full error, also take a look at https://github.com/googlesamples/android-ndk/tree/master/hello-thirdparty that shows how to link to a third-party `.a` from another project.

Very very valuable sample, but when i clicked on the link 'page not found' error is coming. So of you are aware, can you please tell me if this example is currently available anywhere on github?

**Comment by ggfan** [comment]
it could be https://github.com/android/ndk-samples/tree/main/hello-libs?
