### ISSUE TITLE
Update all samples to use libc++_static or gnustl_static

### ISSUE THREAD

**Issue by vharron** [googlesamples/android-ndk#104]
Endless tunnel is using stlport, which is deprecated.

As I understand it, gnustl_static is more complete.

libc++_static has easier license terms and is the long term path for Android.

**Comment by proppy** [comment]
See also #53

**Comment by vharron** [comment]
gcc's optimized debug info is still much better than clang I think.  I want to recommend gcc until that is resolved.

**Comment by proppy** [comment]
@vharron is lldb capable of using gcc stl debug info?

**Comment by vharron** [comment]
It's really good at it as of 1.4

**Comment by ggfan** [comment]
this is addressed with latest code pull:  we are converging to 
   gnustl_static
   toolchain = clang
closing for now
