### ISSUE TITLE
sensor graph sample should be renamed "accelerometer graph"

### ISSUE THREAD

**Issue by vharron** [googlesamples/android-ndk#107]
There are lots of sensors and this only demos accelerometer I think.

**Comment by proppy** [comment]
Yes, it was named like this because we'd like it to draw more sensor in the future.

**Comment by ggfan** [comment]
create a pull https://github.com/googlesamples/android-ndk/pull/200
Purpose:
  keep the top level directory as sensor-graph as is ( no change )
  rename app to accelerometer everywhere. in the future, other sensor samples will be added
  under sensor-graph directory, parallel accelerometergraph, and inside IDE, they are parallel too.
sensor-graph in the future will be a collection of sensors samples.

please review the code change and see whether this make sense to you.  thanks

**Comment by ggfan** [comment]
merged the pull.
