### ISSUE TITLE
add sample for 0.4.0 dependencies management

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#113]
/cc @Whiteseeker

**Comment by proppy** [comment]
also show include path populated from exported header that @rschiu mentioned here:
https://github.com/proppy/android-ndk/commit/200a3697c3bb63eef409221d2893f725e085af9f#commitcomment-14371759

**Comment by ggfan** [comment]
I think  hello-thirdparty/hello-libs addressed it.
