### ISSUE TITLE
Mixing android plugins from gradle and gradle-experimental

### ISSUE THREAD

**Issue by frogermcs** [googlesamples/android-ndk#119]
Hey,

Actually this is just a copy of my question at StackOverflow (http://stackoverflow.com/questions/33509243/mixing-android-plugins-from-gradle-and-gradle-experimental) but I'm looking for the answer because this is my last piece of puzzle in my project which I'd like to describe in one of my articles on my blog.

Is there any way or workarounds or just hints to make plugins from gradle and gradle-experimental working together? 

For example to mix those two versions:

```
    com.android.tools.build:gradle:1.3.1
    com.android.tools.build:gradle-experimental:0.3.0-alpha4
```

I have an existing project which uses some external plugins (`app/build.gradle`):

```
    apply plugin: 'com.android.model.application'
    apply plugin: 'com.android.databinding'
    apply plugin: 'com.jakewharton.hugo'
```

in my root `build.gradle` I have:

```
    com.android.tools.build:gradle-experimental:0.3.0-alpha4
```

Issues which I have:

```
    * What went wrong:
    A problem occurred evaluating project ':app'.
    > Failed to apply plugin [id 'com.android.databinding']
       > java.lang.NullPointerException (no error message)
```

or

```
    * What went wrong:
    A problem occurred evaluating project ':app'.
    > Failed to apply plugin [id 'com.jakewharton.hugo']
       > 'android' or 'android-library' plugin required.
```

Without other plugins my project works fine (I have Android Library with some NDK code which is called from my main project. Problem occurs when I add mentioned plugins on any others.

And the question is - is it a gradle-experimental issue or issue of each plugin (hugo, databinding, apt, probably much more). 

Or maybe you have any hints if there is any other way to have app with current stable gradle plugin and library (with NDK code) which uses gradle-experimental?

What I want to avoid is a dealing with *.mk files and (as full as possible) Android Studio support. Bigger picture is to prepare .aar library with NDK code (just simple computation) which will be able to plug in to existing projects.

**Comment by ph0b** [comment]
Hi,

I've answered on SO too.
On my side I've been able to mix gradle stable and -experimental android plugins without any issues by using recent versions in my projects.

You should be able to define both dependencies inside your project's build.gradle file:

    dependencies {
        classpath 'com.android.tools.build:gradle-experimental:0.3.0-alpha7'
        classpath 'com.android.tools.build:gradle:1.4.0-beta6'
    }
and then either use apply com.android.(application|library) or com.android.model.(application|library) from your various module's build.gradle files.

**Comment by frogermcs** [comment]
Thank you for your answer. It works as it should. It was my last piece - I've just published my blog post about integrating FlatBuffers via NDK with Android app http://frogermcs.github.io/json-parsing-with-flatbuffers-in-android/ :)

**Comment by ph0b** [comment]
very nice article!
one last thing you can add is setting the NDK platform version to the same one as your minSdkVersion, in order to ensure that your native lib will properly run on all the Android versions you want to support:

    ndk {
        ///...
        platformVersion = 15
    }

**Comment by frogermcs** [comment]
Thanks, I didn't know that it's not the same as:
```
        defaultConfig.with {
            minSdkVersion.apiLevel = 15
            targetSdkVersion.apiLevel = 23
        }
```

**Comment by proppy** [comment]
@frogermcs do you think a sample showing this would be useful? If yes, I'll go ahead and repurpose this issue into a feature request.

**Comment by frogermcs** [comment]
Yeah, I believe that thanks to new gradle plugin, Java and C pair will be more and more popular. Dev's won't have to big knowledge about C++ to use it in Android apps. :)

**Comment by cavarzan** [comment]
@frogermcs did you try with the latest version of gradle plugins too?

```
 classpath 'com.android.tools.build:gradle:2.0.0-alpha6'
 classpath 'com.android.tools.build:gradle-experimental:0.6.0-alpha5'
```

Using these versions the Android Studio doesn't recognize the imports. Even using `compile project(":jni-module")` in `build.gradle`. In editor the IDE shows a dialog to add `jni-module` as dependencies.

**Comment by IgorGanapolsky** [comment]
@ph0b Are you sure that **platformVersion** in ndk gradle-experimental has anything to do with **minSdkVersion** in app's manifest?  I don't see any documentation proving this fact.

**Comment by ggfan** [comment]
yes,  earlier version it is; new one now might be defaulted to targetSdkVersion, and platformVersion would be used if it is set.

**Comment by phlizik** [comment]
dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'com.android.tools.build:gradle-experimental:0.8.0-rc1'
    }

Error:Unable to load class 'com.android.build.gradle.internal.NdkHandler'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by ggfan** [comment]
@phlizik which branch, which sample I could see this?  gradle 2.14.1 is needed, but I would think android studio rc1 will automatically prompt and handle the upgrade.

**Comment by ggfan** [comment]
closing this one as experimental plugin is hard to be found anywhere on the roadmap
