### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xuelanghu120** [googlesamples/android-ndk#130]
Error:Execution failed for task ':fFmpegTest:compileDebugNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\ndk\android-ndk-r10\ndk-build.cmd'' finished with non-zero exit value 2

do not know how to do

**Comment by ph0b** [comment]
Hi,

this error isn't related to the samples. Please ask your question with more details on stackoverflow.
Your current error means that your project isn't compiling, you can get the error message from running ndk-build.cmd from your project directly, or by look at the *Messagges* pane from Android Studio.
