### ISSUE TITLE
Audio sample showing different audio input sources

### ISSUE THREAD

**Issue by SherlockHao** [googlesamples/android-ndk#135]
Hi Proppy,

Can I ask you a question about how to use other microphones instead of the default microphone?

I am writing an app using OpenSL ES. I want to use other microphones instead of the default microphone. And I only found SL_DEFAULTDEVICEID_AUDIOINPUT. Is there any other values I can use to choose another microphone? I am using Nexus 6 which has three different microphones.

Thanks for your time! Appreciate any response!

Best Regards,
Yiya Hao
haoyiyafighting@gmail.com

**Comment by proppy** [comment]
Hi @SherlockHao, sorry for the late answer.

You might want to ask direct programming question on http://stackoverflow.com/questions/tagged/android-ndk instead (this tracker is more for bug report and feature request around the NDK samples).

It might be a good idea to have a native sample showing this, @ggfan what do you think?

**Comment by ggfan** [comment]
yes, that is good idea to have  a sample to enumerate exiting input devices and select one to use.  What I experienced is that if you have an external speaker/mic,  it will be automatically enabled and use. I did not know open SLES give your the option for this, mostly likely to be the platform api.

**Comment by sigmark14** [comment]
Have been working on this issue for quite a while. Still found no answer. Is there a tutorial regarding how to change different microphone source in OpenSL?

**Comment by sigmark14** [comment]
@ggfan Have been working on this issue for quite a while. Still found no answer. Is there a tutorial regarding how to change different microphone source in OpenSL?

**Comment by ggfan** [comment]
Not from OpenSL side, from Android Java framework side would be ok.  Check out the @dturner 's Audio Device Library in this [repo](https://github.com/googlesamples/android-audio-high-performance/tree/master/audio-device).

**Comment by ggfan** [comment]
please look for [Oboe repo](https://github.com/google/oboe) for android audio, full support from there.

**Comment by Ornolfr** [comment]
@ggfan Did you find out how it is possible to set the input device id in Oboe? I'm having this issue: https://github.com/google/oboe/issues/363
