### ISSUE TITLE
add sample with 3rd party opensource library module

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#142]
We have #71 for a binary dependencies on libgpg, #116 for trivial library module.

As @stewartmiles pointed:
We also need a sample showing how to package as a library module a 3rd party source dependencies that doesn't necessary follow the "gradle source layout".

This sample should demonstrate best practice around the usage of the new `srcDir` and `exportedHeader` directive.

[googletest](https://github.com/google/googletest) would be a good candidate.

**Comment by ggfan** [comment]
the nativeactivity module inside Teapot/MoreTeapot/native-activity/EndlessTunnel addressed the usage model: the sources are inside ndk, we only add link to that source dir in build.gradle with srcDir. 

just for that purpose, it is addressed.

**Comment by stewartmiles** [comment]
@ggfan https://github.com/googlesamples/android-ndk/blob/master/MoreTeapots/app/build.gradle doesn't appear to use the exportedHeader directive is there a reason why this is missing?

**Comment by ggfan** [comment]
Oh, it is inside:
https://github.com/googlesamples/android-ndk/blob/master/MoreTeapots/nativeactivity/build.gradle

export is inside the lib; the client side does not need to do anything.  It is added behind the scenes while compiling for application
