### ISSUE TITLE
Handling dynamic version codes for ABI-specific APKs

### ISSUE THREAD

**Issue by ph0b** [googlesamples/android-ndk#15]
When different APKs are generated for each ABIs, these must have different version codes in order to be published to the Play Store as multiple APKs for a single application.

With the previous DSL, this could be easily accomplished using such task:

```
// map for the version code
project.ext.versionCodes = ['armeabi': 1, 'armeabi-v7a': 2, 'arm64-v8a': 3, 'mips': 5, 'mips64': 6, 'x86': 8, 'x86_64': 9]

android.applicationVariants.all { variant ->
    // assign different version code for each output
    variant.outputs.each { output ->
        output.versionCodeOverride =
                project.ext.versionCodes.get(output.getFilter(com.android.build.OutputFile.ABI), 0) * 1000000 + android.defaultConfig.versionCode
    }
}
```

  or by modifying the version code from a flavor declaration:

```
x86 {
       ndk.abiFilters = "x86"
       versionCode = project.ext.versionCodes.get(output.getFilter(com.android.build.OutputFile.ABI), 0) * 1000000 + defaultConfig.versionCode
    }
```

This behavior should be part of the samples whether they're using _splits_ or _abiFilters_ to generate arch-specific APKs.

However, I couldn't find a way to do the same with the new DSL, could you look into implementing this with the new DSL ?

**Comment by proppy** [comment]
Thanks @ph0b

If that's not available with the new DSL, we should file a feature request on tools.android.com, if this is available we should update our sample to use it.

Let's keep this issue open to track the latter.

**Comment by c3ph3us** [comment]
// You can modify  configuration for each variant.
    components.android {
        binaries.afterEach { binary ->
        //.........
        }
    }

**Comment by ph0b** [comment]
Thanks for the pointer.
Unfortunately, I've looked at binary.targetAbi but it's currently empty when using abiFilters and splits aren't adding any flavors.

I couldn't find how to read the version code from there either.

**Comment by ggfan** [comment]
seems to be experimental related, closing
