### ISSUE TITLE
hello-thirdparty cannot find includes in editor

### ISSUE THREAD

**Issue by landarskiy** [googlesamples/android-ndk#153]
Hi! I follow getting started instructions from 
https://github.com/googlesamples/android-ndk/tree/master/hello-thirdparty
Project building and working but editor cannot find .h files from third party library. It's quite important for me, because I don't understand what happens with my code. Any suggestions?
[Screenshot from studio](http://joxi.ru/MAjMDdKCLbZX2e)

**Comment by proppy** [comment]
@landarskiy did you run the `gpg-sdk` gradle task?
```
Right Click on build.gradle for module gpg-sdk
Select 'Run build'
```

**Comment by kida7** [comment]
I built gpg-sdk ok but I can make project. This is error:
http://i.imgur.com/griLYUa.png
Anyone has a solution? I build on Android Studio 1.5 on Windows 10

**Comment by ggfan** [comment]
not sure what is going on with your screenshot error: maybe clean the project and re-build it: sometime android studio fails to clean up the object files when changing configurations.  Anyway, the sample is removed and replaced with hello-libs. You may try that one; if google play games service is important to you, may you try samples in https://github.com/playgameservices/cpp-android-basic-samples and post questions there?  thanks
