### ISSUE TITLE
audio-echo has high input latency because it doesn't use the SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION preset

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-ndk#154]
On some devices, such as the Nexus 5X not using this recording preset adds significant input latency (approximately 25ms). 

Here's an example of how the preset can be used: 
https://github.com/superpoweredSDK/SuperpoweredLatency/blob/master/Android/app/src/main/jni/SuperpoweredLatency.cpp#L122

**Comment by proppy** [comment]
This is fixed now.
