### ISSUE TITLE
NDK demo bundle app

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#156]
It would be nice to build and release a bundle app that show a curated (see #141) set of NDK demos on play.google.com.

That would allow developer discover samples by
- installing the NDK app on the play store.
- opening the NDK app
- taping one of the demo screenshot on the launcher
- interacting with the demo
- clicking on a github link on the demo to get redirected to the repo

**Comment by ggfan** [comment]
bug aging, feel free to re-open
