### ISSUE TITLE
Unable to debug native code

### ISSUE THREAD

**Issue by 4brunu** [googlesamples/android-ndk#158]
Hi,

I'm using NDK with the experimental gradle plugin, and I was able to debug my native code.

Then I saw this issue https://github.com/googlesamples/android-ndk/issues/119 and this blog post http://frogermcs.github.io/json-parsing-with-flatbuffers-in-android/.
This approach would be great, because I could use the stable gradle plugin for android specific code, and the experimental gradle plugin for the native code, witch would be great to use use databinding for example.
I was able to use this structure, but I lost the ability to debug native code.

I have created a sample project that illustrate my problem.
https://github.com/4brunu/AndroidNDKDebug

In there you can find two projects.
The first one "hello-jni-one-gradle-plugin", only use the experimental gradle plugin, and I'm able to debug the native code.
The second one "hello-jni-two-gradle-plugins", I use the stable gradle plugin for android specific code, and the experimental gradle plugin for the native code, and I'm unable to debug the native code.

Am I doing something wrong?
Could you help me enable native code debug in the second project please?

Thanks

**Comment by 4brunu** [comment]
Solved with this StackOverflow question if anyone has the same problem.

http://stackoverflow.com/questions/36472561/android-ndk-unable-to-debug-native-code-with-two-gradle-plugins

**Comment by proppy** [comment]
maybe someone could update the `README.md` to include that step?
