### ISSUE TITLE
Update hellojni to use c++11

### ISSUE THREAD

**Issue by kmshih** [googlesamples/android-ndk#161]
We're trying to demo using c++11 w/studio -- is it possible to update hellojni to do this via:

1.  adding the std=c++11 cppflag
2.  using auto somewhere in the example

**Comment by ggfan** [comment]
have a look at the code change when you get chance:
https://github.com/googlesamples/android-ndk/pull/162

**Comment by ggfan** [comment]
this is done now, re-open the bug if it does not work for you
