### ISSUE TITLE
Calling .so from C file

### ISSUE THREAD

**Issue by cavarzan** [googlesamples/android-ndk#169]
Hi,

How can I add a .so library in some NDK project and call the methods from a .c file inside `jni` folder?

I didn't find any example and I always got this error when I try to call some method:
`Error:(11) undefined reference to 'ClassInSOLibrary'`

**Comment by ggfan** [comment]
assuming you are using android studio/gradle.

check for this https://github.com/playgameservices/cpp-android-basic-samples/blob/master/samples-android/ButtonClicker/build.gradle
  1) look at repositories{} section, where tells gradle about your .so file and its header location. yours is sharedlib ( .so) so change StaticLibraryBinary --> SharedLibraryBinary
  2) look at android.sources{} section, where tells gradle to use your lib.  dependencies {
                    library "gpg" linkage "static" ...}  change linkage from "static" --> "shared"
then try inside your code to use lib functions. Hope it works for you.

**Comment by cavarzan** [comment]
@ggfan thanks for the help! I made all changes, and seems to partially works. 

```
/usr/local/Cellar/android-ndk/r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/arm-linux-androideabi/bin/ld
Error:error: /User/path-to-project/src/main/lib/libmylibrary.so: incompatible target
```

Did I need to compile the `.so` into different architectures? Or can I compile once and use for all? I think that the error is related to library compilation type... 

I also have the `.a`  file from the library, so I follow the example, but I got some error too:

```
Error:error: /User/path-to-project/src/main/lib/libmylibrary.a(AppCaller.c.o): incompatible target
```

Since I'm a very dumb in C programming, it's hard to find out have is happening here.

**Comment by ggfan** [comment]
yes, under src/main/lib, expect to see
   armeabi/libmylibary.so
   armeabi-v7a/libmylibrary.so
   x86/libmylibrary.so
   ...

then when you build your app, let the android studio to pick up the right one, ${targetPlatform.getName()} is for that purpose. you have c lib, so {stlPortType} part does not matter. 

for quick verification, you may just build for one architecture type in your app: the SAME type you built for your libmylibrary.so.  Well eventually your lib need to be built for all supported architectures, so you could claim your lib supports all of them :-)

**Comment by cavarzan** [comment]
@ggfan thanks! I re-compile the library using `ndk-build` and seems to work now.

**Comment by cavarzan** [comment]
@ggfan The example helped me to work with .a libraries. But using .so libraries, at runtime it throws an exception:

`java.lang.UnsatisfiedLinkError: dlopen failed: library "libmylib.so" not found`

My gradle file is this one: https://gist.github.com/cavarzan/5cf0d5919e1d698adb0e789254ec1d6c
Did you know if some parameter is missing?

**Comment by ggfan** [comment]
dlopen is trying to open the lib on your android device ( this has passed the compile on host ). maybe also put your sharedlib that you meant to load on android device into app/src/main/jniLibs folder so they get copied into your apk/libs folder automatically? after you have the apk, unzip it to make sure it is there. before you push apk into android device.
