### ISSUE TITLE
Issues with linking *,so files

### ISSUE THREAD

**Issue by apres23** [googlesamples/android-ndk#170]
Some of this samples work out of the box (e.g. endless-tunnel), others don't, for example Teapot:
linking libTeapotNativeActivity.so failed.
/usr/local/google/buildbot/src/android/master-ndk/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/exception.cpp:113: error: undefined reference to '__cxa_uncaught_exception'

This directory doesn't exist, even if I create wtitable /usr/local/google directory it remains empty, so where
to set the directory for the libraries and stuff???

I can't find any settings with "/usr/local/google/buildbot/....", and I think I never set this before anywhere in studio...

Without a good starting point with working samples, its heavy...

**Comment by ggfan** [comment]
thank you for reporting this. Yes both teapot and more teapot could not build. 
once my pull is merged ( pending right now ), it will get fixed automatically

**Comment by ggfan** [comment]
for what you have now, after you import project with android studio, open build.gradle file, and change
        stl     = "c++_static"
to
       stl     = "gnustl_static"
it could compile on my system ( mac ).  you might try it out. it should be same for moreteapot project.
(I am using ndk-r12 beta )
after checking for CI, I will merge in pull 168. it should address it.

**Comment by ggfan** [comment]
this one should be fixed by now, please check it out: Teapot/MoreTeapot could build via android studio "import an Android code sample", it will prompted error for ndk path, just set it to your ndk path at that stage [ I used ndk-r12 beta1 ]

I am closing on this issue for now. I will need to address c++_static issues in other thread.
