### ISSUE TITLE
Can not find jni.h file android ndk

### ISSUE THREAD

**Issue by mohdirfan87** [googlesamples/android-ndk#171]
Hi All I am getting error in c file and can not find jni.h file

**Comment by ggfan** [comment]
the file is part of NDK, in 
 your-ndk-path/platforms/$your-android-version/$arch-type/usr/include/jni.h
 one for each ABI and each android version, so you should see a lot of this file inside your ndk

by guessing, I would:
1) check you have the file in your ndk  
2) your gradle/android studio is configured to the right ndk

you may uses android studio's import sample option to import hello-jni into your android studio, and check the thing out there. ndk path is set inside IDE and finally saved into local.properties.

it is a guess. if still have problem, maybe load more info?  thanks

**Comment by ph0b** [comment]
If you're using AS 2.0 or 2.1 on Windows, there are good chances you're hit by this issue: https://code.google.com/p/android/issues/detail?id=195483

**Comment by ggfan** [comment]
may you kindly remind us whether there is any change on your end?  thanks

**Comment by mohdirfan87** [comment]
Hi,
resolved the errors in JNI files but did not get generated the .so file
Regards,
Irfan

**Comment by ggfan** [comment]
Oh, no errors? moduleName is there in your build.gradle, I believe

**Comment by ggfan** [comment]
maybe share your 2 build.gradle files:
 $project/build.gradle
 $project/app/build.gradle
we could sync-up with that? thanks

**Comment by mohdirfan87** [comment]
$project/build.gradle

// Top-level build file where you can add configuration options common
to all sub-projects/modules.
buildscript {
    repositories {
       jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle-experimental:0.7.0-alpha1'
    }

}

allprojects {
    repositories {
        jcenter()
    }
}

*AND *

*$project/app/build.gradle*
apply plugin: 'com.android.model.application'

model {
    android {
        compileSdkVersion = 23
        buildToolsVersion = "23.0.2"

        defaultConfig.with {
            applicationId = "com.example.hellojni"
            minSdkVersion.apiLevel = 4
            targetSdkVersion.apiLevel = 23
        }






    }


    /*
     * native build settings
     */
    android.ndk {
        moduleName = "hello-jni"
        toolchain "clang"
        stl = "stlport_shared"
        cppFlags.add("-std=c++11")

    }
    android.buildTypes {
        release {
            minifyEnabled = false
            proguardFiles.add(file('proguard-rules.txt'))
        }
    }




    android.productFlavors {
        // for detailed abiFilter descriptions, refer to "Supported ABIs" @
        // https://developer.android.com/ndk/guides/abis.html#sa

        create("arm8") {
            ndk.abiFilters.add("arm64-v8a")
        }
        create("x86") {
            ndk.abiFilters.add("x86")
        }
        create("x86-64") {
            ndk.abiFilters.add("x86_64")
        }

        // To include all cpu architectures, leaves abiFilters empty
        create("all")
    }

}

**Comment by mohdirfan87** [comment]
also getting error is
Error:error: argument to '-x' is missing (expected 1 value)

**Comment by ggfan** [comment]
this error: 
- Error:error: argument to '-x' is missing (expected 1 value)
is because an earlier bug in plugin,  change, inside $project/build.gradle
   0.7.0-alpha1  to 0.7.0
it should be fixed.  please try it out,  thank you

**Comment by ggfan** [comment]
also  change stl = "stlport_shared"  to    
 stl = "gnustl_static"    
it should not matter now, but I was told gnustl_static/shared is the most stable ones right now

**Comment by mohdirfan87** [comment]
Thank you very much Gerry.
Problem gets resolved and gets .so file.

One more thing is that, Is it possible to debug ndk c\c++ file. in android
studio.

Thanks & Regards,
Irfan

**Comment by mohdirfan87** [comment]
Hi Gerry,
Thank you
I have done both switch from GDB to LLDB and vice-versa

**Comment by ggfan** [comment]
Great!   debugging portion still works:  you could trace code inside JNI: it is one of the major benefits to use android studio for native code development.  In this codelab:    
https://codelabs.developers.google.com/codelabs/android-studio-jni/index.html?index=..%2F..%2Findex#0   
 step 5,  you could see how to trace code.  The tracing from JAVA into jni code [step into a jni function from Java side ] should still work too.

**Comment by mohdirfan87** [comment]
Thank You Gerry, I really appreciate your kind help

**Comment by ggfan** [comment]
glad info here are useful to you  :-).  Come back to make it more useful when you have some free cycles too :-)!  I will close this one for now, thank!

**Comment by mohdirfan87** [comment]
Hi Gerry,
I want to link the c++ 's static library "libcurl.a" in android gradle. I
dont know the process .please help me .


Regards,
Irfan

**Comment by ggfan** [comment]
The lib was built by someone for android platform already? if that is the case, you will have one ( or more ) header files, and one libcurl.a file.  Please look at the hello-libs sample, it is for this purpose. Basically 3 steps:
  1) you copy the libs & headers to somewhere on your local system
  2) In your application, tell gradle where your lib and header are with "PrebuiltLibraries"
  3) in your application, tell gradle that your jni code depends on the prebuiltLibraries with jni.dependencies{} 

the sample is for shared lib, but you could follow gperf's comment to get a working static lib case. One more thing, do not put your lib under main.jniLibs{} anymore since it is static lib, no need to pack into apk.

That should get it going. The other sample is inside branch "static-lib-showcase": look at the "endless-tunnel" in that branch, the nativeactivity is used as a static lib in that sample. 

please try it out and let us know how it goes: Lib management is important for any native proj development, hope it could work for you. thanks
