### ISSUE TITLE
undefined reference to 'bsd_signal' when using gradle 2.10

### ISSUE THREAD

**Issue by entrity** [googlesamples/android-ndk#172]
I've been obliged to upgrade to gradle 2.10, and when I attempt to build the project, I get an undefined reference error for `bsd_signal`:

```
Starting process 'command '/home/myself/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++''. Working directory: /home/myself/projects/DroidEar/app Command: /home/myself/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ @/home/myself/projects/DroidEar/app/build/tmp/linkNativeArmeabi-v7aDebugSharedLibrary/options.txt
Successfully started process 'command '/home/myself/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++''
/android/ndk/platforms/android-9/arch-arm/usr/include/signal.h:113: error: undefined reference to 'bsd_signal'
/android/ndk/platforms/android-9/arch-arm/usr/include/signal.h:113: error: undefined reference to 'bsd_signal'
collect2: error: ld returned 1 exit status
```

It looks to me like bsd_signal is defined in the signal.o component of platforms/android-9/arch-x86/usr/lib/libc.a, but even with my ldLibs call in my `build.gradle` including `c`, I still get the error. Is this a compatibility issue (or is my `build.gradle` just awry)? **Here's my `build.gradle` file:**

```
apply plugin: 'com.android.model.application'

model {
    repositories {
        libs(PrebuiltLibraries) {
            Superpowered {
                binaries.withType(StaticLibraryBinary) {
                    def prefix = "src/main/jniLibs/Superpowered"
                    headers.srcDir "${prefix}"
                    if (targetPlatform.getName() == "armeabi-v7a")
                        staticLibraryFile = file("${prefix}/libSuperpoweredAndroidARM.a")
                    else if (targetPlatform.getName() == "arm64-v8a")
                        staticLibraryFile = file("${prefix}/libSuperpoweredAndroidARM64.a")
                    else if (targetPlatform.getName() == "x86_64")
                        staticLibraryFile = file("${prefix}/libSuperpoweredAndroidX86_64.a")
                    else if (targetPlatform.getName() == "X86")
                        staticLibraryFile = file("${prefix}/libSuperpoweredAndroidX86.a")
                }
            }
        }
    }

    android {
        compileSdkVersion = 23
        buildToolsVersion = "23.0.3"

        sources.main {
            jni.dependencies {
                library "Superpowered" linkage "static"
                library "SuperpoweredDroidEar" linkage "shared"
            }
        }

        ndk {
            ldLibs.addAll(['log', 'android', 'c', 'OpenSLES'])
            abiFilters.addAll(["armeabi", "armeabi-v7a", "x86", "arm64-v8a"])
        }

        defaultConfig {
            applicationId = "edu.ucdavis.auditoryenhancer"
            minSdkVersion.apiLevel = 22
            targetSdkVersion.apiLevel = 23
            versionCode = 1
            versionName = "1.0"
        }

        task ndkBuild(type: Exec) {
            Properties properties = new Properties()
            properties.load(project.rootProject.file('local.properties').newDataInputStream())
            def ndkDir = properties.getProperty('ndk.dir')
            commandLine "$ndkDir/ndk-build", '-B', '-C', file('src/main/jni').absolutePath
        }

        tasks.withType(JavaCompile) {
            compileTask -> compileTask.dependsOn ndkBuild
        }
    }

    android.ndk {
        moduleName = "native"
    }

    android.buildTypes {
        release {
                minifyEnabled = false
                proguardFiles.add(file("proguard-rules.pro"))
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
}
```

**Comment by ggfan** [comment]
you are using ndk-build here, may you directly try on terminal/command line with ndk-build to see you have the issue from there?  

the settings inside the gradle may not be passed to ndk-build at all. if you have simply case and upload the code, maybe that is easier

**Comment by ggfan** [comment]
not sure this one is related: 
                library "SuperpoweredDroidEar" linkage "shared"
your pasted code portion does not have it configured, only have Superpowered

**Comment by entrity** [comment]
@ggfan :

Thanks for your response.

1. I have the same result when compiling on the command line as in Android Studio
1. It appears that the settings are getting passed because before I included `log` in my `ldLibs`, I was getting an undefined reference error for a function in the log library.
1. I have successfully used gradle 1.X, but I have not succeeded with 2.8. (With 2.8, the compiler says `Failed to apply plugin [class 'com.android.build.gradle.model.AndroidComponentModelPlugin'] Gradle version 2.10 is required.`

As for `library "SuperpoweredDroidEar" linkage "shared"`, you're right that the pasted code does not have that configured. I must have omitted it by accident, when trying to isolate my problem. Here is that configuration:

```
            SuperpoweredDroidEar {
                binaries.withType(SharedLibraryBinary) {
                    sharedLibraryFile = file("src/main/jniLibs/${targetPlatform.getName()}/libSuperpoweredDroidEar.so")
                }
            }
```

**Comment by ggfan** [comment]
commandLine "$ndkDir/ndk-build", '-B', '-C', file('src/main/jni').absolutePath

the above line, it meant to build for libnative.so to be used by your java code of System.loadlibrary("native"), or for the other 2 libs?

**Comment by ggfan** [comment]
could you confirm the above question?  my guess is you are using it to build libnative.so; which is not needed -- you are building twice for this lib, one by your ndk-build, one by Android Studio itself.

**Comment by ggfan** [comment]
looks like you get the thing under control now,  closing this, please re-open whenever you need to.  thank you!
