### ISSUE TITLE
hello third party cannot be imported

### ISSUE THREAD

**Issue by norani** [googlesamples/android-ndk#179]
I tried to import sample code of hello third party but "Sample Import Failed"

**Comment by ggfan** [comment]
yes, talked to owner of the import script owner, he said he was going to make a cl for it.  I will create a bug tmr for that too.

**Comment by proppy** [comment]
isn't hello-thirdparty gone?

**Comment by ggfan** [comment]
hello-thirdparty is removed from repo, the android import side need to do the same:  hello-thirdparty --> hello-libs

**Comment by ggfan** [comment]
this is fixed I think now.
