### ISSUE TITLE
static library in hello-libs

### ISSUE THREAD

**Issue by blackerpaper** [googlesamples/android-ndk#185]
There is a comment about how to use the static library (.a) in hello-libs sample.
But it didn't work.

It will work if:
[https://github.com/googlesamples/android-ndk/blob/master/hello-libs/app/build.gradle](url) line 57
change "library" into "project". Something like:
`project ':gperf' linkage 'static'`

So the comment in line 56 should be:
`// if gperf were *.a, change shared --> static and library 'gperf'--> project :gperf'`

**Comment by ggfan** [comment]
let me try it out:  the idea is to build a lib, distribute; clients get the lib/header files, and link to it in their app.  It is not the original goal to deliver another app to your customer so she/he could link the app into his app. 

please also provide more info when you get a chance  thanks

**Comment by ggfan** [comment]
I understand the confusion more now.  The nativeactivity is a little bit off the track to see what static lib   with lib distribution model: it demonstrates, well in a java proj way, how to build a AAR ( java ), and have application inside the same android project depends on it.  it is another usage way that when we do not want to distribute a lib to anyone else, but directly consume the lib inside the application [inside the same IDE project].  It is a way to organize the code to be more modularize...

The real lib model we are trying to demo with hello-libs is to decouple them: team A releases a lib to team B, and there is no source for the lib. 

For the static lib purpose, when AAR is built [select build for apk], a native static lib (*.a) will be spelled out in directory ./nativeactivity/build/intermediates/binaries/debug/lib, which is a by-product when building for AAR  -- it is a hacky way to get a static native library right now, at today :-)

modified endless-tunnel project to show how the static lib is configured, it is pushed into branch "static-lib-showcase". it compiles and runs on my N5X ( android N ).  feel free to have a look [ the libnative-activity.a was produced with a non-modiled endless-tunnel projects]

**Comment by ggfan** [comment]
to close the issue: the comment is correct, it should be:
   library 'nativeActivity' linkage 'static'
for static lib case.  thanks
