### ISSUE TITLE
Where is default AndroidManifest.xml?

### ISSUE THREAD

**Issue by norani** [googlesamples/android-ndk#186]
Before this, AndroidManifest.xml already provides the following : 

<uses-sdk
        android:minSdkVersion="13"
        android:targetSdkVersion="23" />

But now the AndroidManifest.xml file under C:\...\Hello-libs\app\src\main not contain the above code. 

I found another AndroidManifest.xml fileunder C:\...\Hello-libs\app\build\intermediates\manifest\androidTest\debug and it contain the above code. Which default AndroidManifest.xml shpuld I use?

**Comment by claywilkinson** [comment]
src/main/AndroidManifest.xml is the source manifest. The SDK versions are now added by the Gradle plugin during the build process (Android Studio uses Gradle to build).  If you are building without using Gradle/Android Studio, you'll need to add them manually.

**Comment by norani** [comment]
Oh I see. Thanks
