### ISSUE TITLE
Random() no longer working as intended in endless-tunnel 

### ISSUE THREAD

**Issue by crujose** [googlesamples/android-ndk#192]
In endless-tunnel/app/src/main/jni/util.hpp the following was changed from
```
int Random(int uboundExclusive);
inline int Random(int lbound, int uboundExclusive) {
    return lbound + Random(uboundExclusive - lbound);
}
```

to

```
int Random(int uboundExclusive, int lbound = 0);
```

The cpp file has the following:
```
int Random(int uboundExclusive) {
    int r = rand();
    return r % uboundExclusive;
}

int Random(int lbound, int uboundExclusive) {
    int r = rand();
    r = r % (uboundExclusive - lbound);
    return lbound + r;
}
```

The problem is that only the two-argument form is visible while the single argument form is unused.  This breaks nearly everything that used the single argument form.  For example, Random(100) becomes Random(100, 0), however, Random(100) was expected to return a number between 0 and 100 but now returns a number between 100 and 200.  

The game is not nearly as fun now :(

**Comment by ggfan** [comment]
let me take a look, thanks

**Comment by ggfan** [comment]
merged, to close this one soon. please kindly check it out, thank you!

**Comment by crujose** [comment]
Looks good, thanks!
