### ISSUE TITLE
Please re-enable native-media native player 

### ISSUE THREAD

**Issue by khirowatari** [googlesamples/android-ndk#193]
#182 says
> Tested: build on Mac, runs on Android-N/N5X
> Known Issue: native-media native player still is not working

I tested native player on Android M / Nexus 9, native player works. Android N / Nexus 9, not works.
It seems to be Android N preview bug.

Please revert https://github.com/googlesamples/android-ndk/commit/f9007017fd4f1e524b120f4714d21077de40fd1a

**Comment by khirowatari** [comment]
I reported Android N preview issue tracker
https://code.google.com/p/android/issues/detail?id=209410

**Comment by ggfan** [comment]
yes, I disabled it because I could not get it to work on native, only Java works.  I need find owner to fix it on native side.  let me confirm that the M still works: if it does, I will re-open it and we follow it with the other bug

thanks

**Comment by ggfan** [comment]
yes, indeed: it works on my Nexus 6 (M);  Nexus 5X ( N preview ) is not working. I will enabled it and file internal bug to link to your bug.  hope to get it fix soon

thanks

**Comment by ggfan** [comment]
@khirowatari please "LGTM" in this pull https://github.com/googlesamples/android-ndk/pull/194?  I will merge it in.  thanks

**Comment by ggfan** [comment]
merged, thank you!
