### ISSUE TITLE
Full screen mode disables hardware buttons

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-ndk#195]
I am running the Teapots and More Teapots samples, and they completely disable hardware buttons on the device.  Now I cannot even exit this app on Marshmallow since neither the home button, menu button nor back button are active.  
![nexus5x](https://cloud.githubusercontent.com/assets/201209/15122881/0e016fe4-15ef-11e6-986d-443d1082b5c2.png)
![nexus7](https://cloud.githubusercontent.com/assets/201209/15122883/110c17ca-15ef-11e6-8d22-6e88bd8c4b18.png)

See screenshots:

**Comment by IgorGanapolsky** [comment]
Never mind, I realize that I have to bezel swipe from top of the screen.  This will in-turn display the hardware buttons.  Kinda confusing and unintuitive...

**Comment by ggfan** [comment]
yeah, swift from bottom to top also bring it out.
