### ISSUE TITLE
Error:Could not find property 'manifest' on source set 'main'.

### ISSUE THREAD

**Issue by Kourtessia** [googlesamples/android-ndk#201]
Hi, 
"Error:Could not find property 'manifest' on source set 'main'" comes to console when I use following build.gradle
Note:experimental gradle plugin with version 0.6.0-beta5
build.gradle:
sourceSets {
            main {
                manifest.source {
                   include 'AndroidManifest.xml'
How include AndroidManifest with Gradle Experimental Plugin?

**Comment by ggfan** [comment]
If you put androidManifest.xml into ${project-dir}/app/src/main  [then it will be included automatically], it should work

**Comment by ggfan** [comment]
Hope you get your project compiled and run smoothly! I will close this one for now, feel free to re-open and/or adding additional notes at any time.  cheers
