### ISSUE TITLE
No tool chain is available to build for platform 'armeabi-v7a'

### ISSUE THREAD

**Issue by midoreigh** [googlesamples/android-ndk#202]
While running the sample NDK program Native Audio in Android studio I get the following error:

> Error:Execution failed for task ':app:compileNative-audio-jniArmeabi-v7aDebugSharedLibraryNative-audio-jniMainC'.
> No tool chain is available to build for platform 'armeabi-v7a': - Tool chain 'ndk-clang' (Clang): Could not determine Clang version: failed to execute clang -dM -E -.

How can I correct this error? Do I need to make a tool chain so that i can run the sample ndk program?

**Comment by ggfan** [comment]
which ndk version you are using?  for trial, may you do one of the followings:
1)  download ndk-r12  from  https://github.com/android-ndk/ndk/wiki,  scroll down to "current beta release", and point your android studio to use that version from native-audio/local.properties file
2) use your current ndk as-is, but comment out the following from native-audio/app/build.gradle
&nbsp;&nbsp; toolchain = 'clang'
 then it will gcc to build

**Comment by midoreigh** [comment]
@ggfan That solved the issue. Thank you.
