### ISSUE TITLE
565 palette conversion is wrong

### ISSUE THREAD

**Issue by SChalice** [googlesamples/android-ndk#204]
The green calc is off for the palette routine, it should be:

```
static uint16_t  make565(int red, int green, int blue)
{
    return (uint16_t)( ((red   << 8) & 0xf800) |
                       ((green << 3) & 0x07e0) |
                       ((blue  >> 3) & 0x001f) );
}
```

**Comment by ggfan** [comment]
that is true, actually.  the original code of:    
(green << 2) & 0x03e0)    
only uses 5 bits green, more like a 555 format processing.  do you have chance to create a pull request for it?  for both bitmap-plasma and native-plasma? if not I will create one and you could review it. 

good catch, thanks!

**Comment by ggfan** [comment]
ok, created a pull
https://github.com/googlesamples/android-ndk/pull/205

may you have a look and LGTM, I will merge it in. It is a bug, thanks.

**Comment by SChalice** [comment]
LGTM! Thanks
