### ISSUE TITLE
Remove armeabi-v7a 'hard float' support from gradle setting.

### ISSUE THREAD

**Issue by hak** [googlesamples/android-ndk#207]
As we won't support mixture of hard float and soft float convention, those setting need to be removed.

**Comment by ggfan** [comment]
Oops, mal-clicked.  this is interesting one,  any more info on this?

**Comment by ggfan** [comment]
Create the pull:  https://github.com/googlesamples/android-ndk/pull/217
those hardware floating pointer register/calling convention is going away from future ndk release. Flags will be gone, so we should remove them.

**Comment by ggfan** [comment]
merged, thanks!
