### ISSUE TITLE
This app seems not working on Samsung Galaxy S7 and S7 Edge

### ISSUE THREAD

**Issue by yctung** [googlesamples/android-ndk#208]
Sorry about this message. I think it works. (It didn't play the sound rightly initially but it is ok now)
Yu-Chih

**Comment by ggfan** [comment]
which app it is about?  thanks

**Comment by yctung** [comment]
Hi, sorry for the misleading.

I tried the audio-echo app. In the beginning, my phone doesn't play the
sound well. I uninstall the app and re-compile the app again and it works.
Than you for the asking.

Yu-Chih

On Fri, May 20, 2016 at 10:05 AM, Gerry <notifications@github.com> wrote:

> which app it is about? thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/android-ndk/issues/208#issuecomment-220614619>
>



-- 
Regards
Yu-Chih Tung

**Comment by ggfan** [comment]
thank you for update. At certain time I will have a double look at it: did it in a hurry, some portion might need to be re-arranged concerning pthread and audio buffer handling...
