### ISSUE TITLE
Unable to compile project

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-ndk#210]
I have imported your Hello-libs project.  I am unable to run the sample.  I get a C++ compilation error: 
> Error C++ debugger package is missing or incompatible.  See screenshot:
<img width="1422" alt="screen shot 2016-05-23 at 9 33 36 am" src="https://cloud.githubusercontent.com/assets/201209/15472534/9660e9a2-20c9-11e6-936a-aff02cb99762.png">

**Comment by ggfan** [comment]
May you click on the "Fix" to let it install LLDB debugger component? let's see what it will happen ( suppose to fix and runnable after update ) ...

**Comment by IgorGanapolsky** [comment]
Unfortunately now I get another error: 
> Unable to load class 'com.android.build.gradle.internal.NdkHandler'

See screenshot:
<img width="1134" alt="screen shot 2016-05-23 at 10 43 20 am" src="https://cloud.githubusercontent.com/assets/201209/15478797/90952e72-20ea-11e6-82ff-b21ebd7b678b.png">

**Comment by ggfan** [comment]
need some debug on my end:
  your OS :             window or Mac/Linux?
  your ndk-version: open your local.properties file, follow to your ndk.dir path, open source.properties, version is inside
 your target android OS version:
 your android studio version: ( I am not sure this one matters at all, just give to me for in case ) 

thanks

**Comment by IgorGanapolsky** [comment]
@ggfan 
- Mac OS El Capitan 10.11.5
- kg.Desc = Android NDK
- Pkg.Revision = 12.0.2867246-beta2
- targetSdk 23
- Android Studio 2.2 Preview 1

**Comment by ggfan** [comment]
got it, let me give 2.2 preview a try

**Comment by ggfan** [comment]
might be debugging some strange issue: I could build it with preview 2.2 and run on N5X api 23.  let me do a fresh pull from github.  may you try to clean up the project inside IDE (build -> clean project ), and go to terminal, rm -fr hello-libs/build hello-libs/app/build;  then retry build? just for safety, rebuild project twice.  

we have the similar settings, kind of strange

**Comment by IgorGanapolsky** [comment]
I've done clean/rebuild.  Are we on the same ndk version?

**Comment by ggfan** [comment]
yes it is the same version of NDK 12 beta2.  let's back up a little bit?  try to build another one: like hello-jni, see if you could get through; that would narrow down to android studio or sample related.  thanks ( it is a try, not much clue )

**Comment by IgorGanapolsky** [comment]
Same problem with HelloJNI.  It tells me 
> Instant Run requires a newer version of the Gradle plugin.  
Then when I click the red **Update Project** button, it errors out with:
> Error updating to new Gradle version.

**Comment by ggfan** [comment]
Ok, now we get focus on Android Studio itself. Check you are enabling gradle wrapper:
Android Studio --> Preference --> Build, Execution, Deployment --> Gradle  page, make sure "Use default gradle wrapper"

**Comment by IgorGanapolsky** [comment]
**Default** gradle wrapper is selected.  Oh snap, I just clicked **Fix**, and then it downloaded LLDB 2.2.  Now it seems to work.  But that **fix** button is still red, and I have to click it every time to re-download LLDB 2.2.  Very strange!
![screen shot 2016-05-23 at 5 00 35 pm](https://cloud.githubusercontent.com/assets/201209/15484416/e5256a16-2107-11e6-8af2-bc9105515012.png)

**Comment by ggfan** [comment]
seems some issue with 2.2 version, I could not replicate it, may you kindly put the detail procedure so I could use to ask around? really like to see it on my end.

thank you so much for bringing it up!

**Comment by IgorGanapolsky** [comment]
@ggfan See screen recording of the problem in HelloJNI sample: https://www.dropbox.com/s/77npmr0oy5oym75/recording.mov?dl=0

**Comment by ggfan** [comment]
ok. I will give it a shot soon and update here.

**Comment by ggfan** [comment]
tried to replicate, not able to see what you are seeing:
  1) delete android studio, ~/.AndroidStudio*, ~./lldb [I do not know why I delete those though]; redownload 2.2 preview from tool.android.com, and install
  2) get a new copy of the samples from github
  3) open android studio 2.2 preview 1, select "Import project (Eclipse ADT, Gradle, etc)", browse and open hello-jni ( i used master branch )
  4) build and runs ok.

I definitely missed something from your environment which prevent me from seeing it. may you try run on an emulator maybe? my emulator is device Nexus_5_API_23_x86. to be honest, I do not think it matters.

**Comment by IgorGanapolsky** [comment]
@ggfan No dude.  You need to uninstall lldb from SDK Manager.  Then re-install LLDB.  Android Studio binary has nothing to do with it.

**Comment by ggfan** [comment]
Ok, thanks! my android studio somehow could not see sdk at all inside "Appearance & behavior" --> System Settings". maybe yours is related to this one:
  https://code.google.com/p/android/issues/detail?id=204760

Looks you got it fixed, that is great :-).  kindly close it when you get a chance, thank you again
