### ISSUE TITLE
hello-jnicallback JNI_OnUnload never called

### ISSUE THREAD

**Issue by khirowatari** [googlesamples/android-ndk#212]
hello-jnicallback sample uses JNI_OnUnload to clean up function.
But JNI_OnUnload never called on android generally.
This sample cause misunderstanding for Android-JNI newbie.

**Comment by ggfan** [comment]
Oh, that is I do not know and let me check and fix it.

**Comment by ggfan** [comment]
yeah, it is never get called indeed. created 2 pulls to fix it -- one for each branch. also pulled out pthread mutex management into start/stop ticks so we have get a good control.  @	khirowatari, please kindly review and LGTM if they are ok to you:
  https://github.com/googlesamples/android-ndk/pull/215
  https://github.com/googlesamples/android-ndk/pull/214

thank you for pointing it out!

**Comment by ggfan** [comment]
merged, closing it. Thanks for reviewing the change!
