### ISSUE TITLE
libwepb sample

### ISSUE THREAD

**Issue by makoy21** [googlesamples/android-ndk#219]
Can you included sample for libwebp, how can i use it in android studio.

https://developers.google.com/speed/webp/faq#how_do_i_use_the_libwebp_java_bindings_in_my_android_project

**Comment by ggfan** [comment]
Sure, let me find time to check it out, thanks

**Comment by ggfan** [comment]
some experiment is here:
  https://github.com/ggfan/playground/tree/master/android

decode webp file and display into native window's buffer directly.  I will clean it up and try to merge it somewhere.  It is like a hello-webp 

the good thing is webp team will integrate android cmake build into source tree, so pretty soon your app could just  checkout out the latest webp source, use
add_subdirectory(webp-dir)
include_directories(for-header-files)
and ready to go.

**Comment by ggfan** [comment]
adding a sample with:
  https://github.com/googlesamples/android-ndk/pull/279

may you have a look? I like to merge it in before switching branch, so LGTM if you are ok.  thanks

**Comment by ggfan** [comment]
merged, closing this one
