### ISSUE TITLE
Android NDK Master hello-libs sample not working in Android 4.1.1 Api 16

### ISSUE THREAD

**Issue by chandraprakash5** [googlesamples/android-ndk#223]
Could not load library "libgmath.so" needed by "libhello-libs.so" error is thrown. Please take a look at call stack and let us know the reason for this. Let me know if some more information is required to reproduce the issue.

```
D/dalvikvm( 1225): Trying to load lib /data/app-lib/com.example.hellolibs-1/libhello-libs.so 0x40cd5ba0
E/dalvikvm( 1225): dlopen("/data/app-lib/com.example.hellolibs-1/libhello-libs.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libgmath.so" needed by "libhello-libs.so"; caused by load_library(linker.cpp:745): library "libgmath.so" not found
W/dalvikvm( 1225): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/example/hellolibs/MainActivity;
W/dalvikvm( 1225): Class init failed in newInstance call (Lcom/example/hellolibs/MainActivity;)
D/AndroidRuntime( 1225): Shutting down VM
W/dalvikvm( 1225): threadid=1: thread exiting with uncaught exception (group=0x40a71930)
E/AndroidRuntime( 1225): FATAL EXCEPTION: main
E/AndroidRuntime( 1225): java.lang.ExceptionInInitializerError
E/AndroidRuntime( 1225): 	at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime( 1225): 	at java.lang.Class.newInstance(Class.java:1319)
E/AndroidRuntime( 1225): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1054)
E/AndroidRuntime( 1225): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2097)
E/AndroidRuntime( 1225): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
E/AndroidRuntime( 1225): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime( 1225): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
E/AndroidRuntime( 1225): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1225): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1225): 	at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime( 1225): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1225): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1225): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 1225): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 1225): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1225): Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libgmath.so" needed by "libhello-libs.so"; caused by load_library(linker.cpp:745): library "libgmath.so" not found
E/AndroidRuntime( 1225): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime( 1225): 	at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime( 1225): 	at com.example.hellolibs.MainActivity.<clinit>(MainActivity.java:36)
E/AndroidRuntime( 1225): 	... 15 more
W/ActivityManager(  278):   Force finishing activity com.example.hellolibs/.MainActivity
```

**Comment by ggfan** [comment]
which branch do you downloaded code ? master is for gradle-experimental,  master-cmake is for the cmake plugin,  let me know, I will check it out  thanks

**Comment by chandraprakash5** [comment]
Yes, its the master branch indeed. After decompressing the apk, I found that libgmath.so, libgperf.so, libhello-libs.so are all present under "<path_to_decompressed_apk>/lib/armeabi-v7a/" folder . The same apk works for Kitkat, Lollipop and Marshmellow. Let me know if you need more information.

**Comment by ggfan** [comment]
yes, I need learn more details about which android version sets the difference: For now, you could do this:
 inside MainActivity.Java,  find loading library portion and load all libraries manually,  like:
    static {
        System.loadLibrary("gmath");
        System.loadLibrary("gperf");
        System.loadLibrary("hello-libs");
    }
[note that sequence matters]

if you see compiling error for that debug print of PRIu64, you could comment it out on your machine and get it going.

**Comment by ggfan** [comment]
not able to find something solid for it, likely those have be loaded by app so on those old platforms, hope this workaround ( app explicitly loading ) works for you, let me know please

**Comment by chandraprakash5** [comment]
The problem is on devices with API version less that 18. On API version 18, things run perfectly fine.
This workaround works for me (tested on API version 17) but still it would be great if you can fix this issue. I have a music analysis app where I have to depend on 15 shared libraries, so loading all the libraries in the correct order, in every class that uses JNI calls would be cumbersome.

**Comment by ggfan** [comment]
tracking it with internal an internal bug for this. I would be patient for this due to priority things etc., hope you are moving along in the meant time: it is clumsy/annoying to put the libs in the right order to load them.

**Comment by ggfan** [comment]
turned out it was there:
  https://code.google.com/p/android/issues/detail?id=34416.  --
"this is in jb-mr2."

The fix need to do a platform update, rated "infeasible" for now for earlier android versions.  So please use the workaround for your project on platforms older than jb-mr2. It is sad but hope the WorkAround could get your app through.

**Comment by chandraprakash5** [comment]
Yes, the workaround works fine.
