### ISSUE TITLE
cmake and dubug in Android Studio

### ISSUE THREAD

**Issue by beeender** [googlesamples/android-ndk#228]
Is it possible to use cmake and debugging native code in Android Studio right now?

The ReadMe of `master-cmake` branch guide me to https://codelabs.developers.google.com/codelabs/android-studio-jni/index.html?index=..%2F..%2Findex#0 which is still the document of experimental plugin.

If it is not possible right now, maybe the readme should be updated ...

**Comment by ggfan** [comment]
yes, it is the same process as that one, it works with 2 trials ( the first time my app did not install ).  just does not have "app-native" under "edit configure" anymore, use "app", and "debug" button.

I need update the doc in README to reflect that.  thanks

**Comment by beeender** [comment]
After updating to AS 2.2 Preview 3, debugging works!
Thanks for the help. You can close this issue if you want.

**Comment by ggfan** [comment]
thanks!
