### ISSUE TITLE
NDK Open SLES SLPlayItf uriPlayerPlay Not Working

### ISSUE THREAD

**Issue by developeruk** [googlesamples/android-ndk#229]
When running the example code to play the audio stream from a URL using URI player (SLPlayItf uriPlayerPlay). Either nothing plays, or after clicking on the "URI Soundtrack" Button in the example, followed by "Play URI" Button, it will throw a crash, with the following spewed out into the log:-

"A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 2880 (ALooper)

```
    [ 06-10 08:25:05.426  1177: 1177 W/         ]
    debuggerd: handling request: pid=2364 uid=10061 gid=10061 tid=2880"
```

**Comment by ggfan** [comment]
replicated it, having a look now

**Comment by ggfan** [comment]
android::CreateHTTPServiceInCurrentJavaContext()  [inside ALooper::lopp()] SIGSEGV for invalid address ( null pointer access ).  opening an internal bug to track this: b/29321867

**Comment by wangii** [comment]
any update? thanks.

**Comment by TheFakeMontyOnTheRun** [comment]
Got the same results - device is Nexus 6 running Android 6.0.1

**Comment by ggfan** [comment]
Oops, this was totally get dropped.   Need to follow-up.

**Comment by TheFakeMontyOnTheRun** [comment]
In fact, I got pretty much a very erratic behavior.

**Comment by ggfan** [comment]
I need to work on this one according to internal bug b/29321867,  will see what I could do.

**Comment by TheFakeMontyOnTheRun** [comment]
Thanks! I'm willing to help testing things out if you need.

**Comment by ggfan** [comment]
thanks: hope to have something soon, working on internal bug thread.

**Comment by ggfan** [comment]
Looks like this bug might need time to get it fixed. What the best scenario is to use Java side of player [that works] for the time being. If the fix goes into the framework, the fix probably will not get into L/M/N [this is my guess, no basis], anyhow will probably not help to your current project[s].  I am sorry to say that you have to use java player; on the other hand, urlPlayer is calling java side function to do the work, app may not expose too much of loss.

Thank you for filing the issue, and to prevent this from happening again, it is better to remove uriPlayer portion from the sample to avoid future confusions.

**Comment by TheFakeMontyOnTheRun** [comment]
Thank you for the openness!
I've been cooking my own C++ <-> Java bridge in a very OpenAL-like interface ever since I came here to support the issue. Now I don't feel so bad in doing it so (and I'm surprised on how it "doesn't suck as much as I expected" ;-P )

**Comment by ggfan** [comment]
It is not a very good picture, TBH. hope you are still able to get the very best at the give situation for your app and be optimistic about future versions ( it should be validated in future OS releases )

**Comment by TheFakeMontyOnTheRun** [comment]
Considering that I have the same code in Android, Desktop Linux and Emscripten behaving *almost* the same way (even with the "sound bridge" to Java), I would say I could be in worst situations ;-)

I'm writing my raw PCM data to AudioTrack - would you suggest something else?

**Comment by ggfan** [comment]
I personally do not know, may you post the question to Android-NDK forum, most content related questions would be helped in this place:  https://groups.google.com/forum/#!forum/android-ndk
[worth a try]

**Comment by TheFakeMontyOnTheRun** [comment]
Thank you!

**Comment by ggfan** [comment]
all of the best [ it is shy situation ]!

**Comment by kaplad** [comment]
Any updates? :)

**Comment by ggfan** [comment]
not yet, will follow-up ( Oboe is having higher weight ).

**Comment by kaplad** [comment]
Any updates? :)

**Comment by ggfan** [comment]
Ok, I will pick it up here, sorry for it.

**Comment by ggfan** [comment]
this one will be delayed again: will look at this after the other one is done. Owner of uriPlayer ( OpenSL ES ) aware of the issue, just the priority thing.

**Comment by kaplad** [comment]
Thank you @ggfan ! :)

**Comment by blausand** [comment]
Also curious about a solution here.
Would we also get the individual channels of e.g. a 5 channel stream and be able to dynamically downmix that on the client?

**Comment by ggfan** [comment]
Oh, have not looked at this for a long while. Probably need to the trace the framework code as Android P is the focus to audio team. I will try after I get my current things handled

**Comment by ggfan** [comment]
Working on it

**Comment by kaplad** [comment]
Thank you @ggfan !

**Comment by ggfan** [comment]
yeah, just created CLs.

It is sad story as this is broken in a few OSes. TBH, it means you will probably never use it anymore:
- app will need to use its own way to stream
- once that works, even OS is fixed, all will very unlikely go back to use URI Player's streaming ( which needs to use different paths in app, based on different OS version )
[Oboe](https://github.com/google/oboe) is the right way to do it, at least from this specific standing point of view: only keeping key audio code in OS, others in open-source lib ( which could be fixed at any time ). 
more CTS would prevent this from happening again; promptly debugging sample content related issues would avoid overlay heavy damages too.
