### ISSUE TITLE
Unable to use Jack compiler

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-ndk#233]
Hello,
the Jack compiler in Android Studio requires gradle 2.13.  However, your project throws an error:
`Failed to apply plugin [class 'com.android.build.gradle.model.AndroidComponentModelPlugin']

> Gradle version 2.10 is required.`

Is there a way to update to gradle 2.13 with the NDK toolset?  I mean, I wish to incorporate your **hello-libs** sample into my project and build on top of it, while using Jack compiler.

Thank you,
Igor

**Comment by ggfan** [comment]
you are probably using gradle experimental plugin? my guess then was the model plugin is changing too much from version over version, the experimental plugin has to be tight closely with that model version ( which is inside gradle ), model in new gradle version may not work, so they have to check with ==, not >= for gradle version. I will confirm that

**Comment by IgorGanapolsky** [comment]
I am indeed using the experimental plugin
'com.android.tools.build:gradle-experimental:0.7.0'

**Comment by rschiu** [comment]
Jack shouldn't require 2.13.  It should work with 2.10 as well.  Consider trying the latest preview experimental plugin version 0.8.0-alpha3 that requires Gradle 2.11.  There are a few Jack related fix there.

**Comment by IgorGanapolsky** [comment]
I also updated to `buildToolsVersion = '24.0.0'`.  But getting this error now:
> IllegalStateException: @NotNull method com/android/tools/idea/run/GradleApkProvider.getApk must not return null

**Comment by rschiu** [comment]
Would you also happen to have "com.android.tools.build:gradle" on your buildscript classpath?  If so, try updating that to version 2.2.0-alpha3.

**Comment by ggfan** [comment]
this is now needed 2.14.1 version for version 0.8.0-alpha7, then it is not a problem for you anymore, correct?

**Comment by ggfan** [comment]
close it for now as experimental plugin is not a thing anymore...
