### ISSUE TITLE
Hello JNI in master-cmake branch not building.

### ISSUE THREAD

**Issue by graph** [googlesamples/android-ndk#235]
[Branch](https://github.com/googlesamples/android-ndk/tree/master-cmake/hello-jni)
> Step 5 Click Tools/Android/Sync Project with Gradle Files.

Don't see android/sync see screenshot below

![screen shot 2016-06-23 at 3 51 29 pm](https://cloud.githubusercontent.com/assets/1088059/16317940/c0f5e8d0-395a-11e6-8438-3485a73f9fa2.png)

Also got these errors if I try `./gradlew build`

```
hello-jni$ ./gradlew build
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Could not find com.android.support.constraint:constraint-layout:1.0.0-alpha2.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/constraint/constraint-layout/1.0.0-alpha2/constraint-layout-1.0.0-alpha2.pom
         https://jcenter.bintray.com/com/android/support/constraint/constraint-layout/1.0.0-alpha2/constraint-layout-1.0.0-alpha2.jar
         file:/Users/ben/.local/android/android-sdk/extras/android/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha2/constraint-layout-1.0.0-alpha2.pom
         file:/Users/ben/.local/android/android-sdk/extras/android/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha2/constraint-layout-1.0.0-alpha2.jar
         file:/Users/ben/.local/android/android-sdk/extras/google/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha2/constraint-layout-1.0.0-alpha2.pom
         file:/Users/ben/.local/android/android-sdk/extras/google/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha2/constraint-layout-1.0.0-alpha2.jar
     Required by:
         hello-jni:app:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.176 secs
```

And I cannot install the constraint packages from SDK Manager as it fails to install them.

**Comment by ggfan** [comment]
your android studio may not the latest of 2.2 preview 3:  the project was re-generated with new android studio, it uses this new feature.  may you check your version and if not the version, download from here:
   http://tools.android.com/download/studio/canary
Also it needs ndk release 12, https://developer.android.com/ndk/downloads/index.html

let me know if you still have the problem ( I am building it on Mac ) which is close to your, if not exactly the same OS.

thanks

**Comment by graph** [comment]
After some flailing around I got it to compile, and managed to install the constraint layout.

Patch includes a git diff for your convenience.

[patch.txt](https://github.com/googlesamples/android-ndk/files/330757/patch.txt)

**Comment by ggfan** [comment]
thanks!  
--- a/hello-jni/app/src/main/res/layout/activity_hello_jni.xml
+++ b/hello-jni/app/src/main/res/layout/activity_hello_jni.xml
@@ -11,9 +11,7 @@
         android:layout_width="wrap_content"
         android:layout_height="wrap_content"
         android:text="Hello World!"
-        app:layout_constraintBottom_toBottomOf="@+id/activity_hello_jni"
-        app:layout_constraintLeft_toLeftOf="@+id/activity_hello_jni"
-        app:layout_constraintRight_toRightOf="@+id/activity_hello_jni"
-        app:layout_constraintTop_toTopOf="@+id/activity_hello_jni" />
+        android:layout_centerInParent="true"
+    />

constraint are not used anymore, I guess.  Other things are ok to me ( I let studio help me update the versions ). 

I will keep this in mind and send your file to experts too.  thanks again!

**Comment by ggfan** [comment]
I am pretty sure you are not using Android Studio 2.2 preview 3: and you updated to a newer one. The samples are for alpha3; some features like passing the parameters to cmake will be different, so you might get a little surprised.

**Comment by graph** [comment]
Yes Iam using Android Studio 2.2 preview 4. That might be why. Thank you :).

@ggfan do you know if there is any documentation for the new cmake setup? I do alot of C++ on android and am really looking forward to the cmake setup android studio preview 2.2 is introducing.

Thank you.

**Comment by graph** [comment]
I see https://code.google.com/p/android/issues/entry?template=Developer%20Documentation it has documentation option did not notice that :+1:

**Comment by ggfan** [comment]
yes, there will be soon a doc coming up here:
  http://tools.android.com/system/app/pages/search?scope=search-site&q=cmake
the second link. if you are internal, drop me a message @gfan 

the format to pass variables to cmake script is in sample gles3jni;  ndk variables that useful to cmake scripts are used in Teapot when building native-app-glue ( ANDROID_ABI, ANDROID_NDK), all of them are at file: ${your-sdk}/cmake/android.toolchain.cmake, pretty good documentation inside there; most of them are read-only.

hope it helps.

**Comment by graph** [comment]
Thank you, yes the in-code documentation helps, I trust that will be transferred to the online documentation resources later. If by internal you mean work at google, I don't. If you'd like you can find my email [in this feature request](https://code.google.com/p/android/issues/detail?id=214218&can=4&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened)  I reported and contact me. I'll be more than happy to share thoughts, opinions & other info that would help make the NDK android development great.

I got Ogre3D to compile and in progress getting it to link into an android app using the new cmake way in android studio. Depending on how things go will determine how fast & when we migrate new & existing projects.

**Comment by ggfan** [comment]
yes, online doc will come for sure;  will certainly pass your info to doc-owner: they are extremely swamped by the work load so might take some time. as a fact, the company is a internet company, so you would safely bet and win that everything possible will be online eventually  :-). Thank you again, and tell us more about your migration process or add it to that bug, it definitely will help!

**Comment by graph** [comment]
Hi ggfan, 

I have posted [info for NDK internals for better CMake](https://code.google.com/p/android/issues/detail?id=214383&can=4&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened) as a feature request. I got a 500 error the first time so there is a duplicate of the same thing you can see the duplicate [by searching my name](https://code.google.com/p/android/issues/list?can=2&q=benzakhar&colspec=ID+Status+Priority+Owner+Summary+Stars+Reporter+Opened&cells=tiles). If you can make sure the relevant parties see this that would be appreciated, if not I'm sure they will find it browsing the bug reports. Really it's things to consider based on the issues I have with the current build NDK build system. And I see cmake route doing very good as it's a great path with lots of potential.

Thank you.

**Comment by ggfan** [comment]
Hey graph,
 thank you very much! they will be reviewed by internal experts for sure.
