### ISSUE TITLE
how to set LOCAL_SRC_FILES in gradle.build ?

### ISSUE THREAD

**Issue by liuchenx** [googlesamples/android-ndk#242]

**Comment by ggfan** [comment]
- with gradle experimental plugin
you just tell the source directory: it is at directory granularity.  All source files under the directory will recursively be included into the build:  The file types considered source files are gnu defined file types (refer to http://labor-liber.org/en/gnu-linux/development/extensions, but list may not be exact).
then if there are files that could not be compiled together, you could use "exclude", which will excludes all files with that name from compiling, does not matter where it locates and how many copies they are. All samples in master branch of this repo use this method.  By default, the directory is at app/src/main/jni, if your source is there, no need to configure anything at all.

- with CMake ( in master-cmake branch of this repo ):  add_library() is the place to list all of the source files. It is more decent and you have all control for files: it is a list of file names, or with wildcard. Anyway this a straight cmake business  :-)

if you are talking about the libraries, they are dealt differently than source files. This is different from ndkBuild's android.mk where LOCAL_SRC_FILES could be a 3rd party lib. Gradle experimental / cmake have their own solution and will not "tolerate" it :-)

**Comment by ggfan** [comment]
closing this one, feel free to re-open if needed.  thanks
