### ISSUE TITLE
Error:A problem occurred configuring project ':lib'

### ISSUE THREAD

**Issue by sevar83** [googlesamples/android-ndk#243]
> Error:A problem occurred configuring project ':lib'.

Happens on Gradle Sync if I add

```
externalNativeBuild {
        ndkBuild {
            path "src/main/jni/Android.mk"
        }
    }
```

Tried targeting 23 and 24, tried to put it in the app module - same sh!t.

**My configuration:**

Gradle 2.10
classpath 'com.android.tools.build:gradle:2.2.0-alpha4'
Android Studio 2.2 P4

**Comment by ggfan** [comment]
not knowing too much experience with ndk-build.  for cmake, even I have error, if I force it to build ( bypass sync ), in gradle window, it points me which line of CMakeLists.txt  is the problem.

you could download master-ndkbuild branch from this repo to have a look at those samples: they are all ndkbuild samples, buildable with android studio preview 4 + ndk r12.  my ndkBuild support is very thin though: best effort.

**Comment by ggfan** [comment]
I think understood what is the problem: I did not check in local.properties file in any of the samples. It contains the ndk and sdk location on your local system: my file does not work for yours even I check it in, but it will throw one error when you open the project, since you do not have that file at all, when you open the project, it will complain with different error.  The real problem might be:  your ndk is not configured in this file, only have sdk.dir.  May you check it:
 in your ${project}/local.properties file, do you have a ndk.dir setting together with sdk.dir?
  it should be something like (yours does not have ndk.dir):
  ndk.dir=/Users/username/dev/sdk_current/ndk-bundle
  sdk.dir=/Users/username/dev/sdk_current

**Comment by sevar83** [comment]
Adding my `ndk.dir` in `local.properties` fixed it! Thanks! Some suggestions: please document what are these "targets" in docs for the external build system. Also include a sample with APPLICATION.MK. And it's quite strange that the experimental work happens on the master branch. Might confuse some people.

And one important question you might know the answer: How to setup native debugging with external ndk-build? http://stackoverflow.com/questions/38080385/debugging-android-native-code-with-custom-android-mk-build

**Comment by ggfan** [comment]
just add that 
  arguments "-DNDK_DEBUG=1" in your gradle inside default config enclosure, like:

defaultConfig {
   ndkBuild {
         arguments "-DNDK_DEBUG=1"
 }
}
I might spell it wrong somewhere if it does not work for you ( I used it and it worked). There is a bug in tools.android.com page mentioning about this.  I think this option will be added in as default so you have no trouble.  Anyhow if you tried and does not work, drop a message, I will find exact syntax for it

will add application.mk there once the option is available (pretty soon). 

As for branch, yeah, thank you for your comment. after cmake settle down, cmake will be master branch, and experimental will be master-experimental.

**Comment by sevar83** [comment]
10x for the help! When I set `NDK_DEBUG` flag I get linker errors for several symbols `relocation truncated to fit: R_ARM_THM_CALL against symbol ...`. Have no idea what is this!

**Comment by ggfan** [comment]
that is real thing: I did not see it before. command line builds fine? only problem when using android studio with ndk-build?

**Comment by sevar83** [comment]
Nope, on the command line is the same. Here's one error message in all it's "glory":

:(.text._ZN10spatialite6dbopenEP7_JNIEnvP8_jobjectP8_jstringi+0x10e): relocation truncated to fit: R_ARM_THM_CALL against symbol `sqlite3_enable_load_extension' defined in .glue_7 section in linker stubs

How could you not love Android NDK development! :D

**Comment by ggfan** [comment]
Sorry I do not know what it is.  if possible, upload your code to somewhere on github or sharable place, I could hack on it and seek help today or tmr ( after tmr I will not be online for 3 weeks ); Or you file a bug on https://github.com/android-ndk/ndk/issues

**Comment by sevar83** [comment]
Ok, I have it on bitbucket. You could send me your email or username to share the repo with you. It's private and I don't wish to open it publicly. My email is sevarbg@gmail.com.

**Comment by ggfan** [comment]
closing down this one: working offline and seems ok now.  feel free to re-open at any time

**Comment by sevar83** [comment]
Just to write down the things that made it work:

- Problem 1: 
`:(.text._ZN10spatialite6dbopenEP7_JNIEnvP8_jobjectP8_jstringi+0x10e): relocation truncated to fit: R_ARM_THM_CALL against symbol sqlite3_enable_load_extension defined in .glue_7 section in linker stubs`

fixed by setting `APP_PLATFORM := android-15` in `APPLICATION.MK`

- Problem 2: 
How to setup native debugging with external ndk-build? http://stackoverflow.com/questions/38080385/debugging-android-native-code-with-custom-android-mk-build

The fix was complex, because the development is in active phase. As far as I understood in Android Studio 2.2+ is used LLDB debugger instead of GDB. In order for LLDB debugging to be set up (assign the symbols directory, include/source directories, etc.): 
1. use Android Studio 2.2 Preview 5 (coming soon) or newer
2. gradle plugin 2.2-alpha5 or newer
3. use the new `externalNdkBuild` gradle notation. (I suppose it does the LLDB setup behind the scenes. Only using `ndk-build` command seems not enough. It just sets the legacy GDB up. Nothing about LLDB.)
4. Set the proper symbols directory in the debug configuration (maybe this step is not really required). For example `build/obj/local/armeabi-v7a' if debugging on ARM.

**Comment by luorenyu** [comment]
I met the same issue。and my problem is that i forget add the ndk.dir to the local.properties.when I add my ndk.dir .it works!
     ndk.dir=E\:\\develop\\Android\\android-ndk-r14b

hope to help you
