### ISSUE TITLE
audio-native with Cmaker - Embedded Soundtrack Problem (assertion "0 <= fd" failed)

### ISSUE THREAD

**Issue by mrodrigues26** [googlesamples/android-ndk#244]
I get this error when I try to play the embedded soundtrack:
A/libc: /home/mateus/AndroidStudioProjects/native-audio/app/src/main/cpp/native-audio-jni.c:719: Java_com_example_nativeaudio_NativeAudio_createAssetAudioPlayer: assertion "0 <= fd" failed
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 9188 (ple.nativeaudio)

**Comment by ggfan** [comment]
I will have a look at this

**Comment by mrodrigues26** [comment]
Thank you! I run DEBUG 'app' option and I get this:

![screenshot from 2016-06-30 12-43-50](https://cloud.githubusercontent.com/assets/20213807/16487078/82eb3ad4-3ec0-11e6-9908-adf245d40890.png)
I

**Comment by ggfan** [comment]
yes, I replicated it: it pretty simple to see.  I will see how this happens -- used to be working.

**Comment by mrodrigues26** [comment]
I was just curious with this new gradle and cmake, but I will stay with the experimental one for now because this problem. Thanks for the help!

**Comment by mrodrigues26** [comment]
I update to Android Studio 2.2 Preview 5, changed the line
_distributionUrl=https://services.gradle.org/distributions/gradle-2.10-all.zip_
to
_distributionUrl=https://services.gradle.org/distributions/gradle-2.14-all.zip_

and now the problem it's solved!
