### ISSUE TITLE
Linker failed while linking libaccelerometergraph.so

### ISSUE THREAD

**Issue by pklepagolsat** [googlesamples/android-ndk#249]
I have dowloaded the android-ndk _sensor-graph_ example few days ago and it worked just fine. Now, on a different PC, running Android Studio 2.1.2 and the latest NDK bundle, building the project get me to this error:

> FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':accelerometer:linkAccelerometergraphArmeabi-v7aDebugSharedLibrary'.
> > A build operation failed.
>      Linker failed while linking libaccelerometergraph.so.
>  See the complete log at: file:///C:/PoCs/sensor->graph/accelerometer/build/tmp/linkAccelerometergraphArmeabi-v7aDebugSharedLibrary/output.txt
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log >output.

Am I doing something wrong? Shouldn't it be working just the same?

**Comment by ggfan** [comment]
maybe you could run from command line at ${project-path}/gradlew assembleDebug, and see what the real error is?

with your other machine working,  it is also an windows system?

No code change for that sample for months, only script file changes.

**Comment by pklepagolsat** [comment]
Both machines were running on Windows 10.

I ran from the command line and got the same error to pop. Also, there's this 

> :accelerometer:linkAccelerometergraphArmeabi-v7aDebugSharedLibrary FAILED

I ran the debug with --info and accessing the output log, I get various "Multiple definition errors of" functions like drawFrame, init, pause, resume, surfaceChanged, among others in the sensorgraph.o file. The definitions are in different folders in the same directory (_C:\PoCs\sensor-graph\accelerometer\build\intermediates\objectFiles\armeabi-v7aDebugSharedLibrary\accelerometergraphMainCpp\e0mq5ya9ljftr5elr0fn6x8pi\sensorgraph.o_).

I tried deleting two of the three definitions and it, not surprisingly didn't work just the same.  Yet it did clean the log, leaving me nothing to work with.


On a side note: I'm a noob and mostly don't understand what i'm doing

**Comment by pklepagolsat** [comment]
Well, i tried unzipping and executing it again and it worked like a charm. I suppose because I had previously runned on another machine and then unzipped something went out of the way.

**Comment by ggfan** [comment]
On the second machine, you get the source code from the first machine, not directly from github? if that is the case, you will have to manually delete a couple of intermediate directories from ${project-dir} like:
- app/build
- build
- app/externealNativeBuild
- remove all *.iml files

then it will be ok, I think.  those intermediate dirs carry too much of your old machine path, and cleaning project won't delete them.
