### ISSUE TITLE
Build static native library using Gradle

### ISSUE THREAD

**Issue by senagbe** [googlesamples/android-ndk#250]
Hi,

It appears that there are several examples of using static libraries, however I can't find any information on how to create a static library using Gradle. I know how to do it using the Android.mk but its not obvious to me how I might duplicate that functionality using my build.gradle.

Any help would be appreciated. Many thanks in advance.

**Comment by ggfan** [comment]
using CMake is too simple, the example is inside branch master-cmake sample hello-libs, directory gen-lib.

using gradle-experimental directly, no.  But indirectly, you might be able to do it, follow Teapot example, app-native-glue, it force to build one aar for it; to do that, as a by-product it spell one *.a file.  Check it out on Teapot, and build an APK(make sure build an APK ) for app, grep to see if *.a is there for the app-glue in the intermediate folder somewhere. It is a hack

**Comment by ggfan** [comment]
closing this one for now. Please reopen if more is needed.  thanks

**Comment by destenson** [comment]
So your solution is to build the static library as an AAR library, and then manually copy the .a file that's generated as a sub-step of the APK & copy it manually into another project? And that sounds like a legitimate solution to you?

**Comment by ggfan** [comment]
:-) to generate a static lib, cmake and ndk-build having their ways. that should be solution.  with Gradle build, do you specifically mean using gradle-experimental plugin? in that case, I do not think there is a direct way.

**Comment by destenson** [comment]
I've had success using each of the three ways to build shared libraries, and android apps. I've had less success using them to build static libraries. And even less success using the shared libraries I build from another project, short of manually copying the binaries into a jnilibs directory. In particular, I have had a very difficult time trying to build libraries that are an integral component of a bigger project and use them easily from the overarching project. Admittedly, I'm fairly inexperienced with NDK in general, but I definitely think there's a lot of work yet to be done making this easier to use, and easier to integrate into a bigger picture.

**Comment by ggfan** [comment]
Agreed 100% with your final comment" there's a lot of work yet to be done making this easier to use, and easier to integrate into a bigger picture"!

If the static lib is used inside the SAME workspace ( for the same project in Android Studio's term), it  should work in the above 3 ways.

When you want to release a static lib ( build in one project, and give to another project), need to hack ( mainly copying out from intermediate directory ), out of which, android.mk way is more natural to normal C/C++ developers ( too personal ) I think.

The special notice probably getting in the way:  lib you publish, and the apps your customers use, should be built with the same:

- toolchain ( gcc or clang )
- stltype ( gnustl/c++ _ shared/static) ==> this seems to be significant

thank you for your comment, for some examples, you could upload your app for build issues, we could have a look and report to the team if it is tool issue.

**Comment by stolk** [comment]
@destenson About using pre-built libraries in other projects:

You can add a pre-built library to your CMakeLists.txt using:

add_library( gpg
             STATIC
             IMPORTED
)

But you need to tell CMake where to find this library with:

set_target_properties( gpg
                PROPERTIES IMPORTED_LOCATION
                $ENV{HOME}/src/gpg-cpp-sdk/android/lib/gnustl/${ANDROID_ABI}/libgpg.a )

This let's me use a pre-built .a file in my project.

That said, I have yet to find out how to built single .a files for Android, though.

**Comment by SahanaTambi** [comment]
I am having issues building static library using CMake and gradle. Here is the project that I am working on [https://github.com/SahanaTambi/Hello-cmake](url) .
I am unable to generate libtestStudentStatic.a file, however when I change the library to SHARED, libtestStudentStatic.so file gets generated when I do "Rebuild Project" or "Build APK" in android studio 2.3.2. Is it required for me to add/set any other flags for building STATIC libraries using gradle.
I am alos unable to generate an executable using the same CMakeList.txt.

**Comment by ggfan** [comment]
```java
        externalNativeBuild {
            cmake {
                abiFilters 'armeabi'

                cFlags "-fexceptions", "-frtti"

                // Sets a flag to enable format macro constants for the C++ compiler.
                cppFlags "-std=c++11", "-D__STDC_FORMAT_MACROS"

                targets "testStudentStatic", "libtest"  // <== adding this forcing a target to built.
            }
        }
```
testStudentStatic works, errored when building for libtext executable, linking error.  Maybe you could continue to work on it from here.

**Comment by SahanaTambi** [comment]
Why do I need to specify the target if it is a static library? The same CMakeList.txt works if it is a SHARED library without mentioning the targets flag in build.gradle file.

**Comment by ggfan** [comment]
Oh, Android is APK; in APK it is the shared lib(s) get packed. So by default only building for shared lib is reasonable guess, I guess. If static lib is indeed used by shared lib, it will be built and consumed on host, but will NOT be packed into APK ( APK is pushed to target ) -- and the "needed static lib" is not needed to put onto target ( dependency )

if want to build static lib that is NOT used by shared lib, some extra work by calling them out. I vaguely remember there is a flag to force "all targets" in CMakeLists.txt to be built, just do not recall exactly what it is ( I could be wrong ). Hope this helps.
