### ISSUE TITLE
audio-echo doesn't work at Samsung A3 2016

### ISSUE THREAD

**Issue by mdenissov** [googlesamples/android-ndk#251]
Sample **"audio-echo"** doesn't work on Samsung A3 2016.

**Comment by mdenissov** [comment]
But if multiply nativeSampleBufSize by 2 it works.

createSLEngine(Integer.parseInt(nativeSampleRate), Integer.parseInt(nativeSampleBufSize) * 2);

**Comment by ggfan** [comment]
from c code, the buffer allocation is accounted for real memory size:
`    uint32_t bufSize = engine.fastPathFramesPerBuf_ * engine.sampleChannels_
                       * engine.bitsPerSample_;
    bufSize = (bufSize + 7) >> 3;            // bits --> byte
`
need more debugging...

**Comment by ggfan** [comment]
please trye [oboe sample](https://github.com/google/oboe/tree/master/samples/LiveEffect) and file bug there: that repo will have full support for audio. Thanks
