### ISSUE TITLE
examples for prebuilt libraries in ndk-build

### ISSUE THREAD

**Issue by DanAlbert** [googlesamples/android-ndk#252]
We support `PREBUILT_SHARED_LIBRARY` and `PREBUILT_STATIC_LIBRARY` in `ndk-build`, but we don't have any samples that use it. It's useful for developers who have prebuilt libraries (possibly from a 3rd party) and want to treat them as first class modules in their projects (so they can link them via `LOCAL_SHARED_LIBRARIES`).

The best example we have right now is in our STLs: https://android.googlesource.com/platform/ndk/+/master/sources/cxx-stl/stlport/Android.mk#89

You have to know they're there in order to discover them, and that particular example is too complicated (since it's only sometimes a prebuilt) to make a good sample.

**Comment by ggfan** [comment]
maybe I should find some time to port the hello-libs sample from cmake/gradle-experimental branch to ndkbuild branch: that sample build libs ( one static, one shared ), and used by the application. almost no code, just to show how the build system handling libs. Will take a look at this after I get back.

**Comment by ggfan** [comment]
@DanAlbert : may you review this one https://github.com/googlesamples/android-ndk/pull/272 see it does the thing you wanted?  thanks

**Comment by ggfan** [comment]
merged into master-ndkbuild, please check it out. thanks
