### ISSUE TITLE
Android Studio don't show hpp files with CMake

### ISSUE THREAD

**Issue by 4brunu** [googlesamples/android-ndk#253]
Hi,

I have a project that uses CMake, and Android Studio doesn't show the hpp files.

I thought that I was doing something wrong in the CMake, so I checked the samples, and found the [endless-tunnel](https://github.com/googlesamples/android-ndk/tree/master-cmake/endless-tunnel/app/src/main/cpp) samples that has hpp files, and the Android Studio doesn't show them too.

Is this a miss configuration of [CMakeLists.txt](https://github.com/googlesamples/android-ndk/blob/master-cmake/endless-tunnel/app/src/main/cpp/CMakeLists.txt) or Android Studio bug?

Thanks

**Comment by ggfan** [comment]
it is more related to android studio: I noticed that but did not follow up with team though( not even search into the existing bug either ).  it is on my later-to-do list, if you could, may search in the bugs at tools.android.com to see if it is already there and if not, create one?  thank you a lot!

**Comment by 4brunu** [comment]
I submitted the but to here, in case you want to had some more info.

https://code.google.com/p/android/issues/detail?id=216138

**Comment by ggfan** [comment]
thank you @4brunu ! we would track it there  -- seems soon it will be added.
