### ISSUE TITLE
Debug the native code with externalNativeBuild and cmake in the separate gradle module

### ISSUE THREAD

**Issue by NikitaFeodonit** [googlesamples/android-ndk#256]
For my experiments I used the project hello-jniCallback from the master-cmake branch.
I use AS 2.2pre5, NDK r12, cmake 3.4.

Briefly, such a problem.

When I move a native cmake code to a separate gradle module then AS builds **both release and debug** versions of the object files **at one time** for the debug version of the apk-file and puts a **release** version of the so-library **to the debug version** of the apk-file.

When a native cmake code is in the app-module then AS builds only debug versions of the object files for the debug version of the apk-file and puts a debug version of the so-library to the debug version of the apk-file.

I would like to get with separate gradle module the building only of debug version of the object files to save time and the debug version of the so-file in the apk-file.

Now in more detail.

First I did update for "com.android.tools.build:gradle:2.2.0-alpha5".

When I do the Build -- Make Project then AS builds only the debug version of the native code, the folder
```
hello-jniCallback/app/externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/hello-jnicallback.dir
```
contains the file "hello-jnicallback.c.o" and the foler
```
hello-jniCallback/app/externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/hello-jnicallback.dir
```
**das not** contain the file "hello-jnicallback.c.o". 

Also the folder
```
hello-jniCallback/app/build/intermediates/cmake/debug/lib/armeabi-v7a
```
contains the file "libhello-jnicallback.so" and the foler
```
hello-jniCallback/app/build/intermediates/cmake/release/lib/armeabi-v7a
```
**das not** contain the file "libhello-jnicallback.so". 

And when I do the Build -- Build apk then **debug** version apk
```
hello-jniCallback/app/build/outputs/apk/app-debug.apk
```
contains the **debug** version of the library libhello-jnicallback.so

And now I can to debug the native code, break points are working.

Now I would like to put all the native code in a separate gradle module. For this I made the fork of your project and this commit:
https://github.com/NikitaFeodonit/android-ndk/commit/6550e34c180b9bff7b23f446ec744f56565c4d15

And now, when I do Build -- Make Project then the folder
```
hello-jniCallback/cmakemodule/externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/hello-jnicallback.dir
```
contains the file "hello-jnicallback.c.o" and the foler
```
hello-jniCallback/cmakemodule/externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/hello-jnicallback.dir
```
**also** contains the file "hello-jnicallback.c.o". 

Also the folder
```
hello-jniCallback/cmakemodule/build/intermediates/cmake/debug/lib/armeabi-v7a
```
contains the file "libhello-jnicallback.so" (debug version) and the foler
```
hello-jniCallback/cmakemodule/build/intermediates/cmake/release/lib/armeabi-v7a
```
**also** contains the file "libhello-jnicallback.so" (release version).

And when I do the Build -- Build apk then **debug** version apk
```
hello-jniCallback/app/build/outputs/apk/app-debug.apk
```
contains the **release** version of the library libhello-jnicallback.so

And now I can not to debug the native code, break points are not working.

As workaround I put the cmake argument "-DCMAKE_BUILD_TYPE=Debug" here (need to uncomment):
https://github.com/NikitaFeodonit/android-ndk/commit/6550e34c180b9bff7b23f446ec744f56565c4d15#diff-649187bb2f9589030e82b7801e9b1a47R14

Now with this argument I get in the debug and release folders equal versions of the so-files and can to debug the native code.

But the problem is in too much expenditure of time for the build and in the release apk-file is also the debug version of the so-file.

Please help me with the problem.

**Comment by NikitaFeodonit** [comment]
For the including the debug version of the library libhello-jnicallback.so to the debug apk-file I found the solution here
http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Library-Publication
and made the commit for it
https://github.com/NikitaFeodonit/android-ndk/commit/0b48e41b6020acc7fbccbbb69134bc12c84f1619

But still AS builds the release and debug version at one time for the debug or release apk-file.

Since this is the specifics of the gradle, then I close the issue here.

**Comment by ggfan** [comment]
thank you for handling the workaround.  my guess is that the library is meant to be aar.  after your build, search for aar file, and examine what is included inside aar (java library). your project essentially builds one Java lib, and used by your app:
 jni code --> aar's lib folder --> app (packaged into the apk eventually )

the problem is what get packed into aar (java library). you should see your aar get exploded into your app's build folder, and your app might actually link with that version of binary)

(I need to download to study it, cloning github repo here is slow (I got 23 KiB/s here).

**Comment by NikitaFeodonit** [comment]
From the [user guide, part "Library Publication"](http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Library-Publication):
"By default a library only publishes its release variant. This variant will be used by all projects referencing the library, no matter which variant they build themselves. This is a temporary limitation due to Gradle limitations"

And I did my last commit by this guid.

There is another variant of the solution:

in cmakemodule/build.gradle instead
```
    publishNonDefault true
```
insert
```
    defaultPublishConfig "debug"
```
and in app/build.gradle instead
```
    debugCompile project(path: ':cmakemodule', configuration: 'debug')
    releaseCompile project(path: ':cmakemodule', configuration: 'release')
```
insert
```
    compile project(':cmakemodule')
```

Then AS builds only one debug version of the cmakemodule and inserts debug version of the so-file to the apk-file. (For this I need some time to completely clean the project and restart the AS, otherwise the AS still builds a both release and debug version of the cmakemodule.)

But when I replace in the cmakemodule/build.gradle "defaultPublishConfig "debug"" to "defaultPublishConfig "release"" then AS builds both version (and insert the release version of the so-file to the apk). The strange thing is that with "debug" AS builds only one debug version and with "release" AS builds both version. And I think this limitation of the gradle.

**Comment by NikitaFeodonit** [comment]
The latest solution has the limitation that for the release version of the apk we need to manually switch the "defaultPublishConfig "debug"" to the "defaultPublishConfig "release"".
