### ISSUE TITLE
Doesn't work with Gradle wrapper 0.8.0

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-ndk#259]
Hello,
your **hello-libs** project does not work with `com.android.tools.build:gradle-experimental:0.8.0-alpha5`.  Android Studio 2.2 Preview 5 keeps spewing an error:
> @NotNull method com/android/tools/idea/run/GradleApkProvider.getApk must not return null

Please advise,
Igor

**Comment by RachelWaffle** [comment]
I met the same problem with `com.android.tools.build:gradle-experimental:0.8.0-alpha5`.
IDE shows an error and can't sync the project when I first open the project.
`Gradle 'hello-libs' project refresh failed`
`Error:Shared library runtime file <ProjectFile>/distribution/gmath/lib/arm64-v8a/libgmath.so does not exist for prebuilt library 'gmath'.`

After changing classpath to `'com.android.tools.build:gradle-experimental:0.7.0'` ,everything works fine.But I changed back to `com.android.tools.build:gradle-experimental:0.8.0-alpha5` and Run 'app' , the IDE occurs an error:
`IllegalStateException: @NotNull method com/android/tools/idea/run/GradleApkProvider.getApk must not return null`

I can general "Build APK" but "Run 'app'" . Is there problems with Android Studio 2.2 Preview5 or gradle or both?

**Comment by ggfan** [comment]
yes, I saw the same thing a moment ago. I manually removed the existing file on my nexus 5 to get the hello-libs going. I was about to forgive myself for it, let me see if I could re-plicate it again

**Comment by ggfan** [comment]
Note:  consolidating a few bugs to this one.  looks like the project dependency of triggering lib to build is not working anymore.  Temporarily to workaround it:
  1) create your local.properties file and configure it to your nkd.dir/sdk.dir in that file
  2) build libs on command line: execute `gradlew :gperf:distributeLib :gmath:distributeLib`
  3) import the project to studio
  4) after build APK, push it via command line ( adb install -r your-apk-file ), and run it ( command line or on target)

once have more info from bug 217262, will update this sample accordingly.  thanks

**Comment by IgorGanapolsky** [comment]
@ggfan > create your local.properties file
Android Studio automatically creates and configures local.properties.  Why would this need to be a manual step?

**Comment by ggfan** [comment]
local.properties is created when project imported into the studio, since this error happens during the importing, so you will see the error first.  if manually create this file, then build on command line, finally import, you will not trigger error.

**Comment by IgorGanapolsky** [comment]
@ggfan 
> since this error happens during the importing

No, this error happens every time you try to build, **NOT** just when importing first!

**Comment by ggfan** [comment]
2 errors with this issue:
1) when libs not there, importing will fail -- the workaround is for that
2) loading apk to target failed with "return null" error, your original issue for this bug

I combined the 1st issue into this id, this might add some confusion.

**Comment by ggfan** [comment]
I am intending to close this one, as experimental -0.8.0-beta3 is out and does not seem to have this particular problem anymore, although it has another issue that not building the lib sometimes. there is a bug tracking for that too:
  https://github.com/googlesamples/android-ndk/pull/286  (closed)
and spawned the real-one:
  https://code.google.com/p/android/issues/detail?id=221050

let me know how big the penalty is if this bug is closed  :-). thanks
