### ISSUE TITLE
Add sample for ldFlags

### ISSUE THREAD

**Issue by Nimrodda** [googlesamples/android-ndk#26]
In traditional NDK make file, I can link a prebuilt static library and specify its headers directory:
**Android.mk**
```
include $(CLEAR_VARS)
LOCAL_MODULE            := somelibrary-prebuilt-static
LOCAL_SRC_FILES         := $(TARGET_ARCH_ABI)/libsomelibrary.a
LOCAL_EXPORT_C_INCLUDES := include 
include $(PREBUILT_STATIC_LIBRARY)
``` 

How do I do that in `build.gradle` using the new plugin's DSL?

**Comment by proppy** [comment]
@Nimrodda you can use `ldFlags` directive, see https://code.google.com/p/android/issues/detail?id=177628.

Updating this issue to request a new sample for showing the proper syntax.

**Comment by proppy** [comment]
Also note #27 build.gradle doesn't yet support building separate library, so you would have to build the standalone library with `Android.mk` before referencing it with `ldFlags`.

**Comment by Nimrodda** [comment]
Thanks for your answer. 
Can you paste an example of how to use `ldFlags` directive with pre-built static lib, taking into account different `TARGET_ARCH_ABI`s?
Also, in previous revision there used to be `jniLibs` folder for that purpose. Is it now dropped completely?

**Comment by proppy** [comment]
@Nimrodda http://tools.android.com/tech-docs/new-build-system/gradle-experimental has an example using `ldFlags`.

It doesn't show how to handle this for different `TARGET_ARCH_ABI` thought, let's ping @rschiu he recently made a change that should enable this:
https://android-review.googlesource.com/#/c/155834/5

**Comment by rschiu** [comment]
If you have one ABI per flavor, you can specify the ldLibs for that flavor.  If you have an apk with multiple ABI, you will need to wait for https://code.google.com/p/android/issues/detail?id=178074 to be resolved, which should be available in the next release.

**Comment by rschiu** [comment]
Also, jniLibs should still work.  .so in src/main/jniLibs should be packaged into the apk.  Does it not?

**Comment by proppy** [comment]
hello-thirdparty shows this now: https://github.com/googlesamples/android-ndk/tree/master/hello-thirdparty
