### ISSUE TITLE
AAR with .a and .h

### ISSUE THREAD

**Issue by igagis** [googlesamples/android-ndk#261]
Is it possible to create AAR containing prebuilt static library and header files?

**Comment by davinctor** [comment]
@igagis as said @ggfan is [this](https://github.com/googlesamples/android-ndk/issues/238) thread - mapBox can use .arr and contain static library

**Comment by ggfan** [comment]
No is easy answer, internal bug is b/28395014 [the feature is not on priority though]

Probably indirectly [tried with shared lib once a while ago], and I personally do not think it is worthwhile:
 - build your lib first to generate a static lib, and one aar [model.library does not tuck *.a into libs directory though]
 - unzip your aar, and put *.a into libs folder
 - find a place for your headers file
 - zip it up back to aar

inside your app, make aar to be your dependent lib, so it will be extracted into exploded-aar folder; then the colorful picture appears:
  - add the intermediate explodeded aar directory into include path
I think it is too hacky and may not be a good idea to impose those into your customers.

traditional way of distributing lib and header files directly is still better, comparing to the above hacking.
For building libs, cmake way is much better, checkout hello-libs in master-cmake branch, hope this helps

**Comment by igagis** [comment]
@ggfan thanks for your explanation!

Unfortunately, distributing lib and header files directly is not an option for me. I have a rather  complex structure of several libraries which depend on each other. So, managing all those by hand, especially if version of one changes and needs updating is terrible.

It is bad that Android lacks native library management. On iOS one can manage by using cocoapods, but there is no similar thing for Android environment...

Hope b/28395014 will be prioritized at some point...

**Comment by ggfan** [comment]
thank you @igagis, added your comment into internal issue and hope it will be addressed

**Comment by ggfan** [comment]
is your application + library on github or somewhere, @igagis ?  like to see how you solve your dependencies if you are building multiple native libs.

**Comment by igagis** [comment]
@ggfan I didn't solve the problem, so I just do not do it right now on Android.

**Comment by ggfan** [comment]
ok, understood.  are you saving your source on github?

**Comment by igagis** [comment]
@ggfan yes, you can view all my repos in my github profile

**Comment by ggfan** [comment]
thanks!

**Comment by ggfan** [comment]
Adding @jomof

**Comment by ggfan** [comment]
@igagis: may you kindly send a summary about your intended usage of AAR for native distribution: you could use my email gfan@google.com,  I will pass to Jomo & Kathryn ( not exposing their email by me here :-)).

**Comment by igagis** [comment]
@ggfan ok, I have sent you an email

**Comment by ggfan** [comment]
@igagis:  thank you very much!  I will close this one from here and leave its normal channel for update if something happens

**Comment by igagis** [comment]
I made a hacky solution to the problem, described here http://stackoverflow.com/a/43661627/1221106

**Comment by ggfan** [comment]
Adding @rschiu @jomof
