### ISSUE TITLE
Error when Running hello-libs

### ISSUE THREAD

**Issue by wrightpt** [googlesamples/android-ndk#263]
Error:Execution failed for task ':app:externalNativeBuildDebug'.
> com.android.ide.common.process.ProcessException: Error while executing '/home/c/Android/Sdk/cmake/3.6/bin/cmake' with arguments {--build /home/c/Downloads/android-ndk-master-cmake/hello-libs/app/externalNativeBuild/cmake/debug/x86 --target hello-libs}
  [1/2] Building CXX object CMakeFiles/hello-libs.dir/hello-libs.cpp.o
  FAILED: /home/c/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  -target i686-none-linux-android -gcc-toolchain /home/c/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64 --sysroot=/home/c/Android/Sdk/ndk-bundle/platforms/android-13/arch-x86  -Dhello_libs_EXPORTS -I/home/c/Downloads/android-ndk-master-cmake/hello-libs/app/src/main/cpp/../../../../distribution/gmath/include -I/home/c/Downloads/android-ndk-master-cmake/hello-libs/app/src/main/cpp/../../../../distribution/gperf/include -isystem /home/c/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/c/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include -isystem /home/c/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti  -std=gnu++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/hello-libs.dir/hello-libs.cpp.o -MF CMakeFiles/hello-libs.dir/hello-libs.cpp.o.d -o CMakeFiles/hello-libs.dir/hello-libs.cpp.o -c /home/c/Downloads/android-ndk-master-cmake/hello-libs/app/src/main/cpp/hello-libs.cpp
  /home/c/Downloads/android-ndk-master-cmake/hello-libs/app/src/main/cpp/hello-libs.cpp:46:32: error: expected ')'
      LOGI("calculation time: %" PRIu64, ticks);
                                 ^
  /home/c/Downloads/android-ndk-master-cmake/hello-libs/app/src/main/cpp/hello-libs.cpp:46:5: note: to match this '('
      LOGI("calculation time: %" PRIu64, ticks);
      ^
  /home/c/Downloads/android-ndk-master-cmake/hello-libs/app/src/main/cpp/hello-libs.cpp:26:29: note: expanded from macro 'LOGI'
    ((void)__android_log_print(ANDROID_LOG_INFO, "hell-libs::", __VA_ARGS__))
                              ^
  1 error generated.
  ninja: build stopped: subcommand failed.

**Comment by davinctor** [comment]
@wrightpt I have same problem, just edit row with
```
LOGI("calculation time: %" PRIu64, ticks);
```
to: 
```
LOGI("calculation time: %d", ticks);
```

and run it.

**Comment by ggfan** [comment]
I will check it out: PRIu64 usage style may not be working with new ndk, probably create my own version of it.

**Comment by ggfan** [comment]
fixed: use equivalent C++ header files make it works again. closing it, thanks for bring it up

**Comment by wrightpt** [comment]
thx Victor and Gerry. will try both solutions.
what do you mean use equivalent header file? create header from c++ file
instead of c? this sounds like something that should be obvious to me but
its not.

**Comment by ggfan** [comment]
fix is checked in, if you update to the latest, it should work now. changes are:
string.h  --> cstring [not very relavent, just changing it too ]
inttypes.h  --> cinttypes [this matters]

thanks

**Comment by wrightpt** [comment]
ok, thank u.
