### ISSUE TITLE
importing OpenGL sample not building

### ISSUE THREAD

**Issue by wrightpt** [googlesamples/android-ndk#265]
4:56:59 PM System Health
           IBus prior to 1.5.11 may cause input problems. See IDEA-78860 for details.
           Do not show again.
4:57:59 PM Instant Run requires Android Gradle Plugin version 2.2.0-alpha6 or higher.
           (Dont show again)
4:58:00 PM Executing tasks: [:app:assembleDebug]

Build.gradle from project:

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
       jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle-experimental:0.7.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

**Comment by ggfan** [comment]
looks you are using stable studio release, you could disable instant run for native project (preferences -> Build, Execution, Deployment -> Instant Run).

Tried to import with version:
   Android Studio 2.2 Preview 6
   Build #AI-145.3070098, built on July 18, 2016
master branch, hello-gl2, seems ok. you could download the Studio version from canary channel

may you try it out? if you are on different branch ( master-cmake/master-ndkbuild) with different sample, please let me know

**Comment by ggfan** [comment]
now AS 2.2.0 is formally released, this should be fixed. please re-open when necessary
