### ISSUE TITLE
Deleted and reimported Hello-Libs project  gmath.so not exist error

### ISSUE THREAD

**Issue by wrightpt** [googlesamples/android-ndk#266]
Error:Shared library runtime file /home/c/AndroidStudioProjects/Hello-libs/distribution/gmath/lib/arm64-v8a/libgmath.so does not exist for prebuilt library 'gmath'.
Gradle 'Hello-libs' project refresh failed

 Using Android Studio 2.2 Preview 6

**Comment by ggfan** [comment]
yeah, looks this is serious one, having more impact.  let's tracking / following it via
 https://github.com/googlesamples/android-ndk/issues/259

**Comment by wrightpt** [comment]
k, thx
