### ISSUE TITLE
Not able to run :-(

### ISSUE THREAD

**Issue by Nau3D** [googlesamples/android-ndk#267]
Hi,

I've imported the hello-libs into Android Studio.

First I got an error because the libs didn't exist. I created empty files and the system build them and place them in the distribution folder. However on the second build it did not copy the libs to the distribution folder. AS claimed it does not know targetPlatform, which is present in build.gradle for the app.

I've set it to create only the x86-64 version and it builds fine but afterwards  I get a Null Pointer Exception at at com.android.tools.idea.run.tasks.DeployApkTask.perform(DeployApkTask.java:89)

Surely I'm doing something wrong ...

This example is exactly the base that I'm need to build my apps. Can anyone help me please?

Thanks,

António

**Comment by ggfan** [comment]
thank you for reporting the issue, it is similar to this one: 
  https://github.com/googlesamples/android-ndk/issues/259

I need to debug on it.  My workaround is inside the bug:
  https://code.google.com/p/android/issues/detail?id=217262
"replication steps"
