### ISSUE TITLE
i can't  assemble app with model library 

### ISSUE THREAD

**Issue by c3ph3us** [googlesamples/android-ndk#27]
hi i can't assamble any project with model.library i get error :

> Error:A problem was found with the configuration of task ':widgets:processDebugResources'.
> Directory 'lib dir \build\intermediates\bundles\debug\res' specified for property 'resDir' does not exist.

pleas provide any sample for case:
app +  library + native 

my gradle file for library :

     apply plugin: 'com.android.model.library'
     
     model {
 
        android {
          compileSdkVersion = 22
          buildToolsVersion = "23.0.0 rc3"

          defaultConfig.with {
              applicationId = "pl.ceph3us.widgets"
              minSdkVersion.apiLevel = 11
              targetSdkVersion.apiLevel = 22
              versionCode = 1
              versionName = "lib 1.0"
          }
      }

          android.buildTypes {
          release {
              isMinifyEnabled = false
              proguardFiles += file('proguard-rules.pro')
          }

          debug {
              isDebuggable = true
              isMinifyEnabled = false
              proguardFiles += file('proguard-rules.pro')
          }
        }
      }  
     
      dependencies {
         compile fileTree(dir: 'libs', include: ['*.jar'])
         compile 'com.android.support:appcompat-v7:22.2.0'
       }

**Comment by proppy** [comment]
The new experimental gradle plugin doesn't yet support creating standalone library, see https://code.google.com/p/android/issues/detail?id=177631
