### ISSUE TITLE
usage of ProGuard causes error in release-build of hello-jni

### ISSUE THREAD

**Issue by mHerasimov** [googlesamples/android-ndk#270]
I changed just couple lines in _hello-jni_ project, such as enabled _ProGuard_, so my _buildTypes_  section is next

```
buildTypes {
            release {
                minifyEnabled = true
                //proguardFiles.add(file('proguard-rules.txt'))
                proguardFiles.add(file('proguard-rules.pro'))
            }
        }
```

As you can see here I've replaced _proguard-rules.txt_ with _proguard-rules.pro_.

My _ProGuard_ custom options are next 

```
-optimizationpasses 5
-optimizations !class/unboxing/enum
-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int i(...);
    public static int w(...);
    public static int d(...);
    public static int e(...);
}
```

At this stage everything works fine, even creation of _Signed APK_, but after addition of standard dependencies creation of _Signed APK_ FAILS.

So here is dependencies I've added to app's _build.gradle_ file

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.0.0'
}
```

After performing generation of _Signed APK_ I've got **1 error and 5 warnings**, error is next
`Execution failed for task ':app:transformClassesAndResourcesWithProguardForAllRelease'.`
As far as I see warnings are related with _android.support.v4_ and _android.support.v7_

 Here is lines, which are colored in red in _Gradle Console_

```
Note: there were 7 duplicate class definitions.
Warning: android.support.v4.app.NotificationCompat$NotificationCompatImplBase: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
Warning: android.support.v4.app.NotificationCompat$NotificationCompatImplGingerbread: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
Warning: android.support.v4.app.NotificationCompatGingerbread: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
Warning: there were 3 unresolved references to library class members.
         You probably need to update the library versions.
```

Help me please, I don't understand what causes this problems.

**Comment by ggfan** [comment]
both this one and issue 269 are new to me, hope someone could help out.

**Comment by MikeHerasimov** [comment]
I found a solution on my own, as I said those warnings are related with _android.support.v4_ and _android.support.v7_, so I added `-dontwarn android.support.**` instruction to my _proguard-rules.pro_ file.
As far as I see, after addition of this instruction you can still see warning messages in _Gradle Console_, but there is no error and creation of _Signed APK_ performs successfully.

**Comment by ggfan** [comment]
thanks, I will ask authority about it, and see if the warning matters: maybe keep this one open to remind us : it need to be followed up.

**Comment by ggfan** [comment]
yes, could you still run your signed apk? I do not see I could executed it, with error:
No implementation found for java.lang.String com.example.hellojni.HelloJni.a()
[it is crash on Nexus 6]. if you could run your apk, that is good

**Comment by ggfan** [comment]
many years from last discussion, Android studio 3.1.3 seems ok...
