### ISSUE TITLE
How to set CMAKE_TOOLCHAIN_FILE

### ISSUE THREAD

**Issue by dpull** [googlesamples/android-ndk#273]
such as:

        externalNativeBuild {
            cmake {
                    arguments "-DCMAKE_TOOLCHAIN_FILE=../../cmake/my_android.toolchain.cmake"
            }
        }

**Comment by dpull** [comment]
I know, it must use an absolute path

**Comment by dpull** [comment]
oh,  it duplicated.

```
-DCMAKE_TOOLCHAIN_FILE=/Users/dpull/Library/Android/sdk/cmake/3.6/android.toolchain.cmake
-DANDROID_NATIVE_API_LEVEL=21
-DTARGET_PLATFORM_VERSION=18
-DANDROID_TOOLCHAIN=clang
-DCMAKE_TOOLCHAIN_FILE=/.../Test/Android/app/src/android.toolchain.cmake
```

**Comment by chaoren** [comment]
Duplicating should be fine. We use our own toolchain file. If you want to use a different one, what you're doing here should work. Appending the argument should just override the previous `CMAKE_TOOLCHAIN_FILE`.

Be aware that you're on your own if you run into problems with your own toolchain file.
