### ISSUE TITLE
Announcement: flipping Branches soon: master-cmake <--> master

### ISSUE THREAD

**Issue by ggfan** [googlesamples/android-ndk#278]
CMake support is at Beta,  like to have this repo to match the milestone. So soon the cmake branch ( master-cmake ) will become master, with master (gradle experimental ) becoming master-experimental branch

once it is switched, android studio importing samples will only import cmake samples, not experimental samples.

**Comment by graph** [comment]
what's happening to the gradle experimental. Will development continue for months down the road to help people transition to cmake, or will it continue to try and compete with cmake, or other? I see there is already works on gradle experimental 0.8.

**Comment by ggfan** [comment]
cmake branch will be very active to keep up with the latest development with android studio + cmake support, might spend some time on ndkbuild branch; but very little time on experimental branch to keep them still build-able.

**Comment by graph** [comment]
I think my question is better suited for the [android ndk](https://github.com/android-ndk/ndk/issues) than in the google samples issue tracker because I was referring to the experimental plugin itself and not the samples.  Anyway thank you. I just want to get a sense of how long term the cmake build system will be, and the plans for the experimental plugin. I hope cmake will stay the recommended system for android for the long term future. Seeing that there is a c++ checkmark in android studio makes me think this is the case :).

**Comment by ggfan** [comment]
you are correct.  the samples are also trying to align with android studio/ndk support priority, cmake is to stay with more features enabled, from my understanding.  Gradle experimental will be is not very active on development.

**Comment by kmshih** [comment]
To clarify; the studio team intends to continue actively supporting gradle experimental, but progress on the plugin is currently gated on the status of the upstream gradle project.  As a result, we anticipate that cmake will be able to provide more near term features.

**Comment by ggfan** [comment]
thank you @kmshih!  @graph, this would be the most correct message.

**Comment by ggfan** [comment]
with 3 building systems on the moving, and with request to support all ( means samples and docs I think ).  I am thinking to:
- make cmake to be master branch ( no change )
- create a directory in cmake branch, name it sth like 'other-build-systems', and put ndkbuild and experimental samples there. only keep the build script in those sub directories, but keep native content code only inside cmake branch, other building systems pointing to the native code there.

one copy of the content code to minimize maintenance work, save some time to address other things (like today the recommendation of ${ANDRIOD_NDK_ROOT} inside local.properties )

say sth if this is going to add more work on your  side, thanks!

**Comment by ggfan** [comment]
sure, I will drink with Adarsh when I first spot him next time for sure :-).

**Comment by ggfan** [comment]
this PR https://github.com/googlesamples/android-ndk/pull/285 brings ndkbuild into master-cmake branch. Hope this will not disturb your existing code base too much: it does have some impact. This should be merged before branch switch happening.

**Comment by ggfan** [comment]
this is now flipped:
- master:  cmake;   ndk-build support and experimental plugin are under `other-builds` directory
- master-cmake / master-ndkbuild: redundant, will be deleted soon
- gradle-experimental: original master branch, will be kept for a migration reference, not actively maintained
