### ISSUE TITLE
Hello-libs breaks

### ISSUE THREAD

**Issue by accesio** [googlesamples/android-ndk#280]
Hi,

Your sample hello-libs doesn't run.

```bash
./gradlew build
....lots of output
Download https://jcenter.bintray.com/com/android/tools/lint/lint-api/25.2.0-alpha6/lint-api-25.2.0-alpha6.jar
Download https://jcenter.bintray.com/com/android/tools/annotations/25.2.0-alpha6/annotations-25.2.0-alpha6.jar

FAILURE: Build failed with an exception.

* Where:
Build file '/media/jdamon/Development/Documents/Projects/android-ndk/hello-libs/app/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/model/AppComponentModelPlugin : Unsupported major.minor version 52.0

```

**Comment by ggfan** [comment]
you are using from master, right? may you check what inside local.properties file, and run "gradlew tasks" too?

**Comment by accesio** [comment]
This is off of master 06ee6ae056d5

```bash
cat local.properties
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Fri Jul 22 16:52:54 PDT 2016
ndk.dir=/to/your/ndk/path
sdk.dir=/to/your/sdk/path
```

and 

```bash
./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/media/jdamon/Development/Documents/Projects/android-ndk/hello-libs/app/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/model/AppComponentModelPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.948 secs
```

**Comment by ggfan** [comment]
yeah, please update local.properties to your own sdk and ndk location, then try build with gradlew asssembleDebug command ( or other commands ). see how it goes ( it should be ok )

**Comment by accesio** [comment]
Isn't this something that can be picked up from 
$ANDROID_NDK_ROOT and $ANDROID_SDK_HOME ?

**Comment by ggfan** [comment]
it could come from 2 sources:  the env variables you mentioned and directly from android studio. when you import the project, android studio will automatically create the file and put the right path to it   -- if you have android studio to manage your sdk and NDK.

let android studio manage sdk and NDK avoid some unnecessary bugs at some times, so in the repo the file (local.properties) was not checked in at all. Then got complaint from users, so fake dirs are added. if you look at the error, somewhere it should say something about the wrong ndk path.

**Comment by accesio** [comment]
I don't see any error messages when running gradelw command line that indicate ndk path errors

As posted earlier;

```bash
paris hello-libs (master)% ./gradlew clean

FAILURE: Build failed with an exception.

* Where:
Build file '/media/jdamon/Development/Documents/Projects/android-ndk/hello-libs/app/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/model/AppComponentModelPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.054 secs
```

Even on a clean it errors out saying this.

Also, isn't the point of Gradle to not force people to use Android Studio ?  Perhaps a README.md file indicating this only works with Android Studio should be present.

**Comment by ggfan** [comment]
thanks for the suggestion, will make a note of it.

**Comment by accesio** [comment]
I consider this not closed. I tried out your suggtestions and this still  is a bug.

**Comment by ggfan** [comment]
Oh, ok.  let's re-open it.

**Comment by ggfan** [comment]
coming back to this. could you list the things as:
OS ( windows/mac/...)
local.properties contents
hello-libs/build.gradle and hello-libs/app/build.gradle:  they should be same as in the repo or versions are updated?

then we could check if you have the tools version inside build.gradle installed, if not, please install them ( those are  compileSdkVersion and buildToolsVersion ), takes some time, but will get it through.

Libs are important to android: lots of libs are ready to get ported or already ported from desktop, I would try my best to get this simple lib demo work for you, and hopefully to save you some development time.

**Comment by ggfan** [comment]
If you "import" the project into Android Studio, android studio will update the files into your local machine settings, avoiding manually update them. If you have installed (most likely )a new version of com.android.tools.build:gradle than the one inside the repo, you would could:
1) open android studio to get its version
2) put that version into your hello-libs/build.gradle
3) update gradle-wrapper version matching that android version into gradle-wrapper.properties. 

the error message will show the above things: it shows first error, you fix it, then it prompts the next.  

when you get change, give it one more try and let me how it goes.  thanks

**Comment by ggfan** [comment]
may you kindly look at this place to see if the instruction is sufficient for you?     
README.md there @ the very top, please give that instruction a try to see whether you could  build your android-ndk samples [by theory it should ].

if it works for you, I will add those instructions into android-ndk repo's readme.md, kindly let me know. thanks

**Comment by ggfan** [comment]
hi, wondering if you still care about it: with this PR on flight
 https://github.com/googlesamples/android-ndk/pull/287
I will update the build instructions, this will be factored in that work.  kindly let me know  thanks

**Comment by ggfan** [comment]
Closing this one for now, please re-open at anytime if needed, CMake & NDKBuild support with Android Studio is released today, master branch is with cmake builds from today.  thanks
