### ISSUE TITLE
Could not find method externalNativeBuild()

### ISSUE THREAD

**Issue by apres23** [googlesamples/android-ndk#281]
I am struggling creating native exampls with in cmake-branch. After updating to java 1.8 to get rid of Unsupported major.minor version 52.0 error, I get now this error (tried hello-jni and Teapot):
Could not find method externalNativeBuild().
Full error for hello-jni:
Error:(12, 0) Could not find method externalNativeBuild() for arguments [build_9hct8tomygwyb1kopay9ff0va$_run_closure1$_closure3$_closure6@1ba1327b] on ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=15, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=23, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=1.0, applicationId=com.example.hellojni, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.ProductFlavor.

It seems that original value in gradle-wrapper.properties (Teapot-example)
distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-bin.zip
was set on my machine to:
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
changing it back to -2.10-bin.zip
caused a new error:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 2.14.1.  Current version is 2.10. If using the gradle wrapper, try editing the distributionUrl in gradle-wrapper.properties

Can anybody tell me what to do, I am not an And.Studio or gradle expert, I am am coming from the C++ world.

I am using And.Studio 2.1.3, cmake 3.6.1, ubuntu 14.04 64 bit
Thanks in advance

**Comment by apres23** [comment]
Seems that externalNativeBuild ist only supported i AS 2.2, right?

**Comment by apres23** [comment]
Seems working now, first hello-jni test was successfull with AS beta 2.2

**Comment by ggfan** [comment]
yes, I need update samples to 2.2-beta2. what you are seeing is correct:
 1) let android studio update samples to 2.2-beta2 
 2) each version is closely tight with gradle version, so for this one, it is 14.1: just change that gradle wrapper file would be fine

externalNativeBuild is only available in 2.2.0 and above, right now it is only available in canary ( not formal released yet )
