### ISSUE TITLE
samples should use JNIEXPORT and JNICALL

### ISSUE THREAD

**Issue by graph** [googlesamples/android-ndk#282]
even though the following declaration works

```
jstring
Java_com_example_hellojni_HelloJni_stringFromJNI( JNIEnv* env,
jobject thiz )
```
it really should be

```
JNIEXPORT jstring JNICALL
Java_com_example_hellojni_HelloJni_stringFromJNI( JNIEnv* env,
jobject thiz )
```

without the JNIEXPORT if the compiler or linker sees that `Java_com_example_hellojni_HelloJni_stringFromJNI` is not used it will be removed even though it's used from java by doing reflection on the shared library. This doesn't happen in the samples because the options for it in debug/release are not set by default. Of course JNIEXPORT could be avoided by using registerNatives related functions. 

JNICALL makes the function use the proper calling convention.  Depending on architecture the calling convention is different and JNICALL expands to the proper one. Not having JNICALL can result is weird stack corruption issues. 

And [Some android docs](https://developer.android.com/training/articles/perf-jni.html) would also need to be updated to use JNIEXPORT & JNICALL. I haven't checked android docs diligently for this. 

Thank you.

**Comment by ggfan** [comment]
with PR of merging almost done, will move into contents.  as you said samples are get away with it by forcing `minifyEnabled = false`.

**Comment by ggfan** [comment]
PR https://github.com/googlesamples/android-ndk/pull/296 is to fix it
