### ISSUE TITLE
java.lang.UnsatisfiedLinkError no implementation found when linking to a jni library

### ISSUE THREAD

**Issue by yperess** [googlesamples/android-ndk#290]
I have a project that includes 2+ Android apps: a producer and consumer for now. To facilitate some of the common code I'm using a 3rd module to create the library. The library is modeled after the [gen-libs](https://github.com/googlesamples/android-ndk/blob/master/cmake/gen-libs/src/main/cpp/gperf/CMakeLists.txt) module in the cmake examples. The only difference is that I'm using a `distribution_DIR` inside the module's directory `$projectDir/build/outputs/lib`.

For the common library I'm trying to generate 2 .so files, one for just my library (test.cpp) which I'll be able to use in iOS or other native integrations, the other has all the JNI code for my Android/Java apps. The common app includes some `com.example.TestApis` class with native functions giving access to the functions defined in test.cpp. My common library's CMakeLists.txt is as follows:

    cmake_minimum_required(VERSION 3.4.1)

    set(LIB_SOURCES
        src/main/cpp/test.cpp
        )

    set(JNI_LIB_SOURCES
        src/main/jni/TestApis.cpp
        )

    set(distribution_DIR ${CMAKE_CURRENT_SOURCE_DIR}/build/outputs/lib)

    # Define the libraries this module creates.
    add_library(common     SHARED ${LIB_SOURCES} )
    add_library(jni-common SHARED ${JNI_LIB_SOURCES} )

    # Find the android logging library.
    find_library(log_LIB log )

    # copy out the lib binary and remove generated files
    set_target_properties(common PROPERTIES LIBRARY_OUTPUT_DIRECTORY
        "${distribution_DIR}/${ANDROID_ABI}")
    set_target_properties(jni-common PROPERTIES LIBRARY_OUTPUT_DIRECTORY
        "${distribution_DIR}/${ANDROID_ABI}")

    # Linking rules
    target_link_libraries(common ${log_LIB} )
    target_link_libraries(jni-common common )

I then include the following in my producer...

build.gradle now includes:

    android {
        ...
        sourceSets {
            main {
                // let gradle pack the shared library into apk
                jniLibs.srcDirs = ['../common/build/outputs/lib']
            }
        }
        externalNativeBuild {
            cmake {
                path 'CMakeLists.txt'
            }
        }
        ...
    }
    dependencies {
        ...
        compile project(':common')
    }

CMakeLists.txt has:

    cmake_minimum_required(VERSION 3.4.1)

    set(distribution_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../common/build/outputs/lib)

    find_library(jni_common_LIB
        NAMES jni-common
        PATHS ${distribution_DIR}/${ANDROID_ABI}
        NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)

    if (NOT jni_common_LIB)
        message(FATAL_ERROR "Failed to find jni-common at ${distribution_DIR}/${ANDROID_ABI}")
    endif()

    add_library(jni-common SHARED IMPORTED )
    set_target_properties(jni-common PROPERTIES
        IMPORTED_LOCATION ${jni_common_LIB})

Everything builds fine, the final producer and consumer APKs include the .so files generated by the common library, but it appears that during runtime they say that they can't find the JNI implementation: `E/UncaughtException: java.lang.UnsatisfiedLinkError: No implementation found for int com.example.common.TestApis.setMode(int) (tried Java_com_example_common_TestApis_setMode and Java_com_example_common_TestApis_setMode__I)`. Using the *nm* tool to look at the symbols in the .so files I do see an entry to setMode with the following signature: `0000000000006430 T _Z48Java_com_example_common_TestApis_setModeP7_JNIEnvP7_jclassi`.

**Comment by ggfan** [comment]
the prototype for Java_com_example_common_TestApis_setMode() was generated by android studio? I would think there should be no mangling in this function since it crosses the language boundaries (Java --> Native ), extern "C" would be added automatically.

**Comment by yperess** [comment]
OK, I got things working, looks like the issue was all on my end (I apologize for wasting your time). It turns out I just needed to take out the `externalNativeBuild` block and the `CMakeLists.txt` from both my producer and consumer. Just having the common library in the dependencies and the added `jniLibs.srcDirs` is enough to get everything working.
