### ISSUE TITLE
Error while calling a new native method in MainActivity

### ISSUE THREAD

**Issue by Anvesh46** [googlesamples/android-ndk#294]
<img width="1337" alt="screen shot 2016-09-19 at 10 37 25 am" src="https://cloud.githubusercontent.com/assets/22280335/18642345/2b05a5fa-7e55-11e6-8b2e-e44184008fc2.png">
Hi, 
I was getting an error whenever, I tried to call the new native method created by me.

the error says that, "no implementation found" for the native method. Can you please resolve this

thank you

**Comment by ggfan** [comment]
could you paste:
- the line declaring your new native function function in Java file
- the line implementing the native function in your C/C++ file

it should be something as: `public native String  unimplementedStringFromJNI();`, then inside android studio IDE, highlight the above native function, click on pop-up prompt( like a red bulb ) to bring out the menu, choose the top one in the list to let Android Studio to create the needed native side prototype for the same function. The rest would be fill in your function with  your implementation on native side.  Clean and rebuild, there it should do what it is supposed to do.  Thanks

**Comment by Anvesh46** [comment]
Yes, I did the same. but I don't know why I was getting this error. I worked fine for .c file in hello_jni sample, but it is not working in c++ files. Is there any better way I can create a my native function in .C++ file  instead of .c file

thank you

**Comment by ggfan** [comment]
Oh, maybe you forgot to use `extern "C"` when you renamed the file to C++?  it should looks like the following in C++ file ( not needed for C file ):
extern "C" JNIEXPORT void JNICALL ...

**Comment by Anvesh46** [comment]
Hello Gerry,

This images may explain what I was saying. I thing this extern "C" is
unstable.

1)At first in MainActivity (1.png) I haven't called the newNdkString()
function.
  In the c++ file(2.png) I added extern "C" only for newNdkString() but not
for other methods.
  when I run this I got the output(3.png). Even though the extern "C" is
not added
2) When I try to call the newNdkString() function, I was getting this
error(4.png)

note: newNdkString()  was the method created after refactoring the .c file
to .c++

**Comment by ggfan** [comment]
maybe forgot adding your images?  maybe upload your project to somewhere so we could talk with code.  thanks

**Comment by Anvesh46** [comment]
<img width="582" alt="1" src="https://cloud.githubusercontent.com/assets/22280335/18652411/2cf60ca6-7e87-11e6-871f-7e93529525c3.png">
<img width="764" alt="2" src="https://cloud.githubusercontent.com/assets/22280335/18652413/2cfb31b8-7e87-11e6-98f4-19ba94fe2247.png">
<img width="460" alt="3" src="https://cloud.githubusercontent.com/assets/22280335/18652412/2cf73176-7e87-11e6-88e9-3366a24566fd.png">
![Uploading 4.png…]()

**Comment by ggfan** [comment]
could not see what could be wrong from the code. so if you just change to:
  `if( intString() == 10 ) {
        txtView.setText(newNdkString());
   }`    

it will be error? you are using newTextView, for testing purpose, do not use a new textview, just use the working txtView, only swap the native function to be newNdkString(). 

not what I could guess out from the above code (tried to put hello-jni to that function, it works ). if you could upload the full project to github somewhere, we could try on both ends. 

one more thing, before you, manually clean up on command line 2 directories (build app/build ); if you are using cmake, clean another one ( app/.externalNativeBuild ), then build.

thanks

**Comment by Anvesh46** [comment]
JNI.zip
please find the code in this zip

**Comment by Anvesh46** [comment]
please find the code in this ZIP file
[JNITest 2.zip](https://github.com/googlesamples/android-ndk/files/481401/JNITest.2.zip)

**Comment by ggfan** [comment]
some minor issues get in the way:
- the c/C++ shared lib name mis-match. lib name built in app/build.gradle is 'hello-libs' (moduleName = 'hello-libs'), so your java code need to load shared lib with that name:`System.loadLibrary("hello-libs");`
- in native code helloJni.c++, extern "C" needed to be added for every function called from Java side. So add `extern "C"` to all 3 functions ( your code only added to the very first one )

then it would run.  

this [codelab](https://codelabs.developers.google.com/codelabs/android-studio-jni/index.html?index=..%2F..%2Findex#0) might be useful when getting familiar with jni and android studio debugging. 

thanks

**Comment by Anvesh46** [comment]
Thanks for your time, thank you very much
