### ISSUE TITLE
Recording audio while device put to sleep

### ISSUE THREAD

**Issue by farleylai** [googlesamples/android-ndk#295]
Hi,

I am looking for the way to record audio while the device is put to sleep just like the wake-up sensors. The Java APIs (AudioReocrd) does not provide the callback interface as OpenSL ES does. However, it is not clear whether the wakelock is automatically acquired and the device is woken when the callback is invoked. Can you give a definitive clarification?

Thanks.
Farley

**Comment by ggfan** [comment]
I will try to ask Audio team when I get chance: lack of background in this area: will update when having something.  Sorry for those political answers

**Comment by farleylai** [comment]
Just conducted a simple audio recording experiment using both OpenSL ES and Android AudioRecord class on Nexus 6. Both APIs seem to acquire the wakelock internally and never releases it until the recording is stopped. Does this behavior depend on the driver implementation or the APIs intentionally acquire the wakelock for some essential reason?

**Comment by ggfan** [comment]
may you shoot your question to this place:  https://groups.google.com/forum/#!forum/android-ndk?  apologize for not getting your the answer.

**Comment by farleylai** [comment]
Thanks, I just posted there.

**Comment by ggfan** [comment]
great, hope for the best.

**Comment by ggfan** [comment]
closing this since you are engaged with audio owners there.  thank you for the question
