### ISSUE TITLE
ndk-gdb failed.

### ISSUE THREAD

**Issue by wang37921** [googlesamples/android-ndk#297]
1. clone code from Branch: master-ndkbuild
2. debug from android studio.
3. console change workdir to app/src/main
4. exec ndk-gdb, then got error msg:
5. Failed to retrieve application ABI from Android.mk.

**Comment by ggfan** [comment]
I trace code from android studio ide: menu "Run" --> "Debug ...".  that having trouble?

**Comment by wang37921** [comment]
@ggfan 
not used experimental gradle plugin. 
gradle android version 2.2, and makefile.
checkout code from branch: master-ndkbuild.

**Comment by wang37921** [comment]
@ggfan Can you trace native code by console through ndk-gdb?

**Comment by wang37921** [comment]
gradle android 2.2 add External C++ Build Support, so now, we can debug at android studio ide....

> http://tools.android.com/tech-docs/external-c-builds
