### ISSUE TITLE
hello-libs: Rebuild libraries

### ISSUE THREAD

**Issue by mpcarlos87** [googlesamples/android-ndk#301]
Hello,

I think I found a little error on hello-libs sample. I wanted to rebuild the libraries gperf and gmath so I deleted the folders under "distribution". I looked for the file build.gradle under /app/build-gradle and this file says:

`// uncomment out this one to generate lib binaries,
    // and also uncommented out the one in settings.gradle
    // after lib is generated, just comment them out again
//        compile project(':gen-libs')`

When I checked settings.gradle, didn't exist any code to comment out:

`include ':app'`

So I just added this line to settings.gradle and it worked perfectly: 

`include ':gen-libs'`

Please, may you add this to the repository?

Thanks.

**Comment by ggfan** [comment]
Ok, I will take a look at it.  thanks.
