### ISSUE TITLE
CMake Error: Could not create named generator Android Gradle - Ninja

### ISSUE THREAD

**Issue by falbertp** [googlesamples/android-ndk#302]
try your code and got problem at gradle console:
CMake Error: Could not create named generator Android Gradle - Ninja
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> executing external native build for cmake D:\Frank\workspace\hello-jni\app\src\main\cpp\CMakeLists.txt

at gradle sync:
External Native Build Issues
Build command failed.
Error while executing 'd:\android\cmake\bin\cmake.exe' with arguments {-HD:\Frank\workspace\hello-jni\app\src\main\cpp -BD:\Frank\workspace\hello-jni\app\.externalNativeBuild\cmake\arm8Release\mips64 -GAndroid Gradle - Ninja -DANDROID_ABI=mips64 -DANDROID_NDK=D:\androidndk -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\Frank\workspace\hello-jni\app\.externalNativeBuild\cmake\arm8Release\obj\mips64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=d:\android\cmake\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=d:\android\cmake\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_TOOLCHAIN=clang}
CMake Error: Could not create named generator Android Gradle - Ninja

Please help solve this issue - Thank you

**Comment by ggfan** [comment]
Not sure about this one: may you check your cmake version @ $SDK_DIR/cmake

also you are importing the project into android studio, correct?

**Comment by falbertp** [comment]
cmake version 3.6.2
Android Studio version 2.2 with installer: android-studio-bundle-145.3276617-windows.exe
Windows 8 x64
using ndk installer: android-ndk-r12b-windows-x86_64.zip
try gradle with default gradle wrapper or using gradle installer: gradle-3.1-bin.zip, both the same problem

**Comment by ggfan** [comment]
I am using cmake ( $SDK/cmake/):
09/16/2016  11:32 AM    <DIR>          3.6.3133135
09/16/2016  11:37 AM    <DIR>          3.6.3155560

could you uninstall your cmake, using android sdk tool, and re-install it again?   In Android Studio, click that SDK Manager:
- SDK Tools
- Uncheck CMake
- Apply
- after done, Check "CMake" again to re-install it. 

you should get a newer version.  Not sure this will totally fix it, worth a try: I am building on window 10 fine.   Thank you for confirming it

**Comment by falbertp** [comment]
Finally, its work by reinstall windows and everything from clean. I suspect a lot has happening to this office computer before assigned to me, so better I reinstall clean everything to make sure everything will work according to my needs.

Thanks @ggfan your hint to reinstall cmake did me think about reinstalling everything.

**Comment by ggfan** [comment]
glad you get it solved! use cmake + android for your new project, so we could make cmake-support better and better for Android  :-)   -- more usage drives more support / efforts!

**Comment by MyJesus** [comment]
update your NDK ,I have a same issue with the NDK r10e. it solved that update NDK to r13

**Comment by ggfan** [comment]
Oh, yes, I got put it into wiki or somewhere: cmake support could only be done with ndk-r12 ( it will use android.toolchain.cmake file inside sdk ), or ndk-r13 ( studio will use the android.toolchain.cmake packed there ). it does not matter too much, in case there is error, you know where to find things.

**Comment by Ketanbankar** [comment]
same error for windows 10, NDK 19, Cmake3.10.2 , Studio 3.0.1

**Comment by ggfan** [comment]
I would need to try it out too later, could you try with out version 3.3.1 instead? ( I would expect that to work )

**Comment by RuiCuco** [comment]
Hi. I have the same error. Only there is also the following text after the error message:

Generators
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 8 2005 [arch]  = Deprecated.  Generates Visual Studio 2005
                                 project files.  Optional [arch] can be
                                 "Win64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - MinGW Makefiles   = Generates CodeLite project files.
  CodeLite - NMake Makefiles   = Generates CodeLite project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - MinGW Makefiles       = Generates Kate project files.
  Kate - NMake Makefiles       = Generates Kate project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.



As you can see there is no generator 'Android Gradle - Ninja' in the list. I'm using the latest cmake from Android Studio. I hope this helps you to identify the problem.

**Comment by RdeWilde** [comment]
For me the issue seems with the arguments list. 

```
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_PLATFORM=latest",
                        "-DENABLE_QRCODE=Off",
                        "-DENABLE_UPNP=Off",
                        "-DBUILD_SHARED_LIBS=1",
                        "-DANDROID_TOOLCHAIN=clang",
                        "-DSECP256K1_ECMULT_GEN_PRECISION=4",
                        "-DSECP256K1_ECMULT_WINDOW_SIZE=15",
                        "-DSECP256K1_USE_ASM=OFF",
                        "-DCMAKE_BUILD_TYPE=Release",
                        "-GCodeBlocks - Unix Makefiles",
                        "-DANDROID_STL=c++_shared"
                cppFlags "-std=c++17"
            }
        }
```
Gives me this error:
```
/home/robert/projects/myapp/CMakeLists.txt : C/C++ debug|arm64-v8a : Failed to activate protocol version: The combination of generator "CodeBlocks - Unix Makefiles" and extra generator "" is not supported.
```
It somehow adds a space after the command, probably to seperate the arguments, but that seems to screw things up.
Also when I try to qoute it:
```
"-G\"CodeBlocks - Unix Makefiles\"",
```
It doesn't parse it right (it seems to take the quotes literal as part of the generator name):
```
/home/robert/projects/myapp/CMakeLists.txt : C/C++ debug|arm64-v8a : Failed to activate protocol version: Generator ""CodeBlocks - Unix Makefiles"" not supported.
```

Any workaround?

**Comment by ggfan** [comment]
are you trying to produce build files for codeblocks IDE or other purposes?
