### ISSUE TITLE
Cannot find declaration of includes

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-ndk#306]
Hello,
I am unable to go to any declarations of the include statements in hello-libs.cpp.  Android Studio pops up an error: **Cannot find declaration to go to**.  See screenshot:

<img width="1440" alt="screen shot 2016-10-12 at 2 00 53 pm" src="https://cloud.githubusercontent.com/assets/201209/19321791/69e2183a-9084-11e6-82d8-ad6fa8ea373f.png">

Please advise,
Igor

**Comment by ggfan** [comment]
this one I need to drink some strong coffee to follow-up:  you are definitely ahead of me -- I am on "to get under-neath gradle+cmake to be perfect"   there are disconnections between UI and underneath gradle+cmake and I was not bother to file those bug at all TBH  :-)

**Comment by IgorGanapolsky** [comment]
@ggfan So is this a Cmake bug, or Android Studio bug?

**Comment by ggfan** [comment]
I would suspect this is more like IDE parsing related issue: external module that is not visible to gradle is not parsed.

**Comment by ggfan** [comment]
Took a brave try with 2.2.1 on mac and linux and Mac, open hello-libs.cpp, it could bring me to the header files and open it with right clicks.  Mine does not have that many red error as yours anymore.

**Comment by IgorGanapolsky** [comment]
@ggfan  I also tried with **2.2.1** on a Mac, and did Invalidate Caches/Restart in A.S.  Now it works.  @changetip $1.

**Comment by changetip** [comment]
Hi @ggfan, @IgorGanapolsky sent you a tip worth 1,555 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/953272)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by ibitton** [comment]
I have the same issue and invalidating the caches doesn't seem to do anything. It was working previously but I think my upgrade to AS 2.2.2 messed something up and now all my files have a cpp icon next to them (before header icons were different).

**Comment by ggfan** [comment]
you are on windows?
