### ISSUE TITLE
Vulkan Sample doesn't seem to sync

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [googlesamples/android-ndk#307]
Just after importing the sample from the Android Studio 2.2.1 main menu, I got an error message:

Error:Project ':threading' does not export native artifacts

Am I missing some component to be installed from the SDK manager? I've been using Gradle-Experimental NDK support for over a year and more recently, CMake support for the OpenSL ES samples (albeit with some issues in itself). Sorry if this is a duplicte in any way - I tried to find if there was any other issue regarding this, but the search came empty.

My system: Ubuntu 14.04 64 bits

**Comment by ggfan** [comment]
you are using ndk-r12 and gradle experimental, correct?  latest code here:
https://github.com/googlesamples/android-vulkan-tutorials  ( tutorial03 ) should be able to build, it is cmake ( and ndk-build for mac + linux,  windows having trouble for layer build  with ndk-build, but cmake is fine ).  Maybe you are using previous version of the samples there,  or you are using lunarG sample repo itself?   please kindly clarify this, we will take a look

**Comment by TheFakeMontyOnTheRun** [comment]
I'm just using the oficial repos and NDK 13.0.3315539. Using the referred code yields the same results.
Looking at the README, it says version  13 is not supported (yet?).

**Comment by TheFakeMontyOnTheRun** [comment]
OTOH, information spilled from 
> ./gradlew clean --info --stacktrace
Says something about LunarG. How can I check the repos I'm using? Isn't it the "SDK Update Sites" under SDK Manager?

**Comment by ggfan** [comment]
the gradle-experimental code inside ndk-12 is removed from ndk-r13.   so you are building strictly from ndk/sources/third_party? ndk-r12 is previous version, what is in there is still there, but not in ndk-R13.  from ndk-R13, you could only build with ndk-build.

**Comment by TheFakeMontyOnTheRun** [comment]
Hmmm, TBH, I use NDK transparently - I have no idea what you're talking about, unfortunately.
In fact, gradle-experimental was the first time I was able to use NDK at all.

**Comment by ggfan** [comment]
that is fine, sorry about the confusion.  where did you get your vulkan sample source code?

**Comment by TheFakeMontyOnTheRun** [comment]
Directly from Android Studio menu. "New>Import Sample..."

**Comment by ggfan** [comment]
I see: the repo backing up that one is this:  https://github.com/googlesamples/vulkan-basic-samples
I believe for that one, you have to use ndk-r12, not r13.  based on what you stated, android studio would download the latest formal release of ndk-r13 to your android's sdk directory under #SDK/ndk-bundle directoy.

**Comment by TheFakeMontyOnTheRun** [comment]
I see. Well, I'm not in a hurry. I hope it will get fixed someday =)

**Comment by ggfan** [comment]
in the mean time, you could also try out the repo:
https://github.com/googlesamples/android-vulkan-tutorials
  to explore, or port the similar thing to the samples you are interested in https://github.com/googlesamples/vulkan-basic-samples ( this is one you are after ).  I will create a bug on that repo and we trace it there: it is long process:  need fix that repo, and also push into upstream which is in LunarG vulkan ( including desktop version ) https://github.com/LunarG/VulkanSamples. But we will get it done, thank you for bring it up

**Comment by ggfan** [comment]
forgot the link:  https://github.com/googlesamples/vulkan-basic-samples/issues/3
