### ISSUE TITLE
hello-jni for x86

### ISSUE THREAD

**Issue by nasht00** [googlesamples/android-ndk#308]
I downloaded the hello-jni as-is and followed the readme.
When running it, I get "Device supports x86_64, x86, but APK only supports armeabi-v7a".

The readme does not mention any changes needed to run on x86, and the screenshot even shows x86.

**Comment by ggfan** [comment]
yeah, the screenshot is from million years ago :-), will fix that. 
this is one example uses productFlavors, so you need choose which one you are building for ( arm, arm7, arm8, x86 ... ).  inside IDE, left bottom edge, click "Build Variants", choose your platform to build from there.  It picks up the 1st one by default, which is arm7 inside app/build.gradle.  APK is smaller comparing to the other samples which including all ABIs. Yes, will update readme to reflect it, thank you for reporting it.
