### ISSUE TITLE
CMake Error Invalid Android NDK revision (should be 12)

### ISSUE THREAD

**Issue by falbertp** [googlesamples/android-ndk#309]
Hi, please help:
I'm using the same JNI Hello sample without problem before updating to NDK 13, please what should I do to fix it?

The Gradle console log:
Executing tasks: [:app:assembleArm7Debug]
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
CMake Error at C:/Users/admin/AppData/Local/Android/sdk/cmake/3.6.3155560/android.toolchain.cmake:356 (message):
  Invalid Android NDK revision (should be 12): 13.0.3315539.
Call Stack (most recent call first):
  D:/Frank/workspace/hello-jni/app/.externalNativeBuild/cmake/arm8Debug/mips64/CMakeFiles/3.6.0-rc2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

Please help, thank you

**Comment by ggfan** [comment]
ndk-r13 suppose to use android.toolchain.cmake inside #NDK_ROOT/build/cmake,  not the one inside sdk's copy. But android studio should automatically do the switch: so somewhere there is a mismatch of your used versions. At one time the beta android-ndk was accidentally gotten into the SDK manager's auto update channel ( very brief moment, then it was fixed ).  couple of checks for sure this version mis-matching will go away:
- delete your .externalNativeBuild directory in your app/ [and other modules if you have them ]: this is significant if you WERE building the SAME project in the SAME place with another version of NDK (cmake caches are NOT cleared when you clean project, need manually remove them )
-  check you do have android.cmake.toolchain in your ndk's  build/cmake directory [you could try to remove sdk bundled ndk and re-download it. but if you just updated ndk-r13 yesterday, this is NOT the problem]
-  your android studio version need aware of different android.cmake.toolchain files, 2.2.0 and 2.2.1 formal release should do a fine work [ previews may have trouble ]. 
Hope it helps.

**Comment by devindi** [comment]
@falbertp check that 'ndk.dir' points to actual ndk folder. After update ndk is a part of sdk)
My local.properties
Before:
```
sdk.dir=/home/devindi/Work/soft/android-sdk-linux
ndk.dir=/home/devindi/Work/soft/android-ndk-r10d
```

After:
```
sdk.dir=/home/devindi/Work/soft/android-sdk-linux
ndk.dir=/home/devindi/Work/soft/android-sdk-linux/ndk-bundle
```

**Comment by falbertp** [comment]
@ggfan thank a lot your direction fix the problem, I did all your three suggestions and tried to run voila it work like a charm :) 
I'm really happy, not only because the program works, also because your reply is very fast and accurate. Great!

My office project currently require me to do with NDK not just ussual Java app, and this is my first time and still learning NDK. Got help a lot here, so now I have a good spirit to continue the project. Thanks again.

@devindi 
This is my current and I check it is correct:
ndk.dir=C\:\\Users\\admin\\AppData\\Local\\Android\\sdk\\ndk-bundle
sdk.dir=C\:\\Users\\admin\\AppData\\Local\\Android\\sdk
thank you

**Comment by ggfan** [comment]
@falbertp thank you for the encouraging comment: makes me feel I should do more :-).  Good luck for your project; if there is something we could make your project smooth, feel free to comment to us -- we love to get some feedback for android  studio + ndk usage.
