### ISSUE TITLE
how to setup additional libraries?

### ISSUE THREAD

**Issue by falbertp** [googlesamples/android-ndk#311]
Hi, my project requires me to include both opencv and tesseract, in visual studio 2012 I can setup by:

1. add to c++ include directories :
`.\api;.\ccmain;.\ccutil;.\ccstruct;.\classify;.\cube;.\cutil;.\dict;.\image;.\neural_networks\runtime;.\textord;.\viewer;.\wordrec;.;$(SolutionDir)\include;$(SolutionDir)include\leptonica;.\port;D:\Frank\opencv\build\include;%(AdditionalIncludeDirectories)`

2. add to linker additional library directories:
`D:\Frank\opencv\build\x64\vc11\lib;$(SolutionDir)lib\$(Platform)\$(Configuration);%(AdditionalLibraryDirectories)`

3. add to linker input:
`ws2_32.lib;user32.lib;liblept$(LIBLEPT_VERSION).lib;libtesseract302.lib;opencv_calib3d2413d.lib;opencv_contrib2413d.lib;opencv_core2413d.lib;opencv_features2d2413d.lib;opencv_flann2413d.lib;opencv_gpu2413d.lib;opencv_highgui2413d.lib;opencv_imgproc2413d.lib;opencv_legacy2413d.lib;opencv_ml2413d.lib;opencv_nonfree2413d.lib;opencv_objdetect2413d.lib;opencv_ocl2413d.lib;opencv_photo2413d.lib;opencv_stitching2413d.lib;opencv_superres2413d.lib;opencv_ts2413d.lib;opencv_video2413d.lib;opencv_videostab2413d.lib`

4. and where should I put the actual .h and .lib files on android studio project structure?

So please help me how can I do those steps in android studio NDK ?

Thank you

**Comment by ggfan** [comment]
For openCV, you might look at this pull Request:  https://github.com/sengsational/HelloCv/pull/1.  That simple project is trying to do the same thing.  Following is my guess:  OpenCV has prebuilt android libs ( under OpenCV-3.1.0-android-sdk ), they have native/jni directory hosting a set of libs.   The referred project pre-copied the lib into his app's app/src/main/jniLibs, then:
- tell linker in CMakeLists.txt to link against libs inside jniLibs
- The shared lib will also automatically be packed [I saw just one shared lib, the rest are static lib ] into your app's final APK, which is nice -- you do not need to do anything at all.

**Comment by falbertp** [comment]
Hi @ggfan ,
I feel very newbie and quite downed because setting those directories in NDK wasn't as easy as I thought, from this morning, I've tried to grasp the meaning and example you've pointed out and tried things, but stuck on gradle error. Quite difficult for me grasp the change the way I used to setting things on Visual Studio and on Android Studio NDK.

The directory for android studio project at:
D:\Frank\workspace\CardScanner
For android OpenCV at:
D:\Frank\OpenCV-android-sdk (can I use the non android version or I must use this android version of the OpenCV?)
For tesseract well I do not have the android version just the standard version located at:
D:\Frank\tesseract-vs2012-master

This is the CMakeLists.txt I've tried to change following your sample, forgive me for what went wrong:

```
cmake_minimum_required(VERSION 3.4.1)
?? do you mean that I should put CMAKE_SOURCE_DIR on system Path environment???
set(pathToOpenCv ${CMAKE_SOURCE_DIR}/../../../OpenCV-android-sdk)
include_directories(${pathToOpenCv}/sdk/native/jni/include)

add_library(native-lib SHARED src/main/cpp/native-lib.cpp
            lib_opencv SHARED IMPORTED ?????? there is no lib_opencv.cpp file ???
             )
             
set_target_properties(lib_opencv PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libopencv_java3.so)

find_library(log-lib 
              log )

target_link_libraries( # Specifies the target library.
                        native-lib
                        android
                        jnigraphics
                        lib_opencv
                        log
                        m
                       # Links the target library to the log library
                       # included in the NDK.
                       ${log-lib} )
```
Please help, thank you

**Comment by falbertp** [comment]
> yes, Android app must use libs built for android. Generic one may not work
Is there any way I can built common libs to android one?

**Comment by ggfan** [comment]
with the source code, you could build then as android native lib:  android studio could do that: you need create cmake scripts or ndk-build script for it ONLY if they do not have script already created. Check the source code to see if they already have scripts for android already.  https://github.com/googlesamples/android-ndk/tree/master/hello-libs/gen-libs might be useful if you go down to build your own libs for android ( it builds one shared and one static lib )

**Comment by falbertp** [comment]
Hi, this is the corrected one:
```
cmake_minimum_required(VERSION 3.4.1)
set(pathToOpenCv ${CMAKE_SOURCE_DIR}/../../../OpenCV-android-sdk)
include_directories(${pathToOpenCv}/sdk/native/jni/include)

add_library(native-lib SHARED src/main/cpp/native-lib.cpp
             )

set_target_properties(lib_opencv PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libopencv_java3.so)

find_library(log-lib
              log )

target_link_libraries( native-lib
                        android
                        jnigraphics
                        lib_opencv
                        log
                        m )
```

From what I'm understand that line means:
lib_opencv = will be the variable name of location of the opencv's libs
${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libopencv_java3.so = actual path to file libopencv_java3.so according to the ANDROID_ABI (arm64-v8a, armeabi, armeabi-v7a, mips .... )

I'm also copying the complete folder from inside opencv's sdk\native\libs which contains libopencv_java3.so files inside several ANDROID_ABI (arm64-v8a, armeabi, armeabi-v7a, mips .... )
folders into the android project ${CMAKE_SOURCE_DIR}/src/main/jniLibs/

but still it has gradle error:
CMake Error at CMakeLists.txt:9 (set_target_properties):
  set_target_properties Can not find target to add properties to: lib_opencv

line no 9 is:
`set_target_properties(lib_opencv PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libopencv_java3.so)`

**Comment by ggfan** [comment]
How about you try it out first, then modify yours? ---
- get code from this repo: https://github.com/ggfan/HelloCv ( it is source of that PR )
- checkout out branch "private-master"  [ i have his origin repo as origin, my forked named private ]
- "import" the project into your android studio so local.properties will be created
- then build and see how it goes [ it should work ]

to check on yours, I would do:
- rm -fr app/.externalNativeBuild
- in terminal,  ls  .../src/main/jniLibs/armeabi/libopencv_java3.so, see if it errors, make sure no errors then build from android studio.

**Comment by falbertp** [comment]
@ggfan download the HelloCv source and change CMakeLists.txt to my paths:
```
set(pathToProject D:/Frank/workspace/HelloCv)
set(pathToOpenCv D:/Frank/OpenCV-android-sdk)
```

but when run gradle error:
`Error:error: 'D:/Frank/workspace/HelloCv/app/src/main/jniLibs/arm64-v8a/libopencv_java3.so', needed by '../obj/arm64-v8a/libnative-lib.so', missing and no known rule to make it`

And for my project, I'm following your suggestions:
1. delete directory app/.externalNativeBuild
2. list to check whether file libopencv_java3.so exists in my project/src/main/jniLibs/armeabi/ and it is exists no error

then resync gradle, clean project, rebuild project then run again, but still the same gradle error at:
`set_target_properties(lib_opencv PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libopencv_java3.so)`

does it has notation different between linux and windows? because I'm using windows.

**Comment by ggfan** [comment]
probably you did not checkout the branch: private-master -- I deleted pathToProject in branch. let me remove master branch to avoid confusion [ close android studio; git checkout -b test origin/private-master; git clean -xdf; git reset --hard; then re-import project ]

If it is real problem of disk[I am not sure], you could try to use relative path for pathToOpenCv.  The syntax could be windows or Unix format for path, maybe use Unix format and let CMake do its own trick for windows translation [ that way, you code would be buildable on all OSes ].

**Comment by falbertp** [comment]
hi @ggfan , sorry I can't do git directly from my computer because my office network rules, but I can download the zip file (which I did before the previous question) and try your code, which then result the gradle error.

Anyway I'm just thinking, can I do it the other way. Suppose currently I have all the ".so" files (at respected ABI directories), could you please help me out on guiding step by step how can I use that so files as library, so I can for example do "import com.googlecode.tesseract.android.TesseractAPI;" then use for example like:
TessBaseAPI tessBaseAPI = new TessBaseAPI();

I've read lots of "android studio how to add so files", but the solutions is deprecated and false for android 2.2 or maybe just for the setup of my new android project in android 2.2. Tried to read from NDK sites it's really confusing because mixed between cmake, ndk_build, etc.

Note: I'm succeeded on creating *.so files from tesseract API by doing this:
```
ndk-build
android update project --path C:\...\tesseract --target android-16
ant release
```
Please help

**Comment by ggfan** [comment]
yes, if you re-download the file, it should be different from previous one. double check for your app/cmakelists.txt in the zip file is same as the one at: https://github.com/ggfan/HelloCv/blob/master/app/CMakeLists.txt

**Comment by falbertp** [comment]
Hi @ggfan , I've redownload the zip then load the extracted to android studio, tried to run it and produce error, tried to delete .externalNativeBuild and re sync and run again the same error:

```
Executing tasks: [:app:assembleDebug]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:openCVLibrary310:preBuild UP-TO-DATE
:openCVLibrary310:preReleaseBuild UP-TO-DATE
:openCVLibrary310:checkReleaseManifest
:openCVLibrary310:prepareReleaseDependencies
:openCVLibrary310:compileReleaseAidl UP-TO-DATE
:openCVLibrary310:compileReleaseNdk UP-TO-DATE
:openCVLibrary310:compileLint UP-TO-DATE
:openCVLibrary310:copyReleaseLint UP-TO-DATE
:openCVLibrary310:mergeReleaseShaders UP-TO-DATE
:openCVLibrary310:compileReleaseShaders UP-TO-DATE
:openCVLibrary310:generateReleaseAssets UP-TO-DATE
:openCVLibrary310:mergeReleaseAssets UP-TO-DATE
:openCVLibrary310:mergeReleaseProguardFiles UP-TO-DATE
:openCVLibrary310:packageReleaseRenderscript UP-TO-DATE
:openCVLibrary310:compileReleaseRenderscript UP-TO-DATE
:openCVLibrary310:generateReleaseResValues UP-TO-DATE
:openCVLibrary310:generateReleaseResources UP-TO-DATE
:openCVLibrary310:packageReleaseResources UP-TO-DATE
:openCVLibrary310:processReleaseManifest UP-TO-DATE
:openCVLibrary310:generateReleaseBuildConfig
:openCVLibrary310:processReleaseResources
:openCVLibrary310:generateReleaseSources
:openCVLibrary310:incrementalReleaseJavaCompilationSafeguard
:openCVLibrary310:compileReleaseJavaWithJavac
:openCVLibrary310:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:openCVLibrary310:processReleaseJavaRes UP-TO-DATE
:openCVLibrary310:transformResourcesWithMergeJavaResForRelease
:openCVLibrary310:transformClassesAndResourcesWithSyncLibJarsForRelease
:openCVLibrary310:mergeReleaseJniLibFolders
:openCVLibrary310:transformNative_libsWithMergeJniLibsForRelease
:openCVLibrary310:transformNative_libsWithSyncJniLibsForRelease
:openCVLibrary310:bundleRelease
:app:prepareComAndroidSupportAnimatedVectorDrawable2420Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72420Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCompat2420Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUi2420Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUtils2420Library UP-TO-DATE
:app:prepareComAndroidSupportSupportFragment2420Library UP-TO-DATE
:app:prepareComAndroidSupportSupportMediaCompat2420Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42420Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2420Library UP-TO-DATE
:app:prepareHelloCvMasterOpenCVLibrary310UnspecifiedLibrary
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:generateJsonModelDebug UP-TO-DATE
:app:externalNativeBuildDebug
  building D:\Frank\workspace\HelloCv-master\app\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so
:app:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
Error while executing 'C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\bin\cmake.exe' with arguments {--build D:\Frank\workspace\HelloCv-master\app\.externalNativeBuild\cmake\debug\arm64-v8a --target native-lib}
[1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
FAILED: C:\Users\admin\AppData\Local\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  -target aarch64-none-linux-android -gcc-toolchain C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64  -Dnative_lib_EXPORTS -I../../../../../../OpenCV-3.1.0-android-sdk/sdk/native/jni/include -isystem C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -isystem C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -frtti -fexceptions -std=gnu++11 -O0 -fno-limit-debug-info -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\native-lib.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -c D:\Frank\workspace\HelloCv-master\app\src\main\cpp\native-lib.cpp
D:\Frank\workspace\HelloCv-master\app\src\main\cpp\native-lib.cpp:3:10: fatal error: 'opencv2/core.hpp' file not found
  #include <opencv2/core.hpp>
           ^
  1 error generated.
  ninja: build stopped: subcommand failed.
```

Should I change anything related to my path before tried the code?

Thank you please help

**Comment by falbertp** [comment]
It works! :) :+1:  :+1:  :+1:  The sample works.
I will learning the sample before asking again :) thank you so much

**Comment by falbertp** [comment]
By creating correct CMakeLists.txt I can call opencv methods from c++, but when I want to call opencv methods from android cannot, and only can be done after I'm copying the structure of openCVLibrary310 from the HelloCv sample and add it on gradle setting. What I'm confuse now is the structures and files openCVLibrary310 cannot be found from the official opencv for android library downloaded from official site: http://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.1.0/OpenCV-3.1.0-android-sdk.zip/download . So I presume the author of HelloCv has created openCVLibrary310 manually instead of just copying from the official library, am I right? If so for others external libraries I must do the same right?

**Comment by ggfan** [comment]
by looking that sample and the downloaded sdk, my guess:
- openCV has 2 set of interfaces or android: call native directly, or call from Java code
- native API is under folder your-3-1-0-sdk/native/...
- java API is under folder  your-3-1-0-sdk/java

I think that openCVLibrary310 module is something related to openCV java interface, and you would just need one module from your app. But if you want to use openCV from your JAVA and your native code, you would need both ( this is my guess, I am not familiar with it ). Anyhow, that openCVLibrary more like the module imported from sdk/java directory.  You might refer to this 
http://stackoverflow.com/questions/27406303/opencv-in-android-studio to try it out on importing java module, see how it goes.

**Comment by falbertp** [comment]
I'm following the steps suggested at http://stackoverflow.com/questions/27406303/opencv-in-android-studio it's a success, from what I'm understand that way only for how to access opencv methods from java side and not from c++ side? So if I want to do from the c++ side I still need to config the CMakeList.txt?

**Comment by ggfan** [comment]
My knowledge about the openCV contents is limited [at the moment at least :-)]. if your native code wants to call openCV directly, most likely you need configure the CMakeLists.txt to
-  include header files
-  add linked libs [ is has some static libs, one shared lib, I saw ]

but configure those things is extremely simple [if you do not care master-level cmake script quality]. HelloCv already does that so you would just move on with it.  You could try not to pack the shared lib in your app to see if openCVLibrary310 packs already:  after build apk, use analyze apk, check the lib folder inside apk, then you know.  If it does not pack it [ that is my guess], your app need to pack it as HelloCv does.  Again HelloCv is someone else repo, I only modify the scripts to make it easier for android studio 2.2.0+ [ or maybe I made it harder :-)].  just my thoughts

**Comment by falbertp** [comment]
@ggfan you are THE BEST :) :+1: :+1: :+1: thanks everything is clear
