### ISSUE TITLE
Android NDK - Teapot Sample

### ISSUE THREAD

**Issue by NativeCodeSamples** [googlesamples/android-ndk#315]
Can you provide me a NDK code for render a 3D Teapot with textures using .bmp of .tga file ?

**Comment by ggfan** [comment]
do not have the code in this set of samples; remembered in vulkan sample only have some code for png texture.  you will have to do a search for existing libs to use

**Comment by kunjeshhello** [comment]
Can you provide website or book name for learning complete NDK.

**Comment by ggfan** [comment]
NDK itself is about a set of tools (compiler version, linkers cross-platform scripts0: https://github.com/android-ndk/ndk, the owner of that one is the master minds for the toolset.
Android Studio for native development is UI using NDK tools ( enabling code navigation and debugging, profiling etc in UI )
The application contents are in various development APIs ( input, out [openSLES-not very pleasing though, 2D graphics, 3D graphics, VR etc]. It spreads over various domain knowledge, and which I personally think is more important than a bunch of the build scripts [ very biased ].  Those domain knowledge related APIs could be found in various documentation from Google developer's webpage and other websites.  Domain knowledge are transparent: desktop and mobile no difference -- doing the same thing just with a little different ways. 

Search on amazon page for android-ndk( I had one of them), you might come up several titles, get one to start up would be good [ the documentation tends to be fragmented and does not come up with a whole picture], then you would need to keep up with ndk and android studio page for the latest one [ books are normally not up to date ]. Again what you do [ the domain knowledge ] defines main course of the meal, good tools [like NDK, studio] stay to shorten your development time. 

sorry for not coming up with a specific answer to your question.

**Comment by ggfan** [comment]
closing this for now, I will remember the requirement for the texture.
