### ISSUE TITLE
Memory leak in native-activity sample

### ISSUE THREAD

**Issue by domdom** [googlesamples/android-ndk#317]
https://github.com/googlesamples/android-ndk/blob/master/native-activity/app/src/main/cpp/main.cpp

```
auto supportedConfigs = new EGLConfig[numConfigs];
```
Allocated array on line 94, but it is never freed. Is there a missing delete[] after the last use of supportedConfigs on line 113?

**Comment by ggfan** [comment]
yes, need to fix it
