### ISSUE TITLE
Android Studio doesn't respect the relative including path in cmake's `android_gradle_build.json`

### ISSUE THREAD

**Issue by beeender** [googlesamples/android-ndk#319]
We are generating JNI header files in the build dir when cmake starts, relevant `CMakeList.txt` can be found https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/cpp/CMakeLists.txt

```
set(jni_headers_PATH ${PROJECT_BINARY_DIR}/jni_include)
# ...
include_directories(${REALM_CORE_DIST_DIR}/include
    ${CMAKE_SOURCE_DIR}
    ${jni_headers_PATH}
    ${CMAKE_SOURCE_DIR}/object-store/src)
```

You can see from above, the `jni_headers` is a absolute path inside the build dir. But for some reason, the compile options becomes:

``` json
                {
                    "flags" : "   -DANDROID -Drealm_jni_EXPORTS -isystem /home/cc/.android-ndk/android-ndk-r10e/platforms/android-9/arch-x86/usr/include -isystem /home/cc/.android-ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/cc/.android-ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include -isystem /home/cc/.android-ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I/home/cc/repo/realm/realm-java-2/realm/realm-library/distribution/realm-core/core-1.0.0-BETA-3.1/include -I/home/cc/repo/realm/realm-java-2/realm/realm-library/src/main/cpp -Ijni_include -I/home/cc/repo/realm/realm-java-2/realm/realm-library/src/main/cpp/object-store/src  -fexceptions -frtti -fpic --sysroot=/home/cc/.android-ndk/android-ndk-r10e/platforms/android-9/arch-x86 -funwind-tables -funswitch-loops -finline-limit=300 -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DREALM_ANDROID -DREALM_HAVE_CONFIG -DPIC -pthread -fvisibility=hidden -std=c++14 -fsigned-char -DREALM_SYNC -Wall -Wextra -pedantic -Wno-long-long -Wno-variadic-macros -Wno-missing-field-initializers -Wmissing-declarations -Wno-error=uninitialized -Wno-error=maybe-uninitialized  -ggdb -Og -DNDEBUG    -c ",
                    "src" : "/home/cc/repo/realm/realm-java-2/realm/realm-library/src/main/cpp/object-store/src/sync_manager.cpp",
                    "workingDirectory" : "/home/cc/repo/realm/realm-java-2/realm/realm-library/.externalNativeBuild/cmake/objectServerDebug/x86"
                },
```

that the `-Ijni_include` points to the relative path to the `workingDirectory` .

This caused the header files in the `jni_include` cannot be found in the AS.

The question is:
1. Why the absolute path of `jni_headers_PATH` becomes a relative one after `include_directories`?
2. If the 1) is the desired behavior, I think the AS should respect the `workingDirectory` when finding the header files?

Thanks!

**Comment by ggfan** [comment]
I thought the working directory at building time is at the binary directory, not the directory where the CMakeLists.txt is sitting.  I will follow-up after a couple of days [after keeping my current thing in order]

**Comment by beeender** [comment]
Now my workaround is adding a `/./` before `${PROJECT_BINARY_DIR}` like set(jni_headers_PATH /./${PROJECT_BINARY_DIR}/jni_include)`. So the absolute path won't be stripped into the relative path to the binary dir. I cannot find any reasons why does cmake has this behavior.

**Comment by ggfan** [comment]
trying to compile it, something else get in the way:
 Error:(20, 46) fatal error: object-store/src/object_schema.hpp: No such file or directory
when I tried with project under /realm-java/realm/, maybe I missed some pre-required steps?  thanks

**Comment by beeender** [comment]
Did you do a `git submodule update --init` before calling `./gradlew assemble` from the project root directory?

**Comment by ggfan** [comment]
yeah, that is it. thanks!

**Comment by ggfan** [comment]
I think latest one ( Android Studio 2.3 Beta 1 from canary ) might fix it already; or you are using windows to build? I am using Mac. Please let me know

Either removing your workaround or leaving it does not matter, realm-library could build on my Mac. 
you could see the compile flags in action with my build[ I deliberately added error into file io_realm_internal_CheckedRow.cpp to cause a stop so I could see what the compile options are at the time; just remove my-added-errors and rebuild, it will succeed, you got to trust me for this :-)]

I could also see, with your workaround, the option is:
-I/./Users/gfan/proj/bugfix/realm-java/realm/realm-library/.externalNativeBuild/cmake/baseDebug/arm64-v8a/jni_include
[it works too on Mac ]

My replicate environment:

use project in: realm-java/realm with
- clone your source
- git submodule -init 
- import realm-java/realm/build.gradle into android studio
- add file(make_directory ${class_PATH}) to cmakelists.txt <=== this might need to be added into your repo
- change the version back to its 2.2.1 [I could not deal with 2.3.0-SNAPSHOT version]
- change ABI to ARM family only, does not support x86 and mips [build.gradle]
- def ndkPathInEnvVariable = "/Users/gfan/dev/android-ndk-r10e" [you are asking both environ and local.properties to be same...]
- changed SHA256 [dependencies.list]
#REALM_SYNC_SHA256=7bbaa9cdef722d85489feb1b70da11d5640869540d9a0fc40621de7352dd9ffd
REALM_SYNC_SHA256=3463fa7a3b232839c6205a616ce431ddedd7c667918971231ec2ff700618c25f

it is NOT your exact environment, BUT it should not matter for this include-path-issue either.
 
----- the compile flags in effect when building, after removing your "/./" workaround -------
/Users/gfan/dev/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++   -DANDROID -Drealm_jni_EXPORTS -isystem /Users/gfan/dev/android-ndk-r10e/platforms/android-21/arch-arm64/usr/include -isystem /Users/gfan/dev/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /Users/gfan/dev/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -isystem /Users/gfan/dev/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I/Users/gfan/proj/bugfix/realm-java/realm/realm-library/distribution/realm-core/core-1.0.0-BETA-5.0/include -I/Users/gfan/proj/bugfix/realm-java/realm/realm-library/src/main/cpp -Ijni_include -I/Users/gfan/proj/bugfix/realm-java/realm/realm-library/src/main/cpp/object-store/src -fexceptions -frtti -Wno-psabi --sysroot=/Users/gfan/dev/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DREALM_ANDROID -DREALM_HAVE_CONFIG -DREALM_HAVE_EPOLL -DPIC -pthread -fvisibility=hidden -std=c++14 -fsigned-char -Wall -Wextra -pedantic -Wno-long-long -Wno-variadic-macros -Wno-missing-field-initializers -Wmissing-declarations -Wno-error=uninitialized -Wno-error=maybe-uninitialized  -ggdb -Og -DNDEBUG -fPIC -MD -MT CMakeFiles/realm-jni.dir/io_realm_internal_CheckedRow.cpp.o -MF CMakeFiles/realm-jni.dir/io_realm_internal_CheckedRow.cpp.o.d -o CMakeFiles/realm-jni.dir/io_realm_internal_CheckedRow.cpp.o -c /Users/gfan/proj/bugfix/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_CheckedRow.cpp
  /Users/gfan/proj/bugfix/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_CheckedRow.cpp:19:1: error: 'skfdljdsl' does not name a type
   skfdljdsl;fkdsf;   //<=== this is [on purpose] an error to see what the compile options are
   ^                          // removes this compile fine

**Comment by beeender** [comment]
@ggfan Sorry, I didn't make issue description clear. The build part is fine with/without the workaround. The problem is in the AS (I mean the IDE), `android_gradle_build.json` is using the relative path of `jni_include`, and the AS needs to know the path to find header files to do the syntax checking. But AS cannot, since it doesn't know the working path of cmake, which you can see it will report `header files cannot be found` error in the AS when you opening the `io_realm_internal_CheckedRow.cpp` inside the AS editor.

BTW, I am using AS under Linux. AS reports more strange "header files cannot be found" issues with my mac, but that is another topic, i haven't spent too much time to investigate that yet.

**Comment by beeender** [comment]
Also, from your build log, i can see the command line is still using `-Ijni_include` which is the relative path to the cmake dir. I think that also means `android_gradle_build.json` is still using the relative dir which still causes trouble for AS cpp editor for finding the header files.

**Comment by ggfan** [comment]
I see, this issue is about the AS, not about the gradle.  The AS-UI has more similar issues, like:  https://code.google.com/p/android/issues/detail?id=208114. 

it is valid bug, added a link in the above issue to this one, we would follow up on that one and close down this one.  UI portion is tough to track : much more work I felt.

**Comment by ggfan** [comment]
do you mind to re-test to see if it is still necessary with `/./` workaround? I do not think anything particularly done for it. thanks

**Comment by ggfan** [comment]
aging this one out
