### ISSUE TITLE
Add a sample how to create a keyboard with ndk

### ISSUE THREAD

**Issue by seniorivn** [googlesamples/android-ndk#323]
Hi, was looking for a way to create lightweight keyboard(ime) using ndk, unfortunately there is no such sample.

**Comment by ggfan** [comment]
yes, I do not remember knowing that: a while back mentioned among us about that and the conclusion was using keyboard from java side, and via JNI to communicate back and forth.

**Comment by seniorivn** [comment]
@ggfan, thanks.
that looks not so good

**Comment by ggfan** [comment]
will ask around to see what the current status is.

**Comment by proppy** [comment]
https://github.com/googlesamples/android-ndk/pull/137 was showing how do this using JNI.

**Comment by proppy** [comment]
@seniorivn oups, sorry for the missunderstanding!

**Comment by ggfan** [comment]
closing this one as no info from native side found/available (probably go through jni to use java side api ). Please re-open it at any time as appropriate. thanks for bringing it up

**Comment by koyach** [comment]
this is a den of vipers

dude pk
ls ...

**Comment by ggfan** [comment]
THB: there is no native-side interface for this, I am sorry for not being direct if you were looking for a confirmative-direct answer.

**Comment by seniorivn** [comment]
@ggfan i got it, no problem
