### ISSUE TITLE
Minor: Incorrect error check.

### ISSUE THREAD

**Issue by ketanm** [googlesamples/android-ndk#324]
Hi,

In the file - https://github.com/googlesamples/android-ndk/blob/master/native-codec/app/src/main/java/com/example/nativecodec/MyGLSurfaceView.java

Uniform variables check should use correct handle:

        muSTMatrixHandle = GLES20.glGetUniformLocation(mProgram, "uSTMatrix");
        checkGlError("glGetUniformLocation uSTMatrix");
        if (muMVPMatrixHandle == -1) {
            throw new RuntimeException("Could not get attrib location for uSTMatrix");
        
Replace if(muMVPMatrixHandle with if (muSTMatrixHandle).

Ketan

**Comment by ggfan** [comment]
that is great finding, create PR:  https://github.com/googlesamples/android-ndk/pull/326  to fix it. thank you to bring it up!
