### ISSUE TITLE
Frame length of the input micropone signal

### ISSUE THREAD

**Issue by reddchanka** [googlesamples/android-ndk#328]
I am trying to read the microphone signal and insert a Speech Enhancement for every frame. But I am not able to figure out the buffer length of each frame. I would like to know if I can modify the sampling frequency and the buffer length that fits my needs. Thanks!!

**Comment by ggfan** [comment]
not sure your question is addressed, for future audio questions, feel free to post

- [android-ndk-forum](https://groups.google.com/forum/#!forum/android-ndk)
- [stackoverflow](https://stackoverflow.com)
- [audio high performance repo](https://github.com/googlesamples/android-audio-high-performance) --- experts are behind this
