### ISSUE TITLE
Add sample with different configuration per built type

### ISSUE THREAD

**Issue by Nimrodda** [googlesamples/android-ndk#33]
I might be missing something, but judging by the provided samples so far, I don't see a way to set different NDK configuration per build type. 
Examples:
1.    Depending on prebuilt library, I'd like to use the debug version of the prebuilt lib when in a debug build type, etc.
2.    Having different cflags per build type, etc.
@ph0b has previously provided a temporary solution using the old-DSL:
Check out http://stackoverflow.com/questions/28878689/android-ndk-and-gradle-different-android-mk-per-build-type for what I am trying to achieve.

**Comment by ggfan** [comment]
might try this:
1) in module gradle, set build flag for specific build flavor 
    android.productFlavors {
        create("x86-release") {
            ndk.abiFilters += "x86"
            ndk.CFlags += "-DNO_DEBUG"
        }
        create("x86-debug") {
            ndk.abiFilters += "x86"
            ndk.CFlags += "-DDEBUG_ENABLE"
        }
    }
2) inside Android Studio, choose the right one to build  with "Build Variant"
3) if you build from command line, I think you could find the right target to build and build specific one you like and build it etc.

**Comment by proppy** [comment]
We should have a sample that show this, renaming the issue to track this.

**Comment by proppy** [comment]
2. should be possible by adding cFlags into `android.buildTypes` block.

/cc @rschiu is the new dependencies system capable of resolving debug vs release prebuild?

**Comment by rschiu** [comment]
Yes, if the build type is not specified, it will try to find one that matches the build type of the application
