### ISSUE TITLE
native-media sample crashed when clicked "Start / Pause Java MediaPlayer" button

### ISSUE THREAD

**Issue by khirowatari** [googlesamples/android-ndk#333]
native-media sample crashed when clicked "Start / Pause Java MediaPlayer" button.
```
E/NativeMedia: IOException java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
E/MediaPlayer: prepareAsync called in state 1
D/AndroidRuntime: Shutting down VM
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.nativemedia, PID: 9294
                  java.lang.IllegalStateException
                      at android.media.MediaPlayer.prepareAsync(Native Method)
                      at com.example.nativemedia.NativeMedia$7.onClick(NativeMedia.java:239)
                      ...
```

Patch for fix issue.
```
diff --git a/native-media/app/build.gradle b/native-media/app/build.gradle
index 249a1c3..471b9f1 100644
--- a/native-media/app/build.gradle
+++ b/native-media/app/build.gradle
@@ -30,4 +30,7 @@ apply plugin: 'com.android.application'
              path 'src/main/cpp/CMakeLists.txt'
          }
      }
+     aaptOptions {
+         noCompress 'ts'
+     }
 }
```

**Comment by ggfan** [comment]
yes, indeed: there is a crash on java side player, and this fixes it.  thank you for pointing it out:  I will create a CL and check others as well; then let you review the changes.  

thanks

**Comment by ggfan** [comment]
https://github.com/googlesamples/android-ndk/pull/335, Please take a look, thanks

**Comment by ggfan** [comment]
it is checked in.  I did notify this time that I need to restart the app after I used one of the player ( either native or java player) to use the other one, will look at it some time later ( I suspect it was designed like that )

thanks

**Comment by Pezhin** [comment]
aaptOptions {
          noCompress 'ts'
      }
why is this fixing the issue? can you explain this a little bit?

**Comment by khirowatari** [comment]
@ggfan Thanks merge!

@Pezhin 
This issue caused by AssetManager#openFd
openFd method cannot open compressed asset. And android build system compresses assets except specific extensions(jpg, png, mp3, etc...).
"noCompress" option register asset extensions to avoid compress.

(But https://developer.android.com/reference/android/content/res/AssetManager.html#openFd(java.lang.String) document lacked...)

I found same case in stackoverflow.
http://stackoverflow.com/questions/11678043/filereader-csv-filenotfoundexception-this-file-can-not-be-opened-as-a-file-de
http://stackoverflow.com/questions/5534212/cannot-play-audio-from-assets-it-is-probably-compressed

**Comment by Pezhin** [comment]
@khirowatari  Very helpful, thanks a lot
