### ISSUE TITLE
License for CMake

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-ndk#334]
Hello,
I am trying to run the project on a CI machine (via commandline).  Upon executing `./gradlew assemble`, I get this error:
>  You have not accepted the license agreements of the following SDK components:
        [CMake 3.6.3155560].

Do you know why this is happening?

Igor

**Comment by ggfan** [comment]
Not really myself, I installed it with SDK manager UI thus far. not sure it is related, do you install it on command line (for cmake? it is under $sdk/cmake directory )?  will ask expert for this one.

**Comment by IgorGanapolsky** [comment]
@ggfan You are absolutely right!  I was missing the $sdk/cmake directory.  How can I install it from commandline (instead of SDK UI)?

**Comment by ggfan** [comment]
https://developer.android.com/studio/intro/update.html#download-with-gradle

**Comment by jomof** [comment]
The rest of the message should give you the instructions you need. Basically you have to copy the license over from a machine where you have accepted them. See  http://d.android.com/r/studio-ui/export-licenses.html

**Comment by IgorGanapolsky** [comment]
@jomof That doesn't resolve the CMake issue.  Those licenses (**android-sdk-license**, **android-sdk-preview-license**, **intel-android-extra-license**) have already been copied from my machine.

**Comment by jomof** [comment]
The file android-sdk-license is the one that will contain the CMake acceptance. Here's what I did to verify.

On Android Studio machine:
- Uninstall CMake
- Delete $sdk/licenses
- Try to build a CMake project and confirm I get the message you posted above.
- Install CMake and confirm $sdk/licenses/android-sdk-license has appeared

On CI machine,
- copy $asdk/licenses/android-sdk-license from other machine
- Without CMake installed build same project (./gradlew assemble)

At this point you should get messages indicating that CMake is installed.

> Checking the license for package CMake 3.6.3155560 in /usr/local/google/home/jomof/Android/Sdk/licenses
> License for package CMake 3.6.3155560 accepted.
> Preparing "Install CMake 3.6.3155560".
> "Install CMake 3.6.3155560" ready.
> Finishing "Install CMake 3.6.3155560"
> Installing CMake 3.6.3155560 in /usr/local/google/home/jomof/Android/Sdk/cmake/3.6.3155560
> "Install CMake 3.6.3155560" complete.
> "Install CMake 3.6.3155560" finished.

 Then the build will continue.

**Comment by IgorGanapolsky** [comment]
@jomof  When you say 
>Install CMake

how exactly were you installing it?  I am only doing it from command-line, so there is no option to install CMake...

**Comment by jomof** [comment]
It is stealthily hidden under Appearance & Behavior in the settings dialog. Easiest way to get there is Android Studio/Settings.../type "SDK"/SDK Tools/CMake/Apply

**Comment by changetip** [comment]
Hi @jomof, @IgorGanapolsky sent you a tip worth 1,364 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/955107)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by IgorGanapolsky** [comment]
@ggfan Thanks for the tip on $sdk/licenses directory.  @changetip $1.

**Comment by changetip** [comment]
Hi @ggfan, @IgorGanapolsky sent you a tip worth 1,364 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/955108)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by jomof** [comment]
Oh, AFAIK you have to run AS somewhere to create the license file. After that you can copy the license around

**Comment by ggfan** [comment]
tried with:

- copy "licenses" from my Mac $sdk_home directory to a virtual machine ( linux )'s $sdk_home/ ( there was no licenses dir there ); make sure I installed cmake on my Mac BEFORE copying the "licenses" dir
- ./gradlew  dependencies on hello-jni sample
I could that cmake is installed. 

closing down this one, please let me know otherwise: thanks for bring it up -- it is very important usage case.
