### ISSUE TITLE
redundant activity_hello_jni.xml in Hello JNI sample

### ISSUE THREAD

**Issue by RogerHardiman** [googlesamples/android-ndk#336]
The Hello_JNI sample includes an activity layout called
    activity_hello_jni.xml

However this is not used in the sample.

The Java code creates a Text View and then uses this Java created TextView as the ContentView
  TextView tv = new TextView(this);
  tv.setText( stringFromJNI() );
  setContentView(tv);

For consistency either
a) the XML view layout should be removed
OR
b) the Java code should findViewById on the ImageView in the Layout XML

**Comment by ggfan** [comment]
that is true:  should find some time to clean it out. This must be caused during the migration process where using new android studio template to generate new project and copying old file to over it for  to migrate. thanks for the findings, will get it cleaned

**Comment by RogerHardiman** [comment]
Would you prefer to remove the XML layout or prefer to use it?
Just checking as I can do a Pull Request if you want

**Comment by ggfan** [comment]
I like to use it: to make template team happy

**Comment by ggfan** [comment]
I personally felt that that removing XML file is better: that one uses constraint layout, as this is supposed to be simple one to start with, we could be forgiven without introducing the constraint layout feature. what do you think?

**Comment by ggfan** [comment]
code merged in, thank you very much for bring it up!
