### ISSUE TITLE
CFlags option '-fomit-frame-pointer' not allowed with '-pg'

### ISSUE THREAD

**Issue by liangshuochen** [googlesamples/android-ndk#337]
hi,
I'm using  Experimental NDK Plugin 0.7.0, following[ this doc](http://tools.android.com/tech-docs/new-build-system/gradle-experimental#TOC-Ndk-Integration),
I want to profile my ndk code, so in my project app/build.gradle, 
I config it as this:
`        
       buildTypes {
            debug {
                ndk {
                    debuggable = true
                }
            }
        }
`
and add  `CFlags.addAll( '-pg'])` 

but, it seems still compiled as release version, I also test the sample other-builds/experimental/gles3jni, it has the same result,  
in the build/tmp/compileGles3jniArm64-v8aDebugSharedLibraryGles3jniArm64-v8aDebugSharedLibraryMainC/option.txt file has the `-fomit-frame-pointer` option.
The whole file is:
```
-x
c
-c
-fPIC
-DANDROID
-DANDROID_NDK
-gcc-toolchain
/Users/liangshuochen/MyApplications/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64
-target
aarch64-none-linux-android
-fpic
-ffunction-sections
-funwind-tables
-fstack-protector
-no-canonical-prefixes
-O2
-g
-DNDEBUG
-fomit-frame-pointer
-fstrict-aliasing
-O0
-UNDEBUG
-fno-omit-frame-pointer
-fno-strict-aliasing
-fno-limit-debug-info
-Wall
-pg
-I
/Volumes/MacintoshHD/Documents/work/otherTest/android-ndk-git/other-builds/experimental/gles3jni/app/src/main/headers
--sysroot=/Users/liangshuochen/MyApplications/android-ndk-r10e/platforms/android-21/arch-arm64
```

 could anyone has the same situation?

**Comment by ggfan** [comment]
yeah, I could see it on my ends: need to study it and update it here.  thanks

**Comment by ggfan** [comment]
let's follow with that [bug](https://code.google.com/p/android/issues/detail?id=230098).
