### ISSUE TITLE
Will i able to get system audio output as buffer or byte array or stream using android ndk? 

### ISSUE THREAD

**Issue by sulaimansust** [googlesamples/android-ndk#338]
In description of your first sampe, android-echo, you have told that "the playback on speaker will be captured immediately and played back." . Is that mean i can get system audio output using android NDK?? I badly need it.

**Comment by ggfan** [comment]
by doing that it means that:
  the speaker plays the audio out, so it goes out to the surrounding;
  the microphone would immediately pick up the audio from speaker and record it again

the above makes a positive feedback loop: the effect is pretty laud noise and pretty disturbing to people around you in the office area.

**Comment by sulaimansust** [comment]
Oh. I thought i can get the internal output data which is passed to speaker instead of recording the speaker data

**Comment by ggfan** [comment]
sorry, I do not know the interface for that. closing this one for now.
