### ISSUE TITLE
Sample hello-jni won't compile

### ISSUE THREAD

**Issue by gengjiawen** [googlesamples/android-ndk#34]
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
        at com.android.dx.command.dexer.Main.processClass(Main.java:704)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:170)
        at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
        at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
        at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
        at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:632)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/example/hellojni/R.class

6 errors; aborting               
                                 
:app:dexAllDebug FAILED          
              
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':app:dexAllDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_45\bin\java.exe'' finished with non-zero exit value 1
              
* Try:        
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
              
BUILD FAILED  
              
Total time: 6.0 secs
```

**Comment by ggfan** [comment]
could you try with Java 1.7 and see if it makes any difference? or you could use java byte order 1.7 version, something similar to:
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

**Comment by gengjiawen** [comment]
@ggfan I tried using compileOptions in build.gradle like this:
```
    android {
        #Other code ommited
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_7
            targetCompatibility JavaVersion.VERSION_1_7
        }
    }
```
And I got this
```
* What went wrong:          
A problem occurred configuring project ':app'.
> Exception thrown while executing model rule: model.android
   > Could not find method compileOptions() for arguments [build_88ycgas1g8rq8raef3fwnrgku$_run_closure1_closure2_closure7@77c3c037] on project ':app'.
                            
* Try:                      
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
                            
BUILD FAILED                
                            
Total time: 13.193 secs   
```

**Comment by ggfan** [comment]
if use 1.7 java version in android studio, would that make any difference?

**Comment by gengjiawen** [comment]
I installed java 1.7,it finally worked.

**Comment by ggfan** [comment]
may you give it a try of this[change to use java8 in AS, with following syntax of module build.gradle]] 
model {
    android {
         ...
    }
    ...
    android.compileOptions {
        sourceCompatibility=JavaVersion.VERSION_1_7
        targetCompatibility=JavaVersion.VERSION_1_7
    }
}

**Comment by gengjiawen** [comment]
@ggfan It's not working, I still got the same error.

**Comment by zella** [comment]
@ggfan , `android.compileOptions` not working. But 

    compileOptions.with {
        sourceCompatibility = JavaVersion.VERSION_1_7
        targetCompatibility = JavaVersion.VERSION_1_7
    }

works

**Comment by gengjiawen** [comment]
`compileOptions.with` do works.

**Comment by ggfan** [comment]
great, thanks!

**Comment by gengjiawen** [comment]
@ggfan will you make patch to the build.gradle or report this to Google Gradle Team?

**Comment by ggfan** [comment]
sure I will report out.  thanks

**Comment by ggfan** [comment]
I am closing the issue, please let me know for any problems  thanks

**Comment by ZhengRui** [comment]
it seems this fix 

```
compileOptions.with {
    sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7
}
```

does not work with me, my Android Studio is 1.3.2, still get the same error, any suggestions?

**Comment by ggfan** [comment]
I thought they are put inside the android  {  } for sourceCompatibility = ...  
this works for me:
        tasks.withType(JavaCompile) { 
            sourceCompatibility = JavaVersion.VERSION_1_7
            targetCompatibility = JavaVersion.VERSION_1_7
        }
inside android { ... }  
maybe you could try it out.

**Comment by ZhengRui** [comment]
Thanks ggfan, your suggestion also works, but untill now i could not debug native code, i have tried all kinds of places where i should put "debuggable = true", and it seems no matter i click "run" or "debug", it is the same output from console, like this:

```text
local path: /Users/zerry/AndroidStudioProjects/AndroidNDKSamples/hello-jni/app/build/outputs/apk/app-debug.apk
	remote path: /data/local/tmp/com.example.hellojni
No apk changes detected. Skipping file upload, force stopping package instead.
DEVICE SHELL COMMAND: am force-stop com.example.hellojni
Launching application: com.example.hellojni/com.example.hellojni.HelloJni.
DEVICE SHELL COMMAND: am start  -n "com.example.hellojni/com.example.hellojni.HelloJni" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
DEVICE SHELL COMMAND: run-as com.example.hellojni mkdir -p /data/data/com.example.hellojni/lldb/bin
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.example.hellojni/.HelloJni }

DEVICE SHELL COMMAND: cat /data/local/tmp/lldb-server | run-as com.example.hellojni sh -c 'cat > /data/data/com.example.hellojni/lldb/bin/lldb-server; chmod 700 /data/data/com.example.hellojni/lldb/bin/lldb-server'
DEVICE SHELL COMMAND: rm /data/local/tmp/lldb-server
DEVICE SHELL COMMAND: cat /data/local/tmp/start_lldb_server.sh | run-as com.example.hellojni sh -c 'cat > /data/data/com.example.hellojni/lldb/bin/start_lldb_server.sh; chmod 700 /data/data/com.example.hellojni/lldb/bin/start_lldb_server.sh'
DEVICE SHELL COMMAND: rm /data/local/tmp/start_lldb_server.sh
Now Launching Native Debug Session
Debugger attached to process 5495
```

**Comment by ggfan** [comment]
yes, debugging works for after I created the new configure in studio. my general procedure is like this:
Procedures  
   * Enable Debug Build  -- put  debug { "debuggable = true" } inside android.buildTypes [the variable name is different for plugin 0.1.0, --- isDebuggable then]
   * Create an Android Native Debug Configuration and selecte it in Android studio
   *  Set a breakpoint into your native code, resync the project, and debug [ with that little "bug" button]
   the starting up is slow, but it works for me. If you build gradle plugin yourself for 1.4 branch, I heard it is fixed there so you will not have long waiting anymore.  Other than that it works fine.   
[I was trying to paste my doc, but markdown syntax is too much, I have to do lot of editing]

**Comment by ggfan** [comment]
I am using 1.4 preview 3. I thought this feature the version does not matter that much.

**Comment by ggfan** [comment]
I do not the problem there is due to the init code.  I am using 1.4 preview 3, debugging is ok: it takes time to start up the debugger -- waiting to connect. after coming up, it is fine. [I am on Linux ]

the create "create debug config" step is necessary, and selection the right options in that step.  I was trying to paste a small doc here on steps, but too much editing with markdown formatting, I give it up :-(

**Comment by proppy** [comment]
Note that 1.4 preview 3 should fix the debug on init issue (by waiting for the debugger to attach before starting the app).

If you want to try debugging a sample with the 1.3 stable release, I would suggest to try `heelo-gl2` and put a breakpoint in `drawFrame` so you can hit the breakpoint after the app is started.

**Comment by ZhengRui** [comment]
thanks @ggfan @proppy, i will give 1.4 preview 3 a try.
