### ISSUE TITLE
Execution failed for task 'app/externalNativeBuildDebug'.

### ISSUE THREAD

**Issue by samylegalloudec** [googlesamples/android-ndk#348]
Hi Everyone, I got some problems to compile my program. I explain : 

I'm programming an Android Application using C++ (so using CMakeLists). I'm using libcurl library, and i had many problems to include it, but i did some hours ago. But now, i got another problem that i can't solve. I don't know it the error comes from the CMakeLists or the program itself. I have seen another topic with the same mistake, but the solution didnt help me. So i try

Here is my program : native-lib.cpp
`#include <jni.h>
#include <string>
#include <curl/curl.h>

extern "C"
JNIEXPORT jstring JNICALL Java_com_lna_slegallo_application_1android_MainActivity_stringFromJNI(JNIEnv *env, jobject /* this */)
{
    std::string hello = "Hello from C++";
    return env->NewStringUTF(hello.c_str());
}
/..
../
extern "C"
JNIEXPORT jstring JNICALL Java_com_lna_slegallo_application_1android_MainActivity_httpRequest(JNIEnv *env, jobject obj)
{
    curl_global_init(CURL_GLOBAL_ALL);

    CURL *curl = curl_easy_init();
    if(curl) {
        CURLcode res;
        curl_easy_setopt(curl, CURLOPT_URL, "http://www.google.fr");
        res = curl_easy_perform(curl);
        curl_easy_cleanup(curl);
    }
}`

Here is my CMakeLists.txt : 
`    # Sets the minimum version of CMake required to build the native
       # library. You should either keep the default value or only pass a
       # value of 3.4.0 or lower.

       cmake_minimum_required(VERSION 3.4.1)

       # Creates and names a library, sets it as either STATIC
       # or SHARED, and provides the relative paths to its source code.
       # You can define multiple libraries, and CMake builds it for you.
       # Gradle automatically packages shared libraries with your APK.

       add_library( # Sets the name of the library.
                    native-lib

                    # Sets the library as a shared library.
                    SHARED

                    # Provides a relative path to your source file(s).
                    # Associated headers in the same location as their source
                    # file are automatically included.
                    src/main/cpp/native-lib.cpp )

       # Searches for a specified prebuilt library and stores the path as a
       # variable. Because system libraries are included in the search path by
       # default, you only need to specify the name of the public NDK library
       # you want to add. CMake verifies that the library exists before
       # completing its build.

       find_library( # Sets the name of the path variable.
                     log-lib
                     -lcurl

                     # Specifies the name of the NDK library that
                     # you want CMake to locate.
                     log
                     -lcurl )

       # Specifies libraries CMake should link to your target library. You
       # can link multiple libraries, such as libraries you define in the
       # build script, prebuilt third-party libraries, or system libraries.

       INCLUDE_DIRECTORIES($/usr/include/)

       target_link_libraries( # Specifies the target library.
                              native-lib

                             # Links the target library to the log library
                              # included in the NDK.
                              ${log-lib} )

    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

    set(CURL_INCLUDE_DIR "/usr/include")
    set(CURL_LIBRARY "-lcurl")

    find_package(CURL REQUIRED)
    include_directories(${CURL_INCLUDE_DIRS})
    target_link_libraries(native-lib ${CURL_LIBRARIES})`

And here is my MainActivity.java (i don't think the mistake can come from here)
`package com.lna.slegallo.application_android;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.Button;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {

    // Used to load the 'native-lib' library on application startup.
    static {
        System.loadLibrary("native-lib");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Example of a call to a native method
        TextView tv = (TextView) findViewById(R.id.sample_text);
        tv.setText(stringFromJNI());

        TextView tv_ip = (TextView) findViewById(R.id.ip_text);
        tv_ip.setText(stringFromJNI2());

        Button button = (Button) findViewById(R.id.bouton);
        button.setText(stringFromJNI3());
    }

    /**
     * A native method that is implemented by the 'native-lib' native library,
     * which is packaged with this application.
     */
    public native String stringFromJNI();
    public native String stringFromJNI2();
    public native String stringFromJNI3();
    public native String httpRequest();
    //public native int intFromJNI();
}
`

I am working on Android Studio, any help is welcome.

Best Regards :)

**Comment by ggfan** [comment]
working version cmakelists.txt for this could be:
```java
cmake_minimum_required(VERSION 3.4.1)
set(CMAKE_VERBOSE_MAKEFILE ON)

add_library( # Sets the name of the library.
             native-lib
             SHARED
             src/main/cpp/native-lib.cpp )

find_library( # Sets the name of the path variable.
              log-lib

              log )
#my build curl lib is at ${proj_dir_root}/curl/build
set(LIBCURL_DIR  ${CMAKE_SOURCE_DIR}/../curl/build)
include_directories(${LIBCURL_DIR}/include)
find_library(lib-curl  curl
             PATHS ${LIBCURL_DIR}/lib
             NO_DEFAULT_PATH
             NO_CMAKE_FIND_ROOT_PATH)
target_link_libraries( # Specifies the target library.
                       native-lib

                       # Links the target library to the log library
                       # included in the NDK.
                       z
                       ${log-lib}
                       ${lib-curl})
```
with my build libcurl for android,  your `httpRequest()` c code works ok ( I could trace code with android studio for that small c function).  If you do similar, it should work as is.  build libcurl for android take sometime to research and trial, good luck on your build ( I am not sure my build is 100% correct )

**Comment by samylegalloudec** [comment]
Hi ggfan,

Thank you a lot for giving me your time, i will try this monday at office.

If will let you know if it works, thanks a lot again.

Best Regards.

**Comment by ggfan** [comment]
Ok, hope your monday is not there yet so avoid some confusion:  I only built for arm v7a libcurl.a, and in build.gradle, also only build for armeabi-v7a with
```java
 defaultConfig{
    ...
    ndk {
           abiFilters 'armeabi-v7a'
    }
}
```
otherwise, I only have one abi-type lib, gradle is going to build for all ABIs, then errors again everywhere.

If you do want to build for ALL ABIs, then: 

- Build all curl libs for ALL ABIs and tuck them under lib/${ANDROID_ABI}/, so each abi has its own sub-folder
- use `PATHS ${LIBCURL_DIR}/lib/${ANDROID_ABI}`in your find_library(...), no other change. 
Build system scan cmakelists.txt for each ABI build with the right ABI setting inside ${ANDROID_ABI}. You knew this many years ago already

so as long as you got the one ABI build works, to expand to others is simple.
to make your thing to work, need also to add internet access permission inside androidmanifest.xml too (it is not build problem anymore :-))

**Comment by samylegalloudec** [comment]
Hi, thanks again for the precisions.

I'm a beginner as you can see; so can you show me the tree of your project ? To see what folders of libcurl i have to put in it.

And your cmakelist.txt looks ok, now the only problem i have is to know what i have to put in my project. I'm not used to use external librairies and cross-compilation

But thank you for all the informations you gave me, i understand things better now :)

**Comment by ggfan** [comment]
my procedure:

- Used Android Studio to generate the[ simple C++ hello-world](https://codelabs.developers.google.com/codelabs/android-studio-cmake/index.html?index=..%2F..%2Findex#0) application [ remember to click the "C++ project" on the template page]
- copied over your java code, and add button, text box etc resource to match your java code
- copied over your C++ code
- comment out libcurl related code in all places[cmakelists.txt, build.gradle], make sure it builds and runs fine. The add back the libCurl things ( only changed cmakelists.txt, build.gradle, I did not think changing your C code )
- download libcurl ( and hack, really just hacking to ) build for Android; make sure build is for Android, NOT for linux or Mac

my file structure:
```java
  ${project_root} (you decide where it is on your disk):
     - app
       -- CMakeLists.txt ( it has to be here, otherwise, cmakelists.txt script needed to change )
       -- build.gradle, proguard-rules.pro etc 
     - curl
           this is the clone repo root dir, which has .git dir in it. lots of directories/files.  But one mattering is:
        -- build
           --- bin ( has sub-dir liks bin/local/share/..., but I was not using this directory, it comes out from "make install" -- I think)
           --- include ( this one is used )
                ---- curl ( hosting all headers )
           --- lib ( used )
                ---- libcurl.a ( used )
                ---- libcurl.la ( not used )
      
```

**Comment by samylegalloudec** [comment]
Well that's exactly what i have. I built it for android with this tuto : 
http://ieroot.com/2015/03/29/1728.html
I followed only step 5, the only thing i changed is that i didnt use the "--with-ssl \" parameter. 
Then when i compilated, i had problems with my .so

**Comment by ggfan** [comment]
maybe upload your code to github, then I could download it and compare?

**Comment by samylegalloudec** [comment]
I'll do that tomorrow !

**Comment by ggfan** [comment]
make sure to use static lib of your libcur, not the shared  lib.   that is what I used.  also copy your error code up, we could see if it is link problem or compile issue.

**Comment by samylegalloudec** [comment]
So, i've finally found the solution, i will share it.

My first problem was : How do i include curl in my C++ android studio project ?

I downloaded this : git clone https://github.com/gcesarmza/curl-android-ios.git

I went inside the folder, then i did "git submodule init && git submodule update"

When it was done, i went in my NDK root, (to me it was /home/login/Android/Sdk-bundle" took the "way" with pwd and i did : export NDK_ROOT=[result of pwd]

Verify with echo $NDK_ROOT

Then i did : git pull origin pull/27/head

Verify that you have installed "automake", "autoconf" and "libtool" then go in curl-compile-scripts (in curl-android-ios) and execute build_Android.sh (it takes 20 min)

Then i used this cmakelist :

`cmake_minimum_required(VERSION 3.4.1)

set(distribution_DIR ${CMAKE_SOURCE_DIR}/../distribution)

add_library(lib-curl STATIC IMPORTED)

set_target_properties(lib-curl PROPERTIES IMPORTED_LOCATION ${distribution_DIR}/curl/lib/${ANDROID_ABI}/libcurl.a)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")

add_library( # Sets the name of the library.
             native-lib
             SHARED
             src/main/cpp/native-lib.cpp )

target_include_directories(native-lib PRIVATE
                           ${distribution_DIR}/curl/include)


find_library( # Sets the name of the path variable.
              log-lib

              log )

target_link_libraries( # Specifies the target library.
                       native-lib
                       lib-curl
                       z
                       ${log-lib}
                       )
` 

With this tree : 

  ${project_root}:
     - app
        --cmakelist.txt
     - distribution
        --curl
                 ---lib
                     -arm64-v8a
                     -...
                 ---include
                    -curl
                    -Makefile
                    -Makefile.am
                    -...
      

To do all these steps, i used these websites who helped a lot : 

https://github.com/googlesamples/android-ndk

https://github.com/gcesarmza/curl-android-ios

https://github.com/gcesarmza/curl-android-ios/issues/29

http://ieroot.com/2015/03/29/1728.html

Thank you a lot for helping ggfan
I hope this little "tuto" will help other poeple who has the same issue

Best regards

**Comment by ggfan** [comment]
Glad you get it working! Thank you very much @samylegalloudec: they are very detailed steps and will save a lot of time for people trying to do similar thing! ( formatted a little of your message to make it easier for future reference )! thank you for sharing!
