### ISSUE TITLE
A problem occurred when set singingConfigs

### ISSUE THREAD

**Issue by Lycoriso** [googlesamples/android-ndk#35]
code build.gradle:

android.signingConfigs {
        myConfig{
            storeFile += file('bim.keystore')
            storePassword = "bmtech"
            keyAlias = "bim"
            keyPassword = "bmtech"
        }
}

error:
Error:A problem occurred configuring project ':app'.
> The following model rules are unbound:
    model.android.signingConfigs.myConfig
      Mutable:
        - android.signingConfigs.myConfig (java.lang.Object)

**Comment by ggfan** [comment]
maybe try this:
    android.signingConfigs {
        create("myConfig") {
         ....
        }
   }

**Comment by Lycoriso** [comment]
work well, thanks.

for example:
android.signingConfigs {
        create("myConfig") {
            storeFile = file("bim.keystore")
            storePassword = "bmtech" // System.console().readLine("\nKeystore password: ")
            keyAlias = "bim"
            keyPassword = "bmtech" // System.console().readLine("\nKey password: ")
        }
 }
