### ISSUE TITLE
Update the gles3jni sample to support OpenGL ES 3.2

### ISSUE THREAD

**Issue by qchong** [googlesamples/android-ndk#350]
@ggfan @hak 

There's native support for OpenGL ES 3.2 for Android API level 24. The sample should be updated to use the latest OpenGL ES version.

**Comment by ggfan** [comment]
@hak PLAT, thx

**Comment by ggfan** [comment]
https://github.com/googlesamples/android-ndk/pull/462 is merged,thanks
