### ISSUE TITLE
Cannot build with jdk7

### ISSUE THREAD

**Issue by ranjali** [googlesamples/android-ndk#352]
I have no issue to build the sample "hello-jni" with jdk8.

However, when I tried to build the sample with jdk7, it give me an error: java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

I have tried to google the solution, yet none of them work.May I know if there is a workaround to build it with jdk7?
Or jdk8 is the requirement for building ndk?

**Comment by ggfan** [comment]
java8 is needed to build samples
