### ISSUE TITLE
Can someone please tell me what in the #@#!%@#@ this error means!?

### ISSUE THREAD

**Issue by mlfarrell** [googlesamples/android-ndk#355]
Attempt to mutate closed view of model of type 'java.lang.Object' given to rule

Every time I try to edit ANYTHING in the gradle, it gives me this.  No more information.  Throw me a damn bone here.

Excuse the formatting - github's code formatting markdown is garbage

```java
android.sources {
        main {
            jni {
                source {
                    srcDir "../app/src"
                }
                source {
                    srcDir "../../../LibBregGLEngine/src"
                    exclude "**/SDLTextureLoader.cpp"
                }
            }

            //this simply will..not..work (if I remove the jnilibs, it syncs fine)
            jniLibs {
                dependencies {
                    library "assimp"
                }
            }
        }
    }
```

**Comment by ggfan** [comment]
Gradle could be a thing: having been an apprentice to it for a long while and still not sure when the graduation date is for me yet.

your project is built with gradle-experimental plugin, seems to have a another project inside your project, called "assimp", could you check it? it should be sitting parallel to your app's directory. Add a colon to the front to make it like:    
`library ":assimp" linkage static`

then try it again. Sometimes when error happens, going to terminal and execute `./gradlew assembleDebug` giving more info.

you could check this file to see if it could help, it uses native app glue as dependent ':nativeactivity' project:
https://github.com/googlesamples/android-ndk/blob/master/other-builds/experimental/native-activity/app/build.gradle

**Comment by ggfan** [comment]
closing this off for now, feel free to re-open whenever needed  thx
