### ISSUE TITLE
Could you please add md5 encryption in android studio with ndk example?

### ISSUE THREAD

**Issue by sinhpn92** [googlesamples/android-ndk#357]
I'm trying to generate MD5 hash for a string, but i have problem with result. My result wrong on some device. This is my question in [stackoverflow](http://stackoverflow.com/questions/42303607/returning-wrong-md5-hash-in-jni). 

Could you please add example for md5 hash a string in android studio with ndk?

**Comment by ggfan** [comment]
will need time to get to this one from my end; did post the SO question to a group, hopefully someone with MD5 expertise could race to get your question answered soon.

**Comment by ggfan** [comment]
Oops, this is answered already, no need for this one to be around.
