### ISSUE TITLE
Teapot sample

### ISSUE THREAD

**Issue by NativeCodeSamples** [googlesamples/android-ndk#359]
Please don't use shaders from outside files because it will not run in API-17 and below APIs. it will generate run time error.

So for the solutions Store the string of shaders in a variable of any header file and concate it with using "\n" and then load it. it will work finely in API 17 and below APIs.

**Comment by ggfan** [comment]
Ok,  thanks for the information, will follow-up: the samples kind kept the way when it was created, leaning towards to satisfy latest version of things ( Android OS, Android Studio, NDK ). Not in the very strict requirement, from what I saw ( personal view ).

**Comment by ggfan** [comment]
you got it working, so no need for this one here now, I think

**Comment by ggfan** [comment]
getting to this one. could you give more info? Sample puts the shaders inside assets directory, using AssetManager to ready the content into a char buffer, then pass this buffer to glCompileShader().  To this point, as along as it gets into the memory and pass it to glCompileShader(), it should be ok, I think.  May you give more info on this before I go ask around? ( tried to verify on a device; during flashing process, it just got killed, sad ).

**Comment by NativeCodeSamples** [comment]
Instead loading shaders from Assets through AssetManager, load it from a
constant pointer variable.
Like below:

*const char* vert_shader = "PUT THE SHADER SOURCE with \n";*
*const char* frag_shader = "PUT THE SHADER SOURCE with \n";*

*and return this variable to shader source variable that is deal with
glShadeSource function..*

And

put The NULL in the size in a function gShaderSource(shader, 1, source,
NULL);

or

if you really want to load shader from Assets

*It is necessary to pass the size of shader (which is the length of
currently new initialized assets.)*

*so function will be like glShaderSource(shader, 1, shader, SIZE);*

*where SIZE = sizeof(Your shader variable).*



*1. Remove the line "ndk_helper::JNIHelper::Init(state->activity,
HELPER_CLASS_NAME);" from TeapotNativeActivity.cpp because it cause
recursive calls to java class.*
*2. Change the Loadshader function my sample i sent you through this email.*



Run it !!

*Please provide a sample that load the photos as texture in 3D model......*

**Comment by ggfan** [comment]
thank you for the explanation!  it is getting to details of this  :-).  seems you think there is problem with this one, is my guess correct?:
```java
  *shader = glCreateShader(type);
  glShaderSource(*shader, 1, &source, &iSize);  // Not specifying 3rd parameter
                                                // (size) could be troublesome..

```
May you elaborate the problem you saw with it? The prototype is here:
 https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glShaderSource.xml
```java
void glShaderSource( GLuint shader, GLsizei count, const GLchar * const *string, const GLint *length);
```
at run time, iSize is 1815.

thanks

**Comment by ggfan** [comment]
looks like you filed a few issues for teapots: some are related to sample, some about features: we could focus on the sample first, then look at the features.

**Comment by ggfan** [comment]
just ping for this:  from my view, the usage of the glShaderSource() is ok.  The function takes an array of strings ( char*), and array of GLint ( to indicate length for each corresponding string ), and the count of both array size.   The file size is retrieved from assetManager (multiple files inside assets will have multiple file_lengths). Since this is one source file shader, directly passing the address of the iSize will do the trick.  Let me know if we are talking about different things, thanks

**Comment by NativeCodeSamples** [comment]
From performance point of view invoking Assets manager for some basic and
simple stuff is not good. Or is it??. Why we should even very slightly slow
down execution, if we wanna to think about core working...

**Comment by ggfan** [comment]
:-) thank you for your comments and they definitely have true in it. On the other hands, shaders are part of game assets I think, and showing the asset operation in sample demos more areas than just embedding shaders in source code: embedding source code is pretty straightforward.  thank you again and appreciate your interests to make samples better here. Will definitely look at our other issues soon.
