### ISSUE TITLE
Library build error

### ISSUE THREAD

**Issue by Lycoriso** [googlesamples/android-ndk#36]
Only build app it's OK, When build the app reference library module, the library module get below problem:

Error:A problem was found with the configuration of task ':bim:processDebugResources'.
> Directory 'D:\broadmap\explore\im\idea\BIM\bim\build\intermediates\bundles\debug\res' specified for property 'resDir' does not exist.

this is a bug.

**Comment by ggfan** [comment]
I think Proppy has commented this:  https://github.com/googlesamples/android-ndk/issues/26
[mainly currently preview does not support building lib yet. suppose to arrive in next release]

**Comment by proppy** [comment]
This is a related but different issue than #26, see https://code.google.com/p/android/issues/detail?id=177631.
