### ISSUE TITLE
hello-libs dlopen error

### ISSUE THREAD

**Issue by steven5401** [googlesamples/android-ndk#364]
I'm using sharp Z2 mobile phone(with mali gpu). In MainActivity.java, I comment 
>System.load("/system/vendor/lib/libPVROCL.so"); 

and add
>System.load("libGLES_mali.so");

After running, it shows that loading libGLES_mali.so is successful, but at  System.loadLibrary("hello-libs");
>dlopen failed: library "/home/laplace/Desktop/Hello-libs/app/src/main/cpp/../../../../distribution/gperf/lib/arm64-v8a/libPVROCL.so" not found

Why does it find the file with my computer path instead of phone path?
Another problem is that my gpu is not powervr, will it be okay after fixing path problem above?
Do I still need to change something else to fit the mali configuration?

**Comment by ggfan** [comment]
you are using something different from sample using: on android, it is:
System.loadLibrary("hello-libs");

and the expected lib should be packed inside APK's jni sud directory.

you are using System.load(), maybe you could check to see where the default lib path prefix is? I am suspecting the cross-compiling auto-matically added some path to your absolute path when using load ( I am not totally sure though )

**Comment by steven5401** [comment]
the whole code in static is like following
```
static {
        System.load("libGLES_mali.so");
        //System.load("/system/vendor/lib/libPVROCL.so");
        System.loadLibrary("hello-libs");
    }
```
the error message is like this

>  java.lang.UnsatisfiedLinkError: dlopen failed: library "/home/laplace/Desktop/Hello-libs/app/src/main/cpp/../../../../distribution/gperf/lib/arm64-v8a/libPVROCL.so" not found
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                           at java.lang.System.loadLibrary(System.java:1076)
                                                                           at com.example.hellolibs.MainActivity.<clinit>(MainActivity.java:38)

I check the CMakeList in ./app/src/main/cpp

> set_target_properties (OpenCL PROPERTIES VERSION "1.2" SOVERSION "1" IMPORTED_LOCATION
    #${distribution_DIR}/OpenCL/lib/${ANDROID_ABI}/libPVROCL.so)
	${distribution_DIR}/gperf/lib/${ANDROID_ABI}/libPVROCL.so)

Is this the reason why hello-libs call libPVROCL?
I don't know whether libPVROCL is not in the phone or just the path setting is wrong.

**Comment by ggfan** [comment]
Hello-libs is just to show how to use external static and shared libs on Android with CMake. It is mostly CMake's syntax.  With your change, I am not sure what in your application code and how your libhello-libs.so is linked.  If your hello-libs is original sample code, NO, it should not load another of openCL lib -- it has nothing to do with it.
openGL driver on android is inside system image, i thought, you do not have to load it.  you might check other openGL samples ( teapot is openGL, hello_gl etc ) in this repo to see what lib to link to use it, no need to load it;it is my guess.  At this moment, I am looking at my local project to use gl3 on android, linking is:
```java
target_link_libraries(native-activity
                      android
                      app-glue
                      EGL
                      GLESv3
                      log)
```
the EGL and GLESv3 is the only thing I need to link and then I could use openGL functions ( of course, I need include GL headers like:
```java
#include <EGL/egl.h>
#include <GLES3/gl3.h>
```
I do not have to deal with whatever underneath gpu vendors my test phone uses.

**Comment by Shu-Ji** [comment]
@ggfan I have the same problem.

I want to add another lib into hello-libs.

In CMakeLists.txt, I add:

```cmake
# this is from the hello-libs sample code
add_library(lib_gperf SHARED IMPORTED)
set_target_properties(lib_gperf PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/gperf/lib/${ANDROID_ABI}/libgperf.so)

########## I add this after the sample code:  ###########
add_library(lib_py SHARED IMPORTED)
set_target_properties(lib_py PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/gperf/lib/${ANDROID_ABI}/libpython.so)
```

And this:
```cmake
target_link_libraries(
        hello-libs
        android
        lib_gperf

        #### this line ######
        lib_py

        log)
```

And copy `libpython.so` in the directory where `libgperf.so` located:

<image src="https://user-images.githubusercontent.com/1127594/54079376-4f487180-4316-11e9-995d-c1ae036ef478.png" width="250" />

Also copy the python headers into the include directory:

<image src="https://user-images.githubusercontent.com/1127594/54079404-e281a700-4316-11e9-8bad-43c8a87de9e5.png" width="250" />

When I click the run button:
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "/Users/finn/Downloads/hello-libs/app/src/main/cpp/../../../../distribution/gperf/lib/arm64-v8a/libpython.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.example.hellolibs.MainActivity.<clinit>(MainActivity.java:36)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

The path exists in my computer, but why the apk use my computer path, but not the android device path?

And I use the Android device file explorer, the lib is in the directory:

<image src="https://user-images.githubusercontent.com/1127594/54079423-5459f080-4317-11e9-8ead-d02952b48a3e.png" width="350" />

Then how can I make the apk use the right path? Or I miss something to add?

**Comment by ggfan** [comment]
make sure the library is generated for Android,  could you make a simple version of you app, and upload somewhere?

**Comment by sjfricke** [comment]
@Shu-Ji  Can you list which version of Android Studio and NDK you are using as well?

**Comment by Guang1234567** [comment]
@sjfricke 

I I have the same problem like @Shu-Ji.

```java
android studio 3.4

NDK 14

gradle 4.10.3
```

**Comment by Guang1234567** [comment]
@Shu-Ji 

Temporary solution:

Instead

```cmake
add_library(lib_py SHARED IMPORTED)
set_target_properties(lib_py PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/gperf/lib/${ANDROID_ABI}/libpython.so)
````

to 

```cmake
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -L${distribution_DIR}/gperf/lib/${ANDROID_ABI}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -L${distribution_DIR}/gperf/lib/${ANDROID_ABI}")
```


Hope it useful for you.

**Comment by ggfan** [comment]
sure thanks!  but it bypasses the CMake and directly go with compiler flags...   could you see whether get the [absolute path](https://cmake.org/cmake/help/v3.14/command/get_filename_component.html) work ?

**Comment by Guang1234567** [comment]
@ggfan 

Absolute path also not working, ⊙﹏⊙|||

**Comment by Guang1234567** [comment]
Hello @ggfan:

What is the problem? Is the cmake version of android ndk 14 ?  Thanks.

**Comment by bobosui** [comment]
I met the same problem with android-ndk-r15c.
The logcat shows
`java.lang.UnsatisfiedLinkError: dlopen failed: library "C:/myprj/test01/pybridge/app/src/main/obj/local/x86/libpython3.7m.so" not found`

I unziped the generated .so file, and check the ".dynstr" file, and saw the absolute path was written at the end:
``` 
__cxa_finalize LIBC libc.so libpybridge.so __cxa_atexit PyInit_androidlog PyModule_Create2 setAndroidLog 
......
 abort memcpy 
__cxa_begin_cleanup __cxa_type_match __cxa_call_unexpected _edata __bss_start _end 
C:/myprj/test01/pybridge/app/src/main/obj/local/x86/libpython3.7m.so liblog.so libm.so libstdc++.so libdl.so
 ```

The link command using "ndk-build --dry-run" shows below information:
`c:/Android/android-ndk/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -Wl,-soname,libpybridge.so -shared --sysroot=c:/Android/android-ndk/build//../platforms/android-21/arch-x86 C:/myprj/test01/pybridge/app/src/main/obj/local/x86/objs/pybridge/pybridge.o -lgcc -Wl,--exclude-libs,libgcc.a  C:/myprj/test01/pybridge/app/src/main/obj/local/x86/libpython3.7m.so  -gcc-toolchain c:/Android/android-ndk/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -no-canonical-prefixes  -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings  -Lc:/Android/android-ndk/build//../platforms/android-21/arch-x86/usr/lib -llog -lc -lm -o  C:/myprj/test01/app/src/main/obj/local/x86/libpybridge.so`

llvm clang++ version 5.0.300080  (based on LLVM 5.0.300080)

**Comment by ggfan** [comment]
This one would be similar to https://github.com/android/ndk-samples/issues/669
copying the solution here: 
```
    add_library(pybridge SHARED  pybridge.c)
    target_include_directories(pybridge PRIVATE  ${distribution_DIR}/conda-android- 
    python/include/${ANDROID_ABI})
    target_compile_options(pybridge PRIVATE -Wno-unused-value)
    target_link_libraries(pybridge
        android
        log
        -lpython3.7m -L${distribution_DIR}/conda-android-python/lib/${ANDROID_ABI}
        )
```
The workaround would similar for other libraries with the similar issues. The real solution is for the lib owners to build the libs with the right flag `Wl,-soname,$your-lib-name.so`

**Comment by Guang1234567** [comment]
@ggfan

 The official doc: 

https://developer.android.google.cn/studio/projects/configure-cmake?hl=en#add-other-library

is also like below:

```
add_library(lib_py SHARED IMPORTED)
set_target_properties(lib_py PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/gperf/lib/${ANDROID_ABI}/libpython.so)
```

I think should create  a ASOP issue instead of here….⊙﹏⊙|||

**Comment by ggfan** [comment]
thank you!  The root cause for this issue is this:  the libpython.so built for Android was mis-configured, hence causing the NDK's link to use the host path for the target the run-time path. The first is really to have owner of libpython.so to generate the right configuration in libpython.so's header ( description portion inside the binary ). The details are in the #669.

Documentation is based on the correctly built libs for Android platform, it might help to make a note of this error case; on the other hand, to document that, ELF spec has to be pulled in, that would be interesting as not many people are interested or have to know it.

let me know if we are mis-understanding or for any further thoughts, thank you again for using Android native interfaces!

**Comment by Guang1234567** [comment]
@ggfan 
Thank you.

@Other

More info about why need to set soname for android platform?
https://android-developers.googleblog.com/2016/06/android-changes-for-ndk-developers.html

This my fixed [demo](https://github.com/Guang1234567/rust_android_common_lib/commit/36417eea02f60d169968c37358be1344cd8a547d) after set soname.

**Comment by yinjimmy** [comment]
> This one would be similar to #669
> copying the solution here:
> 
> ```
>     add_library(pybridge SHARED  pybridge.c)
>     target_include_directories(pybridge PRIVATE  ${distribution_DIR}/conda-android- 
>     python/include/${ANDROID_ABI})
>     target_compile_options(pybridge PRIVATE -Wno-unused-value)
>     target_link_libraries(pybridge
>         android
>         log
>         -lpython3.7m -L${distribution_DIR}/conda-android-python/lib/${ANDROID_ABI}
>         )
> ```
> 
> The workaround would similar for other libraries with the similar issues. The real solution is for the lib owners to build the libs with the right flag `Wl,-soname,$your-lib-name.so`

The dlopen('lib path'); has been changed, Thanks.
But there still is one issue with ffmpeg:

## configure

```
    target_link_libraries(external
        -lavcodec -L${CMAKE_CURRENT_SOURCE_DIR}/ffmpeg/prebuilt/android/armeabi-v7a
        -lavformat -L${CMAKE_CURRENT_SOURCE_DIR}/ffmpeg/prebuilt/android/armeabi-v7a
        -lswscale -L${CMAKE_CURRENT_SOURCE_DIR}/ffmpeg/prebuilt/android/armeabi-v7a
        -lavutil -L${CMAKE_CURRENT_SOURCE_DIR}/ffmpeg/prebuilt/android/armeabi-v7a
    )
```

## code

```
            System.loadLibrary("avutil"); // nocrash
            System.loadLibrary("avcodec"); // crash
```

## crash log on nexus 6p

```
                         E  java.lang.UnsatisfiedLinkError: dlopen failed: cannot find "libavutil.so" from verneed[1] in DT_NEE
                            DED list for "/data/app/com.daming.sea2-GYpo1LsgIlQLHlJivoHIKA==/lib/arm/libavcodec.so"
```

Is there workaround for this issue ?
