### ISSUE TITLE
NDK-UI supports

### ISSUE THREAD

**Issue by i-Android** [googlesamples/android-ndk#365]
why not provide skia GUI lib to developer， in order to we can wirte dynamic code。 it can improve our Product efficiency。

**Comment by ggfan** [comment]
I love this one! the argument might be that GMS will not move to native, so app will have to go Java side to do it; UI part follow the path.

But personally I like to have native UI too: it save lots of trouble for JNI. Let's keep this one open and  I do want to do some study when I get chance. ( there is also a FlatUI lib, might also have a look at that one, specifically it is from @hak :-))

thanks

**Comment by pjmlp** [comment]
Fully agree, it doesn't have to be a fully featured UI.

Having SKIA, which is already on the device anyway, promoted to official NDK library would already be enough.

Right now, we are forced to write NIH 2D code on top of OpenGL ES, go old school with software bitmaps and NEON/SIMD or increase the APK size by including something like SDL.

Given the usual excuse of of not havia a stable SKIA .so implementation, and following the NDK platform guidelines of C APIs, BitmapInfo could earn new functions similar to Canvas on the Java side.

**Comment by ggfan** [comment]
slowly looking into this, focusing on the one inside android.

**Comment by ggfan** [comment]
slowly moving to this one: judge might re-open the case, where to pick the jury and build a strong case?

**Comment by kmshih** [comment]
Just to be clear, if we wanted to provide this outside of the APK then it isn't something that would actually be in the NDK; it would need to be a new set of platform APIs.

If you're willing to have skia inside of your APK and don't require platform APIs, then I'd recommend encouraging the maintaining team to integrate it with cdep for easy integration:
https://github.com/google/cdep

**Comment by ggfan** [comment]
closing this down too, could re-open after there is a decision for it.
