### ISSUE TITLE
endless tunnel about section is missleading

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#38]
https://github.com/googlesamples/android-ndk/blob/4d07eb1ff8c9f2a7cb0e50218df86db6ee280392/endless-tunnel/app/src/main/jni/data/blurb.inl#L19

It says:
```
    "This is a sample game showing how\n" \
    "to integrate the Google Play Games API
```

Where as the version is in this repo doesn't call any Google Play Games APIs.

**Comment by ggfan** [comment]
https://github.com/googlesamples/android-ndk/pull/183 fixed it
