### ISSUE TITLE
Need sample to demonstrate how to call assembly code from an app.

### ISSUE THREAD

**Issue by qchong** [googlesamples/android-ndk#381]
@ggfan CMake in NDK now supports building with YASM (https://github.com/android-ndk/ndk/issues/346). Can we have an NDK sample to demonstrate how app developers can use this functionality to call assembly programs from their apps?

**Comment by ggfan** [comment]
Having a whack at this one( after a hundred of years of touching assembly last time :-)). But it is all good and like to escape asap too :-).

Starting from assembly level, the calling conventions
========================================
- x86_64:  first 6 parameters are in 6 64 bit registers; if there are more than 6 parameters to pass, the right are pushed onto the stack ( from right to left ) with cdecl convention. The return address is always at the top of the stack. Also there are certain registers to be preserved between the calls, others are supposed to be clobbered. The concept is described in [MIT page](http://cons.mit.edu/sp17/x86-64-architecture-guide.html)  ( but yasm / nasm uses different symbols).
- x86: strictly cdecl (right to left push-stack order for parameters), with the return address at the top ( when entering callee ).

One [example](https://github.com/ggfan/playground/tree/staging/staging/hello-yasm) could be like the following:
- x86_64:
```java
c/C++ side:
--------------
#include <jni.h>
#include <string>

extern "C" int64_t _add(int64_t a, int64_t b);  //Implementation is in assmbly
extern "C" JNIEXPORT jstring JNICALL
    Java_com_google_sample_hello_1yasm_YasmMainActivity_stringFromJNI(
        JNIEnv *env, jobject) {
          int64_t   val = _add(15, 20);
          std::string hello = "Hello from C++" + std::to_string(val);
          return env->NewStringUTF(hello.c_str());
}

assembly file (like add_yasm.asm, it must be with suffix of asm)
------------------------------------------------------------------------------------
; make the add function visible to the linker
; There are 2 versions of _add and _double, the version 1 is to see how to pass
; variable on the stack if we really have to. Version2 would be normal one to use

section .text
         global _add
	     global _double

;prototype: int64_t add(int64_t v1, int64_t v2) />
;desc: adds two integers and returns the result
;       RDI <-- v1
;       RSI <-- v2
;  calling convention:
;       first 6 parameters are in registers
;       the rest are following cdecl on stack[rsp]
;       return address FOLLOWED by saved rbp are always on stack
_add:
    push rbp
    mov  rbp, rsp

    push r12   ; persistence r12 - r15 across calls
    push  rsi  ; pass the second parameter on stack
    call _double2
    pop  rsi  ; clean the stack, rcx is not used
    mov  r12,  rax
    
    push rdi  ; pass the 1st parameter 
    call _double2
    add  rax, r12
    pop  rdi   ; clear the stack used by rdi; we do not care the value to rdi anymore
    pop  r12   ; restore r12

    leave             ; restore (rbp, rsp)
    ret               ; return from sub-routine

;simple version for _add, passing parameter in register rax
_add2:
    push rbp
    mov  rbp, rsp

    push rcx
    mov  rax, rsi  ; get the 2nd parameters off the stack
    call _double
    mov  rcx,  rax
    mov  rax,  rdi
    call _double
    add  rax, rcx
    pop  rcx

    leave             ; restore (rbp, rsp)
    ret               ; return from sub-routine


; function _double
;   returns rax <- rax + rax, no overflow assumed
_double:
    push    rbp
    mov     rbp, rsp  ; could also use "enter 0, 0" to replace the 2 instructions here

    add rax, rax
    
    leave
    ret

; function _double2
; just to demo how to pass parameters via stack (it is superficial)
;    input:  64 bit value on stack
;    return: 64 bit value * 2 --> rax
_double2:
    mov rax, qword [rsp + 8]
    push rbp
    mov  rbp, rsp

    add rax, rax

    leave
    ret
    
```

- x86:
The similar thing on x86 could be ( 32 bit version of implementation, not 64 implementation on 32 bit machine -- remember that I want to escape asap from this )
```java
C side
--------
#include <stdio.h>

/*
 * declaring add as extern tells the compiler that the definition
 * can be found in a separate modules
 */
extern int __attribute__((__cdecl__)) _add(int a, int b);

int trigger_function(...) {
   
    int ret;
    ret =  _add (10, 20 );
    return 0;
}

Assembly side ( 32 bit version)
-------------------
; make the add function visible to the linker
section .text
         global _add
	 global _double

; prototype: int __cdecl add(int a, int b)
; desc: adds two integers and returns the result
;      on the stack:
;            ret_address
;            right-most parameter
;            left-most parameter
_add:
    push ecx
    mov eax, [esp+8]  ; get the 2nd parameters off the stack
    call _double
    mov ecx, eax
    mov eax, [esp+12] ; get the 1st parameter off the stack
    call _double
    add eax, eax      ; add the parameters, return value in eax
    pop ecx
    ret               ; return from sub-routine

; function _double
;   returns eax <- eax + eax, no overflow assumed
_double:
    add eax, eax
    ret
```

Android Studio CMake Integration
==========================
CMake [documentation](https://developer.android.com/ndk/guides/cmake.html#yasm-cmake) on DAC is correct.  One small addition:
if in case need to pass some compile parameters to yasm, it could be done:
```java
set_property(SOURCE src/main/cpp/yasm_compute.asm
    APPEND_STRING PROPERTY COMPILE_FLAGS "-f elf64")
```
cmake [set_property()](https://cmake.org/cmake/help/v3.0/command/set_property.html) is a good friend. Note you do not have to pass elf64, it is already added by cmake when building for x86_64 ( I assume "-f elf32" will be added automatically too for x86 build )


What to go from here
================
once get channel from C/C++ into assembly, other things could be done ( SSE matters most I think ). will try to do some real assembly implementation for image/graphics (like color conversion) in the future. 
(for now, I will close this -- but hope this description could help you for doc purpose )

References
========
- Processor Manuals:  [x86/x86-64](https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf)
- [MIT paper](http://cons.mit.edu/sp17/x86-64-architecture-guide.html)
-[Eli's paper](http://eli.thegreenplace.net/2011/09/06/stack-frame-layout-on-x86-64) quite helpful
- [yasm](https://github.com/yasm/yasm/wiki)
