### ISSUE TITLE
Need sample for how to use native text-to-speech API (tts.h) 

### ISSUE THREAD

**Issue by qchong** [googlesamples/android-ndk#383]

**Comment by ggfan** [comment]
yeah, it is interesting area, will address it!  thanks

**Comment by ggfan** [comment]
yeah, it is interesting one: I did not pay attention to that.  maybe think about samples after Android - O

**Comment by ggfan** [comment]
Looks like this interface is on the list of being removed from NDK, so no need to provide samples. For people interested in it, might look at third-party github repo:
  https://github.com/happyalu/Flite-TTS-Engine-for-Android
