### ISSUE TITLE
Native Audio : How to play multiple audio together?

### ISSUE THREAD

**Issue by cears-bhumika** [googlesamples/android-ndk#385]
Hey,

How to play multiple sounds files from the asset folder in sync using Native Audio ?

**Comment by ggfan** [comment]
The only thing I know of is to blend audio streams in your app:  app would open those files and get into different buffers ( or read file one chunk of a time ); then inside audio callback function, blend them into the given callback buffer; and hand over the BLENDED buffer back to audio engine ( openSLES or future AAudio's callback functions ). This would get your files in sync during playing.

Sync could be interesting I think: if you could read all files in ( memory could hold them ) then that is less stress; but if they could not be fit into the memory, different threads need to read files, etc.  app could not read disk from callback thread. If there is other way I found, I will update.  Hope this helps

**Comment by cears-bhumika** [comment]
Currently I'm playing multiple sounds by creating multiple instance of engine and SLPlayItf.
Can you tell me how can I get callback currently playing song.

for instance as in Mediaplayer setOnSeekCompleteListener is there..

Is there anything so we can get current milisecond at the time of pause and can set SEEK to that milisecond while playing?

how can get current milisecond and set seek to that milisecond in SLPlayItf.

Thanks in advance

**Comment by ggfan** [comment]
+ @dturner @gkasten

**Comment by dturner** [comment]
Please post your question on stackoverflow.com with your OpenSL ES source code and I will attempt to answer.
