### ISSUE TITLE
request: add example or explain how-to build ICU for android with Android Studio

### ISSUE THREAD

**Issue by ivankarpey** [googlesamples/android-ndk#386]
Already a long time I'm struggling with building project with ICU deps for android. After some time I was able to build it using created standalone tool chain, but still having troubles to make it with simple android studio generated project. Could you please add some guidance regarding that either in text form as a comment to this ticket or add sample. Thanks.

**Comment by ggfan** [comment]
thank you for quests! personally I did not know anything about ICU, from here:
  https://developer.android.com/guide/topics/resources/icu4j-framework.html#migration
it says:
  "NDK developers should know that Android ICU4C is not supported"
so with that holds, it is not much could do now, I did not know any roadmap for this feature either.

**Comment by ggfan** [comment]
May you post a message to request for the feature in this forum: 
  https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/android-ndk/
that one is monitored by many teams.  I will close this one for now
