### ISSUE TITLE
Huge latency observed when playing the audio in BT headset

### ISSUE THREAD

**Issue by Sathya-Subbiah** [googlesamples/android-ndk#391]
Hi, 
Audio-Echo application could not play the audio in BT headset. After increasing the buffer size the audio was heard in BT headset but with huge latency. 

Appreciate any help on how the latency can be reduced while playing BT headset,

**Comment by ggfan** [comment]
ok, I felt this is very known to android audio team ( USB, BlueTooth ). anyhow, please send your favorite BT headset type and I could have one excuse to buy one  :-).  Promising solving USB and Bluetooth audio would be a lie from me, so I better not lie.   I will get more details later.

**Comment by Sathya-Subbiah** [comment]
I am using Sony SBH60 Wireless stereo headphones

**Comment by ggfan** [comment]
It is well known to the team, has been worked on; when the result is available, I am sure there will be news going to all developers. yeah, hope for the best I think.  Sorry for no conclusion for this one.
