### ISSUE TITLE
Is there really a way to make externalNativeBuild default to Make as generator/-G

### ISSUE THREAD

**Issue by n0clu3** [googlesamples/android-ndk#393]
Documentation says that:
```
-G <build-system>	
Type of build files that CMake generates.

For projects in Android Studio with native code, the <build-system> is set to Android Gradle - Ninja. This setting indicates that CMake uses Gradle together with the ninja build system to compile and link the C/C++ sources for your app.

If <build-system> is not specified, CMake defaults to using the Make build system.
```

Whatever I try to pass as argument to externalNativeBuild on the hello-jni example the cmake_build_command.txt shows that it still uses `Android Gradle -Ninja`
To me it seems like Ninja is the one and only default.

**Comment by jomof** [comment]
Unfortunately, the documentation is wrong here. Android Studio team only support Ninja as the generator.
I'll request a documentation change

**Comment by n0clu3** [comment]
@jomof 

Actually it was possible to do this.
Needed to just change the generator to Android Gradle - Unix Makefiles
And provide the -DCMAKE_MAKE_PROGRAM

Had to change this for windows because of how ninja runs the link command.
It appends all the POST_BUILD commands to the link command which doesn't really work on windows as the command length will come too long very easily.
