### ISSUE TITLE
gles3jni will not create ES3 contexts.

### ISSUE THREAD

**Issue by stolk** [googlesamples/android-ndk#398]
Even though the gles3jni sample has support for GLES3 rendering, it will never create an ES3 renderer.

This is because the app always requests an ES2 context, and never an ES3 context.

In line 42 of GLES3JNIView.java the argument should be 3, not 2:
        setEGLContextClientVersion(3);

**Comment by ggfan** [comment]
this should be fixed, please re-open if it is still there.
