### ISSUE TITLE
ExternalNativeDebugBuild fails

### ISSUE THREAD

**Issue by dennohtu** [googlesamples/android-ndk#404]
Am trying to build Mupdf for android with a linux environment. The build however fails. Here is the output

GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating goal targets....
 File 'assemble' does not exist.
   File 'assembleDebug' does not exist.
     File 'generate' does not exist.
    Must remake target 'generate'.
make -j4 -C libmupdf generate
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
make[1]: Entering directory '/root/mupdf-android-viewer-mini/libmupdf'
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: pkg-config: not found
Updating goal targets....
 File 'generate' does not exist.
Must remake target 'generate'.
Successfully remade target file 'generate'.
make[1]: Nothing to be done for 'generate'.
make[1]: Leaving directory '/root/mupdf-android-viewer-mini/libmupdf'
    Successfully remade target file 'generate'.
  Must remake target 'assembleDebug'.
ANDROID_HOME= ./gradlew assembleDebug
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processArmeabi-v7aDebugManifest UP-TO-DATE
:processArmeabi-v7aDebugResources UP-TO-DATE
:processX86DebugManifest UP-TO-DATE
:processX86DebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:javaPreCompileDebug
:compileDebugJavaWithJavac UP-TO-DATE
:mergeDebugShaders UP-TO-DATE
:compileDebugShaders UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:transformClassesWithDexForDebug UP-TO-DATE
:generateJsonModelDebug UP-TO-DATE
:externalNativeBuildDebug
Build mupdf_java x86
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for x86_64-pc-linux-gnu
Reading makefiles...
Updating goal targets....
 File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/libmupdf_java.so' does not exist.
   File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_java//root/mupdf-android-viewer-mini/libmupdf/platform/java/mupdf_native.o' does not exist.
  Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_java//root/mupdf-android-viewer-mini/libmupdf/platform/java/mupdf_native.o'.
make[1]: Entering directory `/root/mupdf-android-viewer-mini'
   File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/libmupdf_core.a' does not exist.
     File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/archive.o' does not exist.
    Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/archive.o'.
[x86] Compile        : mupdf_java <= mupdf_native.c
     File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bbox-device.o' does not exist.
    Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bbox-device.o'.
     File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi.o' does not exist.
    Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi.o'.
[x86] Compile        : mupdf_core <= archive.c
     File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi-std.o' does not exist.
    Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi-std.o'.
[x86] Compile        : mupdf_core <= bbox-device.c
[x86] Compile        : mupdf_core <= bidi.c
In file included from 
/root/mupdf-android-viewer-mini/libmupdf/platform/java/mupdf_native.c
:
12
:
In file included from 
/root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz.h
:
16
:
In file included from 
/root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/hash.h
:
6
:
/root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/output.h
:
190
:
16
:
 
error
: 
redeclaration of 'strlen' must have the 'overloadable' attribute
        extern size_t strlen(const char *s); /* avoid including string.h in public header */
                      ^
/root/Android/Sdk/ndk-bundle/sysroot/usr/include/string.h
:
97
:
8
:
 
note
: 
previous overload of function is here
size_t strlen(const char* _Nonnull) __attribute_pure__ __overloadable
       ^
In file included from /root/mupdf-android-viewer-mini/libmupdf/source/fitz/bbox-device.c:1:
In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz.h:16:
In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/hash.h:6:
/root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/output.h:190:16: error: redeclaration of 'strlen' must have the 'overloadable' attribute
        extern size_t strlen(const char *s); /* avoid including string.h in public header */
                      ^
/root/Android/Sdk/ndk-bundle/sysroot/usr/include/string.h:97:8: note: previous overload of function is here
size_t strlen(const char* _Nonnull) __attribute_pure__ __overloadable
       ^
In file included from /root/mupdf-android-viewer-mini/libmupdf/source/fitz/archive.c:1:
In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz.h:16:
In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/hash.h:6:
/root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/output.h:190:16: error: redeclaration of 'strlen' must have the 'overloadable' attribute
        extern size_t strlen(const char *s); /* avoid including string.h in public header */
                      ^
/root/Android/Sdk/ndk-bundle/sysroot/usr/include/string.h:97:8: note: previous overload of function is here
size_t strlen(const char* _Nonnull) __attribute_pure__ __overloadable
       ^
In file included from /root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi.c:37:
In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz.h:16:
In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/hash.h:6:
/root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/output.h:190:16: error: redeclaration of 'strlen' must have the 'overloadable' attribute
        extern size_t strlen(const char *s); /* avoid including string.h in public header */
                      ^
/root/Android/Sdk/ndk-bundle/sysroot/usr/include/string.h:97:8: note: previous overload of function is here
size_t strlen(const char* _Nonnull) __attribute_pure__ __overloadable
       ^
1
 error
 generated.
make[1]: *** [/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/archive.o] Error 1
make[1]: *** Waiting for unfinished jobs....
1
 error
 generated.
make[1]: *** [/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bbox-device.o] Error 1
1
 error
 generated.
make[1]: *** [/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi.o] Error 1
1 error generated.
make[1]: *** [/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_java//root/mupdf-android-viewer-mini/libmupdf/platform/java/mupdf_native.o] Error 1
make[1]: Leaving directory `/root/mupdf-android-viewer-mini'
:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /root/Android/Sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/root/mupdf-android-viewer-mini/libmupdf/platform/java/Android.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/lib -j4 /root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/libmupdf_java.so}
  GNU Make 3.81
  Copyright (C) 2006  Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.
  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
  PARTICULAR PURPOSE.
  
  This program built for x86_64-pc-linux-gnu
  Reading makefiles...
  Updating goal targets....
   File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/libmupdf_java.so' does not exist.
     File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_java//root/mupdf-android-viewer-mini/libmupdf/platform/java/mupdf_native.o' does not exist.
    Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_java//root/mupdf-android-viewer-mini/libmupdf/platform/java/mupdf_native.o'.
  make[1]: Entering directory `/root/mupdf-android-viewer-mini'
     File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/libmupdf_core.a' does not exist.
       File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/archive.o' does not exist.
      Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/archive.o'.
  [x86] Compile        : mupdf_java <= mupdf_native.c
       File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bbox-device.o' does not exist.
      Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bbox-device.o'.
       File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi.o' does not exist.
      Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi.o'.
  [x86] Compile        : mupdf_core <= archive.c
       File `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi-std.o' does not exist.
      Must remake target `/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi-std.o'.
  [x86] Compile        : mupdf_core <= bbox-device.c
  [x86] Compile        : mupdf_core <= bidi.c
  In file included from /root/mupdf-android-viewer-mini/libmupdf/platform/java/mupdf_native.c:12:
  In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz.h:16:
  In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/hash.h:6:
  /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/output.h:190:16: error: redeclaration of 'strlen' must have the 'overloadable' attribute
          extern size_t strlen(const char *s); /* avoid including string.h in public header */
                        ^
  /root/Android/Sdk/ndk-bundle/sysroot/usr/include/string.h:97:8: note: previous overload of function is here
  size_t strlen(const char* _Nonnull) __attribute_pure__ __overloadable
         ^
  In file included from /root/mupdf-android-viewer-mini/libmupdf/source/fitz/bbox-device.c:1:
  In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz.h:16:
  In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/hash.h:6:
  /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/output.h:190:16: error: redeclaration of 'strlen' must have the 'overloadable' attribute
          extern size_t strlen(const char *s); /* avoid including string.h in public header */
                        ^
  /root/Android/Sdk/ndk-bundle/sysroot/usr/include/string.h:97:8: note: previous overload of function is here
  size_t strlen(const char* _Nonnull) __attribute_pure__ __overloadable
         ^
  In file included from /root/mupdf-android-viewer-mini/libmupdf/source/fitz/archive.c:1:
  In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz.h:16:
  In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/hash.h:6:
  /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/output.h:190:16: error: redeclaration of 'strlen' must have the 'overloadable' attribute
          extern size_t strlen(const char *s); /* avoid including string.h in public header */
                        ^
  /root/Android/Sdk/ndk-bundle/sysroot/usr/include/string.h:97:8: note: previous overload of function is here
  size_t strlen(const char* _Nonnull) __attribute_pure__ __overloadable
         ^
  In file included from /root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi.c:37:
  In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz.h:16:
  In file included from /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/hash.h:6:
  /root/mupdf-android-viewer-mini/libmupdf/include/mupdf/fitz/output.h:190:16: error: redeclaration of 'strlen' must have the 'overloadable' attribute
          extern size_t strlen(const char *s); /* avoid including string.h in public header */
                        ^
  /root/Android/Sdk/ndk-bundle/sysroot/usr/include/string.h:97:8: note: previous overload of function is here
  size_t strlen(const char* _Nonnull) __attribute_pure__ __overloadable
         ^
  1 error generated.
  make[1]: *** [/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/archive.o] Error 1
  make[1]: *** Waiting for unfinished jobs....
  1 error generated.
  make[1]: *** [/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bbox-device.o] Error 1
  1 error generated.
  make[1]: *** [/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_core//root/mupdf-android-viewer-mini/libmupdf/source/fitz/bidi.o] Error 1
  1 error generated.
  make[1]: *** [/root/mupdf-android-viewer-mini/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/mupdf_java//root/mupdf-android-viewer-mini/libmupdf/platform/java/mupdf_native.o] Error 1
  make[1]: Leaving directory `/root/mupdf-android-viewer-mini'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.213 secs
Makefile:11: recipe for target 'assembleDebug' failed
make: *** [assembleDebug] Error 1

What might be causing the issue, and how do I fix it?

**Comment by ggfan** [comment]
looks like it is just one error: strlen() it got declared twice  -- one in string.h, the other one in your own /include/mupdf/fitz/output.h.  I would look at output.h to see how strlen is defined / implemented (in which source file).  then go from there.  if just include string.h in output.h would get rid of your local strlen() in output.h, that would be good; otherwise it needs more digging (whether there is some macro missed that output.h expecting to choose which version of strlen() to use ...)

If you feel it is unified header problem, please file a bug on https://github.com/android-ndk/ndk

**Comment by ggfan** [comment]
closing down this, re-open when needed please.
