### ISSUE TITLE
Unable to generate STATIC libraries

### ISSUE THREAD

**Issue by SahanaTambi** [googlesamples/android-ndk#406]
teapot example has ndk-helper/CMakeLists.txt which is supposed to generate a ndk-helper.a library. But when I run this sample code with NDK 15 and gradle version 3.3, no static library is generated. 
I have a  sample project which needs to generate a STTAIC library as well, I have the same issue where .a library is not generated. When I change the library to SHARED, I see .so file gets generated.
[https://github.com/SahanaTambi/Hello-cmake](url)

**Comment by ggfan** [comment]
we chatted in the other thread, in your file
https://github.com/SahanaTambi/Hello-cmake/blob/master/app/build.gradle
just add "targets" ( Raymond told me today ) as:
```java
        externalNativeBuild {
            cmake {
                abiFilters 'armeabi'

                cFlags "-fexceptions", "-frtti"

                // Sets a flag to enable format macro constants for the C++ compiler.
                cppFlags "-std=c++11", "-D__STDC_FORMAT_MACROS"

                targets "testStudentStatic"   // <=== this is the only line added, will force to build testStudentStatic target in your CMakeLists.txt.
            }
        }
```
I did have some problem building your exe module, you could hack it out I guess. just add your exe target after "testStudentStatic" will do, as:
```
targets "testStudentStatic", "libtest"
```
it should generate the static lib for teapots samples,  in my case, it is in:
```
~/tmp/core/teapots>find  . | grep   \\.a  
./choreographer-30fps/.externalNativeBuild/cmake/debug/arm64-v8a/libnative_app_glue.a
./choreographer-30fps/.externalNativeBuild/cmake/debug/arm64-v8a/ndk_helper/libndk-helper.a
```
may do a build of teapot samples, and search for the libndk-helper.a under .externaNativeBuild directory?  I am on Mac

**Comment by SahanaTambi** [comment]
Thanks ggfan! I can find libndk-helper.a now.

**Comment by ggfan** [comment]
great! when you are done, may you kindly help to close this bug?  thank you!
