### ISSUE TITLE
add some samples using something like djinni?

### ISSUE THREAD

**Issue by DanAlbert** [googlesamples/android-ndk#413]
https://www.reddit.com/r/androiddev/comments/6nuq0a/were_on_the_engineering_team_for_android_o_ask_us/dkdch0x/

> What about supporting something similar to SafeJNI, instead of having samples full of NDKHelper copies?

We probably should have some samples showing how to use something like this. There are a handful of options. I usually point people to [Djinni](https://github.com/dropbox/djinni) (not for any particular reason, it just seems to be the most popular), and that post is recommending [SafeJNI](https://github.com/MortimerGoro/SafeJNI).

**Comment by kmshih** [comment]
Studio's also been talking about picking a single jni generation library and blessing it.   We should just get all the C++ folks in a doc, look at all the options, and then decide which we like best.

**Comment by ggfan** [comment]
Ok, we will come to it after the decision.

**Comment by ggfan** [comment]
close this down and could re-open later when there is a decision to go with it.
