### ISSUE TITLE
Not able to record

### ISSUE THREAD

**Issue by pratikrao** [googlesamples/android-ndk#415]
AudioTrack: did not receive expected priority boost on time

**Comment by ggfan** [comment]
is this happening when you ran sample? some more info might help: I am one layer above core AudioTrack code in framework, I could ask expert given more info, thanks

**Comment by pratikrao** [comment]
Yes.. i am facing this issue with sample....

**Comment by pratikrao** [comment]
Actually i need to record internal audio from application..Any help would be appreciated

**Comment by pratikrao** [comment]
AudioRecord: AUDIO_INPUT_FLAG_FAST denied by server; frameCount 0

**Comment by ggfan** [comment]
I saw that "the audio record is not in the fast path",  will follow up internally -- audio team is pretty busy these days.

The recording does work even the recording is not in the fast path, the playback is in fast path.

**Comment by pratikrao** [comment]
I need to record internal audio playing on my application..Eg:- Music maker jam application to allow user create track and record it

**Comment by ggfan** [comment]
This is noticed and tracked already with internal issues b/13569849 and b/37225931, evaluating internally. your report certainly put more weight on those issues. 

In the mean time, your app could not record other app's audio directly: need these other apps add their own internal self-recording, and give the interfaces to your app so your app could get access, I guess.

for future feature related, you could create a discussion on [android-ndk](https://groups.google.com/forum/#!forum/android-ndk), I believe audio team closely monitoring the forum.

Thanks for filing issue, I will keep "recording not on fast path" part of the issue and debug it from another channel.
