### ISSUE TITLE
Build type isn't jni debuggable

### ISSUE THREAD

**Issue by rkrishnan2012** [googlesamples/android-ndk#42]
@proppy  I followed the instructions importing into AndroidStudio but when I create a  "Android Native" run configuration, I get the error "Build type isn't jni debuggable". Any thoughts?

This is on latest canary version of studio 1.3 rc 3 and gradle 2.5 rc1 . This happens for all the samples, but im referring to hello-jni

**Comment by proppy** [comment]
@rkrishnan2012 yes, you have to add isJniDebuggable to the `debug {}` section in build.gradle, see: #20

**Comment by proppy** [comment]
FYI the new syntax with `gradle-experimental-0.2.0` is:
```
android.buildType {
  release {
    ndk {
      debuggable = true
    }
  }
}
```
And it's activated by default for the `debug` `buildType`.

**Comment by merlux** [comment]
Just if anyone stumbles across, it's ```ndk.with```, so:
```
android.buildType {
  release {
    ndk.with {
      debuggable = true
    }
  }
}
```

**Comment by rkrishnan2012** [comment]
lol thanks for keeping this up to date :+1:

**Comment by conect** [comment]
Hi I'm using Android Studio 1.5 Preview. When I post merlux code I receive: 
Error:(25,0):
* The project my be using a version of Gradle that does not contain the method.
* The build file may be missing a Gradle plugin.

What can I do?
thx a lot.

**Comment by kimkha** [comment]
Now you just say:


            jniDebuggable true

**Comment by ggfan** [comment]
This works for me:

android.buildTypes {
    release {
          minifyEnable=false
          proguardFiles.add(file("proguard-android.txt"))
   }
   // the following are default when you choose debug build inside android studio
   // you could add them into your module gradle to try it out.
   debug {
         debuggable = true
         ndk.with {
              debuggable = true  //change this to false, you will see Android studio complain could not debug anymore
         }
    }
[I am using version 1.4.1, latest gradle-experimental plugin 0.4.0, gradle 2.8

**Comment by IgorGanapolsky** [comment]
@ggfan Why do you have **debuggable** in two places?

**Comment by ggfan** [comment]
that was long one ago, need to confirm.  My thought there was: one for java, one for native
