### ISSUE TITLE
error:'neon_vector_type'attribute is not suppoted for this target

### ISSUE THREAD

**Issue by Liuhongmiao** [googlesamples/android-ndk#420]
When I run the hello-neon sample in AS, it comes out this error:

building /home/lhm/Desktop/ndk-folder/android-ndk-master-ndkbuild/hello-neon/app/build/intermediates/ndkBuild/debug/obj/local/x86/libhelloneon.so
typedef __attribute__((neon_vector_type(8))) int8_t int8x8_t;
                       ^
typedef __attribute__((neon_vector_type(16))) int8_t int8x16_t;
                       ^
typedef __attribute__((neon_vector_type(4))) int16_t int16x4_t;
                       ^
typedef __attribute__((neon_vector_type(8))) int16_t int16x8_t;
                       ^
...
/home/lhm/PCSoft/for_hongmiao/android-ndk-r14b/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/3.8.275480/include/arm_neon.h
Error:(48, 24) error: 'neon_vector_type' attribute is not supported for this target
Error:(49, 24) error: 'neon_vector_type' attribute is not supported for this target
Error:(50, 24) error: 'neon_vector_type' attribute is not supported for this target
Error:(51, 24) error: 'neon_vector_type' attribute is not supported for this target
...
My system is ubuntu. Is there any advices for me? I appreciate it very much.

**Comment by ggfan** [comment]
surprisingly that I was checking out the build on master-ndkbuild branch last night, saw something similar. so I changed that one to build with gcc ( not using clang ).

In master branch, x86 build for neon is not enabled, so in theory, you should not see it happen when building for x86.

some questions though: do you care x86 for neon?  your environment is emulator I assume, not making product with x86 neon, correct?

**Comment by ggfan** [comment]
Ok, someone already complained a while back and answers in it too:
  https://github.com/android-ndk/ndk/issues/260
that is really good one actually, super useful description for the problem domain ( regarding to gcc and clang).
  https://software.intel.com/en-us/blogs/2012/12/12/from-arm-neon-to-intel-mmxsse-automatic-porting-solution-tips-and-tricks?page=1
  https://github.com/intel/ARM_NEON_2_x86_SSE

**Comment by ggfan** [comment]
for code inside master branch, some code snippet, in CMakeLists.txt, add something like, in the if ()  ... endif()
```
   elseif (${ANDROID_ABI} STREQUAL "x86")
    set(neon_SRCS helloneon-intrinsics.c)
    set_property(SOURCE ${neon_SRCS}
    APPEND_STRING PROPERTY COMPILE_FLAGS " -msse3")
    add_definitions(-DHAVE_NEON_X86=1 -DHAVE_NEON=1)
else
```
then inside source code, helloneon-instrinsics.c, change the include thing to:
```
#include "helloneon-intrinsics.h"
#if defined(HAVE_NEON) && defined(HAVE_NEON_X86)
  #include "NEON_2_SSE.h"
#elif defined(HAVE_NEON)
  #include <arm_neon.h>
#endif
```
finally, download NEON_2_SSE.h from https://software.intel.com/en-us/blogs/2012/12/12/from-arm-neon-to-intel-mmxsse-automatic-porting-solution-tips-and-tricks?page=1 or [github](https://github.com/intel/ARM_NEON_2_x86_SSE) to the source dir ( app/src/main/cpp/ )

builds and execute fine.  I like to get some performance number difference before update that sample, so may not be any time soon.

or stay with gcc as in master-ndkbuild branch.

**Comment by Liuhongmiao** [comment]
@ggfan Thank you I'm trying with it.
