### ISSUE TITLE
Camera: Notify on capture

### ISSUE THREAD

**Issue by sjfricke** [googlesamples/android-ndk#425]
It would be nice to add some JNI callback to display an "image captured" or "picture saved".
I can't be the only one who took like 50 photos because I wasn't sure if the button was working and there is no log print to notify it either.

**Comment by ggfan** [comment]
yeah, will add prompt for it  thx

**Comment by ggfan** [comment]
this one is fixed for now, tested on Pixel XL device on O, worked OK.

**Comment by sjfricke** [comment]
Can confirm on my Galaxy S6 (Android N) works too. I think it was that extra touch needed!

**Comment by ggfan** [comment]
thank you for conformation, yeah prompt should be there!  there is much more to do in camera area, will come back to it for more API coverage when possible. thanks again!
