### ISSUE TITLE
when i used android 4.1.2 it happen some error ! missing and no known rule to make it

### ISSUE THREAD

**Issue by smallsilver** [googlesamples/android-ndk#429]
this is my error :

`Error:error: '/Volumes/macox/Users/sunrise/gitPro/android-ndk_new/hello-libs/distribution/gmath/lib/arm64-v8a/libgmath.a', needed by '/Volumes/macox/Users/sunrise/gitPro/android-ndk_new/hello-libs/app/build/intermediates/cmake/debug/obj/arm64-v8a/libhello-libs.so', missing and no known rule to make it`

when i used Android above 5.0 it normal!

please help me,thank you!

**Comment by ggfan** [comment]
probably arm64 was not available on that platform ( it started on andriod api level 21 ). those libs are produced with project file in hello/libs/gen-libs  directory

**Comment by vipulsiddhi** [comment]
Build command failed.
Error while executing process /Users/siddhi/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/siddhi/Desktop/vipul/Project/android-opencv-ffmpeg-master/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target native-lib}
ninja: error: '../../../../libs/armeabi-v7a/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so', missing and no known rule to make it
