### ISSUE TITLE
How to use  program

### ISSUE THREAD

**Issue by miguel-jgl** [googlesamples/android-ndk#436]
Good morning to the community. My name is Miguel Gutiérrez Lanza, I am Venezuelan and I am not a programmer. Just checking the internet I copy, paste and make some programs. My question is this:

Could I use a program from this community in a paid application, specifically the audio-echo program? How should I contribute when using that program?

And excuse my ignorance, I remember I'm not a programmer. Could you include that program in another I'm doing as a bookstore?

Please ask for help, articles where I can be instructed.

In general I am tsu in electronics and my goal with this project is to make an android application for people who are stuttering. I designed a free javaFx application and I have the device in physical, but I would like many people to use it by creating the android application and offering it at a very low cost. At least 80% lower price of the tools that are on the market.

Thank you in advance.

**Comment by ggfan** [comment]
The [README.md](https://github.com/googlesamples/android-ndk/blob/master/README.md) file pointing to the [license](https://github.com/googlesamples/android-ndk/blob/master/LICENSE) terms. It is [APACHE 2.0](http://www.apache.org/licenses/LICENSE-2.0).  Hope that helps.

As for  audio-echo, it uses OpenSL ES; from Android O and on, there is another API called [AAudio](https://developer.android.com/ndk/guides/audio/aaudio/aaudio.html), the equivalent sample is in [audio repo](https://github.com/googlesamples/android-audio-high-performance/tree/master/aaudio). It depends what you are targeting: for future OSes, AAudio API is a great choice; for your customers before Android Oreo, app has to use OpenSL ES ( only talking from Android C/C++ side -- java side has its own API )

**Comment by miguel-jgl** [comment]
Sorry for the translation. 

He was very grateful for your answer, I want my application to be used in the most amount of device and if they are old better as it would reach everyone who needs it. I want that echo effect to complement a very simple stuttering correction application, as that feature initially helps dysphemic or stuttering patients. 

I am a novice in programming so I would like to add code and enhance the application, since it is a complement to a series of exercises. I am facilitated since I use android study.

I want the native language because of the speed it offers according to what I have read for speech processing. That is why I would like to add your code to my application respecting and complying with all legal and honesty procedures.

**Comment by ggfan** [comment]
thanks for the update., recommend you just glance through the [license](http://www.apache.org/licenses/LICENSE-2.0), it is pretty much no restrictions.
 Best of the luck for your project; if you have any questions, feel free to ask on stackoverflow, here, or [audio-high-performance repo](https://github.com/googlesamples/android-audio-high-performance)

**Comment by miguel-jgl** [comment]
Thank you for your help.
