### ISSUE TITLE
Use Earphones.

### ISSUE THREAD

**Issue by miguel-jgl** [googlesamples/android-ndk#437]
Translation
Good day. I remember I'm a rookie in this programming thing.

The program already works for me on the phone is noisy but that's the return.

Which setting should I change so that the sound is heard by the headphones only. ?

Thank you very much

**Comment by ggfan** [comment]
https://github.com/googlesamples/android-audio-high-performance/tree/master/aaudio/hello-aaudio
it chooses various input/output device, could you check on that ( I think it is from Java side API to choose devices, I might be wrong )

**Comment by ggfan** [comment]
https://github.com/googlesamples/android-audio-high-performance/tree/master/aaudio/hello-aaudio
it chooses various input/output device, could you check on that ( I think it is from Java side API to choose devices, I might be wrong )

**Comment by miguel-jgl** [comment]
Thank you. I don't understand google translation well, so I'm still going to check the link. Greetings from Venezuela

**Comment by miguel-jgl** [comment]
It's a translation.

I was able to understand his answer. It happened that I tried the application with a hands-free phone and it didn't work, then I switched to a headset and it was fine. What I noticed is that the delay effect of the echo is almost imperceptible. You could tell me where I can change it or point me to where I can research the subject.

Thank you before hand.

**Comment by ggfan** [comment]
when you look at the hello-AAudio sample, it has functions to select devices. I was trying to say that you could try port that code ( device selection ) into your application, so you could choose the device ( or follow the logic there to hardcode to headphone ).

Sorry about the confusion.

The delay ( latency ) is when your run the echo app,  correct? is your headset is wireless/USB?
To adjust in code, you could try to make the buffer counts to be a smaller number. ( it has side effect: if it is too small, then it breaks -- as when play callback happens, if recording slightly missed the callback, then the total system breaks. So something need to be done around this area.  I do not know what could be done on your phone platform: what in there is in there, we could not change thing in that OS image anymore)

**Comment by miguel-jgl** [comment]
Don't apologize for the inconvenience, probably the confusion is me, I must first translate and then investigate what you have suggested. 
However, I've already added the audio-echo program to the application I'm creating that I just want an echo in the order of 200 and 500 milliseconds, which is the time required to create an effect in relation to stuttering. That is to say, to provoke the chorus effect.
I take your suggestions 100% and I hope you will understand that I am a little slow in understanding your technical computer language, however, and that I investigate what I capture the idea translated.

I am using cable headphones to avoid complicating myself, due to my lack of computer experience, in the future I will add the activity for the wifi or bluetooth headset. My application is simple, it is only a complement to the series of exercises that help children overcome the condition of dysphemia or stuttering.

Thank you for your answers and thank you very much.

**Comment by ggfan** [comment]
The cabled headphone is great: it is best way to use on Android at moment ( the other ways a way slow). The echo you experience should not be that long with cable headphone. Could you list the phone model and Android OS version here? thanks

**Comment by miguel-jgl** [comment]
I'm using a small earpiece. The echo does not work with the handsfree. My cell phone is a zte z812, Android 22. But as I explained I would like to know if you can use the application from version 9 onwards.
    I've been testing and the echo delay time can work almost imperceptibly, but that delay can work. The idea is to create an effect on the stuttering child who initially feels that someone is accompanying his or her speech.

**Comment by ggfan** [comment]
I will try to find the same phone you are using and check it out.  The echo should work for Android 9 ( and on wards ).  The latency might varies on different platforms ( hardware ): I did not aware there is any latency standard requirements for Android Phones. so the latency time would be different on different phones.

**Comment by miguel-jgl** [comment]
I'd be thrilled with your help.

**Comment by ggfan** [comment]
Got a device of Z730, Android 4.3, API 18.  When running echo, the audio buffer size is:  512 samples, sample rate is 48KHz.  Echo will start after recording PLAY_KICKSTART_BUFFER_COUNT buffers ( which is 3 ).  Buffering itself incurs latency of 512 x 3 / 48K = 32 ms. yeah, I could feel the longer latency than running on Nexus phones.

When there is fast audio path, the audio buffer size is much smaller ( Nexus 9 is at 192 samples/buffer, I think ). if I decrease the buffering count to 2, echo breaks pretty quickly. To get low latency on this phone need to do some deep investigation ( may never be able to achieve the pro-audio standard )...

Now let us get into the same understanding:
        do you want to get lower latency?
    or you need 200ms -- 500 ms delay?

you could email me too at: gfan@google.com, this might take more back and force chat.

**Comment by ggfan** [comment]
clsoing down this as there is special communication channel set up concerning.
