### ISSUE TITLE
NDK Samples lock up

### ISSUE THREAD

**Issue by PelicanPete2** [googlesamples/android-ndk#439]
The Teapot sample and the Native-Activity samples exhibit the same problem.   If the programs are opened and closed a few times using the Square symbol, then they lock-up.  
The Teapot sample doesn't respond to pinch and flick, but it still spins, and the Native-Activity sample doesn't respond to taps and the colors freeze.  In both cases restarting the App fixes it.

I found a broken sample online.  This pre-built APK also locks on my 2 phones and tablet in the same way as explained above.  It says updated Jun 1, but can't find what year:
https://github.com/joakim-noah/android/releases/tag/tea

Another broken tea pot in the Google App Store at this link:
 https://play.google.com/store/apps/details?id=com.duongnx.ndk.examples

My own builds using MSVS have the same problem as above.
Thanks.

 
  
Owner 
DanAlbert commented on Jul 18 
Probably refile this with the samples folks: https://github.com/googlesamples/android-ndk. This sounds like either a samples issue or a platform bug (and either way, the samples should probably be accounting for it).

 
 DanAlbert closed this on Jul 18 The Teapot sample and the Native-Activity exhibit the same problem.   If the programs are opened and closed a few times using the Square symbol, then they lock-up.  
The Teapot sample doesn't respond to pinch and flick, but it still spins, and the Native-Activity sample doesn't respond to taps and the colors freeze.  In both cases restarting the App fixes it.
This pre-built APK also locks on my 2 phones and tablet in the same way as explained above.  It says updated Jun 1, but can't find what year:
https://github.com/joakim-noah/android/releases/tag/tea
Another broken tea pot in the Google App Store at this link:
 https://play.google.com/store/apps/details?id=com.duongnx.ndk.examples
My own builds using MSVS have the same problem as above.
Thanks.

 
  
Owner 
DanAlbert commented on Jul 18 
Probably refile this with the samples folks: https://github.com/googlesamples/android-ndk. This sounds like either a samples issue or a platform bug (and either way, the samples should probably be accounting for it).

 
 DanAlbert closed this on Jul 18

**Comment by ggfan** [comment]
yeah, I saw your filed bug in the other place too: if you just use android studio/gradle to build, not via MS VS, will you still see the same problem? I am interested to check it out, but pretty tied up with a few things right now.

**Comment by PelicanPete2** [comment]
<<  if you just use android studio/gradle to build, not via MS VS, will you still see the same problem?  >>

I'm almost positive that you will, that is why I included links to 2 broken copies built by others.  One on Google App store and the other on GitHub.  I think the only NDK sample which does not have this problem is the EndLess Tunnel, so I made a Frankenstein of that and the Teapot sample but still has the same problem.  The EndLess Tunnel doesn't have any Java, so maybe the problem is in that Java layer?   What command gets invoked when the user hits the square symbol on the phone?  Maybe best to just terminate the app at that point?  

Regards,
Pete 

-----Original Message-----

**Comment by ggfan** [comment]
In that case, may you try the APK ( debug APK ) here: 
  https://drive.google.com/a/google.com/file/d/1Q0QmDhlik0iMO8d6dRE3kydjJTIE3hhz/view?usp=sharing

you do not have access, but once you request access, you will be granted shortly ( but not automatically ).

Then need your device environment:
   OS version, phone models

It could be some life-cycle processing issue in the sample when app minimized / restore, would like to see it first.

**Comment by PelicanPete2** [comment]
Thanks for posting the debug apk.  I tried installing it on my 3 devices (twice) and it says "App not installed".

Here is a description of my 3 devices:
1. LG phone, model LG-k330, Android 5.1.
2. Lenovo tablet, model TB3-850F, Android 6.
3. Samsung Galaxy S6, Android 7.


<< would like to see it first  >>  
That's easy, just install on your phone, open, close using square symbol, tap on minimized window to restart, repeat a few times until teapot freezes.  On the Samsung, it freezes after reopening once.  On the other devices, you can reopen 2 or 3 times before it freezes.

<<  It could be some life-cycle processing issue  >>
I think that's probably what's wrong.  I was able to fix the Native Activity sample by adding 1 line as follows:


case APP_CMD_GAINED_FOCUS:
   engine->animating = 1;  //// test new,  DID THIS FIX IT ???????   !!!!!  <-------------------------------------<<<< new line
  break;

So, I'm moving my app to the fixed Native Activity sample, It is slow and tedious, but should result in a better app because it handles the life-cycle using C without the ++.    As mentioned before, the Endless Tunnel sample works OK, and the Native Activity sample works after fixed, as mentioned above.  The common denominator is that the 2 samples that work are using C for the life-cycle processing and the broken ones use C++.  Also the 2 samples that work don't have much Java.

I think the path to a robust app is to eradicate all the Java and ++, so that's what I'm doing.  Wish me luck; thanks.  Everything that is pure C, such as native-app-glue EGL and GLES work fine.  The only thing I'm using Java for is the package manager.  Hopefully I can manage the assets from the native side and get rid of all the Java.


Regards,
Pete Palmer
Global Navigation Software Co.
www.globenav.com
Telephone: USA (619) 735-0380



-----Original Message-----

**Comment by ggfan** [comment]
thank you for the detailed explanation and certainly good luck to you!  will follow up with your investigation and see what could do: this reported issues are not visible to me (that apk is build with Android studio 3.0 tested on Pixel XL + O-MR1 though.)

**Comment by ggfan** [comment]
yeah, with your device + android 7, I could see the problem.  (My guess)It is might be related to accelerometer_sensor_ and tap_camera_, will study and debug.

**Comment by PelicanPete2** [comment]
Thanks for looking into it.  Just to save you a little work, I took out the sensor code and changed the tap-camera stuff to C.  Also took out the CPU Features lib, and the Glue lib.  I put the glue .c and .h files in the same module as the lifecycle code.  Then I deleted everything else I could out of the NDK helper lib, and all the Java, except the package manager stuff,  also took out all the performance monitor code and its call to Java.  So that's where it is now, for the record and it still locks-up.  I forgot to mention that when the performance monitor was there, it would jump to way over 60 when the app froze.

My wild guess is that there is too much ++ in there.  It has classes calling classes that call classes.  Maybe it is some kind of gimbal-lock of the classes???  I'm gradually weeding out the ++ stuff, and I think it will help performance.

Regards,
Pete Palmer
Global Navigation Software Co.
www.globenav.com
Telephone: USA (619) 735-0380



-----Original Message-----

**Comment by ggfan** [comment]
Thank you for your shared debug info. continuing to root cause...

**Comment by ggfan** [comment]
some more investigation and some guessing part, works on my test device: https://github.com/googlesamples/android-ndk/pull/447

The problem was that ANativeWindow may not be the same as the one at the app start-up, when coming back from resume.  The teapot application assumes the window is the same as ( so app does not re-create the gl_context with new ANativeWindow, but using the cached ANativeWindow). Not sure why on the reported device it is different from Nexus/Pixel devices, could be OS customization...

may you have a look and see if this addressed your problem? there is no change to tap_camera_/sensor_manager_ etc, pure render context related, thank you in advance

**Comment by PelicanPete2** [comment]
Thanks Gerry,  The fix works great.  I never would have been able to figure it out.  I'm sure that developers, contemplating Android will appreciate your fix.

Regards,
Pete Palmer
Global Navigation Software Co.
www.globenav.com
Telephone: USA (619) 735-0380



-----Original Message-----

**Comment by ggfan** [comment]
making you happy is best part of my work :-)!  will get through code review and merge it in. All of the best!
