### ISSUE TITLE
1.3Preview ndk demo

### ISSUE THREAD

**Issue by a251115100** [googlesamples/android-ndk#44]
Error:Execution failed for task ':app:dexAllDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 1

**Comment by yuruxuan** [comment]
I also meet this problem.-_-!

**Comment by taehwandev** [comment]
Same problem.

My solutions is.

allprojects {
sourceCompatibility = 1.7
targetCompatibility = 1.7
}

build.gradle.

**Comment by DennyCai** [comment]
Why they can not support the Java1.8?

**Comment by proppy** [comment]
Do you also have 1.7 installed?
(Android Studio requires JDK7 as specified by https://developer.android.com/sdk/index.html#Requirements)

Alternatively you can specify the JDK location in `File > Project Structure > JDK Location`.

**Comment by proppy** [comment]
Closing this, and moving the discussion to #43.
