### ISSUE TITLE
lude\linux/types.h:21:10: fatal error: 'asm/types.h' file not found

### ISSUE THREAD

**Issue by crazies** [googlesamples/android-ndk#441]
Updating the latest version makes it unusable
ndk version 15.2.4203891

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':externalNativeBuildDebug'.
> Build command failed.
Error while executing process F:\Sdk\cmake\3.6.3155560\bin\cmake.exe with arguments {--build F:\luozheng\redpackageluck\.externalNativeBuild\cmake\debug\armeabi-v7a --target qssq666x}
[1/2] Building CXX object src/main/cpp/two/CMakeFiles/qssq666x.dir/__/qssq666x.cpp.o
FAILED: F:\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=F:/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=F:/Sdk/ndk-bundle/sysroot  -Dqssq666x_EXPORTS -isystem F:/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem F:/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem F:/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -Wno-error=format-security -Wno-error=pointer-sign -O0 -fno-limit-debug-info  -fPIC -MD -MT src/main/cpp/two/CMakeFiles/qssq666x.dir/__/qssq666x.cpp.o -MF src\main\cpp\two\CMakeFiles\qssq666x.dir\__\qssq666x.cpp.o.d -o src/main/cpp/two/CMakeFiles/qssq666x.dir/__/qssq666x.cpp.o -c F:\luozheng\redpackageluck\src\main\cpp\qssq666x.cpp
In file included from F:\luozheng\redpackageluck\src\main\cpp\qssq666x.cpp:2:
  In file included from F:/Sdk/ndk-bundle/sysroot/usr/include\stdio.h:42:
  In file included from F:/Sdk/ndk-bundle/sysroot/usr/include\sys/types.h:36:
  F:/Sdk/ndk-bundle/sysroot/usr/include\linux/types.h:21:10: fatal error: 'asm/types.h' file not found
  #include <asm/types.h>
           ^~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

**Comment by ggfan** [comment]
this could not be: this got to be deeply inside NDK's compiler toolchain.  I will load try it out on my windows later today ( it is crazy week for this week for me) to have a look ( I really think this error is something else, not possible to be toolchain thing)

**Comment by crazies** [comment]
Indeed, the toolchain version, I upgraded to V14, it seems that the problem does not appear, in addition, Android studio 3 must let me use toolchain 15, but can not download

**Comment by CubeFeng** [comment]
I hava encountered the same problem.

**Comment by ggfan** [comment]
+@DanAlbert 
I built a sample with android studio 3.0, I did see that I could not debug, but I could run ( so put that problem aside first and address it differently ).  I am using:
  Pkg.Revision = 15.2.4203891

How could I see the build failures you saw?

**Comment by DanAlbert** [comment]
That compilation command is incorrect. It's not including the arch specific includes.

@crazies @CubeFeng: Are you using the CMake provided with the SDK? Are you using the NDK's CMake toolchain file? Are you building this sample exactly as it exists in the repository, or has it been modified?

**Comment by ggfan** [comment]
Just to follow-up: [r16 beta2](https://developer.android.com/ndk/downloads/index.html) is released, could you help to see if the problem goes away?
Another help is to try with [deprecated](https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeaders.md) headers in your NDK 15 by enabling those deprecated header macros in your build(this makes is close to r14) -- if that works, it narrows the guess. 

If you are already using deprecated headers and saw the problem, but with unified headers could build fine, then it is a different issue.  Than you for helping!

**Comment by ggfan** [comment]
closing down it for now, feel free to update or email for any thing we could help
