### ISSUE TITLE
How to capture pictures from metadata?

### ISSUE THREAD

**Issue by gzrjzcx** [googlesamples/android-ndk#448]
Hello,
Throughout the app, I can run the attached camera at my mobilephone.
However, my aim is capture pictures and save these pictures in my local device.
After learning the code, I've realized that maybe I need to write a callback function called ACameraCaptureSession_captureCallbacks, and achieve my aim at the third param of ACameraCaptureSession_captureCallbacks(also is a callback function called ACameraCaptureSession_captureCallback_result).

Well,my problem is that I don't know how to copy the data I need from the metadata. Especially in the C++ language environment.
Therefore,could you mind tell me how to achieve my goal in the foundation of this test app?And possibly it's better that if you can give me an example which could take and save pictures.
thanks !
During the waiting time,I will also explore how to achieve my goal!

**Comment by ggfan** [comment]
:-) thank you for kindness for "During the waiting time ..."  :-)  I will try to catch up and mainly recently spent lot of time on NNAPI thing, it is new area and interesting area.

Tried to make up a sample to capture the jpeg files, does that serve your purpose:  https://github.com/googlesamples/android-ndk/blob/master/camera/basic/src/main/cpp/image_reader.cpp

( it wraps around the AImageReader and give to camera, then camera callbacks to tell application when there is an image ready).

**Comment by ggfan** [comment]
@gzrjzcx, is the file helpful?

**Comment by gzrjzcx** [comment]
So sorry for my misleading words "During the waiting time ...",I just want to express my ambition that I must solve this problem. And please not be angry for these biased words.

Well, back to the topic. I could't run your test app successfully since there are some components I missed probably. And in the short time maybe I could't find these necessary components. However, I have learned something important from your second test example.And I believe it's could be used in the native-camera2-master project, right ? I will try my best to transplant the cpp codes to the first project and achieve the capturing pictures goal.
Then, I know you are busy on NNAPI thing, however if possible, could you please make use of your fragmentation time to help me take and save pictures in the native-camera2-master project?

Well,no metter what things will happen.Very thanks to you and I am looking forward to your reply.
See you！

**Comment by ggfan** [comment]
No worries :-).  what error you got when the sample was failed ( at compile time or run-time )? will find time to look the project you mentioned whenever possible.

**Comment by gzrjzcx** [comment]
Thanks!
Maybe the errors occured in these two codes, and other errors probably were caused by the two missed components.
**code:**
import android.support.annotation.NonNull;
import android.support.v4.app.ActivityCompat;
**Error**
The Android Studio told me that there is not component :android.support.annotation
The Android Studio told me that there is not component :android.support.v4.app

**Comment by ggfan** [comment]
thanks for the follow-up!  This seems to be Java side,  Android Studio would could recover from it automatically, appcompat lib is configured inside project's build.gradle file. 
    compile 'com.android.support:appcompat-v7:24.2.0'

totally clean the project ( with Android Studio ), and rebuild the project.

Will have a look soon.

**Comment by gzrjzcx** [comment]
Oh!!!!
Yes,I have run the code successfully ! Extreamly amazing and excited!
However, there is something wrong that I find the preview (including photos by taken) is not clear like the original camera preview. Possibly some camera params like width and length werw changed ?  I don't  know the potential reasons and I will read and make research in this code carefully.
Many many many thanks to you! Maybe tomorrow you'll also receive my question. jajaja~

**Comment by ggfan** [comment]
yes, you are right: the parameters were not very heavily tuned ( although tried to do my best for it :-)) for best effect.  Just putting 2 parameters adjustable on the UI ( sliders ), to show the way to change those camera parameters. Please explore and submit a patch when you get more parameters tuned -- those are very valuable. Thanks

**Comment by ggfan** [comment]
closing this one for now, feel free to open it whenever needed (camera is interesting subject and I am eager to explore camera pipeline: image, graphics, and machine learning are exciting areas :-), a joke from my personal view right after long weekend!)
