### ISSUE TITLE
Add sample to show vendoring library from a different jni directory

### ISSUE THREAD

**Issue by xueqingxiao** [googlesamples/android-ndk#45]
when i import libsodium(https://github.com/jedisct1/libsodium)  as my JNI lib, can't find some files, cause this not in a same folder.

**Comment by proppy** [comment]
The current version of the new gradle experimental plugin doesn't yet support building standalone library module.

This is being tracker on [b.android.com/177631](b.android.com/177631).

The only workaround for now is to "vendor" the source in the jni directory or point to a different source directory using:
```
model {
    // ...
    android.sources {
        main {
            jni {
                source {
                    srcDir 'src'
                }
            }
        }
    }
}
```

You can find more information about the new plugin model syntax in the [Experimental Plugin User Guide
](http://tools.android.com/tech-docs/new-build-system/gradle-experimental)

Leaving this issue open to provide a sample that show how to vendor an external library from a different source path.

**Comment by proppy** [comment]
Closing in favor of #116
