### ISSUE TITLE
Documentation fails to metion necessary changes to build.gradle for shared libraries

### ISSUE THREAD

**Issue by mondaugen** [googlesamples/android-ndk#459]
"When importing libraries into your app, ..." from the README doesn't indicate the lines in build.gradle that need to be changed in order to pack a shared library into the APK.

    }
    sourceSets {
        main {
            // let gradle pack the shared library into apk
            jniLibs.srcDirs = ['../distribution/gperf/lib']
        }
    }

**Comment by ggfan** [comment]
let me double check on this ( it should be packed automatically ).

**Comment by ggfan** [comment]
yeah, you are correct: it is strict cmake business and cmake is not aware of it is for Android I guess. 
I will update the readme for it: it is critical part of the usage.
thanks
