### ISSUE TITLE
Callback JAVA issues in C ++ threads

### ISSUE THREAD

**Issue by NaturalTravele** [googlesamples/android-ndk#468]
I am calling a JAVA function in a C ++ thread and I can not access the runOnUiThread worker thread in my callback function after I have used AttachCurrentThread and it crashes when I run the program to DetachCurrentThread.
The same logic written in C language is not wrong, may I ask what is the solution?
android studio: 3.0.1
Xiaomi MI-4c android 5.1.1 API 22
My English is not good, please forgive me.

**Comment by ggfan** [comment]
let me look at the similar sample code: my guess at this point is something else ( like JNIEnv pointer may not be valid if not get it via global reference  )

**Comment by NaturalTravele** [comment]
@ggfan 
 Thank you very much for your reply, I have sent the demo project to your email.

**Comment by NaturalTravele** [comment]
Thank you for your help to solve the problem.
