### ISSUE TITLE
hello-neon leads an unexpected result

### ISSUE THREAD

**Issue by moshoujingli** [googlesamples/android-ndk#474]
The project expects to has a result that the neon version is faster then c version, but it seems that on my device, the neon version takes double time.

Device: MIX2 Unibody
Device Android version: 7.1.1 (MIUI 9.1)
Processor: Qualcomm Snapdragon 835

Capture of result:
![3a006b548f7fd5b32436584e73b23618](https://user-images.githubusercontent.com/1410176/34162431-a6a13cee-e50e-11e7-98f4-4c0b2bb724d7.jpg)

**Comment by ggfan** [comment]
Need a lot of digging on this feature: on 32 bit ARM, neon is natively supported.  on 64 bit arm processor, I am not sure.  The build right now is to build for 32 arm, on a 64 bit processor, if NEON is not supported, then it simulates. Will look into this one, together with the other neon one for x86 (neon + x86 is slower, similar to 64 bit arm numbers)

**Comment by ggfan** [comment]
2 things needs to be done for this samples at least:

1. Update it for 64 bit ARM

1. visit x86/x86-64 and act accordingly (C version might be faster than neon version)

**Comment by ggfan** [comment]
@moshoujingli a little info for this ( but not the heavy technical yet ): build for release, and run the sample on my Pixel XL device, my number is:
   60ms  for C version
   18ms   for neon version
On Nexus 5 device:
   C version: 165ms
   Neon Version: 29ms

Debug build might misleading us for performance. May you check it out on your end?  Thanks.

**Comment by ggfan** [comment]
updated description for hello-neon sample with https://github.com/googlesamples/android-ndk/pull/477.  Confirmed with original developer that x86 platform support is mainly for neon-portability purpose.
