### ISSUE TITLE
How can I change delay ?

### ISSUE THREAD

**Issue by alexd555** [googlesamples/android-ndk#476]
Hi,
I want to change delay. for example, by changing sample rate or buffer size.
How can I do it ?

**Comment by ggfan** [comment]
gradually like to route audio to https://github.com/googlesamples/android-audio-high-performance
it is focus on low latency audio. create an issue there:  https://github.com/googlesamples/android-audio-high-performance/issues/92

assuming you want to go lower and lower for latency, buffer size would be directly affecting it. But it could not go too low: system will glitch. let's address it in that repo.

**Comment by alexd555** [comment]
Yes. I want to have ability to change delay.
I try that repo https://github.com/googlesamples/android-audio-high-performance  but it doesn't compile.
