### ISSUE TITLE
Add HPF on Real Time

### ISSUE THREAD

**Issue by alexd555** [googlesamples/android-ndk#478]
Hi,
I want to add HPF to  https://github.com/googlesamples/android-ndk/tree/master/audio-echo/app/src/main/cpp.

I try this
```
double filter[]={-0.000271644477087926,0.00231682081656234,-0.00697762679239381,0.0113431078907557,-0.00922785019978973,-0.000953863100870534,0.00985593896141045,-0.00555013199491495,-0.00869288595337110,0.0130688967200457,0.00298808043964922,-0.0197522326251256,0.00894497147708418,0.0214370330423526,-0.0266004895962514,-0.0129511674987413,0.0473297694426478,-0.0123916710107896,-0.0669754812188437,0.0708843498739455,0.0810696191193916,-0.305755100930970,0.413804336148547,-0.305755100930970,0.0810696191193916,0.0708843498739455,-0.0669754812188437,-0.0123916710107896,0.0473297694426478,-0.0129511674987413,-0.0266004895962514,0.0214370330423526,0.00894497147708418,-0.0197522326251256,0.00298808043964922,0.0130688967200457,-0.00869288595337110,-0.00555013199491495,0.00985593896141045,-0.000953863100870534,-0.00922785019978973,0.0113431078907557,-0.00697762679239381,0.00231682081656234,-0.000271644477087926};

double * convolution(uint8_t *x,int len_signal, double *filter, int len_filter)
{
     double *y=new double[len_signal+len_filter];
     int length = len_signal+len_filter;
     for (int n=0;n<length;n++)
     {
         y[n]=0;
         for(int k=0;k<length;k++)
         {
             if (n-k >=0 && n-k <length)
                 y[n] += x[n-k]*filter[k];
         }
     }
     return y;
}
void ece420ProcessFrame(sample_buf *dataBuf) {
    dataBuf->buf_= (uint8_t *) convolution(dataBuf->buf_, dataBuf->size_, filter, 45);

}
```

Can you help me, please ?

Thanks,
 Alex

**Comment by ggfan** [comment]
when is this due? :-)  I would try it out and bottom line is to inject another thread between capture and playback thread.

**Comment by ggfan** [comment]
I understood this is moving back from Oboe repo.  Both Phil and Don are experts in audio field :-), their advice are really worth to go after.

**Comment by ggfan** [comment]
now get chance to read your code, not sure I get it though:  if it is convolution, the second loop should be looping against filter_length (not `k < length;`), correct?  44 samples from previous buffer have to be saved for the next recorded sample buffer, correct?

as for coding, probably do not allocate the new buffers in each function call, but reserve buffers ( just need one extra, I feel, for the processing thread) ahead of the time.  Once you have your algorithm fixed, you could look into file: audio_recorder.cpp ProcessSLCallback() and follow the recorded buffer chain to add your processing ( eventually you need another thread to do this ).

but please make sure your algorithm are correct before debugging.  I think Don's link http://www.musicdsp.org/files/Audio-EQ-Cookbook.txt is great one to follow.  closing this one for now.

**Comment by alexd555** [comment]
Hi ggfan,
I ran your code but I listen a noise.  Why ?
Thanks,
Alex

**Comment by ggfan** [comment]
yeah, that is the reason that might need to check the filter parameters ( when I change the filter coefficient to pass through only: leave one value to 1.0, the rest all 0s, it is ok)  assignCacheBuffer is done from audio_main.cpp.   you could see how to hook your filter into the record/playback chain.  then you could continue to make sure the coefficients are correct.

**Comment by alexd555** [comment]
@ggfan 
Can you explain how I can create the correct filter ?
I created this in matlab, I also tried to create with fixed-point but it still create with floating-point.
Thank you very much,
Alex

**Comment by ggfan** [comment]
@alexd555 that really need to follow the link from Don, I do not have a tool for that.  This would be good to check for Stackoverflow for creating filters.

**Comment by alexd555** [comment]
Can you also answer on my second question ?
@ggfan

**Comment by ggfan** [comment]
Oh, you mean the matlab one?  that I am unable to comment: not playing with it.  I believe you knew better than me there already :-)

**Comment by alexd555** [comment]
No. I meant size of CacheBuffer. Why isn't countSamples+size_of_filter ?
@ggfan

**Comment by ggfan** [comment]
Oh: when there is only 44 raw samples, they are cached and combined with the next sample buffer to continue filtering.

**Comment by alexd555** [comment]
I don't  sure that I understand your answer  because I know that length of output signal is sum of length of two input signal after convolution.
@ggfan

**Comment by alexd555** [comment]
I don't think that I need to fix my filter. I check it on matlab with chirp and filter worked well.
@ggfan

**Comment by ggfan** [comment]
Ok. I will take a look later. you may also try out since the hooks are there.  once that works ( somewhat), you will need to add another thread to do those processing, when get to that stage, we could chat on how

**Comment by alexd555** [comment]
@ggfan 
Could you explain why I can't debug with breakpoint in this project ?
Could you also explain how I add correct new thread ? I thinks that new use with a new queue and mutex.
Thanks,
Alex

**Comment by ggfan** [comment]
it could be debugged with Android studio 3.0, not seeing problem. if you have problem, maybe checkout https://codelabs.developers.google.com/codelabs/android-studio-cmake/index.html?index=..%2F..%2Findex#0. for thread, I could look at it later next week

**Comment by alexd555** [comment]
My problem is
![problem](https://user-images.githubusercontent.com/25776246/34644231-2e8e9132-f32a-11e7-90e9-9971196b5142.png)
I tried to search in Google but not found solution.
Thanks,
Alex

**Comment by ggfan** [comment]
Ok, I see: I do not use emulator that often. May you file this issue to emulator forum? anything I say would be a guess at its best, better leave to yourself for this one.

**Comment by alexd555** [comment]
Hi @ggfan ,
When do you think that you will get change to help me ? My main problem is noise.
Thanks,
Alex

**Comment by ggfan** [comment]
later next week I could try to come back for some time.  we could also work through email: need more clarification and pick up some audio domain knowledge too.

**Comment by alexd555** [comment]
Hi @ggfan 
I pay attention something strange. I debug with breakpoint on convolution function and I see that buf_ has "read memory from 0x4 failed (0 of 1 bytes read)". But if I leave one value in filter to 1.0, the rest all 0s, it is ok. It is very strange because it before that content of buf_ changes.
my email is alexd555@gmail.com
