### ISSUE TITLE
how to configure shared library in such a situation 

### ISSUE THREAD

**Issue by voidxb** [googlesamples/android-ndk#480]
hello~For my c++ project is very complex,we build it and get our shared library on Linux by cross compiling . The problem is that my .so file depends on libc++_shared.so,libc.so and so on,how to add them in android project so that my shared library can call them and work well.

**Comment by ggfan** [comment]
I am going to sell you Android Studio/Gradle: if you build with AS/Gradle, those needed shared lib will be packed inside APK, in sub folder lib/$ANDROID_ABI/. If you put all of your dependent shared libs into src/main/jniLibs, then it will be packed into APK by default too.

If you use you own scripts to pack APK, just do the similar thing: tuck all dependent shared libs into YOUR-APK/lib/$ANDROID-ABI/ directory and zip it up; or copy all those libs into jniLib folder.

**Comment by ggfan** [comment]
closing down this one: please create a thread on [android-ndk](https://groups.google.com/forum/#!forum/android-ndk) forum, there will be more experts to help out.
