### ISSUE TITLE
Misleading comment in gl3stub_wrapper.c

### ISSUE THREAD

**Issue by ethteck** [googlesamples/android-ndk#481]
I got very confused when reading this comment in the file:

> This file wraps the es3 stub file to current workaround Studio limitation:
> stub file is needed for ES3 systems
> stub file is NOT needed for ES3 systems
> DYNAMIC_ES3 is defined in build_gradle when building for ES2, it is not defined for ES3 systems

My proposed correction:
> This file wraps the es3 stub file to **workaround current** Studio limitation:
> stub file is needed for ES3 systems
> stub file is NOT needed for **ES2** systems
> DYNAMIC_ES3 is defined in build_gradle when building for **ES3**, it is not defined for **ES2** systems

I bolded the parts I suggest changing. It's also very possible I just don't understand what's going on here and the comment is indeed correct.

**Comment by ggfan** [comment]
OOps, it is really confusing now reading it.  thanks for bring it up.  Let me try my understanding and load up a PR, so you could help to take a look and comment. Thanks

**Comment by ggfan** [comment]
PR is merged! Thanks for pointing it out: raise more whenever you find things like this! Thanks.
