### ISSUE TITLE
undefined reference to `AImageReader_'

### ISSUE THREAD

**Issue by NussknackerXXL** [googlesamples/android-ndk#483]
API-Level: 24
ABI: arm64-v8a

I am using some calls like `AImage_Reader_new` and `AImage_Reader_setImageListener`.
I followed the camera-example provided at this repository but get some linking errors:

` undefined reference to 'AImageReader_acquireNextImage'`
` undefined reference to 'AImageReader_new'`
` undefined reference to 'AImageReader_setImageListener'`

I checked the libmediandk.so under `{NDK}/platforms/android-24/arch-arm64/usr/lib` and it contains the named methods before. Why am i getting these errors?

This is the linking part of my CMakeLists.txt
```
target_link_libraries(libName
        android
        log
        m
        camera2ndk
        mediandk
)
```

**Comment by ggfan** [comment]
which NDK version you are using?

**Comment by ggfan** [comment]
just ping: sample could be built with NDK-r16. 

I would check for the header file first: `#include <media/NdkImageReader.h>`; then the linking which is inside the CMakeLists.txt ( what you showed is fine though ). Last step is to just build for one ABI:
```
         ndk {
             abiFilters 'armeabi-v7a'
         }
```
in build.gradle. I would bet one of the three should get the problem narrowed down. if you have the project somewhere, I could certainly take a look. Closing down this one, feel free to re-open it.

**Comment by NussknackerXXL** [comment]
@ggfan I built it with NDK 16.1.4479499. But i did not use gradle. Just used CMake and Android Toolchain. This is what i am trying now.
