### ISSUE TITLE
Building static native libraries similarly to hello-libs example does not work with ndkBuild

### ISSUE THREAD

**Issue by suikki** [googlesamples/android-ndk#484]
I'm trying to use an external native static library that is not using cmake but ndkBuild. When using ndkBuild the `targets` parameter in externalNativeBuild does not seem to accept static libraries at all.

As a workaround I've tried creating an empty dynamic library but it's really not very nice because then if I use the library project directly that also gets included in it.

I already made a small project demonstrating the problem and an issue here: https://issuetracker.google.com/issues/69809765 but I was wondering if there was some better workaround?

I'm also getting really frustrated with the android gradle plugin/android studio bug tracker. They don't seem to respond to any issues I've been tracking there. I had to go through other channels to even get issues assigned to someone but they still never respond to or update the issues :(

**Comment by ggfan** [comment]
sorry for the delay, let me take a look first.  I am part of the gang that making you frustrated, apology for that too.

**Comment by suikki** [comment]
Thanks. I do understand and can totally relate. There are a lot of issues posted there.

**Comment by ggfan** [comment]
I was betting the application.mk to force it; no, it does not do it: @rschiu?

**Comment by ggfan** [comment]
not much from my side. potentially could trigger ndk-build/ndk-build.cmd from build.gradle as a separate task; but it kind of defeats the purpose of gradle though.

**Comment by ggfan** [comment]
close this one as action is happening on the origin bug.
