### ISSUE TITLE
developer.android.com refers to non-existing files

### ISSUE THREAD

**Issue by tsirolnik** [googlesamples/android-ndk#487]
Hello,

The [Android MK guide](https://developer.android.com/ndk/guides/android_mk.html) from the Android Developer website refers to an Android.mk file which currently doesn't exist - 

> This section uses the Android.mk file in the Hello-JNI sample toward that end, explaining the role that each line in the file plays.

Could you please update the website to reflect that? Also, could you please make it clear on whiles method should be used, .MK or CMake?

Thanks

**Comment by ggfan** [comment]
yeah, thank you for bringing it up: it is a mis-match.  Will have it fixed!  for the time being, the code for that is at https://github.com/googlesamples/android-ndk/tree/android-mk/hello-jni.

**Comment by ggfan** [comment]
tagged with internal bug: b/72757349. Closing this one for now
