### ISSUE TITLE
opengl and opencv with ndk camera api

### ISSUE THREAD

**Issue by vendelin8** [googlesamples/android-ndk#496]
Hi,

I'm thinking about writing an app similar to a qr-code reader, with some other content. I'm quite new to both image processing and native android, please be gentle. :)

I found the native camera example at, which seems to be a very good start:
https://github.com/googlesamples/android-ndk/tree/master/camera

So for drawing some frame on the screen, is it possible to manipulate the image with opengl in c++? If yes, how?

And then for the rest, it would be awesome having a separate thread for some opencv image processing. I'd be very grateful for some pointers how to get started with this.

Many thanks!

**Comment by ggfan** [comment]
yeah, openGL in C++ definitely could process the images.  send those images as texture and read them into GPU with sampler ( shader texuring commands ), then your shader will have control: certainly could do lot of things. Finally write them out to texture render target.

For different thread, OpenGL supports shared context: create in one thread and use the same context in the other thread. I do think samples are using the shared context but it is the way to go.

**Comment by vendelin8** [comment]
Perfect, thank you!

**Comment by gpx1000** [comment]
Hate to jump in from the peanut gallery, but thought the following tidbits would be useful:

1.) multithreading with OpenGL using shared contexts.  Note of warning: OpenGL operates as a monolithic system.  To a single resource it can either update the resource or it can draw it.  It can't do both at the same time.  Translation: load/make changes in separate thread, when that thread is done with changes, mark the object ready for drawing in your main render frame loop.
2.) Vulkan offers a bit better capacity for directly circumventing issues mentioned in 1, however, it's not easy to work with for new comers and likely overkill unless you have specific needs that OpenGL's pipeline doesn't address.

To do what you're wanting to do:
in your main draw thread where the shared context needs to be created you're gonna want something like this:
`
    // initialize OpenGL ES and EGL
    const EGLint attribs[] =
    {
        EGL_BLUE_SIZE, 8,
        EGL_GREEN_SIZE, 8,
        EGL_RED_SIZE, 8,
        EGL_DEPTH_SIZE, 0,
        EGL_NONE
    };

    EGLDisplay display = eglGetDisplay(EGL_DEFAULT_DISPLAY);

    EGLint major, minor;
    eglInitialize(display, &major, &minor);
    INFO("EGL version %d.%d", major, minor);

    EGLConfig configs[512];
    EGLint numConfigs = 0;
    eglGetConfigs(display, configs, 512, &numConfigs);

    EGLConfig config = 0;
    for (int i = 0; i < numConfigs; i++)
    {
        EGLint value = 0;

        eglGetConfigAttrib(display, configs[i], EGL_RENDERABLE_TYPE, &value);
        if ((value & EGL_OPENGL_ES3_BIT_KHR) != EGL_OPENGL_ES3_BIT_KHR)
        {
            continue;
        }

        eglGetConfigAttrib(display, configs[i], EGL_SURFACE_TYPE, &value);
        if ((value & (EGL_WINDOW_BIT | EGL_PBUFFER_BIT)) != (EGL_WINDOW_BIT | EGL_PBUFFER_BIT))
        {
            continue;
        }

        int	j = 0;
        for (; attribs[j] != EGL_NONE; j += 2)
        {
            eglGetConfigAttrib(display, configs[i], attribs[j], &value);
            if (value != attribs[j + 1])
            {
                break;
            }
        }
        if (attribs[j] == EGL_NONE)
        {
            config = configs[i];
            INFO("CreateRenderContext, found EGL config");
            break;
        }
    }

    if (config == 0)
    {
        INFO("CreateRenderContext, failed to find EGL config");
        return -1;
    }

    //Reconfigure the ANativeWindow buffers to match, using EGL_NATIVE_VISUAL_ID.
    EGLint format;
    eglGetConfigAttrib(display, config, EGL_NATIVE_VISUAL_ID, &format);
    ANativeWindow_setBuffersGeometry(appContext.nativeWindow, 0, 0, format);

    //Create a surface 
    EGLSurface surface;
    surface = eglCreateWindowSurface(display, config, appContext.nativeWindow, NULL);
    if (surface == EGL_NO_SURFACE)
    {
        LOGE("CreateRenderContext: eglCreateWindowSurface failed");
        return -1;
    }

    //Create a context
    EGLint contextAttribs[] =
    {
        EGL_CONTEXT_CLIENT_VERSION, 3,
        EGL_NONE
    };
    EGLContext context;
    context = eglCreateContext(display, config, NULL, contextAttribs);
    if (context == EGL_NO_CONTEXT)
    {
        ERROR("CreateRenderContext: eglCreateContext failed");
        return -1;
    }

    //Attach the surface to the context
    if (eglMakeCurrent(display, surface, surface, context) == EGL_FALSE)
    {
        ERROR("CreateRenderContext: eglMakeCurrent failed");
        return -1;
    }

    EGLint w, h;
    eglQuerySurface(display, surface, EGL_WIDTH, &w);
    eglQuerySurface(display, surface, EGL_HEIGHT, &h);

    appContext.display = display;
    appContext.eyeRenderContext = context;
    appContext.eyeRenderSurface = surface;
`

At this point do the rest of your thread setup stuff to create a worker thread for OpenCV to work with your captured image.  Here I'll show how to setup the context to create on the worker thread:

`
        // Get values for the current OpenGL activity
	EglDisplay = eglGetCurrentDisplay();
	if (EglDisplay == EGL_NO_DISPLAY)
	{
		ERROR("EGL_NO_DISPLAY");
		abort();
	}

	EGLContext EglMainContext = eglGetCurrentContext();
	if (EglMainContext == EGL_NO_CONTEXT)
	{
		ERROR("EGL_NO_CONTEXT");
		abort();
	}

	EGLint attribList[] =
	{
		EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
		EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
		EGL_NONE
	};

	EGLint numConfigs;
	if (!eglChooseConfig(EglDisplay, attribList, &EglConfig, 1, &numConfigs))
	{
		ERROR("eglChooseConfig failed");
		abort();
	}

	if (PEnv->EglConfig == NULL)
	{
		ALOGE("EglConfig NULL");
		abort();
	}
	if (!eglQueryContext(EglDisplay, EglMainContext, EGL_CONTEXT_CLIENT_VERSION, (EGLint *)&EglClientVersion))
	{
		ERROR("eglQueryContext EGL_CONTEXT_CLIENT_VERSION failed");
		abort();
	}
	VERBOSE("Current EGL_CONTEXT_CLIENT_VERSION:%i", PEnv->EglClientVersion);

	EGLint SurfaceAttribs[] =
	{
		EGL_WIDTH, 1,
		EGL_HEIGHT, 1,
		EGL_NONE
	};

	EglPbufferSurface = eglCreatePbufferSurface(EglDisplay, EglConfig, SurfaceAttribs);
	if (EglPbufferSurface == EGL_NO_SURFACE) 
	{
		ERROR("eglCreatePbufferSurface failed");
	}

	EGLint bufferWidth, bufferHeight;
	if (!eglQuerySurface(EglDisplay, EglPbufferSurface, EGL_WIDTH, &bufferWidth) ||
	!eglQuerySurface(EglDisplay, EglPbufferSurface, EGL_HEIGHT, &bufferHeight))
	{
		ERROR("eglQuerySurface failed");
		abort();
	}
	// Create a new GL activity
	EGLint loaderContextAttribs[] =
	{
		EGL_CONTEXT_CLIENT_VERSION, EglClientVersion,
		EGL_NONE, EGL_NONE,
		EGL_NONE
	};
	LoaderContext = eglCreateContext(EglDisplay, EglConfig, EglMainContext, loaderContextAttribs);
	if (LoaderContext == EGL_NO_CONTEXT)
	{
		ERROR("eglCreateContext failed");
		abort();
	}
`

The rest should just involve using OpenCV && NativeCamera API.  This should just hopefully get you going on the second part of your question.  However, you don't necessarily NEED a shared glcontext just to do OpenCV processing on a buffer returned from GL.  If you maintain just one frame pump and draw the image to a framebuffer, you can then save the framebuffer out to an OpenCV image matrix; let OpenCV do its thing in the separate thread and then convert the OpenCV image back to a gl texture.
