### ISSUE TITLE
Unable to create pre trained model for NN sample

### ISSUE THREAD

**Issue by vnsmurthysristi** [googlesamples/android-ndk#498]
Hello I am looking for help how to create a new trained model binary like in below link 

 https://github.com/googlesamples/android-ndk/tree/master/nn_sample/app/src/main/assets

for my model, i don't find any good documentation to create it, please help me with the steps. 

I wanted to create for a simple 2D conv

**Comment by miaowang14** [comment]
The trained model binary file is expected to be generated by machine learning frameworks like TensorFlow (Lite), Caffe2, or your own libraries, as long as the binary is densely packed and not compressed.

If the model is trained using TensorFlow, I would recommend using TOCO to generate the model file, which could then be used by TFLite and NNAPI, e.g : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/cmdline_examples.md

**Comment by ggfan** [comment]
@vnsmurthysristi  the file you pointed represents the trained data: in this case it is a file of all 0.5f -- the input values into the model's adders ( it is not a model ).  The model is hard-coded in the sample: 2 layer model --  2 adders and one multiplier.  To deal with Machine Learning's model, need use higher level frameworks: that is what @miaowang14 pointing out. 

closing down this one for now, thank you for your question!

**Comment by vnsmurthysristi** [comment]
@ggfan Thank you. My goal is not to use the higher level Machine Learning framework lie TFlite, rather wanted to directly work with the NN operations itself.

**Comment by ggfan** [comment]
NN API does not have interface to handle  in memory model save to/restore from external files. Only the  input data ( tensors ) could be inside the shared-memory.  Anything you do with:
   -- creating an Android NN model in memory in your app
   -- save to the external media   <=== application could do whatever it could, no help from NNAPI
Application could freely choose the right format to use to represent NNAPI model to save; restoring direction will use the same format.
