### ISSUE TITLE
audio-echo: AudioRecorder object delivers wrong audio buffer format (certain Android 7.0 devices)

### ISSUE THREAD

**Issue by tgrain** [googlesamples/android-ndk#499]
Audio format problems occurred with my app, that uses the NDK audio initialization / transfer sequence from the audio-echo example to record and process the main microphone signal of the phone.

Although the app requests 1-channel (mono) recording format, the AudioRecorder delivers interleaved 2-channel (stereo) audio buffers via the SLAndroidSimpleBufferQueueItf callback. This behaviour occurrs on a Samsung Galaxy J7 2017 / Android 7.0 phone of one of my app's users. 

Sample rate 48000 and buffer length 240 Samples are queried in Java like shown in audio-echo example:
	mAudioMgr.getProperty ( AudioManager.PROPERTY_OUTPUT_SAMPLE_RATE );
	mAudioMgr.getProperty ( AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER );
As every sample is repeated once in this wrong buffer format, the signal can not be processed properly. 

Shouldn't the Samsung's Android system deliver exaclty the 1-channel format I requested? How to query if the AudioRecorder delivers other buffer formats than requested? 

### test case:
NDK Example app  audio-echo on Samsung J7 2017 /Android 7.0
https://github.com/googlesamples/android-ndk/blob/master/audio-echo/

Channel number: 1
set in audio-echo/app/src/main/cpp/audio_common.h :
#define AUDIO_SAMPLE_CHANNELS 1 

* NDK Version: 16.1.4479499
* Device / API: Samsung J7 2017, Android 7.0
* Gradle targetSdkVersion: 19
* Gradle buildToolsVersion: 25.0.2
* Gradle compileSdkVersion: 25

Audio format definition (in prepareAudioFormat() ):

```
	memset(pcmFormat, 0, sizeof(*pcmFormat));
	pcmFormat->endianness  = SL_BYTEORDER_LITTLEENDIAN;
	pcmFormat->formatType = SL_DATAFORMAT_PCM;
	pcmFormat->sampleRate  = audioFormat->fsamp_;
	pcmFormat->channelMask = SL_SPEAKER_FRONT_CENTER;
	pcmFormat->numChannels = 1;
	pcmFormat->containerSize = 16;
	pcmFormat->bitsPerSample =  16;
	pcmFormat->representation = 0;
```

Audio Recorder Initialization:

```
   SLresult result = SL_RESULT_SUCCESS;
    audioFormat_ = *sampleFormat;
    prepareAudioFormat(&format_pcm_, &audioFormat_);

    SLDataLocator_IODevice loc_dev = {SL_DATALOCATOR_IODEVICE,
                                      SL_IODEVICE_AUDIOINPUT,
                                      SL_DEFAULTDEVICEID_AUDIOINPUT,
                                      NULL };
    SLDataSource audioSrc = {&loc_dev, NULL };

    SLDataLocator_AndroidSimpleBufferQueue loc_bq = {
            SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE,
            NBUFFERS_QUEUE };

    SLDataSink audioSnk = {&loc_bq, &format_pcm_};

    const SLInterfaceID id[2] = {SL_IID_ANDROIDSIMPLEBUFFERQUEUE,
                                 SL_IID_ANDROIDCONFIGURATION};
    const SLboolean req[2] = {SL_BOOLEAN_TRUE, SL_BOOLEAN_TRUE};
    result = (*slEngine)->CreateAudioRecorder(slEngine,
                                              &recObjectItf_,
                                              &audioSrc,
                                              &audioSnk,
                                              2,id, req);
    SLASSERT(result);

    SLAndroidConfigurationItf inputConfig;
    result = (*recObjectItf_)->GetInterface(recObjectItf_,
                                            SL_IID_ANDROIDCONFIGURATION,
                                            &inputConfig);

    if (SL_RESULT_SUCCESS == result) {
        SLuint32 presetValue = SL_ANDROID_RECORDING_PRESET_UNPROCESSED;
        (*inputConfig)->SetConfiguration(inputConfig,
                                         SL_ANDROID_KEY_RECORDING_PRESET,
                                         &presetValue,
                                         sizeof(SLuint32));
    }

    result = (*recObjectItf_)->Realize(recObjectItf_, SL_BOOLEAN_FALSE);
    SLASSERT(result);
    if (result != SL_RESULT_SUCCESS) return;


    result = (*recObjectItf_)->GetInterface(recObjectItf_,
                    SL_IID_RECORD, &recItf_);
    SLASSERT(result);
    if (result != SL_RESULT_SUCCESS) return;

    result = (*recObjectItf_)->GetInterface(recObjectItf_,
                    SL_IID_ANDROIDSIMPLEBUFFERQUEUE, &recBufQueueItf_);
    SLASSERT(result);
    if (result != SL_RESULT_SUCCESS) return;


    result = (*recBufQueueItf_)->RegisterCallback(recBufQueueItf_,
                    bqRecorderCallback, this);
    if (result != SL_RESULT_SUCCESS) return;
    SLASSERT(result);

```

**Comment by ggfan** [comment]
For audio streams, they would like pick up the best one, even in AAudio, if app asks for frequency A(which may not be the native frequency), AAudio might create the stream with native frequency.  Not sure this is the same reason, I will take a look

**Comment by ggfan** [comment]
@tgrain, may you try it on your end -- for the mono, use 
  pcmFormat->channelMask = SL_SPEAKER_FRONT_LEFT;  // not use SL_SPEAKER_FRONT_CENTER

it actually is supposed to use FL for mono.   Our expert is willing to help once I get a repro., so I will also try hard to find a similar device ( there is no exact device as yours I could find ).  Thank you so much!

**Comment by ggfan** [comment]
It does not happen on Google devices, Samsung device ( that device only ) specific problem, but I am getting one device soon

**Comment by gkasten** [comment]
Thanks for checking.  In that case, we should contact the device manufacturer, and also improve the CTS testing.  A workaround could also be added to Oboe wrapper.  I filed a bug at Oboe for that. See
https://github.com/google/oboe/issues/181

**Comment by ggfan** [comment]
With Samsung J7 ( 2016 ) Android M,  I am unable to see the problem:
- adb shell dumpsys media.audio_flinger:  input is mono
- record and capture to file, file size shows the same fact: mono. 
@tgrain may you double check you really got 2 channels for input?

**Comment by ggfan** [comment]
closing this one, feel free to follow it up on [google/oboe #181](https://github.com/google/oboe/issues/181)

**Comment by tgrain** [comment]
@gkasten The problem occurred on this Samsung model only (the device of one of my users). In the meantime I do the audio capturing in the Java Android SDK not in the NDK anymore, this approach works on the user's device without a problem.
