### ISSUE TITLE
cpp code should conform to google c++ style guide

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#50]
We should run https://github.com/google/styleguide/tree/gh-pages/cpplint on travis to enforce [Google C++ Style guide](https://google-styleguide.googlecode.com/svn/trunk/cppguide.html)

**Comment by ggfan** [comment]
close: this is big task and do not bear too much fruit: good API sample really demonstrate how to use API is more useful thank anything else ( before the really good & useful API doc is born, the doc that developer read and could jump start coding)
