### ISSUE TITLE
force close on endless-tunnel

### ISSUE THREAD

**Issue by BuiTinh** [googlesamples/android-ndk#504]
Hello
I try running demo tunnel
when press button play
application force close 
03-07 16:54:18.877 622-647/com.google.sample.tunnel E/EndlessTunnel:Native: *** Vertex shader compilation failed.
03-07 16:54:18.877 622-647/com.google.sample.tunnel E/EndlessTunnel:Native: *** Getting info log for shader 4
03-07 16:54:18.877 622-647/com.google.sample.tunnel E/EndlessTunnel:Native: *** Info log:
                                                                            0:3: L0001: Expected identifier, found 'mediump'
03-07 16:54:18.877 622-647/com.google.sample.tunnel E/EndlessTunnel:Native: *** GAME ABORTING.
03-07 16:54:18.878 622-647/com.google.sample.tunnel A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 647 (e.sample.tunnel)
please help me.

**Comment by ggfan** [comment]
yeah, thanks: do not know why I out it into the wrong sequence and how that passed my own test last time. it should be fixed now.
