### ISSUE TITLE
Android Neural Netowrk API status on Pixel Visual Core active.

### ISSUE THREAD

**Issue by dimitryn** [googlesamples/android-ndk#512]
Hi , 
I am using Pixel 2 , 8.1 android .
Is there way to know if Pixel Visual Core enabled for NNAPI  ( some status )?
Thanks.

**Comment by ggfan** [comment]
Fact first:

- Android 8.1's NNAPI does not have Visual Core support
- Android P developer preview's NNAPI does have DSP support

There is no interface to report hardware acceleration status in NNAPI api: my guess was that if hardware is available, it will be turned on ( there is debugging way to turn it on and off from adb "I think" ) as long as the required driver/library are stable with good performance.
