### ISSUE TITLE
javac HelloJni.java error

### ISSUE THREAD

**Issue by XiaZiXi** [googlesamples/android-ndk#513]
i changed the directory to hello-jni,fo get hello-jni.h，i found the directory named hellojni,and i exec the command "javac HelloJni.java",and i get lots of errors 
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
HelloJni.java:18: 错误: 程序包android.support.v7.app不存在
import android.support.v7.app.AppCompatActivity;
                             ^
HelloJni.java:19: 错误: 程序包android.os不存在
import android.os.Bundle;
                 ^
HelloJni.java:20: 错误: 程序包android.widget不存在
import android.widget.TextView;
                     ^
HelloJni.java:22: 错误: 找不到符号
public class HelloJni extends AppCompatActivity {
                              ^
  符号: 类 AppCompatActivity
HelloJni.java:25: 错误: 找不到符号
    protected void onCreate(Bundle savedInstanceState) {
                            ^
  符号:   类 Bundle
  位置: 类 HelloJni
HelloJni.java:24: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
HelloJni.java:26: 错误: 找不到符号
        super.onCreate(savedInstanceState);
        ^
  符号:   变量 super
  位置: 类 HelloJni
HelloJni.java:31: 错误: 程序包R不存在
        setContentView(R.layout.activity_hello_jni);
                        ^
HelloJni.java:32: 错误: 找不到符号
        TextView tv = (TextView)findViewById(R.id.hello_textview);
        ^
  符号:   类 TextView
  位置: 类 HelloJni
HelloJni.java:32: 错误: 找不到符号
        TextView tv = (TextView)findViewById(R.id.hello_textview);
                       ^
  符号:   类 TextView
  位置: 类 HelloJni
HelloJni.java:32: 错误: 程序包R不存在
        TextView tv = (TextView)findViewById(R.id.hello_textview);
                                              ^
11 个错误
i can not understand why,what do i should do?i'm sorry about my english,thank you!!!

**Comment by ggfan** [comment]
The samples here meant to be compiled with Gradle ( Android Studio uses gradle ),so the command line would be at gradle level. I think it might be easier to use Android Studio IDE to see if it could give you a quick start. There is a [codelab](https://codelabs.developers.google.com/codelabs/android-studio-cmake/#0) for debugging, it would include more things you needed, but once you pass the compile stage with that codelab, you will know already how this works:
  https://codelabs.developers.google.com/codelabs/android-studio-cmake/#0

If you really want to compile from command line, you could do:

- cd hello-jni
- gradlew ( or gradlew.bat if on windows ) assembleDebug

By the way, Android Studio uses its own Java compiler ( one version of OpenJDK, I think ).

**Comment by ggfan** [comment]
may you look at the stackoverflow and see whether [this](https://stackoverflow.com/questions/21663423/generating-header-file-with-jni-using-javah) helps?

**Comment by XiaZiXi** [comment]
I solved the problem!I went to the directory "XXX/hello-jni/app/src/main/java",and run the command "javah -classpath . com.example.hellojni.HelloJni",and it generate a file named com_example_hellojni_HelloJni.h，that is what i want to get!!!!!!!

**Comment by XiaZiXi** [comment]
I am sorry,but i need your help.As you know,i get the head file,**and now i want to build a shared library.**
At the moment ,my jni paroject like this:
➜  hello-jni git:(master) ✗ tree
.
├── README.md
├── app
│   ├── build.gradle
│   ├── proguard-rules.pro
│   └── src
│       └── main
│           ├── AndroidManifest.xml
**│           ├── cpp
│           │   ├── Android.mk
│           │   ├── Application.mk
│           │   ├── CMakeLists.txt
│           │   ├── com_example_hellojni_HelloJni.h
│           │   └── hello-jni.c**
│           ├── java
│           │   └── com
│           │       └── example
│           │           └── hellojni
│           │               └── HelloJni.java
│           └── res
│               ├── layout
│               │   └── activity_hello_jni.xml
│               ├── mipmap-hdpi
│               │   └── ic_launcher.png
│               ├── mipmap-mdpi
│               │   └── ic_launcher.png
│               ├── mipmap-xhdpi
│               │   └── ic_launcher.png
│               ├── mipmap-xxhdpi
│               │   └── ic_launcher.png
│               ├── mipmap-xxxhdpi
│               │   └── ic_launcher.png
│               ├── values
│               │   ├── colors.xml
│               │   ├── dimens.xml
│               │   ├── strings.xml
│               │   └── styles.xml
│               └── values-w820dp
│                   └── dimens.xml
├── build
│   └── android-profile
│       ├── profile-2018-04-11-15-21-15-557.json
│       └── profile-2018-04-11-15-21-15-557.rawproto
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradle.properties
├── gradlew
├── gradlew.bat
├── screenshot.png
└── settings.gradle

21 directories, 31 files
In the cpp directory ,i make a Android.mk file,content is this ：
➜  cpp git:(master) ✗ cat Android.mk
**LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := libhellojni
LOCAL_SRC_FILES := hello_jni.c
LOCAL_C_INCLUDES +=$(call my-dir)
LOCAL_C_INCLUDES += $(JNI_H_INCLUDE)

include $(BUILD_SHARED_LIBRARY)**
And Application content is this:
➜  cpp git:(master) ✗ cat Application.mk
APP_ABI := all
And hello-jni.c is this:
#include <string.h>
#include <jni.h>
#include "com_example_hellojni_HelloJni.h"
JNIEXPORT jstring JNICALL
Java_com_example_hellojni_HelloJni_stringFromJNI( JNIEnv* env,
                                                  jobject thiz )
{
    return (*env)->NewStringUTF(env, "Hello from JNI !  Compiled with ABI " ABI ".");
}
And the com_example_hellojni_HelloJni.h file is this:

#include <jni.h>
#ifndef _Included_com_example_hellojni_HelloJni
#define _Included_com_example_hellojni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_HelloJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_HelloJni_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hellojni_HelloJni
 * Method:    unimplementedStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_HelloJni_unimplementedStringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
And in the cpp directory , i run this command "ndk-build NDK_PROJECT_PATH=. **APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk**",but i get a error
## **make: *** No rule to make target `hello_jni.c', needed by `obj/local/arm64-v8a/objs/hellojni/hello_jni.o'.  Stop.**,i don't know why i get the error,thank you !

**Comment by ggfan** [comment]
seems ok, just the file name is mis-spelled. it is hello-jni.c ( dash or underscore ).

**Comment by ggfan** [comment]
Also could you kind avoid doing this manually and let tools do it for you? the purpose for the tool is

- you write your java code
- java code calls into native code for some purposes like acceleration os use existing libs
- so you decide what function name you want to use ( jni function names ) inside your Java source code, and put native prototype there in the Java source code.
- then, put your mouse (cursor ) on the native function name inside java file; after the pop-up menu comes up, select/click on "generate jni functions".  The tool will create the correct C function prototype with the right parameter types for you. you do not have to use javah, javac etc on command line.
- from here you are purely in C/C++ land, do whatever you want as C/C++ programmers do normally (calling to other C/C++ libs etc )

the Gradle and ndk-build combination examples is here in the "[master-ndkbuild](https://github.com/googlesamples/android-ndk/tree/master-ndkbuild)" branch. Either Android.mk or cmakelists.txt, no need to be both at the same time, I think.

**Comment by XiaZiXi** [comment]
I made a so low-level mistake,now i generate the dynamic libraries!I just started learning the android and ndk development,before i just learn some c++,i  know the portability of the IDE tool,so much so that I want to find out the probably process behind.After this time,i will use Android Studio.Thanks again!

**Comment by ggfan** [comment]
Everyone makes typos, it is normal.  Glad you got what you wanted: your persistence helped :-). Keeps on exploring, and dig deep to understand things inside out is great thing to possess! Do not hesitate to create Pull Requests in  the future to help fix bugs in this repo.
