### ISSUE TITLE
can't operate with 2.3.3

### ISSUE THREAD

**Issue by FlashPanda** [googlesamples/android-ndk#514]
![image](https://user-images.githubusercontent.com/29620260/38847002-e6d4d70a-4231-11e8-9ab4-b2c0e44a7785.png)
My android studio version is 2.3.3. Then I modified the classpath to 2.3.3, another problem came.
![image](https://user-images.githubusercontent.com/29620260/38848120-ebedc318-4237-11e8-9f08-643e9a544f49.png)
Any idea?

**Comment by FlashPanda** [comment]
The project is hello-jni.

**Comment by ggfan** [comment]
The sample needs to use android studio [3.0.1+](https://developer.android.com/studio/index.html) to open.  do you have to use 2.3.3 version? ( or it is due to the readme.md here was old?)

**Comment by ggfan** [comment]
If you have to use 2.3.3, [this](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html) might help -- just need to do the reverse actions.  For the error "implementation", change it to "compile" would be it, then other errors will emerge (gradle version etc ).
