### ISSUE TITLE
using cpp to read file failed

### ISSUE THREAD

**Issue by cs123951** [googlesamples/android-ndk#517]
I use `ifstream in(filename);` to read file in my cpp code,  the filename refers to the path in my android phone,  `in` returned false, I checked that I did have `filename `in my phone.

Is it possible to use this method to read file from android?
If possible, why `in` return false?

Thanks

**Comment by ggfan** [comment]
this would be a guess: in logcat, do you see any permission errors? ( or you check to make sure you have requested write access at run-time ). In one sample, tried to use the C to do I/O once [here](https://github.com/googlesamples/android-ndk/blob/master/audio-echo/app/src/main/cpp/debug_utils.cpp#L72), seems to be ok once requested access right.

**Comment by cs123951** [comment]
Permission is the cause!
Thank you very much!!
