### ISSUE TITLE
Some errors when build audio-echo and native-audio

### ISSUE THREAD

**Issue by GReaper13** [googlesamples/android-ndk#519]
Hello. I have some errors when build audio-echo and native-audio, sorry because i'm start to learn NDK android. I cloned audio-echo and have an error in audio_main.cpp: Can't resolve AudioQueue, and native-audio have an error in native-audio-jni.c: Expression expected at "static const char android[] =#include "android_clip.h"; . Both of them are have an error in MainActivity: Cannot resolve corresponding jni function at all native function. Sorry because my English is limited. Thank you.

**Comment by ggfan** [comment]
Are you using Android Studio to build? if Android Studio to build C/C++ is new to you, this [codelab](https://codelabs.developers.google.com/codelabs/android-studio-cmake/index.html?index=..%2F..%2Findex#0) might be helpful for environment setup. After your environment set up correctly, you could try to open those audio projects from Android Studio. Use the [latest Android Studio](https://developer.android.com/studio/) is good.

I am guessing that you need to install CMake and NDK from Android studio, then you could open the project ( NOT import the project anymore, Android Studio Version 3.0.0+ changed a little bit )

Please update if you still have trouble after that.

**Comment by sharmavishal914** [comment]
I have installed CMake and NDK and build my project with CMake using Android Studio Version 3.1.1 and target version 27, but still facing this issue "Can't resolve AudioQueue" in files (audio_main.cpp, audio_player.cpp and audio_recorder.cpp).

**Comment by ggfan** [comment]
you changed these 2 lines to 27:

- [compileSdkVersion 25](https://github.com/googlesamples/android-ndk/blob/master/audio-echo/app/build.gradle#L4)
- [targetSdkVersion 25](https://github.com/googlesamples/android-ndk/blob/master/audio-echo/app/build.gradle#L14)

probably also the appcompat inside app/build.gradle, correct? The file should be there: [buf_manager.h](https://github.com/googlesamples/android-ndk/tree/master/audio-echo/app/src/main/cpp), could you check your app/src/main/cpp directory?

even you do not change anything( clone it again ), would you be able to build?  Thanks

**Comment by sharmavishal914** [comment]
Yes, i changed inside app/build.gradle and I rebuild the project too with old version. The weird thing is, when i am in the Project view inside Android studio app/src/main/cpp directory in this path **buf_manager.h** file is there but in Android view this file isn't there and i am a newbie in this i had followed all the steps that are mentioned in the docs and the file that you have mentioned in "codelab".
Thanks

**Comment by ggfan** [comment]
It is known bug of the IDE: only the header files that have equivalent source files( .c, .cpp, ...) could be displayed inside Android View.  It is an annoying issue for C/C++ developers. But you could build the project though, correct?

**Comment by sharmavishal914** [comment]
Yes, project build is successful all the time. At run time i am getting error, (Audio Queue not found) not able to run the app.

**Comment by sharmavishal914** [comment]
With the above steps i am able to run the build successfully but all the native methods aren't imported yet, i assume that's why App is running but nothing is working. Thanks

**Comment by ggfan** [comment]
may you kindly open a new bug and outline your steps, and the error you got?
build other samples like ( hello-jni ) first and see it is working, then try this audio-echo one: increase the volume when you are running it... but yeah do paste the error message. thanks

**Comment by sharmavishal914** [comment]
I just added this code in my gradle 
ndk {
                moduleName "echo"
                // Link with these libraries!
                stl "stlport_shared"
            }
It started working. i don't know how, but still native methods aren't imported yet and (Audio Queue not found) but App is working perfectly fine.
