### ISSUE TITLE
version of gradle wrapper too low to build from command line with java 9 or newer

### ISSUE THREAD

**Issue by mschwaig** [googlesamples/android-ndk#522]
The gradle wrapper files which ship with these examples are not compatible with java 9 or newer, since gradle cannot handle the java version string.

This is the resulting error on Ubuntu 18.04 right now, which ships with openjdk 10:

```
mschwaig@zbox:~/Documents/android-ndk/hello-jni$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```
Other projects are also having this issue:
https://github.com/facebook/react-native/issues/16536

To fix build support form the command line the version inside all `gradle-wrapper.properties` files should be updated to at least 4.3. I believe when using Android Studio this is less of an issue as Android Studio will suggest to update the version for you.

**Comment by mschwaig** [comment]
I think there is another issue blocking this anyway, as the whole Android SDK seems to not work with java 9 or 10 out of the box.
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by ggfan** [comment]
thanks for bring it and "thinking about this place" :-).  Yeah Trevor told me that, yeah we are on 8, not 9, not 10.
