### ISSUE TITLE
player callback not entered

### ISSUE THREAD

**Issue by sigmark14** [googlesamples/android-ndk#526]
I use this sample code for real time playing & recording. But I found it weird that when I set audio recorder's state to recording, then play callback not longer entered. Need help. Thanks.

**Comment by sigmark14** [comment]
I follow audio-echo sample and made my own. In some devices, I cannot enter into player callback while recorder state set to recording. Is it a thread issue? Maybe I can try the oboe interface. Also may I know which api would prevail in the future?

**Comment by ggfan** [comment]
+@dturner for policy question. ( Oboe should be there in the future, Oboe wraps OpenSL ES or AAudio )

The recording callback and player callback are in different threads and they autonomous(this "autonomous" thing is also the thing that makes app's life a little harder ); make sure they have a buffer when there is a callback happening from either thread. Then your app should be ok to see both callbacks happen regularly. If you app does not provide a buffer at the callback, and playback / recording uses up all available buffers you provided before, yeah, then there is no callback anymore. Not sure this is your symptoms

also depends on the device + OS, the behavior varies too: I think for Oboe, we could spend time on it. If your project is not that urgent, you could share your code somewhere. Again debugging this could be interesting at the minimum.

**Comment by sigmark14** [comment]
@ggfan I can run my app on most of the devices, so I think it's device + OS issue. I will spend some time on Oboe. Thanks for the information.
