### ISSUE TITLE
android gradle experimental plugin 0.11.1 disappeared from jcenter

### ISSUE THREAD

**Issue by igagis** [googlesamples/android-ndk#528]
I was using android gradle experimental plugin version 0.11.1 some time ago and it was working good for me. But recently I discovered that it was removed from jcenter reprository, so gradle sync gives error:

```
Could not find com.android.tools.build:gradle-experimental:0.11.0.
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/build/gradle-experimental/0.11.0/gradle-experimental-0.11.0.pom
    https://jcenter.bintray.com/com/android/tools/build/gradle-experimental/0.11.0/gradle-experimental-0.11.0.jar
Required by:
    project :
```

Although, I can confirm that plugin version 0.9.3 is still there, but I need 0.11.1.

Why was 0.11.1 removed from jcenter()? When can I expect a newer version of it available?

**Comment by ggfan** [comment]
have to wait for Xav for more info.

**Comment by alexcohn** [comment]
FWIW, you can get it from https://mvnrepository.com/artifact/com.android.tools.build/gradle-experimental

**Comment by igagis** [comment]
It looks like it is available in `google` repository:
https://mvnrepository.com/artifact/com.android.tools.build/gradle-experimental?repo=google

But how do I use it from my gradle script?
My current `build.gradle` looks like this:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle-experimental:0.11.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

So, it seems it uses `jcenter` now...

**Comment by igagis** [comment]
Ok, I found I can do it like this:

```
repositories {
        jcenter()
        maven {
            url "https://maven.google.com/"
        }
    }
```

So, problem solved

**Comment by ggfan** [comment]
ok, thanks. in that case just add [`google()`](https://github.com/googlesamples/android-ndk/blob/master/camera/build.gradle)to it.

**Comment by gongzelong0718** [comment]
I downloaded com.android.tools.build:gradle-experimental:0.11.1, does anyone know where to put them?

gradle-experimental-0.11.1.jar
gradle-experimental-0.11.1.pom

**Comment by igagis** [comment]
you didn't have to download it manually, just add a dependency on it to your `build.gradle` as in https://github.com/googlesamples/android-ndk/issues/528#issuecomment-390410277
but along with `jcenter()` add also a new line with `google()` and that's it.
