### ISSUE TITLE
all samples should use c++ and the same version of the stl

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#53]
```
android-ndk 🍊  find .  | grep '\.c$'
./bitmap-plasma/app/src/main/jni/plasma.c
./gles3jni/app/src/main/jni/gl3stub_wrapper.c
./hello-jni/app/src/main/jni/hello-jni.c
./native-activity/app/src/main/jni/main.c
./native-audio/app/src/main/jni/native-audio-jni.c
./native-media/app/src/main/jni/native-media-jni.c
./native-plasma/app/src/main/jni/plasma.c
./san-angeles/app/src/main/jni/demo.c
```

**Comment by freestyletime** [comment]
Both are okay.

**Comment by ggfan** [comment]
there are some subtitles between accessing JNI structures from C and C++, we might keep our coverage to be some C++, some C.

I will look at the ones that currently are C++ and standardize them with the same stl and clang toolchain
then go from there

**Comment by ggfan** [comment]
The score of this change would be:
1) c++_static and toolchain=clang for projects:
    ./audio-echo/app/src/main/jni/audio_player.cpp
    ./endless-tunnel/app/src/main/jni/android_main.cpp
    ./gles3jni/app/src/main/jni/gles3jni.cpp
    ./hello-gl2/app/src/main/jni/gl_code.cpp
    ./hello-thirdparty/app/src/main/jni/main.cpp
    ./MoreTeapots/app/src/main/jni/Common/ndk_helper/interpolator.cpp
    ./native-activity/app/src/main/jni/main.cpp
    ./native-codec/app/src/main/jni/looper.cpp
    ./sensor-graph/app/src/main/jni/sensorgraph.cpp
    ./Teapot/app/src/main/jni/Common/ndk_helper/gestureDetector.cpp
2. use source code inside NDK wherever applicable [avoid source code copy]
    native_activity source will be removed and a gradle project using that source will be added instead in the place it is used

**Comment by ggfan** [comment]
code merged, closing this one
