### ISSUE TITLE
NDK 17 cannot find -landroid_support

### ISSUE THREAD

**Issue by igagis** [googlesamples/android-ndk#530]
I'm trying to build my App which has native code using `NDK 17` and I get the following linker error:

```
C:\Users\ivan.gagis\AppData\Local\Android\Sdk\ndk-bundle\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld: cannot find -landroid_support
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
```

here are the actual command line options:

```
-shared
-Wl,-soname,libmordavokneapp.so
-o
... //list of object files
-Wl,--no-undefined
-Wl,-z,noexecstack
-Wl,-z,relro
-Wl,-z,now
-Wl,--warn-shared-textrel
-Wl,--build-id
-LC:\\Users\\ivan.gagis\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\sources\\cxx-stl\\llvm-libc++\\libs\\arm64-v8a
-lc++_shared
-LC:\\Users\\ivan.gagis\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\sources\\cxx-stl\\llvm-libc++\\libs\\arm64-v8a
-landroid_support
-gcc-toolchain
C:\\Users\\ivan.gagis\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\aarch64-linux-android-4.9\\prebuilt\\windows-x86_64
-target
aarch64-none-linux-android
-landroid
-llog
... //list of my custom libraries
-lc++
--sysroot=C:\\Users\\ivan.gagis\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\platforms\\android-21\\arch-arm64
-LC:\\cygwin64\\home\\ivan.gagis\\arithmetic-game\\android\\app/build/ndkLibs/arm64-v8a
```

Before I was using `NDK 15c` and it was working OK. But in `17` there were some changes, like unified headers, so I had to resolve some issues by adding additional include paths. But then I stuck with this linker error. I do not explicitly add linkage against `libandroid_support`, so it adds it to command line options imlicitly for some reason.
Searching the NDK directory tree for `libandroid_support*` gave that there are only 2 files:

```
c:\Users\ivan.gagis\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a\libandroid_support.a
c:\Users\ivan.gagis\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\llvm-libc++\libs\x86\libandroid_support.a
```

So, there is no version for `arm64`.

And I'm using `experimental gradle plugin 0.11.1`.

Any idea what's wrong?

**Comment by ggfan** [comment]
+@jomof, experimental  plugin could not support unified headers out of the box. It is mainly up to your own  if you like to use the latest NDK with Gradle experimental plugin.

For your purpose, may you copy the same lib from NDK 16 ( you need to download it ) to your NDK 17 directory, and see if this is the only problem you will have for your project?

**Comment by igagis** [comment]
@ggfan actually, as I could understand, the `libandroid_support.a` is not needed at all for `arm64`, so the problem is that the plugin adds `-landroid_support` option automatically, when it should not. Any idea how I can prevent it from adding the option?

**Comment by ggfan** [comment]
I got no clue for that: I probably will download the source to see where it is added inside experimental plugin. will see

**Comment by igagis** [comment]
Reading this blog post:
https://android-developers.googleblog.com/2017/09/introducing-android-native-development.html

I could understand that on newer platforms (version 21+) the `libandroid_support` is not needed, and I assume all `arm64` platforms belong to those *newver* platforms.

**Comment by ggfan** [comment]
probably "newer" means the NDK version, not the Android OS version as that is orthogonal to NDK's version.

**Comment by ggfan** [comment]
@igagis: [this line](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/ndk/NdkR12StlSpecificationFactory.java#44) probably contributed to the fact you saw; but it does not solve your problem -- I do not know how to overwrite it on command line: -Xlinker --exclude-libs android_support does not work for me :-(.

**Comment by igagis** [comment]
@ggfan that line seems to be about `static` STL, but I'm using `c++_shared`. And version is the version of the platform, not NDK. In `build.gradle` for example I have `platformVersion = 21` in the `ndk{}` section. I understand that it is because older platforms did not provide all what `libc++.so` needed, so `libandroid_support` was backporting the needed parts, but starting from 21 everything is right in `libc++.so`, so `libandroid_support` is not needed.

I have put 'libandroid_support.a` files to

```
c:\Users\ivan.gagis\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a\libandroid_support.a
c:\Users\ivan.gagis\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\llvm-libc++\libs\x86\libandroid_support.a
```

with the following contents of the files:

```
INPUT(-lc++)

```

Now linker treats those as `linker script` and just adds another `-lc++` option to the command line which does no harm as it seems. Ugly workaround, and I haven't tested yet if generated binaries actually work.

**Comment by igagis** [comment]
Ok, I confirm that the generated binary is working.

**Comment by igagis** [comment]
in which version of experimental plugin is this fixed?

**Comment by ggfan** [comment]
It hard to guess any code change / support for experimental plugin in any time.

**Comment by nick-scape** [comment]
For anyone else coming here with this problem NDK 18b on linux. My problem was the cmake file was somehow trying to link with the ndk 16b which I had in the same directory. Removing previous versions of the NDK solved it for me.
