### ISSUE TITLE
want to know the format of model_data.bin in android-ndk/nn_sample/app/src/main/assets

### ISSUE THREAD

**Issue by KristinHuangGH** [googlesamples/android-ndk#531]
Hi,
I am studying the nn_sample project.
I need to know the format of model_data.bin in android-ndk/nn_sample/app/src/main/assets.
Is there any tool to produce the model_data.bin?
Or how could we do to produce the file model_data.bin after we do the training by tensorflow/tensorflow lite?
Could you please help me?
Thank you very much!

**Comment by ggfan** [comment]
The bin file is not a model: just 1 binary file of the values of 0.5f ( totally 200 x 2 = 400):
   this is to emulate the weights in the normal model ( but the file is not the model )
referring to the [readme file](https://github.com/googlesamples/android-ndk/tree/master/nn_sample),  basically it does (tensor1 + 0.5 ) ( tensor3 + .5), those .5 values are loaded from the bin file.

tensor depth is 200 (TENSOR_SIZE), tensor0 uses the first 200 0.5f values, tensor2 consumes the second part of the file ( 200 of .5f values ).
The file is binary format, you could open it with hexedit to have a look. you could use whatever ways to generate a binary file of 400 .5f values. All of this are inside source code.

Probably you already know that NNAPI, at this level, has no interface to deal a pre-trained model and load it directly: that needs to be done by your application:

- App creates its own representation of its model ( train, save, re-train etc )
- App TRANSLATEs its own model into NNAPI's model and create's NNAPI's model in memory at run-time
- If there is any training happening, App will save to its own model format, re-creates NNAPI's model at run time
- The model format ( in file on the disk or network ) is not in NNAPI interface's scope.

your app will build another layer to translate your-own model representation on disk, into NNAPI's models. TFlite does that so your app does not have to re-create the functionality.
