### ISSUE TITLE
Sample Buffer Controls

### ISSUE THREAD

**Issue by alexd555** [googlesamples/android-ndk#536]
Hi,
Could you explain meanings of  ?
```
#define RECORD_DEVICE_KICKSTART_BUF_COUNT   2
#define PLAY_KICKSTART_BUFFER_COUNT         3
#define DEVICE_SHADOW_BUFFER_QUEUE_LEN      4
#define BUF_COUNT                           64
```

**Comment by ggfan** [comment]
sure
- RECORD_DEVICE_KICKSTART_BUF_COUNT: how many buffers to send down to recorder before kickoing start the recorder
- PLAY_KICKSTART_BUFFER_COUNT: how many recorded buffers needed before starting player ( essentially, it is how many recorder callbacks app needs to see before kicking start player )
- DEVICE_SHADOW_BUFFER_QUEUE_LEN: the capacity of the device shadow queue. In OpenSLES, [SimpleBufferQueue](https://android.googlesource.com/platform/system/media/+/gingerbread/opensles/include/SLES/OpenSLES_Android.h#185) is a pipe in the sense : for player, app pushes in, audio driver pops out; it does not keep track of the buffers for app. So app needs to keep track of those buffers, that is the shadow queue about ).
- BUF_COUNT: how many buffers to allocate. Meaning how many buffers could accumulate between recording  & playback devices. The bigger the number, potentially the more delays; on the other hand it does tolerate more glitches between recorder callback and player callback out of sync issue )
