### ISSUE TITLE
Meanings of Queues

### ISSUE THREAD

**Issue by alexd555** [googlesamples/android-ndk#537]
AudioQueue *freeQueue_;         // user
    AudioQueue *recQueue_;          // user
    AudioQueue *devShadowQueue_;    // owner

play and rec contain audio. What is goal of other queues ?

**Comment by ggfan** [comment]
Conceptually: 
```
  Recorder --> recQueue_ --> Player;  Player --> freeQueue_ -->Recorder
 ```                   
devShadowQueue_: keep track of the buffers for SimpleBufferQueue interface. There are 2: player and  audio driver, recorder and audio driver.

Application creates all of the queues.
