### ISSUE TITLE
what is the model_data.bin?  (android-ndk/nn_sample)

### ISSUE THREAD

**Issue by xiaoyaozhuzi** [googlesamples/android-ndk#538]
How to produce model_data.bin?

**Comment by ggfan** [comment]
this might help: https://github.com/googlesamples/android-ndk/issues/531:
in reality your model would be generated by your learning application.  This one is just a file of 0.5 float value, It could be created with simple code like:
```
#include <iostream>
#include <fstream>

int main() {
  float val = 0.5f;
  std::ofstream out("model_data.bin", std::ios_base::binary);
  for ( int i =0; i < 400; i++)
    out.write((char *)&val, sizeof(float));
  
  out.close();
  
 return 0;
}
```

**Comment by xiaoyaozhuzi** [comment]
Why the model_data.bin is 320000 Byte，400 float is 1600 Byte？What's the rest of it？

**Comment by ggfan** [comment]
Install HexEdit, open the file, you would be find out everything in it.  at this level, HexEdit is your friend and it will be needed often.
