### ISSUE TITLE
"native-audio" sample doesn't show all buttons

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-ndk#539]
This is what the IDE shows about the layout of the sample app "native-audio" ([here](https://github.com/googlesamples/android-ndk/tree/master/native-audio)) :

![image](https://user-images.githubusercontent.com/5357526/41817405-33b41076-77a3-11e8-8671-0f937901eedc.png)

And yet this is what I see when I run it (tested on Pixel 2 with Android P DP3 ) :

![image](https://user-images.githubusercontent.com/5357526/41817407-47728c0a-77a3-11e8-8a86-d6672998d244.png)

**Comment by ggfan** [comment]
Yeah there is a bug that does not play the http: linked file, so some of those buttons disabled: the internal bug was not proceeding, I have not get my time to trace that one yet. It has been for a long while...  if you could, please move to oboe, support is higher there

**Comment by AndroidDeveloperLB** [comment]
@ggfan What's "oboe" ?

**Comment by ggfan** [comment]
[oboe](https://github.com/google/oboe) is a new open source lib, wrapping Android AAudio  and OpenSLES; easier to handle.

**Comment by AndroidDeveloperLB** [comment]
I see. When was oboe talked about ? Are there lectures of Google about it?
BTW, the buttons aren't disabled. They are gone.

**Comment by ggfan** [comment]
Oboe has been there for a while ( got to be more than a year ).  Docs are on its github page, Don's talk is [here](https://www.youtube.com/watch?v=Pjgfje52Yv0). It is pretty active there on the github, if you want some features, feel free to notify there.

**Comment by AndroidDeveloperLB** [comment]
Thank you!

**Comment by AndroidDeveloperLB** [comment]
The video about it mostly talk about reducing latency.
Also, they said they will publish Midi sample, but I don't think they did:
https://youtu.be/Pjgfje52Yv0?t=2461
Anyway, since what I'd like is just about audio recording, I've written about it here:
https://github.com/google/oboe/issues/135

**Comment by ggfan** [comment]
yeah, that is the good place to file it. Don is pretty quick on that repo. When I get the time, I will also look at that ( it is interesting to look at the containers )

**Comment by AndroidDeveloperLB** [comment]
So this repository is in deprecated mode?
If AAudio is new, why not put a sample to it, here too?
It requires NDK too, no?
Sorry for all the questions. I'm very new to this, and I haven't even written in C/C++ for ages (Mostly Java and Kotlin). Even when I did have the time to mess around with C/C++ on Android, I made just a small repository for it ([here](https://github.com/AndroidDeveloperLB/AndroidJniBitmapOperations)), which for some reason became a bit popular.

**Comment by ggfan** [comment]
For Audio, yeah, like to fade out from this repo.

AAudio was released with Android O, it is C interface, so it is exposed via NDK.  AAudio does have its [own place](https://github.com/googlesamples/android-audio-high-performance). Starting with [Oboe](https://github.com/google/oboe) for your new projects would be good for the long run as we are pretty much heavy ( if not all ) on Oboe. New Audio API samples will not coming here for sure, and probably video and graphics new samples not coming here either

**Comment by AndroidDeveloperLB** [comment]
You have some cool new features/libraries to show on video/graphics too?

**Comment by ggfan** [comment]
Vulkan 1.1 enabled video texture, could be a good helper for apps using camera input as texture. That is coming out with Android P with [android hardware buffer extension](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_ANDROID_external_memory_android_hardware_buffer). 

Congratulations to your repo!

**Comment by AndroidDeveloperLB** [comment]
Sadly Vulkan has serious issues:
1. Not supported on most Android versions
2. A very new API, meaning less places to read about and even less samples, and yet requires to learn from scratch.

I don't get why Google doesn't just publish a gaming library that will support all Android versions, and use Vulkan/OpenGL under the hood. Make it available for all, using Java/Kotlin.
The current situation only makes third party engines more attractive to developers than what Google offers, because why waste time and effort on something that others will work hard to generalize...
Only die hard developers would develop straight in Vulkan.

That's how I feel from OpenGL 2. I learned OpenGL 1 in the past, but it has gone so different on version 2 that I had a hard time to study it on my own. Not because I need it, but because I wanted, as I was curious. 
But the more this field changes with more and more APIs and languages, the less I think it's attractive to develop straight in it, instead of using engines that are dedicated to use the best of each...

Thank you about the repository. I have others too ([here](https://github.com/AndroidDeveloperLB?tab=repositories)), and I also make some tiny spare time apps ([here](https://play.google.com/store/apps/developer?id=AndroidDeveloperLB))

**Comment by AndroidDeveloperLB** [comment]
Thank you!
