### ISSUE TITLE
"native-audio" sample doesn't really record anything?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-ndk#540]
About the "native-audio" sample ([here](https://github.com/googlesamples/android-ndk/tree/master/native-audio)) I tried to press "Record", say something, and then press on "Playback", but it didn't do anything.

How to play the recorded sound after pressing on "Record" button? Where's the part that stops recording? And to which file does it record to?

**Comment by ggfan** [comment]
yeah, might be something wrong then. Did tried it on pixel phone + android P preview, seems that it still works with this combination ( I needed to increase the volume when playing back ).

Once press the "record" button, speak to it for 5 seconds, then playback; it should repeat for 3 times. It records the things into [memory](https://github.com/googlesamples/android-ndk/blob/master/native-audio/app/src/main/cpp/native-audio-jni.c#L106), not writing out to disk:
```
#define RECORDER_FRAMES (16000 * 5)
static short recorderBuffer[RECORDER_FRAMES];
static unsigned recorderSize = 0;
```
this sample has been here from the very early generations, might be better to go [oboe](https://github.com/google/oboe).

**Comment by AndroidDeveloperLB** [comment]
@ggfan Oh I see. It does work.
Can you please show how to record to file, though?

**Comment by ggfan** [comment]
if it is just for this short of time of PCMs, you could directly use write() to write the whole buffer out in one shot (make sure to request disk write access in AndroidManifest.xml and at run time ); if recording long files, that would need a queue between recording callback and the file writing thread.  File writing is not much interesting part, just some small portion of writing it in[ debugging code](https://github.com/googlesamples/android-ndk/blob/master/audio-echo/app/src/main/cpp/debug_utils.cpp#L53); you would choose to use CPP equivalent stream functions if you do it -- just for more fun of it. :-)

**Comment by AndroidDeveloperLB** [comment]
Writing directly doesn't make a valid audio file.
Isn't there a way to set a file format for it to record to?
Or do I need to prepare it myself, similar to [here ](https://gist.github.com/kmark/d8b1b01fb0d2febf5770) ?

**Comment by ggfan** [comment]
yeah, you are right. you will need to prepare yourself for headers or compressing before writing it. Now I realize what you mean by writing files, yeah, you will need to prepare headers etc yourself.

**Comment by AndroidDeveloperLB** [comment]
Is there a way to overcome this without reading hundreds of pages of how to save to audio files (their format), and without spending hours over hours of figuring why the compression didn't work as it should?

Can you please put a sample of saving even to the simplest form of audio file (probably wav) ?

**Comment by ggfan** [comment]
this is followed up with https://github.com/google/oboe/issues/135, closing this one
