### ISSUE TITLE
camera sample crashes during device rotation

### ISSUE THREAD

**Issue by philip-lamb** [googlesamples/android-ndk#543]
Device: LG G5 (RS988)
Android: 7.0
Android Studio 3.0.1

Build "camera" NDK sample, target "basic", config debug. Launch on device in portrait mode. Rotate device to landscape. Observe crash.

**Comment by ggfan** [comment]
thank you for the report. I may not able to get to this immediately. If you get chance to debug inside IDE, please get failing points.

**Comment by ggfan** [comment]
Something wrong with the code about the popup window usage, not really camera API related.  I will find time to hack on it later; if you have a good handle on UI, please send a PR, thanks!

**Comment by simonprovost** [comment]
I have same crash, @ggfan Do you fixed ? because i saw that you closed it. When i downloaded the sample it is a crashed when i want to rotate the device (last android ndk release).

**Comment by ggfan** [comment]
yeah, there is a code change to "ignore" the exception, you probably find anther issue?
