### ISSUE TITLE
Error:FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':app:externalNativeBuildDebug'. > Build command failed.

### ISSUE THREAD

**Issue by huashizhoujielun** [googlesamples/android-ndk#549]
Hi 
When i try to build the sample project with gradle, it fail and here the error message 
`Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process D:\androidSDK\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\android-ndk-master\other-builds\ndkbuild\hello-libs\app\Android.mk NDK_APPLICATION_MK=D:\android-ndk-master\other-builds\ndkbuild\hello-libs\app\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/android-ndk-master/other-builds/ndkbuild/hello-libs/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\android-ndk-master\other-builds\ndkbuild\hello-libs\app\build\intermediates\ndkBuild\debug\lib D:/android-ndk-master/other-builds/ndkbuild/hello-libs/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/libhello-libs.so}
  [x86_64] "Compile++      ": "hello-libs <= hello-libs.cpp"
  process_begin: CreateProcess(NULL, D:/androidSDK/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/android-ndk-master/other-builds/ndkbuild/hello-libs/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/hello-libs/D_/android-ndk-master/hello-libs/app/src/main/cpp/hello-libs.o.d -gcc-toolchain D:/androidSDK/ndk-bundle/build//../toolchains/x86_64-4.9/prebuilt/windows-x86_64 -target x86_64-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O0 -UNDEBUG -fno-limit-debug-info -ID:/android-ndk-master/hello-libs/distribution/gmath/include -ID:/androidSDK/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -ID:/android-ndk-master/hello-libs/distribution/gperf/include -ID:/androidSDK/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -ID:/android-ndk-master/other-builds/ndkbuild/hello-libs/app -std=c++11 -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security --sysroot D:/androidSDK/ndk-bundle/build//../sysroot -isystem D:/androidSDK/ndk-bundle/build//../sysroot/usr/include/x86_64-linux-android -c D:/android-ndk-master/hello-libs/app/src/main/cpp/hello-libs.cpp -o D:/android-ndk-master/other-builds/ndkbuild/hello-libs/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/hello-libs/D_/android-ndk-master/hello-libs/app/src/main/cpp/hello-libs.o, ...) failed.
  make (e=2): ?????????????????
  make: *** [D:/android-ndk-master/other-builds/ndkbuild/hello-libs/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/hello-libs/D_/android-ndk-master/hello-libs/app/src/main/cpp/hello-libs.o] Error 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
`

How can i solve this?
Thank!!!

**Comment by ggfan** [comment]
taking a look at it.

**Comment by ggfan** [comment]
tried on my work place windows 10, AS 3.1.3, it is ok to build.

you will have to hack on it: from the info provided, not much could follow up:

- test out your android-studio environment is set up correctly: create a hello-jni template project
- build the hello-jni from  other-builds\ndkBuild\hello-jni
- sometimes, I would directly use ndk-build on command line to build binaries to root out gradle layer with
```
 cd your-project-cpp-dir ( ...\other-builds\ndkbuild\hello-libs\app )
  your-ndk-dir\ndk-build NDK_APPLICATION_MK= .\Application.mk NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=.\Android.mk
```
please be reminded that my use of ndk-build here is not typical in that I want to share the same C/C++ source code used for CMake.  [This](http://web.guohuiwang.com/technical-notes/androidndk1) page might be useful to get some good understanding of ndk-build.

**Comment by huashizhoujielun** [comment]
@ggfan I just updated my AS from 3.0.3 to 3.1.3 
but it still fail to build the sample project and it hold the same error message.
I read the error message again and find the command line argument NDK_PROJECT_PATH=null ,
maybe that is the reason.
I will try again later.

**Comment by ggfan** [comment]
that one is always set to null when gradle invoking it, should not be the problem. Then go to command line to build it directly with ndk-build, see how it goes

**Comment by huashizhoujielun** [comment]
Well
it works after reinstalling NDK ......
XD
Thanks for your helping!!!

**Comment by ggfan** [comment]
cool.
