### ISSUE TITLE
native-media sample missing external storage permission

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#55]
#### Please describe the problem in detail, with the following information (if applicable)
- Host OS: Fedora 21 x86_64
- SDK tools version (available in the "About" section of the 'android' tool
UI):
- Eclipse version: Luna
- ADT plug-in version:
- Platform targeted by your project: Nexus 7 2013
- Version of the platform running in the emulator: not running emulator

#### STEPS TO REPRODUCE:
1. build native-media sample app
2. run it on attached Nexus 7 2013
3. click Start Java Media Player

#### EXPECTED RESULTS:

see video play

#### OBSERVED RESULTS:

app crashes

#### ADDITIONAL INFORMATION:

In LogCat I see:
```
01-07 11:24:22.355: E/NativeMedia(11232): IOException java.io.FileNotFoundException: /sdcard/NativeMedia.ts: open failed: EACCES (Permission denied)
```
Adding android.permission.READ_EXTERNAL_STORAGE to manifest, then rebuilding, and 
re-running fixes the problem.

**Comment by jpshelley** [comment]
Currently READ_EXTERNAL_STORAGE is added to the manifest and its not working for me.

**Comment by ggfan** [comment]
with today's pull, we are playing from app/src/main/assets/clips, not from /sdcard/*  anymore.  so this should be automatically fixed. 

the native_player is disabled for now, will enable it after some deep debugging and fix. 

check it out, if still happens to you, re-open it.
