### ISSUE TITLE
Does the .so file create every time you compile? 

### ISSUE THREAD

**Issue by karlsu** [googlesamples/android-ndk#550]
Does the .so file create every time you compile? Does this result in slow compilation? Is there a caching mechanism for externalNativeBuild scripts?

**Comment by ggfan** [comment]
those would follow the underneath build system: if CMake does not detect there is source file change, it will not re-compile; ndkbuild is the same.  you saw something different? build performance is big thing, all bugs about that are welcome on Android Studio bug page

**Comment by karlsu** [comment]
Thank you very much. No abnormality has been found so far. I just want to find an optimal way to use the new compilation system. Is it possible to put the compiled .so file under the jnilibs directory, and then the externalNativeBuild command automatically selects whether or not to recompile the .so file?
My c++ file doesn't change much, so a compilation is enough. But the new build system doesn't seem to meet my needs, recompiling every time when delete the .externalNativeBuild directory or clean the project.

**Comment by ggfan** [comment]
that would need to trigger certain condition inside Gradle plugin when calling the CMake ( or ndk-build ) command, I am not sure.

Hello-lib  uses CMake's add_custom_command() to copy the the built lib to [different place](https://github.com/googlesamples/android-ndk/blob/master/hello-libs/gen-libs/src/main/cpp/gperf/CMakeLists.txt#L33), it might be similar to what you mentioned;  then inside the CMakeLists.txt, if add a check to see if the copied place already has the so file, it could essentially achieve your thoughts, I think.

The draw back is lost the re-build if there is really a code change, have to patch something for that

**Comment by karlsu** [comment]
Thank you. I'll try！
