### ISSUE TITLE
gradle-experimental error with other-build/hello-jni 

### ISSUE THREAD

**Issue by yannanzheng** [googlesamples/android-ndk#554]
Exception thrown while executing model rule: BaseComponentModelPlugin.Rules#createVariantData(ModelMap<AndroidBinaryInternal>, ModelMap<AndroidComponentSpec>, TaskManager) > afterEach()

**Comment by ggfan** [comment]
No, experimental is not supported with current release of gradle/Android Studio. Refer to [README.md](https://github.com/googlesamples/android-ndk/blob/master/README.md) for exact versions of ndk and gradle that could be used for  it.

move away from it would be a good options, not seeing a future for it internally. let me know you definitely need it: interesting one.

**Comment by dmvictor** [comment]
Hi, @ggfan. The [video plugin](https://github.com/googlevr/gvr-unity-sdk/tree/master/native_libs/video_plugin) in [Google VR SDK for Unity](https://github.com/googlevr/gvr-unity-sdk) use the gradle experimental plugin. When I made the C++ module "video_plugin", Android Studio has no response with no error message. I could not find the built shared library as well. My Android studio version is 3.2.1, and ndk version is r18b. According to [README.md](https://github.com/googlesamples/android-ndk/blob/master/README.md), I downgraded my Android studio and ndk version to 2.3.3 and r10e respectively. Under this setting, I could build [hello-jni](https://github.com/googlesamples/android-ndk/tree/gradle-experimental/hello-jni) and [hello-libs](https://github.com/googlesamples/android-ndk/tree/gradle-experimental/hello-libs) sample successfully. I have no idea why I could not build the C++ module "video_plugin" in the GVR SDK. Could you give me some directions about what is going on? Thank you!

**Comment by ggfan** [comment]
Probably file a bug to video plugin: update the build to cmake plugin or ndk-build. That module itself is straightforward to the change to cmake, do you know whether that module is hand-made or auto-generated by Unity tools?

I could try to connect with that repo owner next week to get some details. File a bug would be a good start there.
