### ISSUE TITLE
NDK-CAMERA-BASIC : application is not able to access camera2 on a Moto-z play

### ISSUE THREAD

**Issue by vyi** [googlesamples/android-ndk#557]
Just tried the ndk sample **camera** on Moto-Z play running android 7.1.1 . The application loads and gives a blank screen. The logcat message suggests there is no camera2 device available (!) so it is using legacy device and thus application doesn't proceed. Here is the Logcat output
```

08-21 20:06:24.676 19841-19841/? I/NDK-CAMERA-BASIC: OnCreate()  

08-21 20:06:24.677 19841-19841/? V/threaded_app: Start: 0xa5c68660  

08-21 20:06:24.677 19841-19861/? V/threaded_app: activityState=10  

08-21 20:06:24.680 19841-19841/? V/threaded_app: Resume: 0xa5c68660  

08-21 20:06:24.680 19841-19861/? V/threaded_app: activityState=11  

08-21 20:06:24.691 19841-19841/? V/threaded_app: InputQueueCreated: 0xa5c68660 -- 0xa5c687a0

08-21 20:06:24.691 19841-19861/? V/threaded_app: APP_CMD_INPUT_CHANGED
    Attaching input queue to looper  

08-21 20:06:24.721 19841-19841/? V/threaded_app: NativeWindowCreated: 0xa5c68660 -- 0xa2329008  

08-21 20:06:24.721 19841-19861/? V/threaded_app: APP_CMD_INIT_WINDOW  

08-21 20:06:24.723 19841-19861/? I/CameraManagerGlobal: Connecting to camera service  

08-21 20:06:24.727 19841-19841/? V/threaded_app: WindowFocusChanged: 0xa5c68660 -- 1  

08-21 20:06:24.754 19841-19861/? E/NDK-CAMERA-BASIC: Found legacy camera Device, this sample needs camera2 device

```
I used Android Studio 3.2 Canary 2 to build the application with SDK for API 27, NDK is V15.1. Any suggestions as to where the problem might be?

**Comment by vyi** [comment]
The other thread implies that the manufacturer has not provided hardware support (Drivers? NDK Support?) for Camera2 (!)
 
In that case, how is Camera2 accessible in Java? And when the manufacturer does not support Camera2, what good Camera2 (in terms of feature control like AF and AE) can offer over the simpler Camera1 API?

**Comment by vyi** [comment]
When OEM didn't provide Camera2, what good Camera2, via Java, offers (in terms of feature control like AF and AE) over the simpler Camera1 API?

**Comment by ggfan** [comment]
details of what/how camera1 maps into camera2 is beyond my knowledge. you may check [AOSP camera release notes](https://source.android.com/devices/camera/versioning) for Camera2 API for high level info ( basically Camera2 API wraps the legacy camera API for compatibility purpose ).

**Comment by ggfan** [comment]
Oh, the wrap is not available for NDK API side: I am forgiven for this :-)

**Comment by vyi** [comment]
Thanks for all the information. I guess I'll have to buy another device. Thanks

**Comment by ggfan** [comment]
Maybe for development only, could try to use the latest emulator. Again in emulator, it is partial emulation of  the real camera2 device: 
- Emulated mode:  functionality is there, but you see NO image in camera ( blocky noisy is displayed )
- WebCam mode:  host camera image is used as content, does not   supported AE/AF etc ( you could not test your code )
it is imperfect world, so to speak.  As app developers, all could be say is "we do our best" :-) , always remember to have a little fun in this frustrated world :-)
