### ISSUE TITLE
cannot add function to so file in hello-libs

### ISSUE THREAD

**Issue by zewenhs** [googlesamples/android-ndk#560]
@ggfan 
Hi, 
when I import hello-libs into android studio(version 3.1.3), it works all well. But I found i can not add a function in so library file which i'd like to achieve my owner purpose, detail as below:

**1.** add a function named `a_get` in gperf.c
```
GPERF_EXPORT uint64_t GetTicks(void) {
    struct timeval Time;
    uint64_t cur_tick = (uint64_t) 1000000;

    gettimeofday( &Time, NULL );
    cur_tick *= Time.tv_sec;

    return (cur_tick + Time.tv_usec);
}

GPERF_EXPORT uint64_t a_get(void) {
    struct timeval Time;
    uint64_t cur_tick = (uint64_t) 1000000;

    gettimeofday( &Time, NULL );
    cur_tick *= Time.tv_sec;

    return (cur_tick + Time.tv_usec);
}

```
**2**. declare this new function in `gperf.h`
```
#ifdef __cplusplus
extern "C"
#endif // __cplusplus
uint64_t GetTicks(void);//1
uint64_t a_get(void);//2
//uint64_t GetTicks(void);


#endif //__GPERF_HPP__

```

**3**. call these two functions in `hello-libs.cpp`
```
  ticks = GetTicks() - ticks;
  
    ticks = a_get();
```
**4**. make project, but it comes error as:
```
android-ndk/hello-libs/app/src/main/cpp/hello-libs.cpp:49: error: undefined reference to 'a_get()'
```

**5**. By now you may say there must something wrong about my project setting, but only after I adjust function declare order in `gperf.h`, it can link to `a_get` but can not link to `GetTicks` , 
```
#ifdef __cplusplus
extern "C"
#endif // __cplusplus
//uint64_t GetTicks(void);
uint64_t a_get(void);//1
uint64_t GetTicks(void);//2
#endif //__GPERF_HPP__
```
after this :
```
android-ndk/hello-libs/app/src/main/cpp/hello-libs.cpp:47: error: undefined reference to 'GetTicks()'
```
**6**. but in libgperf.so, `GetTicks` and `a_get` are all GLOBAL , which mean can link to this function

```
zewen@PC:hello-libs$ readelf -a  ./distribution/gperf/lib/arm64-v8a/libgperf.so | grep GetTicks
     3: 000000000000061c   128 FUNC    GLOBAL DEFAULT   10 GetTicks
    62: 000000000000061c   128 FUNC    GLOBAL DEFAULT   10 GetTicks
zewen@PC:hello-libs$ readelf -a  ./distribution/gperf/lib/arm64-v8a/libgperf.so | grep a_get
    13: 000000000000069c   128 FUNC    GLOBAL DEFAULT   10 a_get
    72: 000000000000069c   128 FUNC    GLOBAL DEFAULT   10  a_get
```

### How is going on? thanks!!!

Android Studio 3.1.3
Build #AI-173.4819257, built on June 5, 2018
JRE: 1.8.0_152-release-1024-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-116-generic

**Comment by ggfan** [comment]
header file needs to be:
```
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint64_t GetTicks(void);//1
uint64_t a_get(void);//2

#ifdef __cplusplus
} // __cplusplus
#endif

//uint64_t GetTicks(void);
```
extern "C" need to decorate to every exported functions.

**Comment by zewenhs** [comment]
Yeah , already OK , thanks!

**Comment by zewenhs** [comment]
I have another question, 
I hvae an library named `libgzewen.so` which is compiled at other place, 
```
zewen@PC:dongle_linux$ file libgzewen.so  
libgzewen.so: ELF 64-bit LSB  shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
```
and it's source file as:
```
static const char *hello_string = "Hello, I'm library zewen";

const char *hello_hello()
{
    return hello_string;
}

unsigned long getl()
{
	return 2018;
}

```

now use this library replace `libgperf.so`, and add `unsigned long getl();` in `gperf.h`, compile show error:
```
android-ndk/hello-libs/app/src/main/cpp/hello-libs.cpp:53: error: undefined reference to 'getl'
```

#### so how can i import already exists library? thanks!

**Comment by ggfan** [comment]
make sure you have exported the file correctly:
- check your header file, must have `extern "C"` for every exported function
- after compilation passing, make sure you have exported all cpu architecture libs that you ARE building in your app -- [abiFilters](https://github.com/googlesamples/android-ndk/blob/fc2ed743f9e34e5b7dcfc06c11420f3eb886f1bf/webp/view/build.gradle#L10)

Once the above 2 handled correctly, it should work.  If you plan to use C++ to create your lib, then there is another dimension -- stl-types. App and your Lib got to have the same stl-type too.

You are already using elf tool checking the things, this would be familiar to you.

you could also share your code, I could hack on it a little bit ( I am not a compile person ).

**Comment by zewenhs** [comment]
@ggfan 

> check your header file, must have extern "C" for every exported function
#### ===>yes

> after compilation passing, make sure you have exported all cpu architecture libs that you ARE building in your app -- abiFilters
#### ===>now I add ` ndk.abiFilters 'arm64-v8a'` in `app/build.gradle`
```
...
versionName = '1.0'
        ndk.abiFilters 'arm64-v8a'
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static'g++ -fPIC libA.cpp -shared -fvisibility=hidden -o libA.so
            }
        }
...
```


Anyway, Now I can compile but got error when it run, also the `libgzewen.so` is **not** compile in `hello-libs` project as I mentioned above., detail msg:
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "/home/zewen/workspace/booksource/test/test/android-ndk/hello-libs/app/src/main/cpp/../../../../distribution/gperf/lib/arm64-v8a/libgperf.so" not found
```
the lib code is very simply, and I already post in previous note, I only compile this by myself，and replace libgerf.so, and the compile command:
```
export HOST=aarch64-linux-android
export CC="/tmp/my-android-toolchain-arm64-26/bin/aarch64-linux-android-gcc-4.9.x --sysroot=/tmp/my-android-toolchain-arm64-26/sysroot"
$CC  -shared -fpic -o libgzewen.so  hello.c  -std=c11
cp libgzewen.so ~/workspace/booksource/test/test/android-ndk/hello-libs/distribution/gperf/lib/arm64-v8a/libgperf.so
``` 
build and run app, logcat will  show `libgperf.so` not found!!!

**Comment by ggfan** [comment]
hard to guess what is going on, even it supposed that your apk does not have that libperf.so in it: if you unzip ( literally just rename your apk to *.zip and unzip, check your lib is under lib dir,  or android studio's analyze apk option ) your apk, it should not be there.

you post code is not correct, by all means it should error out ( not build ). you might double check that ( those "g++ -fPIC libA.cpp -shared -fvisibility=hidden -o libA.so" should never allow you to compile )

clean your project, and `rm -fr $project/app/.externalNativeBuild`, then build APK, analyze APK ( all under build menu), and make sure your *.so files are there.

**Comment by zewenhs** [comment]
I think it's build method issue， I refer to build method of  Android Studio and te result comes OK:

#### detail compile command as :
```
compile:
/home/zewen/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang  --target=aarch64-none-linux-android --gcc-toolchain=/home/zewen/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/home/zewen/Android/Sdk/ndk-bundle/sysroot -Dhello_EXPORTS  -isystem /home/zewen/Android/Sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC -MD -MT /home/zewen/tmp/gperf/CMakeFiles/gperf.dir/src/hello.c.o -MF /home/zewen/tmp/gperf/CMakeFiles/gperf.dir/src/hello.c.o.d -o /home/zewen/tmp/gperf/CMakeFiles/gperf.dir/src/hello.c.o   -c /home/zewen/workspace/booksource/test/test/android-ndk/hello-libs/gen-libs/src/main/cpp/gperf/src/hello.c
```

```
Link:
/home/zewen/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang  --target=aarch64-none-linux-android --gcc-toolchain=/home/zewen/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/home/zewen/Android/Sdk/ndk-bundle/sysroot -fPIC -isystem /home/zewen/Android/Sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /home/zewen/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/home/zewen/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libhello.so -o /home/zewen/workspace/booksource/test/test/android-ndk/hello-libs/distribution/gperf/lib/arm64-v8a/libhello.so /home/zewen/tmp/gperf/CMakeFiles/gperf.dir/src/hello.c.o  -latomic -lm && cd /home/zewen/tmp/gperf && /home/zewen/Android/Sdk/cmake/3.6.4111459/bin/cmake -E copy /home/zewen/workspace/booksource/test/test/android-ndk/hello-libs/gen-libs/src/main/cpp/gperf/src/gperf.h /home/zewen/workspace/booksource/test/test/android-ndk/hello-libs/gen-libs/src/main/cpp/gperf/../../../../../distribution/gperf/include/gperf.h
```

I know It looks so messy, But if you look at it carefully,Most of the contents are path and compile parameters,  To put it simply, the function of the above command is to achieve compile `hello.c` to `libhello.so`.
### So the point is: My bad compilation method led to previous problems. And I will do some further study when I have time. Thanks @ggfan You are the best!!! :+1:  :+1: :+1:
