### ISSUE TITLE
Can not compile hello-jni sample of master branch

### ISSUE THREAD

**Issue by growingant** [googlesamples/android-ndk#567]
I am using Android Studio 3.1.4, with latest NDK version, gradle plugin 3.1.4(3.1.3 in original sample, but i update to 3.1.4 according to Android Studio recommendation). But compile with error"AAPT2 error: check logs for details". I do not paste log file here since it is quite big

**Comment by ggfan** [comment]
Oops, some bug then. Which host OS you are using? if you do not let it update, will it be able to build?

just tried on Linux, it seems ok.

**Comment by growingant** [comment]
64 bit windows. If use gradle plugin version 3.1.3, it can not be able to build either.

**Comment by ggfan** [comment]
yeah, seems to be ok on my windows machine with 3.1.4.  could be version of NDK? maybe do this:
 - git clean -xdf
 - git reset --hard
 - git pull origin/master
 - Open Android Studio  to open the project ( not import )
( basically get a clean code, and re-try ).  The check your NDK version:
  sdk\ndk-bundle\source.properties
thx

**Comment by growingant** [comment]
@ggfan I find the problem finally! It is because security tool of our company, resources of Hello-jni project cached by gradle during compiling were encrypted .  
When i used gradle plugin 3.1.3, there were no direct indication where the problem is. Then i used 3.2.0-alpha18 of gradle plugin , 4.6 of gradle, then i got indication that png files cached by gradle can not be read(something like "bad png signature" ).
Then i use Android Studio 3.0, it can be complied successfully
Thanks very much! Feels great to receive reply immediately

**Comment by ggfan** [comment]
thx! will pass around your findings to the team!
