### ISSUE TITLE
Error:(20, 10) fatal error: 'android/NeuralNetworks.h' file not found

### ISSUE THREAD

**Issue by qianrushi9** [googlesamples/android-ndk#568]
Error:(20, 10) fatal error: 'android/NeuralNetworks.h' file not found 
while running the app～

**Comment by ggfan** [comment]
NN is only enabled in Android O-MR1 ( API 27 ), do not go too far back with NDK version. If you still have problem, please re-open the issue ( it would be really a bug somewhere in NDK ). thanks
