### ISSUE TITLE
Add sample showing custom jniLibs w/ Android.mk

### ISSUE THREAD

**Issue by mnbittorrent** [googlesamples/android-ndk#57]
Is there a way to specify a jniLibs folder so that other .so files may be copied into the .apk?

**Comment by proppy** [comment]
@mnbittorrent are you referring to a `.so` file build from another project (with Android.mk)?

**Comment by proppy** [comment]
Related #26

**Comment by mnbittorrent** [comment]
Yes, potentially. More likely in my case it would be a .so file manually compiled with a clang or gcc toolchain.

**Comment by proppy** [comment]
@mnbittorrent if you have the option to compile a static library, the workaround pointed out in #26 might be interesting, see https://github.com/googlesamples/android-ndk/issues/26#issuecomment-133238221

**Comment by proppy** [comment]
Repurposing this issue to add a sample that show how to set jniLibs option.

**Comment by ph0b** [comment]
If the .so files are already compiled and you only want these to be integrated into the APK, you can change the jniLibs directory this way:

    android.sources{
        main.jniLibs {
            source {
                srcDir 'src/main/libs'
            }
        }
    }

**Comment by proppy** [comment]
@ph0b do you have a good idea for a sample that show that?

Maybe an hybrid sample that use gradle for the app, and Android.mk to build a .so for libcurl?

Related #45

**Comment by ph0b** [comment]
two-libs from the ndk would be a perfect candidate as it can't be converted to the gradle only build yet.

**Comment by proppy** [comment]
@ph0b good idea!

**Comment by proppy** [comment]
@phob but IIRC two-libs is using a static library:
https://github.com/googlesamples/android-ndk/blob/b4700b9499e1c6becc1a76b53a8691ecdeb25173/two-libs/jni/Android.mk#L30

So that would be a better candidate for #45 
- libone: a static library build with `Android.mk`
- libtwo: a dynamic library build with gradle depending on libone with custom `ldFlags`
- app: dynamic load libtwo with a standard `jniLibs`

Here I think we want something like:
- libone: a shared library build with Android.mk
- libtwo: a dynamic library build with gradle
- app: dynamically load libone and libtwo with a custom `jniLibs`

What do you think?

**Comment by ph0b** [comment]
in the case you mention you would have no dependencies between the libs ? Then I don't find it really practical. I would better see the two-libs exactly as it is on the current ndk, keeping their current Android.mk/Application.mk. With the the app that dynamically loads them. 

Sure it's a bit the same concept than your candidate for #26, but it's more practical for developers with complex Makefile setups who don't want to use flavors and ldLibs. If you're looking into doing a different sample like this one to avoid duplicating it, one that uses OpenCV would help many developers.

**Comment by proppy** [comment]
> in the case you mention you would have no dependencies between the libs ? Then I don't find it really practical. I would better see the two-libs exactly as it is on the current ndk, keeping their current Android.mk/Application.mk. With the the app that dynamically loads them.

OK, so the app would have no native part built with gradle, just a custom `jniLibs` pointing to libtwo (that is statically linked to libone), right?

**Comment by proppy** [comment]
I'd also like to have the gradle equivalent of two-libs, which is building a native part with gradle which is statically linking to something built with Android.mk.

**Comment by ph0b** [comment]
yes, the app would have no native part built with gradle.

**Comment by proppy** [comment]
> yes, the app would have no native part built with gradle.

Then I'm not sure if we need more than one lib, it could simply show how to build a .so with Android.mk (outside of gradle) and package it with the Android app.

**Comment by ph0b** [comment]
true, it's not needed to show it works, but having several modules defined in the .mk is a case that justifies the use of makefiles instead of gradle, that's why I proposed this one.

I agree that the other showing how to link to a .a or .so from a gradle project would be super useful! I'm just worried it would be a little bit "hacky" with the current DSL.

**Comment by proppy** [comment]
> true, it's not needed to show it works, but having several modules defined in the .mk is a case that justifies the use of makefiles instead of gradle, that's why I proposed this one.

Oh yeah, I see what you mean know. It totally make sense.

> I agree that the other showing how to link to a .a or .so from a gradle project would be super useful! I'm just worried it would be a little bit "hacky" with the current DSL.

Ironically, that would be the gradle "port" of two-libs that were my confusion came from I think :)

**Comment by ggfan** [comment]
this is now inside hello-libs build.gradle [app/build.gradle] where we points directory of jniLibs to lib distrbution location; those shared libs meant to build into apk could also be copied pyhisically into app/src/main/jniLibs directory. closing down this one for now
