### ISSUE TITLE
WSOLA

### ISSUE THREAD

**Issue by alexd555** [googlesamples/android-ndk#570]
Hi,

I added wsola based on https://gitlab.com/soundtouch/soundtouch/blob/master/source/SoundStretch/main.cpp

My added code is
https://github.com/alexd555/wsola/blob/master/audio-echo/app/src/main/cpp/audio_main.cpp#L246
But it crash.
I also chaged samplerate to 8Khz and buffer size to 1024
Could you help ?

Thanks,
Alex

**Comment by ggfan** [comment]
let me download code and have a look -- for DSP algorithm though, I got to ask experts in Audio team.

**Comment by alexd555** [comment]
Don't you have permission to download?  very strange.
I will send you later today.
Thanks,
Alex

**Comment by ggfan** [comment]
I could download the code, not a problem

**Comment by ggfan** [comment]
a couple of things:

-  the samples from recording is INT16 type, looks like you brutally casting them to float and give to SoundTouch.  that is not going to work -- need to convert from INT16 --> float, do SoundTouch, convert from float -> INT16 to play back to player.
Or sample it with float, as your app does not care too much of latency.

- after getting back the samples from SoundTouch, the sample count needs to be update into buf->size_ = ( sampleCount * 2, it is in byte ), in case SoundTouch does not give back the number of samples you are asking.

Right now it is not right: the original buf_ is INT,16 and you are asking back from sound touch for the same number of samples in FLOAT:  INT16 is 2 bytes, while float is 4 bytes, Is SoundTouch is doing the work, you might end up with memory over-run. If Sound Touch gives less than you are required, then you are playing the extra with whatever old samples ( not Sound Touch processed ) there. So in either case, it does not seem to be correct.

closing down this one as we are working this out in different channel.
