### ISSUE TITLE
[native-audio] No output on Android P using wired headset

### ISSUE THREAD

**Issue by antonkovalyov351** [googlesamples/android-ndk#574]
Hi,
I am developing Android app that uses OpenSL ES lib. I used `native-audio` as an example.

I faced an issue with audio recording on Google Pixel running Android P. Looks like it doesn't work when recording using **wired headset**.

**Google Pixel XL / Android P.** - NO OUTPUT
**Samsung S8+ / Android 8.0.0.** - ALL GOOD

Any help will be appreciated.

**Comment by ggfan** [comment]
By default, it takes the onboard Mic, may you double check that using on-board mic works ( recording via Mic -- speaking pretty closely to your Pixel XL. It is like: "_it is great phone, keep it as close to us as possible_" :-) this is just a joke, I will delete this comment for sure ). 

I forgot the exact bug number filed for this long time ago. Anyhow please:
- try with the onboard mic
- in your app, enable the external mic when detecting one, via Java side API in your initialization steps. Device [code example](https://github.com/google/oboe/tree/master/samples/audio-device) might be helpful.

**Comment by antonkovalyov351** [comment]
@ggfan Thanks for the response.

Onboard mic works. 
Looks like this is headset issue. I used AKG headset from Samsung S9+ box.
Android voice search also does not work.
Here is log from Google Pixel after AKG headset insertion: https://pastecode.xyz/view/4171a8c7

I tested on:
Samsung S8+ / Android 8.0.0
Samsung S9+ / Android 8.0.0
Xiaomi Mi A1 / Android 8.1.0
AKG headset works for these devices.

I faced this issue only with Google Pixel and Google Pixel XL running Android P (PPR2.180905.006)

I tested with different headset (Steelseries) and it worked for all cases (for both native-audio, and oboe).

**Comment by ggfan** [comment]
thanks! please add the exact model of this headset, I will _try_ to follow up on this one like file a bug or something ( I do not think we are short of bugs though :-) ). The point from your previous msg is that:  AKG's this model workable phone list is significantly longer than the non-working phone list, which is important :-). 

thank you again! ( my head is halfly functioning, but I will clean up my comment after I get a bug number linked here, I promise :-) )

**Comment by antonkovalyov351** [comment]
Not sure about exact mode. Headset were with Samsung S9+ phone.
Looks like [this one](https://www.samsung.com/us/mobile/mobile-accessories/phones/samsung-earphones-tuned-by-akg--gray-eo-ig955bsegus/).

Updated list of devices:

**Works on:**
Samsung S8+ / Android 8.0.0
Samsung S9+ / Android 8.0.0
Xiaomi Mi A1 / Android 8.1.0
Huawei Nexus 6P / Android 8.1.0

**Doesn't work on:**
Google Pixel / Android P (PPR2.180905.006)
Google Pixel XL / Android P (PPR2.180905.006)

**Comment by antonkovalyov351** [comment]
Today I flashed Android 8.1.0 on Google Pixel and got same result - No output. 
So I believe this is purely hardware issue and AKG headset and Google phones are not compatible.
So I only have one question left: **can I check headset compatibility using Android SDK?**
In any case this issue can be close. 
Thanks for your help!

**Comment by ggfan** [comment]
I did not know compatibility checking API. That [sample]( https://github.com/google/oboe/tree/master/samples/audio-device) is the good place to start.
