### ISSUE TITLE
floating point

### ISSUE THREAD

**Issue by alexd555** [googlesamples/android-ndk#575]
Hi,
Why app doest support floating point(float).
How can I change it ?
Thanks,
Alex

**Comment by ggfan** [comment]
floating point may not be the device's fast audio path. To enable it though,  you could:

- create audio streams with [SLAndroidDataFormat_PCM_EX](https://android.googlesource.com/platform/frameworks/wilhelm/+/master/include/SLES/OpenSLES_Android.h#48)
- set its formatType  to SL_ANDROID_DATAFORMAT_PCM_EX
- set its representation member to 
  [SL_ANDROID_PCM_REPRESENTATION_FLOAT](https://android.googlesource.com/platform/frameworks/wilhelm/+/master/include/SLES/OpenSLES_Android.h#44)
- configure other members accordingly
- create a stream; if failed, means not supported, fall back to use INT type

have some code inside ConvertToSLSampleFormat() in audio_common.c, you might have a look. This sample not using float.
