### ISSUE TITLE
"bad class file magic (cafebabe) or version (0034.0000)" error when using jdk 1.8

### ISSUE THREAD

**Issue by Piasy** [googlesamples/android-ndk#58]
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
When I add the following to the `model` closure, it works well.
```groovy
    compileOptions.with {
        sourceCompatibility = JavaVersion.VERSION_1_7
        targetCompatibility = JavaVersion.VERSION_1_7
    }
```

**Comment by proppy** [comment]
Happy to continue to discussion in #43. We should update the README.md with instruction on how to set JDK 1.7 and/or add the proper build.gradle workaround.
