### ISSUE TITLE
add platformVersion to all sample

### ISSUE THREAD

**Issue by nmr8acme** [googlesamples/android-ndk#59]
According to https://code.google.com/p/android/issues/detail?id=73725 NDK builds need to be compiled against SDK version <= 20 for backwards compatibility, but appcompat requires >= 21. 

@rschiu Is there a directive to set the compileSdkVersion for the NDK build only?

**Comment by rschiu** [comment]
Yes, I have a bug for that (https://code.google.com/p/android/issues/detail?id=177530) and plan to add the ability to specify platform version for just the NDK.  The caveat is that you will need to be using the experimental plugin.  It should be released in the next version.

**Comment by nmr8acme** [comment]
Thanks, nice job!

**Comment by proppy** [comment]
Repurposing this bug to add a sample that show that.

**Comment by ggfan** [comment]
fixed by https://github.com/googlesamples/android-ndk/pull/187

 logic:
  platformVersion <= apiVersionOnYourAndroidDevice  &&
  platformVersion in { your-ndk/platform/*}  <== this cause the ndk to pick the header/libs from its folder
