### ISSUE TITLE
Typo in build.gradle comment for hello-gl2

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [googlesamples/android-ndk#594]
Hello - first of all, thank you for the effort.

Now, there is this typo that's been triggering my OCD for a while - maybe it's easier for me to point out my suggested correction in my fork: https://github.com/TheFakeMontyOnTheRun/android-ndk/commit/6260f626a191d082ec9a9b15b448ccc8c149b404

**Comment by ggfan** [comment]
thank you for filing the bug for it!  Feel free to fix those things with Pull request or whatever the way.
