### ISSUE TITLE
Error:Could not find com.android.tools.build:gradle-experimental:1.3.0-beta3.

### ISSUE THREAD

**Issue by visa8000** [googlesamples/android-ndk#6]
Error:Could not find com.android.tools.build:gradle-experimental:1.3.0-beta3.
Searched in the following locations:
    file:/D:/androidstudio/androidstudio/gradle/m2repository/com/android/tools/build/gradle-experimental/1.3.0-beta3/gradle-experimental-1.3.0-beta3.pom
    file:/D:/androidstudio/androidstudio/gradle/m2repository/com/android/tools/build/gradle-experimental/1.3.0-beta3/gradle-experimental-1.3.0-beta3.jar
    https://jcenter.bintray.com/com/android/tools/build/gradle-experimental/1.3.0-beta3/gradle-experimental-1.3.0-beta3.pom
    https://jcenter.bintray.com/com/android/tools/build/gradle-experimental/1.3.0-beta3/gradle-experimental-1.3.0-beta3.jar
Required by:
    :hello-jni:unspecified

**Comment by ggfan** [comment]
Thank you for the info!
This is early peek into next release of gradle plugin/AndroiStudio; I also apologize that we do not have the documentation at this moment.

The way to workaround for early access is:
1) download the source code for gradle plugin and follow instruction to build the latest gradle plugin on your location system
       http://tools.android.com/build
     (once you get source code and execute 3 commands: gradlew init;gradlew assemble;gradlew publishLocal, you have the latest gradle plugin on your local machine )
2) your local build should be somewhere @
      $(YOUR_LOCAL_SOURCE_CODE_ROOT_DIR)/out/repo   <== this is the one to be set into CUSTOM_REPO on your local machine.  gradle will be able to find the place via System.getenv('CUSTOM_REPO')
3) you would also follow the directory mentioned in step 2), into the end of the classpath to check out what is your build version
       the latest version could beta3 or others, you could find which one it is by following classpath on your local build --
        $(YOUR_LOCAL_SOURCE_CODE_ROOT_DIR)/out/repo/com/android/tools/build/gradle-experimental
             it should be 1.3.0-beta3 ( maybe beta4 etc)
        find what yours is and put it into the classpath [instead of using the 1.3.30-beta3]
       
       Note: plugin name is gradle-experimental,  latest version may change and it changes pretty fast. Final release version could be 1.3.0-rc, 1.3.0, or others
       
with this you will be able to compile.

Currently we use these 2 samples to develop integration into new Android Studio [to be imported directly from github into local Android Studio ]. When the mechanism is ready, more samples with new Android Studio will be pushed in and documentation will follow pretty quickly. 


thank you again for checking it out and appreciate your early access and feedback!
