### ISSUE TITLE
Unsupported method: NativeArtifact.getSourceFolders()

### ISSUE THREAD

**Issue by vikash-amuratech** [googlesamples/android-ndk#615]
Getting the following error when Running on Android Studio 3.1.4

Unsupported method: NativeArtifact.getSourceFolders().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

**Comment by ggfan** [comment]
Oops, sorry: last time updated to version 3.3 to use "cmake version" feature.

If you need to downgrade it, might need to do:
-  use "3.1.4" in project/build.gradle
- remove " cmake { version '3.10.2' }" from project/app/build.gradle
- this is optional. [$project/gradle/wrapper/gradle-wrapper.properties, change gradle version to 4.4
](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle)

**Comment by Dina07** [comment]
> Oops, sorry: last time updated to version 3.3 to use "cmake version" feature.
> 
> If you need to downgrade it, might need to do:
> 
> * use "3.1.4" in project/build.gradle
> * remove " cmake { version '3.10.2' }" from project/app/build.gradle
> * this is optional. [$project/gradle/wrapper/gradle-wrapper.properties, change gradle version to 4.4
>   ](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle)

if i downgrade it...
it says
- CMake '3.10.2' found in SDK did not match requested version '3.6.0'.
