### ISSUE TITLE
Build is failing for three samples

### ISSUE THREAD

**Issue by hevrard** [googlesamples/android-ndk#632]
`./gradelw assembleDebug` leads to the following error:

```
CMake Error at <REDACTED>/teapots/common/ndk_helper/CMakeLists.txt:4 (include):
  include could not find load file:

    AndroidNdkModules
```

There is a AndroidNdkModules.cmake file under my SDK, but I can't grep any mention of setting CMAKE_MODULE_PATH to include ANDROID_SDK_HOME or something similar?

**Comment by ggfan** [comment]
yeah, if compiling directly on command line, ANDROID_SDK needs to set up correctly, and using the cmake inside sdk would add that path to the modules.

But if using public NDK directly,  the path is not added by default (of course), so need to manually add it (or do not use it -- native_activity related things is just one file )

**Comment by hevrard** [comment]
Maybe the building instructions are out of sync then?
https://github.com/googlesamples/android-ndk#build-steps

I have both ANDROID_HOME and ANDROID_NDK_HOME setup as expected (absolute paths), I change into `teapots`, and call `./gradlew assembleDebug`, get the error.

Other examples like `san_angeles` compile fine with this approach.

Is there a way to make teapots compile with the same build command? Or should the build command instructions be updated to describe how to manually add a Cmake path?

**Comment by hevrard** [comment]
I just tried `./gradlew assembleDebug` on all sample subdirectories, these three fail:

1. builder
```
Task 'assembleDebug' not found in root project 'builder'.
```

2. hello-cdep
```
CMake Error at /usr/local/google/home/hevrard/work/googlesamples_android-ndk/hello-cdep/app/src/main/cpp/CMakeLists.txt:35 (find_package):
  By not providing "Findcdep-dependencies.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "cdep-dependencies", but CMake did not find one.

  Could not find a package configuration file provided by "cdep-dependencies"
  with any of the following names:

    cdep-dependenciesConfig.cmake
    cdep-dependencies-config.cmake
```
3. teapots
```
CMake Error at /usr/local/google/home/hevrard/work/googlesamples_android-ndk/teapots/common/ndk_helper/CMakeLists.txt:4 (include):
  include could not find load file:

    AndroidNdkModules
```

**Comment by ggfan** [comment]
yeah
- builder: do not try it, out of maintenance ( I think this one is meant to manage samples in the repo ): I will update readme.md for it to deprecate it.  thank you for point it out.
- cdep: refer to its [README.md ](https://github.com/googlesamples/android-ndk/tree/master/hello-cdep) for required terminal steps before build ( we do not want to add those extra cdep to project as it is once per host --- decided at that time )
- teapot: probably is the only one using ndk included module for native-activity
