### ISSUE TITLE
How Can I get MediaProjection's interface from NDK?

### ISSUE THREAD

**Issue by joole** [googlesamples/android-ndk#633]
Using java to write the screencapture is easily,but In my project, I want to get MediaProjection's interface from NDK,I can't find any useful docs, In other word, My Question is How to capture screen from NDK,please help me ~

**Comment by ggfan** [comment]
There is no interface from NDK: all supported functionalities are inside header files under NDK, if there is header file, there is no support.  You app will have to do it from Java side API.

**Comment by joole** [comment]
It will broken design for different language, why not plant to support it ?

**Comment by ggfan** [comment]
Only the really necessary features are exposed to native side; for example there is no native api for UI, just use JNI to callback Java side to perform the same functionality.

**Comment by joole** [comment]
so,It's the only way that use aosp  to build private library!

**Comment by joole** [comment]
@ggfan 
My works is like this： using NDK to write a CPP  class which will capture the screen ,and then pass the yuv data to next class  to encoder or render, If Android not supported the way which is that takes a screenshot from ndk, the code will be broken by different language，and then broken struture design.Yes I can call JNI to callback java side ,but,do you consider the efficiency?  by the way, Why  can 
 can audio get highly support in NDK?
