### ISSUE TITLE
CMake Error: Could not create named generator Android Gradle - Ninja

### ISSUE THREAD

**Issue by RuiCuco** [googlesamples/android-ndk#640]
Hi. I just installed cmake, but I keep getting the following error:

Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonModelReleaseArm7'.

> 
Build command failed.
Error while executing process C:\Development\Android\android-sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {-HC:\Users\Rui\Projects\MyApp\build\android-native-build\MyApp\app -BC:\Users\Rui\Projects\MyApp\build\android-native-build\MyApp\app\.externalNativeBuild\cmake\releaseArm7\armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Development\Android\android-ndk-r15b -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Rui\Projects\MyApp\build\android-native-build\MyApp\app\build\intermediates\cmake\releaseArm7\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=C:\Development\Android\android-sdk\cmake\3.10.2.4988404\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Development\Android\android-ndk-r15b\build\cmake\android.toolchain.cmake -DANDROID_PLATFORM=android-15 -DCMAKE_CXX_FLAGS=-frtti -fexceptions}
CMake Error: Could not create named generator Android Gradle - Ninja

Generators
Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
Optional [arch] can be "Win64" or "ARM".
Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
Optional [arch] can be "Win64" or "ARM".
Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
Optional [arch] can be "Win64" or "ARM".
Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
Optional [arch] can be "Win64" or "ARM".
Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
Optional [arch] can be "Win64" or "IA64".
Visual Studio 9 2008 [arch] = Generates Visual Studio 2008 project files.
Optional [arch] can be "Win64" or "IA64".
Visual Studio 8 2005 [arch] = Deprecated. Generates Visual Studio 2005
project files. Optional [arch] can be
"Win64".
Borland Makefiles = Generates Borland makefiles.
NMake Makefiles = Generates NMake makefiles.
NMake Makefiles JOM = Generates JOM makefiles.
Green Hills MULTI = Generates Green Hills MULTI files
(experimental, work-in-progress).
MSYS Makefiles = Generates MSYS makefiles.
MinGW Makefiles = Generates a make file for use with
mingw32-make.
Unix Makefiles = Generates standard UNIX makefiles.
Ninja = Generates build.ninja files.
Watcom WMake = Generates Watcom WMake makefiles.
CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
CodeBlocks - NMake Makefiles JOM
= Generates CodeBlocks project files.
CodeBlocks - Ninja = Generates CodeBlocks project files.
CodeBlocks - Unix Makefiles = Generates CodeBlocks project files.
CodeLite - MinGW Makefiles = Generates CodeLite project files.
CodeLite - NMake Makefiles = Generates CodeLite project files.
CodeLite - Ninja = Generates CodeLite project files.
CodeLite - Unix Makefiles = Generates CodeLite project files.
Sublime Text 2 - MinGW Makefiles
= Generates Sublime Text 2 project files.
Sublime Text 2 - NMake Makefiles
= Generates Sublime Text 2 project files.
Sublime Text 2 - Ninja = Generates Sublime Text 2 project files.
Sublime Text 2 - Unix Makefiles
= Generates Sublime Text 2 project files.
Kate - MinGW Makefiles = Generates Kate project files.
Kate - NMake Makefiles = Generates Kate project files.
Kate - Ninja = Generates Kate project files.
Kate - Unix Makefiles = Generates Kate project files.
Eclipse CDT4 - NMake Makefiles
= Generates Eclipse CDT 4.0 project files.
Eclipse CDT4 - MinGW Makefiles
= Generates Eclipse CDT 4.0 project files.
Eclipse CDT4 - Ninja = Generates Eclipse CDT 4.0 project files.
Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

As you can see there is no generator 'Android Gradle - Ninja' in the list. I'm using the latest cmake from Android Studio. I hope this helps you to identify the problem. I don't know what to do.

**Comment by inPeige** [comment]
hi guy,I don't know how this problem is caused, but in order to solve this problem quickly, it is recommended to use the 16 or 17 version of the NDK.
