### ISSUE TITLE
How can I know the map between NDK version and Android version?

### ISSUE THREAD

**Issue by goodwelldj** [googlesamples/android-ndk#641]
How can I know the map between NDK version and Android version?

**Comment by jomof** [comment]
NDK supports multiple at once. If you need the exact mapping it's in
$NDK/platforms.json and look and min and max

**Comment by goodwelldj** [comment]
I can't find a file named platforms.json, could you help me?

**Comment by ggfan** [comment]
I would go to $NDK/platforms/, all supported API levels would have their directory there, with exception that: when you see holes in api levels, it means that the api uses its preview api directory ( no change for that api from its previous api level ). From api level you could translate to Android versions ( but normally api level is kind of enough for source code )
