### ISSUE TITLE
Teapot sample doesn't build with error

### ISSUE THREAD

**Issue by bobsort** [googlesamples/android-ndk#643]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':textured-teapot:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process *:\android-sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build *:\Projects\NDKSamples\teapots\textured-teapot\.externalNativeBuild\cmake\debug\x86_64 --target TexturedTeapotNativeActivity}
  [1/15] Building CXX object *:/Projects/NDKSamples/teapots/common/ndkHelperBin/Debug/x86_64/CMakeFiles/NdkHelper.dir/gl3stub.cpp.o
  [2/15] Building C object *:/Projects/NDKSamples/teapots/common/ndkHelperBin/Debug/x86_64/CMakeFiles/native_app_glue.dir/*_/android-sdk/ndk-bundle/sources/android/native_app_glue/android_native_app_glue.c.o
  [3/15] Linking C static library *:\Projects\NDKSamples\teapots\common\ndkHelperBin\Debug\x86_64\libnative_app_glue.a
  [4/15] Building CXX object CMakeFiles/TexturedTeapotNativeActivity.dir/Texture.cpp.o
  FAILED: CMakeFiles/TexturedTeapotNativeActivity.dir/Texture.cpp.o 
  *:\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=x86_64-none-linux-android21 --gcc-toolchain=*:/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=*:/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -DTexturedTeapotNativeActivity_EXPORTS -I*:/Projects/NDKSamples/teapots/common -I*:/android-sdk/ndk-bundle/sources/android/native_app_glue -I*:/Projects/NDKSamples/teapots/common/ndk_helper -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -Wall -Werror -fno-exceptions -frtti -O0 -fno-limit-debug-info  -fPIC   -Wno-unused-function -std=c++11 -MD -MT CMakeFiles/TexturedTeapotNativeActivity.dir/Texture.cpp.o -MF CMakeFiles\TexturedTeapotNativeActivity.dir\Texture.cpp.o.d -o CMakeFiles/TexturedTeapotNativeActivity.dir/Texture.cpp.o -c *:/Projects/NDKSamples/teapots/textured-teapot/src/main/cpp/Texture.cpp
  *:/Projects/NDKSamples/teapots/textured-teapot/src/main/cpp/Texture.cpp:21:10: fatal error: 'stb/stb_image.h' file not found
  #include <stb/stb_image.h>
           ^~~~~~~~~~~~~~~~~

**Comment by ggfan** [comment]
Interesting, must be something wrong with this code:
https://github.com/googlesamples/android-ndk/blob/master/teapots/textured-teapot/src/main/cpp/CMakeLists.txt#L24

could you manually download that repo  to the "common" directory at the same level as "textured-teapot"? If you could see what the problem with that code on windows, that is great ( I would be sure your git is inside the system path: you get this repo downloaded ).

**Comment by ggfan** [comment]
it seems to be ok  on local windows machine, might be that you do not have your "git" inside the system PATH.

**Comment by bobsort** [comment]
So hurry to close the issue ;)

The issue is at the end 

'stb/stb_image.h' file not found

in fact I don't have that file anywhere in my system. 

I don't think it has anything to do with git, because I don't have git in my machine and still can compile and run other samples (woah! there are people who still don't work with git!!!) 

aren't dependencies need to be specified in document instead of relying on a tool to download them for you? I'm on metered Internet and can't afford to allow apps downloading whenever the feel like it. (Yes there are still countries with limited Internet access)

**Comment by ggfan** [comment]
sure.  only texture needed to be decoded with stb_image lib, others samples not needed.  that cmakelist is for that textured_teapot only: each one has its own cmakelists.txt. 

you are right:  I will add it into the doc for textured teapot.

One reason to automated it is that: this sample could be imported to Android studio; the importing process could not handle the submodule.  Sample repo infrastructure will be upgraded soon, at that time, it might be able to take care of the submodules, that is good time to change. 
Thank you for bring up the issue.

**Comment by spiritedRunning** [comment]
same issue here.  you need to download stb_image.h, and put it into common/ndk_helper.  modifying the corresponding include.
