### ISSUE TITLE
Library files was not copied to distribution_Dir in project hello-libs

### ISSUE THREAD

**Issue by zoozooll** [googlesamples/android-ndk#645]
### hello-libs
The function **add_custom_command** 
```
add_custom_command(TARGET gperf POST_BUILD
                   COMMAND "${CMAKE_COMMAND}" -E
                   copy "${CMAKE_CURRENT_SOURCE_DIR}/src/gperf.h"
                   "${distribution_DIR}/gperf/include/gperf.h"
                   COMMENT "Copying gperf to output directory")
```

in the file _hello-libs\gen-libs\src\main\cpp\gperf\CMakeLists.txt_ does not run  with Android Studio on Windows.
I added the module _gen-libs_ in _settings.gradle
```
include ':app'

// To generate libs used in this sample:
//   1) enable the gen-libs at end of this file
//   2) enable module build dependency in app/build.gradle
//   3) build the app's APK in Android Studio or on command line
//   4) undo step 1) and 2) above
 include ':gen-libs'
```
And set _implementation_ in the module app's _build.gradle_
`implementation project(path: ':gen-libs')`
And built the apk.  

I can't find the lib files that I built in the folder _distribution_DIR_.  I think the files were not copied to the folder _distribution_DIR_
But the module _gen-libs_ was built OK because I found .so and .a files in folder _gen-libs\build\intermediates\cmake\debug\obj\arm64-v8a_

**Comment by ggfan** [comment]
thank you for bring it up!  I did a try on Windows 10 for the project, it seems to be ok:
1) enable the project inside setting.gradle as you mentioned
2) enable the dependency inside app's [ build.gradle](https://github.com/googlesamples/android-ndk/blob/master/hello-libs/app/build.gradle#L50)
3) gradlew  assembleDebug ( inside windows  command prompt )

your 2) above might be the cause for your issue, refer to the comment in app's build.gradle file for some explanations ( I did not check whether the Latest studio fixed the issue though )

**Comment by zoozooll** [comment]
I ran `gradlew.bat build` in cmd and it worked OK
