### ISSUE TITLE
native-audio fast path denied by default

### ISSUE THREAD

**Issue by lhoracek** [googlesamples/android-ndk#65]
Sample native-audio produces message:
08-23 22:36:58.584    4044-4044/com.example.nativeaudio W/AudioRecord﹕ AUDIO_INPUT_FLAG_FAST denied by client

By default recorder records at 16kHz sample rate and playback at 8kHz. 
At lease comment, that fast path needs native sampling rate (in my case 44_1) would be helpful.

**Comment by ggfan** [comment]
only the playback is enabled in fast path ( normally it is 48Khz ), the recorder stayed as is) hard coded as 16Khz). So when playing back the recorded frames, the samples are duplicated 48K/16k = 3 times.

Fast path is also device dependent, it is pulled out from Java interface and passed to native side to create the audio player [not using it to create recorder].  I will add comment pulling next audio sample [ where both are created in fast path]. thank you for your suggestion!

**Comment by proppy** [comment]
Should we update the sample so that recording and playback use the same sample rate?

**Comment by ggfan** [comment]
not really. The sample has pre-captured audio data [embedded in the code ] for "android" and "hello", they are captured at 8kHz. I like to keep the input audio to be in-sync with that: all captured buffers [pre-catpured or captured at hoc] to be in 8Khz, less change to the existing code.  I should have put an comment in the readme file, I will do that.

**Comment by proppy** [comment]
Maybe we could resample them and move them to assets.

**Comment by ggfan** [comment]
I think current code has some simple up-resample there to get into the fast path: it is not perfect -- if fast audio path is not multiple of recorded sample rate, it will not be noisy... nevertheless the logic to request for fast path is there:  get from java side for the fast audio parameters, send to native to create audio player, and send to SLES to play

like to close this one, re-open if you want to see more development in this DSP thing
