### ISSUE TITLE
Missing x86_64 support in latest Google Play Games C++ SDK 3.0.1

### ISSUE THREAD

**Issue by SysReset** [googlesamples/android-ndk#654]
As Google Play has required 64-bit support for all app submissions/updates since August 2019, it is not possible to update our games with the current SDK.

When can we expect an update of the SDK with x86_64 support?

**Comment by ggfan** [comment]
looks like this got asked here too:  https://github.com/playgameservices/android-basic-samples/issues/293
[I have not trace that repo one for a while]
probably track it over there.

**Comment by ggfan** [comment]
internal bug (b/140722430) also created, let's track it from pgp sample [repo place]( playgameservices/android-basic-samples#293) linked above. Thank you for bringing it up.
