### ISSUE TITLE
Build Variants: Test Artifact Unit Tests doesn't work

### ISSUE THREAD

**Issue by moxi** [googlesamples/android-ndk#77]
The audio-echo has testCompile defined on its build.gradle, I'm trying to add UnitTests to my project and it doesn't compile:
![exampleunittest](https://cloud.githubusercontent.com/assets/437653/9605849/ed9edc72-5074-11e5-88b0-74e21e8cff04.png)
.
I didn't change the code so you can reproduce it using the project found here:
https://github.com/googlesamples/android-ndk/tree/master/audio-echo
 

What I've tried in order to have unit test available and its not working:
* Upgrade to the latest: com.android.tools.build:gradle-experimental:0.3.0-alpha2
* Create a new Module (plug in java), and add the Android project as dependency and it doesn't work either.
* Compiling using gradlew test.

Are you using something different to have the UnitTests up an running?

**Comment by ggfan** [comment]
it is buildtwith gradle experiment 0.1.0, or 0.2.0  I think; I did not use the test project, probably should delete it before I merge in [ it came with Android Studio when I "new project"] .  I will see how it goes with 0.3.0-alpha2

**Comment by proppy** [comment]
I agree, we should probably delete the test project in the meantime if it's not being used.

**Comment by proppy** [comment]
> probably should delete it before I merge in

FYI, it's already merged into master and so will show up in android studio at soon as we whitelist the project.

**Comment by proppy** [comment]
I went ahead and deleted the unused test and filed a new issue to add sample to show proper unittesting (#79).

@moxi feel free to comment/contribute on #79 if you already have idea on what a good sample for this could look like.

**Comment by moxi** [comment]
Yes, I spent some hours this early morning exploring all the sample projects to add a UnitTest example that will make sense. I'll comment on #79.
