### ISSUE TITLE
Surface C++ samples in Android Studio

### ISSUE THREAD

**Issue by vharron** [googlesamples/android-ndk#88]
REPRO STEPS:
Start Android Studio
(close open project, if any)
Welcome Dialog appears
Choose "Import an Android code sample"
"Browse Samples" window appears
Only "Hello JNI" sample is visible, need all samples from https://github.com/googlesamples/android-ndk.git

**Comment by proppy** [comment]
See #2 for the required manifest change.

**Comment by proppy** [comment]
This is partially done with #95, there is still a few sample to whitelist that are not lint free (see #82: gles3jni, native-audio, native-codec, native-media).
