### ISSUE TITLE
third-party example does not download package in default build

### ISSUE THREAD

**Issue by gcasey** [googlesamples/android-ndk#89]
In the third-party example, build fails in compiling the JNI code. The gpg_sdk package is not downloaded and unpacked before compiling the JNI code in the default build configuration. Manually executing the download task first allows the build to proceed, but it would be nice to have a dependency to cause this to happen automatically.

Tested with Android Studio 1.3.2

Thanks

**Comment by proppy** [comment]
I'm surprised that Travis didn't catch that, we should update our builder to use the same build configuration as Studio.
